package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for LLBtorqueAF2TPRB054401 kernel
var LLBtorqueAF2TPRB054401_code cu.Function

// Stores the arguments for LLBtorqueAF2TPRB054401 kernel invocation
type LLBtorqueAF2TPRB054401_args_t struct {
	arg_t1x         unsafe.Pointer
	arg_t1y         unsafe.Pointer
	arg_t1z         unsafe.Pointer
	arg_mx1         unsafe.Pointer
	arg_my1         unsafe.Pointer
	arg_mz1         unsafe.Pointer
	arg_t2x         unsafe.Pointer
	arg_t2y         unsafe.Pointer
	arg_t2z         unsafe.Pointer
	arg_mx2         unsafe.Pointer
	arg_my2         unsafe.Pointer
	arg_mz2         unsafe.Pointer
	arg_hx1         unsafe.Pointer
	arg_hy1         unsafe.Pointer
	arg_hz1         unsafe.Pointer
	arg_hx2         unsafe.Pointer
	arg_hy2         unsafe.Pointer
	arg_hz2         unsafe.Pointer
	arg_alpha_      unsafe.Pointer
	arg_alpha_mul   float32
	arg_alpha1_     unsafe.Pointer
	arg_alpha1_mul  float32
	arg_alpha2_     unsafe.Pointer
	arg_alpha2_mul  float32
	arg_TCurie_     unsafe.Pointer
	arg_TCurie_mul  float32
	arg_Msat_       unsafe.Pointer
	arg_Msat_mul    float32
	arg_Msat1_      unsafe.Pointer
	arg_Msat1_mul   float32
	arg_Msat2_      unsafe.Pointer
	arg_Msat2_mul   float32
	arg_hth11x      unsafe.Pointer
	arg_hth11y      unsafe.Pointer
	arg_hth11z      unsafe.Pointer
	arg_hth21x      unsafe.Pointer
	arg_hth21y      unsafe.Pointer
	arg_hth21z      unsafe.Pointer
	arg_hth12x      unsafe.Pointer
	arg_hth12y      unsafe.Pointer
	arg_hth12z      unsafe.Pointer
	arg_hth22x      unsafe.Pointer
	arg_hth22y      unsafe.Pointer
	arg_hth22z      unsafe.Pointer
	arg_temp_       unsafe.Pointer
	arg_x_          unsafe.Pointer
	arg_x_mul       float32
	arg_nv_         unsafe.Pointer
	arg_nv_mul      float32
	arg_mua_        unsafe.Pointer
	arg_mua_mul     float32
	arg_mub_        unsafe.Pointer
	arg_mub_mul     float32
	arg_J0aa_       unsafe.Pointer
	arg_J0aa_mul    float32
	arg_J0bb_       unsafe.Pointer
	arg_J0bb_mul    float32
	arg_J0ab_       unsafe.Pointer
	arg_J0ab_mul    float32
	arg_lambda0_    unsafe.Pointer
	arg_lambda0_mul float32
	arg_N           int
	argptr          [62]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for LLBtorqueAF2TPRB054401 kernel invocation
var LLBtorqueAF2TPRB054401_args LLBtorqueAF2TPRB054401_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	LLBtorqueAF2TPRB054401_args.argptr[0] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_t1x)
	LLBtorqueAF2TPRB054401_args.argptr[1] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_t1y)
	LLBtorqueAF2TPRB054401_args.argptr[2] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_t1z)
	LLBtorqueAF2TPRB054401_args.argptr[3] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mx1)
	LLBtorqueAF2TPRB054401_args.argptr[4] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_my1)
	LLBtorqueAF2TPRB054401_args.argptr[5] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mz1)
	LLBtorqueAF2TPRB054401_args.argptr[6] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_t2x)
	LLBtorqueAF2TPRB054401_args.argptr[7] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_t2y)
	LLBtorqueAF2TPRB054401_args.argptr[8] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_t2z)
	LLBtorqueAF2TPRB054401_args.argptr[9] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mx2)
	LLBtorqueAF2TPRB054401_args.argptr[10] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_my2)
	LLBtorqueAF2TPRB054401_args.argptr[11] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mz2)
	LLBtorqueAF2TPRB054401_args.argptr[12] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hx1)
	LLBtorqueAF2TPRB054401_args.argptr[13] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hy1)
	LLBtorqueAF2TPRB054401_args.argptr[14] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hz1)
	LLBtorqueAF2TPRB054401_args.argptr[15] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hx2)
	LLBtorqueAF2TPRB054401_args.argptr[16] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hy2)
	LLBtorqueAF2TPRB054401_args.argptr[17] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hz2)
	LLBtorqueAF2TPRB054401_args.argptr[18] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_alpha_)
	LLBtorqueAF2TPRB054401_args.argptr[19] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_alpha_mul)
	LLBtorqueAF2TPRB054401_args.argptr[20] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_alpha1_)
	LLBtorqueAF2TPRB054401_args.argptr[21] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_alpha1_mul)
	LLBtorqueAF2TPRB054401_args.argptr[22] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_alpha2_)
	LLBtorqueAF2TPRB054401_args.argptr[23] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_alpha2_mul)
	LLBtorqueAF2TPRB054401_args.argptr[24] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_TCurie_)
	LLBtorqueAF2TPRB054401_args.argptr[25] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_TCurie_mul)
	LLBtorqueAF2TPRB054401_args.argptr[26] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_Msat_)
	LLBtorqueAF2TPRB054401_args.argptr[27] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_Msat_mul)
	LLBtorqueAF2TPRB054401_args.argptr[28] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_Msat1_)
	LLBtorqueAF2TPRB054401_args.argptr[29] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_Msat1_mul)
	LLBtorqueAF2TPRB054401_args.argptr[30] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_Msat2_)
	LLBtorqueAF2TPRB054401_args.argptr[31] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_Msat2_mul)
	LLBtorqueAF2TPRB054401_args.argptr[32] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth11x)
	LLBtorqueAF2TPRB054401_args.argptr[33] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth11y)
	LLBtorqueAF2TPRB054401_args.argptr[34] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth11z)
	LLBtorqueAF2TPRB054401_args.argptr[35] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth21x)
	LLBtorqueAF2TPRB054401_args.argptr[36] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth21y)
	LLBtorqueAF2TPRB054401_args.argptr[37] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth21z)
	LLBtorqueAF2TPRB054401_args.argptr[38] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth12x)
	LLBtorqueAF2TPRB054401_args.argptr[39] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth12y)
	LLBtorqueAF2TPRB054401_args.argptr[40] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth12z)
	LLBtorqueAF2TPRB054401_args.argptr[41] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth22x)
	LLBtorqueAF2TPRB054401_args.argptr[42] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth22y)
	LLBtorqueAF2TPRB054401_args.argptr[43] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_hth22z)
	LLBtorqueAF2TPRB054401_args.argptr[44] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_temp_)
	LLBtorqueAF2TPRB054401_args.argptr[45] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_x_)
	LLBtorqueAF2TPRB054401_args.argptr[46] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_x_mul)
	LLBtorqueAF2TPRB054401_args.argptr[47] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_nv_)
	LLBtorqueAF2TPRB054401_args.argptr[48] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_nv_mul)
	LLBtorqueAF2TPRB054401_args.argptr[49] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mua_)
	LLBtorqueAF2TPRB054401_args.argptr[50] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mua_mul)
	LLBtorqueAF2TPRB054401_args.argptr[51] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mub_)
	LLBtorqueAF2TPRB054401_args.argptr[52] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_mub_mul)
	LLBtorqueAF2TPRB054401_args.argptr[53] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_J0aa_)
	LLBtorqueAF2TPRB054401_args.argptr[54] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_J0aa_mul)
	LLBtorqueAF2TPRB054401_args.argptr[55] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_J0bb_)
	LLBtorqueAF2TPRB054401_args.argptr[56] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_J0bb_mul)
	LLBtorqueAF2TPRB054401_args.argptr[57] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_J0ab_)
	LLBtorqueAF2TPRB054401_args.argptr[58] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_J0ab_mul)
	LLBtorqueAF2TPRB054401_args.argptr[59] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_lambda0_)
	LLBtorqueAF2TPRB054401_args.argptr[60] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_lambda0_mul)
	LLBtorqueAF2TPRB054401_args.argptr[61] = unsafe.Pointer(&LLBtorqueAF2TPRB054401_args.arg_N)
}

// Wrapper for LLBtorqueAF2TPRB054401 CUDA kernel, asynchronous.
func k_LLBtorqueAF2TPRB054401_async(t1x unsafe.Pointer, t1y unsafe.Pointer, t1z unsafe.Pointer, mx1 unsafe.Pointer, my1 unsafe.Pointer, mz1 unsafe.Pointer, t2x unsafe.Pointer, t2y unsafe.Pointer, t2z unsafe.Pointer, mx2 unsafe.Pointer, my2 unsafe.Pointer, mz2 unsafe.Pointer, hx1 unsafe.Pointer, hy1 unsafe.Pointer, hz1 unsafe.Pointer, hx2 unsafe.Pointer, hy2 unsafe.Pointer, hz2 unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, alpha1_ unsafe.Pointer, alpha1_mul float32, alpha2_ unsafe.Pointer, alpha2_mul float32, TCurie_ unsafe.Pointer, TCurie_mul float32, Msat_ unsafe.Pointer, Msat_mul float32, Msat1_ unsafe.Pointer, Msat1_mul float32, Msat2_ unsafe.Pointer, Msat2_mul float32, hth11x unsafe.Pointer, hth11y unsafe.Pointer, hth11z unsafe.Pointer, hth21x unsafe.Pointer, hth21y unsafe.Pointer, hth21z unsafe.Pointer, hth12x unsafe.Pointer, hth12y unsafe.Pointer, hth12z unsafe.Pointer, hth22x unsafe.Pointer, hth22y unsafe.Pointer, hth22z unsafe.Pointer, temp_ unsafe.Pointer, x_ unsafe.Pointer, x_mul float32, nv_ unsafe.Pointer, nv_mul float32, mua_ unsafe.Pointer, mua_mul float32, mub_ unsafe.Pointer, mub_mul float32, J0aa_ unsafe.Pointer, J0aa_mul float32, J0bb_ unsafe.Pointer, J0bb_mul float32, J0ab_ unsafe.Pointer, J0ab_mul float32, lambda0_ unsafe.Pointer, lambda0_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("LLBtorqueAF2TPRB054401")
	}

	LLBtorqueAF2TPRB054401_args.Lock()
	defer LLBtorqueAF2TPRB054401_args.Unlock()

	if LLBtorqueAF2TPRB054401_code == 0 {
		LLBtorqueAF2TPRB054401_code = fatbinLoad(LLBtorqueAF2TPRB054401_map, "LLBtorqueAF2TPRB054401")
	}

	LLBtorqueAF2TPRB054401_args.arg_t1x = t1x
	LLBtorqueAF2TPRB054401_args.arg_t1y = t1y
	LLBtorqueAF2TPRB054401_args.arg_t1z = t1z
	LLBtorqueAF2TPRB054401_args.arg_mx1 = mx1
	LLBtorqueAF2TPRB054401_args.arg_my1 = my1
	LLBtorqueAF2TPRB054401_args.arg_mz1 = mz1
	LLBtorqueAF2TPRB054401_args.arg_t2x = t2x
	LLBtorqueAF2TPRB054401_args.arg_t2y = t2y
	LLBtorqueAF2TPRB054401_args.arg_t2z = t2z
	LLBtorqueAF2TPRB054401_args.arg_mx2 = mx2
	LLBtorqueAF2TPRB054401_args.arg_my2 = my2
	LLBtorqueAF2TPRB054401_args.arg_mz2 = mz2
	LLBtorqueAF2TPRB054401_args.arg_hx1 = hx1
	LLBtorqueAF2TPRB054401_args.arg_hy1 = hy1
	LLBtorqueAF2TPRB054401_args.arg_hz1 = hz1
	LLBtorqueAF2TPRB054401_args.arg_hx2 = hx2
	LLBtorqueAF2TPRB054401_args.arg_hy2 = hy2
	LLBtorqueAF2TPRB054401_args.arg_hz2 = hz2
	LLBtorqueAF2TPRB054401_args.arg_alpha_ = alpha_
	LLBtorqueAF2TPRB054401_args.arg_alpha_mul = alpha_mul
	LLBtorqueAF2TPRB054401_args.arg_alpha1_ = alpha1_
	LLBtorqueAF2TPRB054401_args.arg_alpha1_mul = alpha1_mul
	LLBtorqueAF2TPRB054401_args.arg_alpha2_ = alpha2_
	LLBtorqueAF2TPRB054401_args.arg_alpha2_mul = alpha2_mul
	LLBtorqueAF2TPRB054401_args.arg_TCurie_ = TCurie_
	LLBtorqueAF2TPRB054401_args.arg_TCurie_mul = TCurie_mul
	LLBtorqueAF2TPRB054401_args.arg_Msat_ = Msat_
	LLBtorqueAF2TPRB054401_args.arg_Msat_mul = Msat_mul
	LLBtorqueAF2TPRB054401_args.arg_Msat1_ = Msat1_
	LLBtorqueAF2TPRB054401_args.arg_Msat1_mul = Msat1_mul
	LLBtorqueAF2TPRB054401_args.arg_Msat2_ = Msat2_
	LLBtorqueAF2TPRB054401_args.arg_Msat2_mul = Msat2_mul
	LLBtorqueAF2TPRB054401_args.arg_hth11x = hth11x
	LLBtorqueAF2TPRB054401_args.arg_hth11y = hth11y
	LLBtorqueAF2TPRB054401_args.arg_hth11z = hth11z
	LLBtorqueAF2TPRB054401_args.arg_hth21x = hth21x
	LLBtorqueAF2TPRB054401_args.arg_hth21y = hth21y
	LLBtorqueAF2TPRB054401_args.arg_hth21z = hth21z
	LLBtorqueAF2TPRB054401_args.arg_hth12x = hth12x
	LLBtorqueAF2TPRB054401_args.arg_hth12y = hth12y
	LLBtorqueAF2TPRB054401_args.arg_hth12z = hth12z
	LLBtorqueAF2TPRB054401_args.arg_hth22x = hth22x
	LLBtorqueAF2TPRB054401_args.arg_hth22y = hth22y
	LLBtorqueAF2TPRB054401_args.arg_hth22z = hth22z
	LLBtorqueAF2TPRB054401_args.arg_temp_ = temp_
	LLBtorqueAF2TPRB054401_args.arg_x_ = x_
	LLBtorqueAF2TPRB054401_args.arg_x_mul = x_mul
	LLBtorqueAF2TPRB054401_args.arg_nv_ = nv_
	LLBtorqueAF2TPRB054401_args.arg_nv_mul = nv_mul
	LLBtorqueAF2TPRB054401_args.arg_mua_ = mua_
	LLBtorqueAF2TPRB054401_args.arg_mua_mul = mua_mul
	LLBtorqueAF2TPRB054401_args.arg_mub_ = mub_
	LLBtorqueAF2TPRB054401_args.arg_mub_mul = mub_mul
	LLBtorqueAF2TPRB054401_args.arg_J0aa_ = J0aa_
	LLBtorqueAF2TPRB054401_args.arg_J0aa_mul = J0aa_mul
	LLBtorqueAF2TPRB054401_args.arg_J0bb_ = J0bb_
	LLBtorqueAF2TPRB054401_args.arg_J0bb_mul = J0bb_mul
	LLBtorqueAF2TPRB054401_args.arg_J0ab_ = J0ab_
	LLBtorqueAF2TPRB054401_args.arg_J0ab_mul = J0ab_mul
	LLBtorqueAF2TPRB054401_args.arg_lambda0_ = lambda0_
	LLBtorqueAF2TPRB054401_args.arg_lambda0_mul = lambda0_mul
	LLBtorqueAF2TPRB054401_args.arg_N = N

	args := LLBtorqueAF2TPRB054401_args.argptr[:]
	cu.LaunchKernel(LLBtorqueAF2TPRB054401_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("LLBtorqueAF2TPRB054401")
	}
}

// maps compute capability on PTX code for LLBtorqueAF2TPRB054401 kernel.
var LLBtorqueAF2TPRB054401_map = map[int]string{0: "",
	70: LLBtorqueAF2TPRB054401_ptx_70}

// LLBtorqueAF2TPRB054401 PTX code for various compute capabilities.
const (
	LLBtorqueAF2TPRB054401_ptx_70 = `
.version 7.1
.target sm_70
.address_size 64

	// .globl	LLBtorqueAF2TPRB054401

.visible .entry LLBtorqueAF2TPRB054401(
	.param .u64 LLBtorqueAF2TPRB054401_param_0,
	.param .u64 LLBtorqueAF2TPRB054401_param_1,
	.param .u64 LLBtorqueAF2TPRB054401_param_2,
	.param .u64 LLBtorqueAF2TPRB054401_param_3,
	.param .u64 LLBtorqueAF2TPRB054401_param_4,
	.param .u64 LLBtorqueAF2TPRB054401_param_5,
	.param .u64 LLBtorqueAF2TPRB054401_param_6,
	.param .u64 LLBtorqueAF2TPRB054401_param_7,
	.param .u64 LLBtorqueAF2TPRB054401_param_8,
	.param .u64 LLBtorqueAF2TPRB054401_param_9,
	.param .u64 LLBtorqueAF2TPRB054401_param_10,
	.param .u64 LLBtorqueAF2TPRB054401_param_11,
	.param .u64 LLBtorqueAF2TPRB054401_param_12,
	.param .u64 LLBtorqueAF2TPRB054401_param_13,
	.param .u64 LLBtorqueAF2TPRB054401_param_14,
	.param .u64 LLBtorqueAF2TPRB054401_param_15,
	.param .u64 LLBtorqueAF2TPRB054401_param_16,
	.param .u64 LLBtorqueAF2TPRB054401_param_17,
	.param .u64 LLBtorqueAF2TPRB054401_param_18,
	.param .f32 LLBtorqueAF2TPRB054401_param_19,
	.param .u64 LLBtorqueAF2TPRB054401_param_20,
	.param .f32 LLBtorqueAF2TPRB054401_param_21,
	.param .u64 LLBtorqueAF2TPRB054401_param_22,
	.param .f32 LLBtorqueAF2TPRB054401_param_23,
	.param .u64 LLBtorqueAF2TPRB054401_param_24,
	.param .f32 LLBtorqueAF2TPRB054401_param_25,
	.param .u64 LLBtorqueAF2TPRB054401_param_26,
	.param .f32 LLBtorqueAF2TPRB054401_param_27,
	.param .u64 LLBtorqueAF2TPRB054401_param_28,
	.param .f32 LLBtorqueAF2TPRB054401_param_29,
	.param .u64 LLBtorqueAF2TPRB054401_param_30,
	.param .f32 LLBtorqueAF2TPRB054401_param_31,
	.param .u64 LLBtorqueAF2TPRB054401_param_32,
	.param .u64 LLBtorqueAF2TPRB054401_param_33,
	.param .u64 LLBtorqueAF2TPRB054401_param_34,
	.param .u64 LLBtorqueAF2TPRB054401_param_35,
	.param .u64 LLBtorqueAF2TPRB054401_param_36,
	.param .u64 LLBtorqueAF2TPRB054401_param_37,
	.param .u64 LLBtorqueAF2TPRB054401_param_38,
	.param .u64 LLBtorqueAF2TPRB054401_param_39,
	.param .u64 LLBtorqueAF2TPRB054401_param_40,
	.param .u64 LLBtorqueAF2TPRB054401_param_41,
	.param .u64 LLBtorqueAF2TPRB054401_param_42,
	.param .u64 LLBtorqueAF2TPRB054401_param_43,
	.param .u64 LLBtorqueAF2TPRB054401_param_44,
	.param .u64 LLBtorqueAF2TPRB054401_param_45,
	.param .f32 LLBtorqueAF2TPRB054401_param_46,
	.param .u64 LLBtorqueAF2TPRB054401_param_47,
	.param .f32 LLBtorqueAF2TPRB054401_param_48,
	.param .u64 LLBtorqueAF2TPRB054401_param_49,
	.param .f32 LLBtorqueAF2TPRB054401_param_50,
	.param .u64 LLBtorqueAF2TPRB054401_param_51,
	.param .f32 LLBtorqueAF2TPRB054401_param_52,
	.param .u64 LLBtorqueAF2TPRB054401_param_53,
	.param .f32 LLBtorqueAF2TPRB054401_param_54,
	.param .u64 LLBtorqueAF2TPRB054401_param_55,
	.param .f32 LLBtorqueAF2TPRB054401_param_56,
	.param .u64 LLBtorqueAF2TPRB054401_param_57,
	.param .f32 LLBtorqueAF2TPRB054401_param_58,
	.param .u64 LLBtorqueAF2TPRB054401_param_59,
	.param .f32 LLBtorqueAF2TPRB054401_param_60,
	.param .u32 LLBtorqueAF2TPRB054401_param_61
)
{
	.reg .pred 	%p<140>;
	.reg .f32 	%f<1537>;
	.reg .b32 	%r<135>;
	.reg .f64 	%fd<56>;
	.reg .b64 	%rd<182>;


	ld.param.u64 	%rd20, [LLBtorqueAF2TPRB054401_param_18];
	ld.param.u64 	%rd21, [LLBtorqueAF2TPRB054401_param_20];
	ld.param.u64 	%rd22, [LLBtorqueAF2TPRB054401_param_22];
	ld.param.u64 	%rd23, [LLBtorqueAF2TPRB054401_param_24];
	ld.param.u64 	%rd24, [LLBtorqueAF2TPRB054401_param_26];
	ld.param.u64 	%rd25, [LLBtorqueAF2TPRB054401_param_28];
	ld.param.u64 	%rd26, [LLBtorqueAF2TPRB054401_param_30];
	ld.param.u64 	%rd30, [LLBtorqueAF2TPRB054401_param_35];
	ld.param.u64 	%rd31, [LLBtorqueAF2TPRB054401_param_36];
	ld.param.u64 	%rd32, [LLBtorqueAF2TPRB054401_param_37];
	ld.param.u64 	%rd33, [LLBtorqueAF2TPRB054401_param_38];
	ld.param.u64 	%rd34, [LLBtorqueAF2TPRB054401_param_39];
	ld.param.u64 	%rd35, [LLBtorqueAF2TPRB054401_param_40];
	ld.param.u64 	%rd36, [LLBtorqueAF2TPRB054401_param_41];
	ld.param.u64 	%rd37, [LLBtorqueAF2TPRB054401_param_42];
	ld.param.u64 	%rd38, [LLBtorqueAF2TPRB054401_param_43];
	ld.param.u64 	%rd40, [LLBtorqueAF2TPRB054401_param_45];
	ld.param.u64 	%rd41, [LLBtorqueAF2TPRB054401_param_47];
	ld.param.u64 	%rd42, [LLBtorqueAF2TPRB054401_param_49];
	ld.param.u64 	%rd43, [LLBtorqueAF2TPRB054401_param_51];
	ld.param.u64 	%rd44, [LLBtorqueAF2TPRB054401_param_53];
	ld.param.u64 	%rd45, [LLBtorqueAF2TPRB054401_param_55];
	ld.param.f32 	%f1465, [LLBtorqueAF2TPRB054401_param_58];
	ld.param.u64 	%rd47, [LLBtorqueAF2TPRB054401_param_59];
	ld.param.u32 	%r3, [LLBtorqueAF2TPRB054401_param_61];
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ctaid.x;
	mad.lo.s32 	%r7, %r4, %r5, %r6;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	setp.ge.s32	%p5, %r1, %r3;
	@%p5 bra 	BB0_150;

	ld.param.f32 	%f1451, [LLBtorqueAF2TPRB054401_param_19];
	ld.param.u64 	%rd176, [LLBtorqueAF2TPRB054401_param_17];
	ld.param.u64 	%rd175, [LLBtorqueAF2TPRB054401_param_16];
	ld.param.u64 	%rd174, [LLBtorqueAF2TPRB054401_param_15];
	ld.param.u64 	%rd173, [LLBtorqueAF2TPRB054401_param_14];
	ld.param.u64 	%rd172, [LLBtorqueAF2TPRB054401_param_13];
	ld.param.u64 	%rd171, [LLBtorqueAF2TPRB054401_param_12];
	ld.param.u64 	%rd170, [LLBtorqueAF2TPRB054401_param_11];
	ld.param.u64 	%rd169, [LLBtorqueAF2TPRB054401_param_10];
	ld.param.u64 	%rd168, [LLBtorqueAF2TPRB054401_param_9];
	ld.param.u64 	%rd167, [LLBtorqueAF2TPRB054401_param_5];
	ld.param.u64 	%rd166, [LLBtorqueAF2TPRB054401_param_4];
	ld.param.u64 	%rd165, [LLBtorqueAF2TPRB054401_param_3];
	cvta.to.global.u64 	%rd48, %rd165;
	mul.wide.s32 	%rd49, %r1, 4;
	add.s64 	%rd50, %rd48, %rd49;
	ld.global.nc.f32 	%f1, [%rd50];
	cvta.to.global.u64 	%rd51, %rd166;
	add.s64 	%rd52, %rd51, %rd49;
	ld.global.nc.f32 	%f2, [%rd52];
	cvta.to.global.u64 	%rd53, %rd167;
	add.s64 	%rd54, %rd53, %rd49;
	ld.global.nc.f32 	%f3, [%rd54];
	cvta.to.global.u64 	%rd55, %rd168;
	add.s64 	%rd56, %rd55, %rd49;
	ld.global.nc.f32 	%f4, [%rd56];
	cvta.to.global.u64 	%rd57, %rd169;
	add.s64 	%rd58, %rd57, %rd49;
	ld.global.nc.f32 	%f5, [%rd58];
	cvta.to.global.u64 	%rd59, %rd170;
	add.s64 	%rd60, %rd59, %rd49;
	ld.global.nc.f32 	%f6, [%rd60];
	cvta.to.global.u64 	%rd61, %rd171;
	add.s64 	%rd62, %rd61, %rd49;
	ld.global.nc.f32 	%f1527, [%rd62];
	cvta.to.global.u64 	%rd63, %rd172;
	add.s64 	%rd64, %rd63, %rd49;
	ld.global.nc.f32 	%f1528, [%rd64];
	cvta.to.global.u64 	%rd65, %rd173;
	add.s64 	%rd66, %rd65, %rd49;
	ld.global.nc.f32 	%f1529, [%rd66];
	cvta.to.global.u64 	%rd67, %rd174;
	add.s64 	%rd68, %rd67, %rd49;
	ld.global.nc.f32 	%f1524, [%rd68];
	cvta.to.global.u64 	%rd69, %rd175;
	add.s64 	%rd70, %rd69, %rd49;
	ld.global.nc.f32 	%f1525, [%rd70];
	cvta.to.global.u64 	%rd71, %rd176;
	add.s64 	%rd72, %rd71, %rd49;
	ld.global.nc.f32 	%f1526, [%rd72];
	setp.eq.s64	%p6, %rd20, 0;
	@%p6 bra 	BB0_3;

	ld.param.f32 	%f1412, [LLBtorqueAF2TPRB054401_param_19];
	cvta.to.global.u64 	%rd73, %rd20;
	add.s64 	%rd75, %rd73, %rd49;
	ld.global.nc.f32 	%f338, [%rd75];
	mul.f32 	%f1451, %f338, %f1412;

BB0_3:
	ld.param.f32 	%f1452, [LLBtorqueAF2TPRB054401_param_21];
	setp.eq.s64	%p7, %rd21, 0;
	@%p7 bra 	BB0_5;

	ld.param.f32 	%f1414, [LLBtorqueAF2TPRB054401_param_21];
	cvta.to.global.u64 	%rd76, %rd21;
	add.s64 	%rd78, %rd76, %rd49;
	ld.global.nc.f32 	%f339, [%rd78];
	mul.f32 	%f1452, %f339, %f1414;

BB0_5:
	ld.param.f32 	%f1453, [LLBtorqueAF2TPRB054401_param_23];
	setp.eq.s64	%p8, %rd22, 0;
	@%p8 bra 	BB0_7;

	ld.param.f32 	%f1416, [LLBtorqueAF2TPRB054401_param_23];
	cvta.to.global.u64 	%rd79, %rd22;
	add.s64 	%rd81, %rd79, %rd49;
	ld.global.nc.f32 	%f340, [%rd81];
	mul.f32 	%f1453, %f340, %f1416;

BB0_7:
	ld.param.f32 	%f1454, [LLBtorqueAF2TPRB054401_param_25];
	setp.eq.s64	%p9, %rd23, 0;
	@%p9 bra 	BB0_9;

	ld.param.f32 	%f1418, [LLBtorqueAF2TPRB054401_param_25];
	cvta.to.global.u64 	%rd82, %rd23;
	add.s64 	%rd84, %rd82, %rd49;
	ld.global.nc.f32 	%f341, [%rd84];
	mul.f32 	%f1454, %f341, %f1418;

BB0_9:
	ld.param.f32 	%f1455, [LLBtorqueAF2TPRB054401_param_27];
	setp.eq.s64	%p10, %rd24, 0;
	@%p10 bra 	BB0_11;

	ld.param.f32 	%f1420, [LLBtorqueAF2TPRB054401_param_27];
	cvta.to.global.u64 	%rd85, %rd24;
	add.s64 	%rd87, %rd85, %rd49;
	ld.global.nc.f32 	%f342, [%rd87];
	mul.f32 	%f1455, %f342, %f1420;

BB0_11:
	ld.param.f32 	%f1456, [LLBtorqueAF2TPRB054401_param_29];
	setp.eq.s64	%p11, %rd25, 0;
	@%p11 bra 	BB0_13;

	ld.param.f32 	%f1422, [LLBtorqueAF2TPRB054401_param_29];
	cvta.to.global.u64 	%rd88, %rd25;
	add.s64 	%rd90, %rd88, %rd49;
	ld.global.nc.f32 	%f343, [%rd90];
	mul.f32 	%f1456, %f343, %f1422;

BB0_13:
	ld.param.f32 	%f1457, [LLBtorqueAF2TPRB054401_param_31];
	setp.eq.s64	%p12, %rd26, 0;
	@%p12 bra 	BB0_15;

	ld.param.f32 	%f1424, [LLBtorqueAF2TPRB054401_param_31];
	cvta.to.global.u64 	%rd91, %rd26;
	add.s64 	%rd93, %rd91, %rd49;
	ld.global.nc.f32 	%f344, [%rd93];
	mul.f32 	%f1457, %f344, %f1424;

BB0_15:
	ld.param.f32 	%f1458, [LLBtorqueAF2TPRB054401_param_46];
	setp.eq.s64	%p13, %rd40, 0;
	@%p13 bra 	BB0_17;

	ld.param.f32 	%f1426, [LLBtorqueAF2TPRB054401_param_46];
	cvta.to.global.u64 	%rd94, %rd40;
	add.s64 	%rd96, %rd94, %rd49;
	ld.global.nc.f32 	%f345, [%rd96];
	mul.f32 	%f1458, %f345, %f1426;

BB0_17:
	ld.param.f32 	%f1459, [LLBtorqueAF2TPRB054401_param_48];
	setp.eq.s64	%p14, %rd41, 0;
	@%p14 bra 	BB0_19;

	ld.param.f32 	%f1428, [LLBtorqueAF2TPRB054401_param_48];
	cvta.to.global.u64 	%rd97, %rd41;
	add.s64 	%rd99, %rd97, %rd49;
	ld.global.nc.f32 	%f346, [%rd99];
	mul.f32 	%f1459, %f346, %f1428;

BB0_19:
	ld.param.f32 	%f1460, [LLBtorqueAF2TPRB054401_param_50];
	setp.eq.s64	%p15, %rd42, 0;
	@%p15 bra 	BB0_21;

	ld.param.f32 	%f1430, [LLBtorqueAF2TPRB054401_param_50];
	cvta.to.global.u64 	%rd100, %rd42;
	add.s64 	%rd102, %rd100, %rd49;
	ld.global.nc.f32 	%f347, [%rd102];
	mul.f32 	%f1460, %f347, %f1430;

BB0_21:
	ld.param.f32 	%f1461, [LLBtorqueAF2TPRB054401_param_52];
	setp.eq.s64	%p16, %rd43, 0;
	@%p16 bra 	BB0_23;

	ld.param.f32 	%f1432, [LLBtorqueAF2TPRB054401_param_52];
	cvta.to.global.u64 	%rd103, %rd43;
	add.s64 	%rd105, %rd103, %rd49;
	ld.global.nc.f32 	%f348, [%rd105];
	mul.f32 	%f1461, %f348, %f1432;

BB0_23:
	ld.param.f32 	%f1462, [LLBtorqueAF2TPRB054401_param_54];
	setp.eq.s64	%p17, %rd44, 0;
	@%p17 bra 	BB0_25;

	ld.param.f32 	%f1434, [LLBtorqueAF2TPRB054401_param_54];
	cvta.to.global.u64 	%rd106, %rd44;
	add.s64 	%rd108, %rd106, %rd49;
	ld.global.nc.f32 	%f349, [%rd108];
	mul.f32 	%f1462, %f349, %f1434;

BB0_25:
	ld.param.f32 	%f1463, [LLBtorqueAF2TPRB054401_param_56];
	mul.f32 	%f350, %f1459, %f1462;
	mul.f32 	%f37, %f1458, %f350;
	setp.eq.s64	%p18, %rd45, 0;
	@%p18 bra 	BB0_27;

	ld.param.f32 	%f1436, [LLBtorqueAF2TPRB054401_param_56];
	cvta.to.global.u64 	%rd109, %rd45;
	add.s64 	%rd111, %rd109, %rd49;
	ld.global.nc.f32 	%f351, [%rd111];
	mul.f32 	%f1463, %f351, %f1436;

BB0_27:
	ld.param.u64 	%rd177, [LLBtorqueAF2TPRB054401_param_57];
	mov.f32 	%f352, 0f3F800000;
	sub.f32 	%f40, %f352, %f1458;
	mul.f32 	%f353, %f1459, %f1463;
	mul.f32 	%f41, %f40, %f353;
	cvta.to.global.u64 	%rd112, %rd177;
	add.s64 	%rd1, %rd112, %rd49;
	setp.eq.s64	%p19, %rd177, 0;
	mov.f32 	%f1464, %f1465;
	@%p19 bra 	BB0_29;

	ld.global.nc.f32 	%f354, [%rd1];
	mul.f32 	%f1464, %f354, %f1465;

BB0_29:
	mul.f32 	%f355, %f40, %f1464;
	mul.f32 	%f44, %f1459, %f355;
	@%p19 bra 	BB0_31;

	ld.global.nc.f32 	%f356, [%rd1];
	mul.f32 	%f1465, %f356, %f1465;

BB0_31:
	ld.param.f32 	%f1466, [LLBtorqueAF2TPRB054401_param_60];
	mul.f32 	%f357, %f1458, %f1465;
	mul.f32 	%f47, %f1459, %f357;
	setp.eq.s64	%p21, %rd47, 0;
	@%p21 bra 	BB0_33;

	ld.param.f32 	%f1438, [LLBtorqueAF2TPRB054401_param_60];
	cvta.to.global.u64 	%rd114, %rd47;
	add.s64 	%rd116, %rd114, %rd49;
	ld.global.nc.f32 	%f358, [%rd116];
	mul.f32 	%f1466, %f358, %f1438;

BB0_33:
	ld.param.u64 	%rd178, [LLBtorqueAF2TPRB054401_param_44];
	cvta.to.global.u64 	%rd117, %rd178;
	add.s64 	%rd119, %rd117, %rd49;
	ld.global.nc.f32 	%f359, [%rd119];
	setp.eq.f32	%p22, %f359, 0f00000000;
	selp.f32	%f360, 0f38D1B717, %f359, %p22;
	cvt.f64.f32	%fd12, %f360;
	cvt.f64.f32	%fd1, %f1454;
	add.f64 	%fd13, %fd1, %fd1;
	setp.gt.f64	%p23, %fd12, %fd13;
	add.f32 	%f361, %f1454, %f1454;
	selp.f32	%f1467, %f361, %f360, %p23;
	setp.neu.f32	%p24, %f1467, %f1454;
	@%p24 bra 	BB0_35;

	add.f64 	%fd14, %fd1, 0dBFB999999999999A;
	cvt.rn.f32.f64	%f1467, %fd14;

BB0_35:
	mul.f32 	%f362, %f2, %f2;
	fma.rn.f32 	%f363, %f1, %f1, %f362;
	fma.rn.f32 	%f364, %f3, %f3, %f363;
	sqrt.rn.f32 	%f53, %f364;
	mul.f32 	%f365, %f5, %f5;
	fma.rn.f32 	%f366, %f4, %f4, %f365;
	fma.rn.f32 	%f367, %f6, %f6, %f366;
	sqrt.rn.f32 	%f54, %f367;
	setp.eq.f32	%p25, %f53, 0f00000000;
	setp.eq.f32	%p26, %f54, 0f00000000;
	or.pred  	%p27, %p25, %p26;
	@%p27 bra 	BB0_148;
	bra.uni 	BB0_36;

BB0_148:
	mul.f32 	%f1534, %f1, 0f00000000;
	mul.f32 	%f1535, %f2, 0f00000000;
	mul.f32 	%f1536, %f3, 0f00000000;
	mul.f32 	%f1531, %f4, 0f00000000;
	mul.f32 	%f1532, %f5, 0f00000000;
	mul.f32 	%f1533, %f6, 0f00000000;
	bra.uni 	BB0_149;

BB0_36:
	ld.param.u64 	%rd181, [LLBtorqueAF2TPRB054401_param_34];
	ld.param.u64 	%rd180, [LLBtorqueAF2TPRB054401_param_33];
	ld.param.u64 	%rd179, [LLBtorqueAF2TPRB054401_param_32];
	cvta.to.global.u64 	%rd120, %rd179;
	add.s64 	%rd122, %rd120, %rd49;
	ld.global.nc.f32 	%f55, [%rd122];
	cvta.to.global.u64 	%rd123, %rd180;
	add.s64 	%rd124, %rd123, %rd49;
	ld.global.nc.f32 	%f56, [%rd124];
	cvta.to.global.u64 	%rd125, %rd181;
	add.s64 	%rd126, %rd125, %rd49;
	ld.global.nc.f32 	%f57, [%rd126];
	cvta.to.global.u64 	%rd127, %rd30;
	add.s64 	%rd128, %rd127, %rd49;
	ld.global.nc.f32 	%f58, [%rd128];
	cvta.to.global.u64 	%rd129, %rd31;
	add.s64 	%rd130, %rd129, %rd49;
	ld.global.nc.f32 	%f59, [%rd130];
	cvta.to.global.u64 	%rd131, %rd32;
	add.s64 	%rd132, %rd131, %rd49;
	ld.global.nc.f32 	%f60, [%rd132];
	cvta.to.global.u64 	%rd133, %rd33;
	add.s64 	%rd134, %rd133, %rd49;
	ld.global.nc.f32 	%f61, [%rd134];
	cvta.to.global.u64 	%rd135, %rd34;
	add.s64 	%rd136, %rd135, %rd49;
	ld.global.nc.f32 	%f62, [%rd136];
	cvta.to.global.u64 	%rd137, %rd35;
	add.s64 	%rd138, %rd137, %rd49;
	ld.global.nc.f32 	%f63, [%rd138];
	cvta.to.global.u64 	%rd139, %rd36;
	add.s64 	%rd140, %rd139, %rd49;
	ld.global.nc.f32 	%f64, [%rd140];
	cvta.to.global.u64 	%rd141, %rd37;
	add.s64 	%rd142, %rd141, %rd49;
	ld.global.nc.f32 	%f65, [%rd142];
	cvta.to.global.u64 	%rd143, %rd38;
	add.s64 	%rd144, %rd143, %rd49;
	ld.global.nc.f32 	%f66, [%rd144];
	add.f32 	%f67, %f37, %f41;
	cvt.rzi.f32.f32	%f369, %f352;
	add.f32 	%f370, %f369, %f369;
	mov.f32 	%f371, 0f40000000;
	sub.f32 	%f372, %f371, %f370;
	abs.f32 	%f68, %f372;
	sub.f32 	%f69, %f37, %f41;
	abs.f32 	%f70, %f69;
	setp.lt.f32	%p28, %f70, 0f00800000;
	mul.f32 	%f373, %f70, 0f4B800000;
	selp.f32	%f374, %f373, %f70, %p28;
	selp.f32	%f375, 0fC3170000, 0fC2FE0000, %p28;
	mov.b32 	 %r10, %f374;
	and.b32  	%r11, %r10, 8388607;
	or.b32  	%r12, %r11, 1065353216;
	mov.b32 	 %f376, %r12;
	shr.u32 	%r13, %r10, 23;
	cvt.rn.f32.u32	%f377, %r13;
	add.f32 	%f378, %f375, %f377;
	setp.gt.f32	%p29, %f376, 0f3FB504F3;
	mul.f32 	%f379, %f376, 0f3F000000;
	add.f32 	%f380, %f378, 0f3F800000;
	selp.f32	%f381, %f380, %f378, %p29;
	selp.f32	%f382, %f379, %f376, %p29;
	add.f32 	%f383, %f382, 0fBF800000;
	add.f32 	%f384, %f382, 0f3F800000;
	rcp.approx.ftz.f32 	%f385, %f384;
	add.f32 	%f386, %f383, %f383;
	mul.f32 	%f387, %f385, %f386;
	mul.f32 	%f388, %f387, %f387;
	mov.f32 	%f389, 0f3C4CAF63;
	mov.f32 	%f390, 0f3B18F0FE;
	fma.rn.f32 	%f391, %f390, %f388, %f389;
	mov.f32 	%f392, 0f3DAAAABD;
	fma.rn.f32 	%f393, %f391, %f388, %f392;
	mul.rn.f32 	%f394, %f393, %f388;
	mul.rn.f32 	%f395, %f394, %f387;
	sub.f32 	%f396, %f383, %f387;
	neg.f32 	%f397, %f387;
	add.f32 	%f398, %f396, %f396;
	fma.rn.f32 	%f399, %f397, %f383, %f398;
	mul.rn.f32 	%f400, %f385, %f399;
	add.f32 	%f401, %f395, %f387;
	sub.f32 	%f402, %f387, %f401;
	add.f32 	%f403, %f395, %f402;
	add.f32 	%f404, %f400, %f403;
	add.f32 	%f405, %f401, %f404;
	sub.f32 	%f406, %f401, %f405;
	add.f32 	%f407, %f404, %f406;
	mov.f32 	%f408, 0f3F317200;
	mul.rn.f32 	%f409, %f381, %f408;
	mov.f32 	%f410, 0f35BFBE8E;
	mul.rn.f32 	%f411, %f381, %f410;
	add.f32 	%f412, %f409, %f405;
	sub.f32 	%f413, %f409, %f412;
	add.f32 	%f414, %f405, %f413;
	add.f32 	%f415, %f407, %f414;
	add.f32 	%f416, %f411, %f415;
	add.f32 	%f417, %f412, %f416;
	sub.f32 	%f418, %f412, %f417;
	add.f32 	%f419, %f416, %f418;
	mul.rn.f32 	%f420, %f371, %f417;
	neg.f32 	%f421, %f420;
	fma.rn.f32 	%f422, %f371, %f417, %f421;
	fma.rn.f32 	%f423, %f371, %f419, %f422;
	mov.f32 	%f424, 0f00000000;
	fma.rn.f32 	%f425, %f424, %f417, %f423;
	add.rn.f32 	%f426, %f420, %f425;
	neg.f32 	%f427, %f426;
	add.rn.f32 	%f428, %f420, %f427;
	add.rn.f32 	%f429, %f428, %f425;
	mov.b32 	 %r14, %f426;
	setp.eq.s32	%p30, %r14, 1118925336;
	add.s32 	%r15, %r14, -1;
	mov.b32 	 %f430, %r15;
	add.f32 	%f431, %f429, 0f37000000;
	selp.f32	%f71, %f431, %f429, %p30;
	selp.f32	%f432, %f430, %f426, %p30;
	mov.f32 	%f433, 0f3FB8AA3B;
	mul.rn.f32 	%f434, %f432, %f433;
	cvt.rzi.f32.f32	%f435, %f434;
	abs.f32 	%f436, %f435;
	setp.gt.f32	%p31, %f436, 0f42FC0000;
	mov.b32 	 %r16, %f435;
	and.b32  	%r17, %r16, -2147483648;
	or.b32  	%r18, %r17, 1123811328;
	mov.b32 	 %f437, %r18;
	selp.f32	%f438, %f437, %f435, %p31;
	mov.f32 	%f439, 0fBF317218;
	fma.rn.f32 	%f440, %f438, %f439, %f432;
	mov.f32 	%f441, 0f3102E308;
	fma.rn.f32 	%f442, %f438, %f441, %f440;
	mul.f32 	%f443, %f442, 0f3FB8AA3B;
	add.f32 	%f444, %f438, 0f4B40007F;
	mov.b32 	 %r19, %f444;
	shl.b32 	%r20, %r19, 23;
	mov.b32 	 %f445, %r20;
	ex2.approx.ftz.f32 	%f446, %f443;
	mul.f32 	%f1468, %f446, %f445;
	setp.eq.f32	%p32, %f1468, 0f7F800000;
	@%p32 bra 	BB0_38;

	fma.rn.f32 	%f1468, %f1468, %f71, %f1468;

BB0_38:
	setp.neu.f32	%p33, %f68, 0f3F800000;
	setp.geu.f32	%p34, %f69, 0f00000000;
	or.pred  	%p1, %p34, %p33;
	setp.eq.f32	%p35, %f69, 0f00000000;
	@%p35 bra 	BB0_42;
	bra.uni 	BB0_39;

BB0_42:
	setp.eq.f32	%p38, %f68, 0f3F800000;
	add.f32 	%f451, %f69, %f69;
	selp.f32	%f1470, %f451, 0f00000000, %p38;
	bra.uni 	BB0_43;

BB0_39:
	mov.b32 	 %r21, %f1468;
	xor.b32  	%r22, %r21, -2147483648;
	mov.b32 	 %f447, %r22;
	selp.f32	%f1470, %f1468, %f447, %p1;
	@%p34 bra 	BB0_43;

	cvt.rzi.f32.f32	%f449, %f371;
	setp.eq.f32	%p37, %f449, 0f40000000;
	@%p37 bra 	BB0_43;

	mov.f32 	%f1470, 0f7FFFFFFF;

BB0_43:
	abs.f32 	%f1448, %f69;
	add.f32 	%f452, %f1448, 0f40000000;
	mov.b32 	 %r23, %f452;
	setp.lt.s32	%p39, %r23, 2139095040;
	@%p39 bra 	BB0_48;

	abs.f32 	%f1449, %f69;
	setp.gtu.f32	%p40, %f1449, 0f7F800000;
	@%p40 bra 	BB0_47;
	bra.uni 	BB0_45;

BB0_47:
	add.f32 	%f1470, %f69, 0f40000000;
	bra.uni 	BB0_48;

BB0_45:
	abs.f32 	%f1450, %f69;
	setp.neu.f32	%p41, %f1450, 0f7F800000;
	@%p41 bra 	BB0_48;

	selp.f32	%f1470, 0f7F800000, 0fFF800000, %p1;

BB0_48:
	mov.f32 	%f1383, 0f00000000;
	mov.f32 	%f1382, 0f35BFBE8E;
	mov.f32 	%f1381, 0f3F317200;
	mov.f32 	%f1380, 0f3DAAAABD;
	mov.f32 	%f1379, 0f3C4CAF63;
	mov.f32 	%f1378, 0f3B18F0FE;
	setp.eq.f32	%p42, %f69, 0f3F800000;
	selp.f32	%f453, 0f3F800000, %f1470, %p42;
	mul.f32 	%f454, %f44, 0f40800000;
	fma.rn.f32 	%f81, %f454, %f47, %f453;
	mov.f32 	%f455, 0f3E800000;
	cvt.rzi.f32.f32	%f456, %f455;
	fma.rn.f32 	%f457, %f456, 0fC0000000, 0f3F000000;
	abs.f32 	%f82, %f457;
	abs.f32 	%f83, %f81;
	setp.lt.f32	%p43, %f83, 0f00800000;
	mul.f32 	%f458, %f83, 0f4B800000;
	selp.f32	%f459, %f458, %f83, %p43;
	selp.f32	%f460, 0fC3170000, 0fC2FE0000, %p43;
	mov.b32 	 %r24, %f459;
	and.b32  	%r25, %r24, 8388607;
	or.b32  	%r26, %r25, 1065353216;
	mov.b32 	 %f461, %r26;
	shr.u32 	%r27, %r24, 23;
	cvt.rn.f32.u32	%f462, %r27;
	add.f32 	%f463, %f460, %f462;
	setp.gt.f32	%p44, %f461, 0f3FB504F3;
	mul.f32 	%f464, %f461, 0f3F000000;
	add.f32 	%f465, %f463, 0f3F800000;
	selp.f32	%f466, %f465, %f463, %p44;
	selp.f32	%f467, %f464, %f461, %p44;
	add.f32 	%f468, %f467, 0fBF800000;
	add.f32 	%f469, %f467, 0f3F800000;
	rcp.approx.ftz.f32 	%f470, %f469;
	add.f32 	%f471, %f468, %f468;
	mul.f32 	%f472, %f470, %f471;
	mul.f32 	%f473, %f472, %f472;
	fma.rn.f32 	%f476, %f1378, %f473, %f1379;
	fma.rn.f32 	%f478, %f476, %f473, %f1380;
	mul.rn.f32 	%f479, %f478, %f473;
	mul.rn.f32 	%f480, %f479, %f472;
	sub.f32 	%f481, %f468, %f472;
	neg.f32 	%f482, %f472;
	add.f32 	%f483, %f481, %f481;
	fma.rn.f32 	%f484, %f482, %f468, %f483;
	mul.rn.f32 	%f485, %f470, %f484;
	add.f32 	%f486, %f480, %f472;
	sub.f32 	%f487, %f472, %f486;
	add.f32 	%f488, %f480, %f487;
	add.f32 	%f489, %f485, %f488;
	add.f32 	%f490, %f486, %f489;
	sub.f32 	%f491, %f486, %f490;
	add.f32 	%f492, %f489, %f491;
	mul.rn.f32 	%f494, %f466, %f1381;
	mul.rn.f32 	%f496, %f466, %f1382;
	add.f32 	%f497, %f494, %f490;
	sub.f32 	%f498, %f494, %f497;
	add.f32 	%f499, %f490, %f498;
	add.f32 	%f500, %f492, %f499;
	add.f32 	%f501, %f496, %f500;
	add.f32 	%f502, %f497, %f501;
	sub.f32 	%f503, %f497, %f502;
	add.f32 	%f504, %f501, %f503;
	mov.f32 	%f505, 0f3F000000;
	mul.rn.f32 	%f506, %f505, %f502;
	neg.f32 	%f507, %f506;
	fma.rn.f32 	%f508, %f505, %f502, %f507;
	fma.rn.f32 	%f509, %f505, %f504, %f508;
	fma.rn.f32 	%f511, %f1383, %f502, %f509;
	add.rn.f32 	%f512, %f506, %f511;
	neg.f32 	%f513, %f512;
	add.rn.f32 	%f514, %f506, %f513;
	add.rn.f32 	%f515, %f514, %f511;
	mov.b32 	 %r28, %f512;
	setp.eq.s32	%p45, %r28, 1118925336;
	add.s32 	%r29, %r28, -1;
	mov.b32 	 %f516, %r29;
	add.f32 	%f517, %f515, 0f37000000;
	selp.f32	%f84, %f517, %f515, %p45;
	selp.f32	%f518, %f516, %f512, %p45;
	mul.rn.f32 	%f520, %f518, %f433;
	cvt.rzi.f32.f32	%f521, %f520;
	abs.f32 	%f522, %f521;
	setp.gt.f32	%p46, %f522, 0f42FC0000;
	mov.b32 	 %r30, %f521;
	and.b32  	%r31, %r30, -2147483648;
	or.b32  	%r32, %r31, 1123811328;
	mov.b32 	 %f523, %r32;
	selp.f32	%f524, %f523, %f521, %p46;
	fma.rn.f32 	%f526, %f524, %f439, %f518;
	fma.rn.f32 	%f528, %f524, %f441, %f526;
	mul.f32 	%f529, %f528, 0f3FB8AA3B;
	add.f32 	%f530, %f524, 0f4B40007F;
	mov.b32 	 %r33, %f530;
	shl.b32 	%r34, %r33, 23;
	mov.b32 	 %f531, %r34;
	ex2.approx.ftz.f32 	%f532, %f529;
	mul.f32 	%f1471, %f532, %f531;
	setp.eq.f32	%p47, %f1471, 0f7F800000;
	@%p47 bra 	BB0_50;

	fma.rn.f32 	%f1471, %f1471, %f84, %f1471;

BB0_50:
	setp.neu.f32	%p48, %f82, 0f3F800000;
	setp.geu.f32	%p49, %f81, 0f00000000;
	or.pred  	%p2, %p49, %p48;
	setp.eq.f32	%p50, %f81, 0f00000000;
	@%p50 bra 	BB0_54;
	bra.uni 	BB0_51;

BB0_54:
	setp.eq.f32	%p53, %f82, 0f3F800000;
	add.f32 	%f537, %f81, %f81;
	selp.f32	%f1473, %f537, 0f00000000, %p53;
	bra.uni 	BB0_55;

BB0_51:
	mov.b32 	 %r35, %f1471;
	xor.b32  	%r36, %r35, -2147483648;
	mov.b32 	 %f533, %r36;
	selp.f32	%f1473, %f1471, %f533, %p2;
	@%p49 bra 	BB0_55;

	cvt.rzi.f32.f32	%f535, %f505;
	setp.eq.f32	%p52, %f535, 0f3F000000;
	@%p52 bra 	BB0_55;

	mov.f32 	%f1473, 0f7FFFFFFF;

BB0_55:
	abs.f32 	%f1391, %f81;
	add.f32 	%f538, %f1391, 0f3F000000;
	mov.b32 	 %r37, %f538;
	setp.lt.s32	%p54, %r37, 2139095040;
	@%p54 bra 	BB0_60;

	abs.f32 	%f1396, %f81;
	setp.gtu.f32	%p55, %f1396, 0f7F800000;
	@%p55 bra 	BB0_59;
	bra.uni 	BB0_57;

BB0_59:
	add.f32 	%f1473, %f81, 0f3F000000;
	bra.uni 	BB0_60;

BB0_57:
	abs.f32 	%f1397, %f81;
	setp.neu.f32	%p56, %f1397, 0f7F800000;
	@%p56 bra 	BB0_60;

	selp.f32	%f1473, 0f7F800000, 0fFF800000, %p2;

BB0_60:
	setp.eq.f32	%p57, %f81, 0f3F800000;
	selp.f32	%f539, 0f3F800000, %f1473, %p57;
	add.f32 	%f540, %f67, %f539;
	div.rn.f32 	%f94, %f540, 0f1AC84ACE;
	sub.f32 	%f541, %f1467, %f94;
	abs.f32 	%f542, %f541;
	cvt.f64.f32	%fd15, %f542;
	cvt.f64.f32	%fd2, %f94;
	mul.f64 	%fd16, %fd2, 0d3F7CAC083126E979;
	setp.lt.f64	%p58, %fd15, %fd16;
	setp.lt.f32	%p59, %f1467, %f94;
	and.pred  	%p60, %p58, %p59;
	mul.f32 	%f543, %f94, 0f3F7E353F;
	selp.f32	%f1495, %f543, %f1467, %p60;
	setp.lt.f32	%p61, %f1495, %f94;
	@%p61 bra 	BB0_62;
	bra.uni 	BB0_61;

BB0_62:
	div.rn.f32 	%f98, %f94, 0f41200000;
	setp.lt.f32	%p62, %f1495, %f98;
	selp.f32	%f1475, %f98, %f1495, %p62;
	cvt.f64.f32	%fd17, %f1475;
	mul.f64 	%fd3, %fd2, 0d3FEFD70A3D70A3D7;
	mov.u32 	%r134, 0;
	setp.leu.f64	%p63, %fd17, %fd3;
	@%p63 bra 	BB0_63;

	cvt.rn.f32.f64	%f1474, %fd3;
	mov.u32 	%r134, 1;
	bra.uni 	BB0_65;

BB0_61:
	abs.f32 	%f1494, %f44;
	abs.f32 	%f1493, %f47;
	mov.f32 	%f1496, 0f3C23D70A;
	mov.f32 	%f1497, %f1496;
	bra.uni 	BB0_99;

BB0_63:
	mov.f32 	%f1474, %f1475;
	mov.f32 	%f1475, %f1495;

BB0_65:
	mul.f32 	%f546, %f1474, 0f19858734;
	rcp.rn.f32 	%f547, %f546;
	mul.f32 	%f103, %f37, %f547;
	abs.f32 	%f1494, %f44;
	mul.f32 	%f105, %f547, %f1494;
	abs.f32 	%f1493, %f47;
	mul.f32 	%f107, %f547, %f1493;
	mul.f32 	%f108, %f41, %f547;
	mul.f32 	%f548, %f105, 0f3F666666;
	fma.rn.f32 	%f109, %f103, 0f3F666666, %f548;
	add.f32 	%f549, %f109, %f109;
	mov.f32 	%f551, 0f3BBB989D;
	fma.rn.f32 	%f552, %f549, %f551, %f505;
	cvt.sat.f32.f32	%f553, %f552;
	mov.f32 	%f554, 0f4B400001;
	mov.f32 	%f555, 0f437C0000;
	fma.rm.f32 	%f556, %f553, %f555, %f554;
	add.f32 	%f557, %f556, 0fCB40007F;
	neg.f32 	%f558, %f557;
	fma.rn.f32 	%f560, %f549, %f433, %f558;
	mov.f32 	%f561, 0f32A57060;
	fma.rn.f32 	%f562, %f549, %f561, %f560;
	mov.b32 	 %r40, %f556;
	shl.b32 	%r41, %r40, 23;
	mov.b32 	 %f563, %r41;
	ex2.approx.ftz.f32 	%f564, %f562;
	fma.rn.f32 	%f110, %f564, %f563, 0f3F800000;
	abs.f32 	%f565, %f110;
	cvt.f64.f32	%fd18, %f565;
	setp.gt.f64	%p64, %fd18, 0d6974E718D7D7625A;
	@%p64 bra 	BB0_67;
	bra.uni 	BB0_66;

BB0_67:
	setp.gt.f32	%p65, %f109, 0f00000000;
	selp.f32	%f1476, 0f3F800000, 0fBF800000, %p65;
	bra.uni 	BB0_68;

BB0_66:
	add.f32 	%f566, %f110, 0fC0000000;
	div.rn.f32 	%f567, %f110, %f566;
	mov.f32 	%f568, 0fBF800000;
	div.rn.f32 	%f569, %f568, %f109;
	add.f32 	%f1476, %f567, %f569;

BB0_68:
	mul.f32 	%f570, %f107, 0f3F666666;
	fma.rn.f32 	%f114, %f108, 0f3F666666, %f570;
	add.f32 	%f571, %f114, %f114;
	fma.rn.f32 	%f574, %f571, %f551, %f505;
	cvt.sat.f32.f32	%f575, %f574;
	fma.rm.f32 	%f578, %f575, %f555, %f554;
	add.f32 	%f579, %f578, 0fCB40007F;
	neg.f32 	%f580, %f579;
	fma.rn.f32 	%f582, %f571, %f433, %f580;
	fma.rn.f32 	%f584, %f571, %f561, %f582;
	mov.b32 	 %r42, %f578;
	shl.b32 	%r43, %r42, 23;
	mov.b32 	 %f585, %r43;
	ex2.approx.ftz.f32 	%f586, %f584;
	fma.rn.f32 	%f115, %f586, %f585, 0f3F800000;
	abs.f32 	%f587, %f115;
	cvt.f64.f32	%fd19, %f587;
	setp.gt.f64	%p66, %fd19, 0d6974E718D7D7625A;
	@%p66 bra 	BB0_70;
	bra.uni 	BB0_69;

BB0_70:
	setp.gt.f32	%p67, %f114, 0f00000000;
	selp.f32	%f1477, 0f3F800000, 0fBF800000, %p67;
	bra.uni 	BB0_71;

BB0_69:
	add.f32 	%f588, %f115, 0fC0000000;
	div.rn.f32 	%f589, %f115, %f588;
	mov.f32 	%f590, 0fBF800000;
	div.rn.f32 	%f591, %f590, %f114;
	add.f32 	%f1477, %f589, %f591;

BB0_71:
	add.f32 	%f1481, %f1477, 0fBF666666;
	add.f32 	%f1480, %f1476, 0fBF666666;
	mov.f32 	%f1478, 0f3F666666;
	mov.f32 	%f1479, %f1478;

BB0_72:
	mul.f32 	%f595, %f105, %f1479;
	fma.rn.f32 	%f125, %f103, %f1478, %f595;
	abs.f32 	%f126, %f125;
	cvt.f64.f32	%fd20, %f126;
	setp.lt.f64	%p68, %fd20, 0d39B4484BFEEBC2A0;
	mov.f32 	%f1485, 0f3EAAAAAB;
	mov.f32 	%f1483, %f1485;
	@%p68 bra 	BB0_79;

	setp.ltu.f32	%p69, %f126, 0f3F800000;
	mul.f32 	%f127, %f125, %f125;
	@%p69 bra 	BB0_75;
	bra.uni 	BB0_74;

BB0_75:
	mov.f32 	%f616, 0f394FFF49;
	mov.f32 	%f617, 0f363D0ADA;
	fma.rn.f32 	%f618, %f617, %f127, %f616;
	mov.f32 	%f619, 0f3C08889A;
	fma.rn.f32 	%f620, %f618, %f127, %f619;
	mov.f32 	%f621, 0f3E2AAAAB;
	fma.rn.f32 	%f622, %f620, %f127, %f621;
	mul.f32 	%f623, %f127, %f622;
	fma.rn.f32 	%f1482, %f623, %f125, %f125;
	bra.uni 	BB0_76;

BB0_74:
	mul.rn.f32 	%f597, %f126, %f433;
	cvt.rzi.f32.f32	%f598, %f597;
	abs.f32 	%f599, %f598;
	setp.gt.f32	%p70, %f599, 0f42FC0000;
	mov.b32 	 %r44, %f598;
	and.b32  	%r45, %r44, -2147483648;
	or.b32  	%r46, %r45, 1123811328;
	mov.b32 	 %f600, %r46;
	selp.f32	%f601, %f600, %f598, %p70;
	fma.rn.f32 	%f603, %f601, %f439, %f126;
	fma.rn.f32 	%f605, %f601, %f441, %f603;
	mul.f32 	%f606, %f605, 0f3FB8AA3B;
	add.f32 	%f607, %f601, 0f4B40007D;
	mov.b32 	 %r47, %f607;
	shl.b32 	%r48, %r47, 23;
	mov.b32 	 %f608, %r48;
	ex2.approx.ftz.f32 	%f609, %f606;
	mul.f32 	%f610, %f609, %f608;
	mov.f32 	%f611, 0f3E000000;
	div.approx.f32 	%f612, %f611, %f610;
	neg.f32 	%f613, %f612;
	fma.rn.f32 	%f615, %f371, %f610, %f613;
	mov.b32 	 %r49, %f615;
	setp.ltu.f32	%p71, %f126, 0f42B40000;
	selp.b32	%r50, %r49, 2139095040, %p71;
	mov.b32 	 %r51, %f125;
	and.b32  	%r52, %r51, -2147483648;
	or.b32  	%r53, %r50, %r52;
	mov.b32 	 %f1482, %r53;

BB0_76:
	abs.f32 	%f624, %f1482;
	cvt.f64.f32	%fd21, %f624;
	setp.gt.f64	%p72, %fd21, 0d6974E718D7D7625A;
	@%p72 bra 	BB0_78;
	bra.uni 	BB0_77;

BB0_78:
	rcp.rn.f32 	%f1483, %f127;
	bra.uni 	BB0_79;

BB0_77:
	mul.f32 	%f625, %f1482, %f1482;
	cvt.f64.f32	%fd22, %f625;
	mov.f64 	%fd23, 0dBFF0000000000000;
	div.rn.f64 	%fd24, %fd23, %fd22;
	cvt.f64.f32	%fd25, %f127;
	rcp.rn.f64 	%fd26, %fd25;
	add.f64 	%fd27, %fd24, %fd26;
	cvt.rn.f32.f64	%f1483, %fd27;

BB0_79:
	mul.f32 	%f627, %f108, %f1479;
	fma.rn.f32 	%f134, %f107, %f1478, %f627;
	abs.f32 	%f135, %f134;
	cvt.f64.f32	%fd28, %f135;
	setp.lt.f64	%p73, %fd28, 0d39B4484BFEEBC2A0;
	@%p73 bra 	BB0_86;

	setp.ltu.f32	%p74, %f135, 0f3F800000;
	mul.f32 	%f136, %f134, %f134;
	@%p74 bra 	BB0_82;
	bra.uni 	BB0_81;

BB0_82:
	mov.f32 	%f648, 0f394FFF49;
	mov.f32 	%f649, 0f363D0ADA;
	fma.rn.f32 	%f650, %f649, %f136, %f648;
	mov.f32 	%f651, 0f3C08889A;
	fma.rn.f32 	%f652, %f650, %f136, %f651;
	mov.f32 	%f653, 0f3E2AAAAB;
	fma.rn.f32 	%f654, %f652, %f136, %f653;
	mul.f32 	%f655, %f136, %f654;
	fma.rn.f32 	%f1484, %f655, %f134, %f134;
	bra.uni 	BB0_83;

BB0_81:
	mul.rn.f32 	%f629, %f135, %f433;
	cvt.rzi.f32.f32	%f630, %f629;
	abs.f32 	%f631, %f630;
	setp.gt.f32	%p75, %f631, 0f42FC0000;
	mov.b32 	 %r54, %f630;
	and.b32  	%r55, %r54, -2147483648;
	or.b32  	%r56, %r55, 1123811328;
	mov.b32 	 %f632, %r56;
	selp.f32	%f633, %f632, %f630, %p75;
	fma.rn.f32 	%f635, %f633, %f439, %f135;
	fma.rn.f32 	%f637, %f633, %f441, %f635;
	mul.f32 	%f638, %f637, 0f3FB8AA3B;
	add.f32 	%f639, %f633, 0f4B40007D;
	mov.b32 	 %r57, %f639;
	shl.b32 	%r58, %r57, 23;
	mov.b32 	 %f640, %r58;
	ex2.approx.ftz.f32 	%f641, %f638;
	mul.f32 	%f642, %f641, %f640;
	mov.f32 	%f643, 0f3E000000;
	div.approx.f32 	%f644, %f643, %f642;
	neg.f32 	%f645, %f644;
	fma.rn.f32 	%f647, %f371, %f642, %f645;
	mov.b32 	 %r59, %f647;
	setp.ltu.f32	%p76, %f135, 0f42B40000;
	selp.b32	%r60, %r59, 2139095040, %p76;
	mov.b32 	 %r61, %f134;
	and.b32  	%r62, %r61, -2147483648;
	or.b32  	%r63, %r60, %r62;
	mov.b32 	 %f1484, %r63;

BB0_83:
	abs.f32 	%f656, %f1484;
	cvt.f64.f32	%fd29, %f656;
	setp.gt.f64	%p77, %fd29, 0d6974E718D7D7625A;
	@%p77 bra 	BB0_85;
	bra.uni 	BB0_84;

BB0_85:
	rcp.rn.f32 	%f1485, %f136;
	bra.uni 	BB0_86;

BB0_84:
	mul.f32 	%f657, %f1484, %f1484;
	cvt.f64.f32	%fd30, %f657;
	mov.f64 	%fd31, 0dBFF0000000000000;
	div.rn.f64 	%fd32, %fd31, %fd30;
	cvt.f64.f32	%fd33, %f136;
	rcp.rn.f64 	%fd34, %fd33;
	add.f64 	%fd35, %fd32, %fd34;
	cvt.rn.f32.f64	%f1485, %fd35;

BB0_86:
	fma.rn.f32 	%f143, %f103, %f1483, 0fBF800000;
	fma.rn.f32 	%f144, %f108, %f1485, 0fBF800000;
	mul.f32 	%f658, %f143, %f144;
	mul.f32 	%f145, %f107, %f1485;
	mul.f32 	%f146, %f105, %f1483;
	mul.f32 	%f659, %f146, %f145;
	sub.f32 	%f147, %f658, %f659;
	setp.eq.f32	%p78, %f147, 0f00000000;
	@%p78 bra 	BB0_94;

	rcp.rn.f32 	%f660, %f147;
	mul.f32 	%f661, %f1481, %f146;
	mul.f32 	%f662, %f1480, %f144;
	sub.f32 	%f663, %f662, %f661;
	mul.f32 	%f148, %f663, %f660;
	mul.f32 	%f664, %f1481, %f143;
	mul.f32 	%f665, %f1480, %f145;
	sub.f32 	%f666, %f664, %f665;
	mul.f32 	%f149, %f666, %f660;
	sub.f32 	%f1478, %f1478, %f148;
	sub.f32 	%f1479, %f1479, %f149;
	mul.f32 	%f667, %f105, %f1479;
	fma.rn.f32 	%f152, %f103, %f1478, %f667;
	add.f32 	%f668, %f152, %f152;
	fma.rn.f32 	%f671, %f668, %f551, %f505;
	cvt.sat.f32.f32	%f672, %f671;
	fma.rm.f32 	%f675, %f672, %f555, %f554;
	add.f32 	%f676, %f675, 0fCB40007F;
	neg.f32 	%f677, %f676;
	fma.rn.f32 	%f679, %f668, %f433, %f677;
	fma.rn.f32 	%f681, %f668, %f561, %f679;
	mov.b32 	 %r64, %f675;
	shl.b32 	%r65, %r64, 23;
	mov.b32 	 %f682, %r65;
	ex2.approx.ftz.f32 	%f683, %f681;
	fma.rn.f32 	%f153, %f683, %f682, 0f3F800000;
	abs.f32 	%f684, %f153;
	cvt.f64.f32	%fd36, %f684;
	setp.gt.f64	%p79, %fd36, 0d6974E718D7D7625A;
	@%p79 bra 	BB0_89;
	bra.uni 	BB0_88;

BB0_89:
	setp.gt.f32	%p80, %f152, 0f00000000;
	selp.f32	%f1486, 0f3F800000, 0fBF800000, %p80;
	bra.uni 	BB0_90;

BB0_88:
	add.f32 	%f685, %f153, 0fC0000000;
	div.rn.f32 	%f686, %f153, %f685;
	mov.f32 	%f687, 0fBF800000;
	div.rn.f32 	%f688, %f687, %f152;
	add.f32 	%f1486, %f686, %f688;

BB0_90:
	mul.f32 	%f689, %f108, %f1479;
	fma.rn.f32 	%f157, %f107, %f1478, %f689;
	add.f32 	%f690, %f157, %f157;
	fma.rn.f32 	%f693, %f690, %f551, %f505;
	cvt.sat.f32.f32	%f694, %f693;
	fma.rm.f32 	%f697, %f694, %f555, %f554;
	add.f32 	%f698, %f697, 0fCB40007F;
	neg.f32 	%f699, %f698;
	fma.rn.f32 	%f701, %f690, %f433, %f699;
	fma.rn.f32 	%f703, %f690, %f561, %f701;
	mov.b32 	 %r66, %f697;
	shl.b32 	%r67, %r66, 23;
	mov.b32 	 %f704, %r67;
	ex2.approx.ftz.f32 	%f705, %f703;
	fma.rn.f32 	%f158, %f705, %f704, 0f3F800000;
	abs.f32 	%f706, %f158;
	cvt.f64.f32	%fd37, %f706;
	setp.gt.f64	%p81, %fd37, 0d6974E718D7D7625A;
	@%p81 bra 	BB0_92;
	bra.uni 	BB0_91;

BB0_92:
	setp.gt.f32	%p82, %f157, 0f00000000;
	selp.f32	%f1487, 0f3F800000, 0fBF800000, %p82;
	bra.uni 	BB0_93;

BB0_91:
	add.f32 	%f707, %f158, 0fC0000000;
	div.rn.f32 	%f708, %f158, %f707;
	mov.f32 	%f709, 0fBF800000;
	div.rn.f32 	%f710, %f709, %f157;
	add.f32 	%f1487, %f708, %f710;

BB0_93:
	sub.f32 	%f1481, %f1487, %f1479;
	mul.f32 	%f711, %f148, %f148;
	setp.gt.f32	%p83, %f711, 0f38D1B717;
	mul.f32 	%f712, %f149, %f149;
	setp.gt.f32	%p84, %f712, 0f38D1B717;
	or.pred  	%p85, %p83, %p84;
	sub.f32 	%f1480, %f1486, %f1478;
	@%p85 bra 	BB0_72;

BB0_94:
	setp.gt.f32	%p86, %f1478, 0f38D1B717;
	selp.f32	%f1496, %f1478, 0f3A83126F, %p86;
	setp.gt.f32	%p87, %f1479, 0f38D1B717;
	selp.f32	%f1497, %f1479, 0f3A83126F, %p87;
	setp.geu.f32	%p88, %f1495, %f98;
	@%p88 bra 	BB0_96;

	add.f32 	%f713, %f1496, 0fBF800000;
	div.rn.f32 	%f714, %f713, %f1474;
	fma.rn.f32 	%f1496, %f1475, %f714, 0f3F800000;
	add.f32 	%f715, %f1497, 0fBF800000;
	div.rn.f32 	%f716, %f715, %f1474;
	fma.rn.f32 	%f1497, %f1475, %f716, 0f3F800000;
	mov.f32 	%f1474, %f1475;

BB0_96:
	setp.eq.s32	%p89, %r134, 0;
	@%p89 bra 	BB0_97;

	sub.f32 	%f717, %f94, %f1475;
	mul.f32 	%f718, %f717, %f1496;
	mul.f32 	%f719, %f94, 0f3BA3D70A;
	div.rn.f32 	%f1496, %f718, %f719;
	mul.f32 	%f720, %f717, %f1497;
	div.rn.f32 	%f1497, %f720, %f719;
	mov.f32 	%f1495, %f1475;
	bra.uni 	BB0_99;

BB0_97:
	mov.f32 	%f1495, %f1474;

BB0_99:
	setp.lt.f32	%p90, %f1496, 0f3C23D70A;
	selp.f32	%f180, 0f3C23D70A, %f1496, %p90;
	setp.lt.f32	%p91, %f1497, 0f3C23D70A;
	selp.f32	%f181, 0f3C23D70A, %f1497, %p91;
	mul.f32 	%f721, %f1494, %f181;
	fma.rn.f32 	%f182, %f37, %f180, %f721;
	mul.f32 	%f183, %f1495, 0f19858734;
	div.rn.f32 	%f184, %f182, %f183;
	mul.f32 	%f722, %f41, %f181;
	fma.rn.f32 	%f185, %f1493, %f180, %f722;
	div.rn.f32 	%f186, %f185, %f183;
	div.rn.f32 	%f187, %f1461, %f183;
	div.rn.f32 	%f188, %f1460, %f183;
	div.rn.f32 	%f189, %f41, %f183;
	div.rn.f32 	%f190, %f37, %f183;
	div.rn.f32 	%f191, %f1493, %f183;
	div.rn.f32 	%f192, %f1494, %f183;
	setp.lt.f32	%p92, %f1495, %f94;
	@%p92 bra 	BB0_101;
	bra.uni 	BB0_100;

BB0_101:
	mul.f32 	%f195, %f184, %f184;
	abs.f32 	%f196, %f184;
	setp.ltu.f32	%p93, %f196, 0f3F800000;
	@%p93 bra 	BB0_103;
	bra.uni 	BB0_102;

BB0_103:
	mov.f32 	%f769, 0f394FFF49;
	mov.f32 	%f770, 0f363D0ADA;
	fma.rn.f32 	%f771, %f770, %f195, %f769;
	mov.f32 	%f772, 0f3C08889A;
	fma.rn.f32 	%f773, %f771, %f195, %f772;
	mov.f32 	%f774, 0f3E2AAAAB;
	fma.rn.f32 	%f775, %f773, %f195, %f774;
	mul.f32 	%f776, %f195, %f775;
	fma.rn.f32 	%f1498, %f776, %f184, %f184;
	bra.uni 	BB0_104;

BB0_100:
	mov.f32 	%f1384, 0f3F800000;
	div.rn.f32 	%f723, %f187, 0f40400000;
	mul.f32 	%f724, %f1494, %f723;
	div.rn.f32 	%f725, %f724, %f183;
	div.rn.f32 	%f726, %f725, 0f40400000;
	div.rn.f32 	%f727, %f189, 0f40400000;
	sub.f32 	%f729, %f1384, %f727;
	div.rn.f32 	%f730, %f188, 0f40400000;
	fma.rn.f32 	%f731, %f730, %f729, %f726;
	div.rn.f32 	%f732, %f190, 0f40400000;
	sub.f32 	%f733, %f1384, %f732;
	mul.f32 	%f734, %f729, %f733;
	div.rn.f32 	%f735, %f191, 0f40400000;
	mul.f32 	%f736, %f1494, %f735;
	div.rn.f32 	%f737, %f736, %f183;
	div.rn.f32 	%f738, %f737, 0f40400000;
	sub.f32 	%f739, %f734, %f738;
	div.rn.f32 	%f1506, %f731, %f739;
	mul.f32 	%f740, %f1493, %f730;
	div.rn.f32 	%f741, %f740, %f183;
	div.rn.f32 	%f742, %f741, 0f40400000;
	div.rn.f32 	%f743, %f192, 0f40400000;
	mul.f32 	%f744, %f1493, %f743;
	div.rn.f32 	%f745, %f744, %f183;
	div.rn.f32 	%f746, %f745, 0f40400000;
	fma.rn.f32 	%f747, %f723, %f733, %f742;
	sub.f32 	%f748, %f734, %f746;
	div.rn.f32 	%f1507, %f747, %f748;
	bra.uni 	BB0_132;

BB0_102:
	mul.rn.f32 	%f750, %f196, %f433;
	cvt.rzi.f32.f32	%f751, %f750;
	abs.f32 	%f752, %f751;
	setp.gt.f32	%p94, %f752, 0f42FC0000;
	mov.b32 	 %r68, %f751;
	and.b32  	%r69, %r68, -2147483648;
	or.b32  	%r70, %r69, 1123811328;
	mov.b32 	 %f753, %r70;
	selp.f32	%f754, %f753, %f751, %p94;
	fma.rn.f32 	%f756, %f754, %f439, %f196;
	fma.rn.f32 	%f758, %f754, %f441, %f756;
	mul.f32 	%f759, %f758, 0f3FB8AA3B;
	add.f32 	%f760, %f754, 0f4B40007D;
	mov.b32 	 %r71, %f760;
	shl.b32 	%r72, %r71, 23;
	mov.b32 	 %f761, %r72;
	ex2.approx.ftz.f32 	%f762, %f759;
	mul.f32 	%f763, %f762, %f761;
	mov.f32 	%f764, 0f3E000000;
	div.approx.f32 	%f765, %f764, %f763;
	neg.f32 	%f766, %f765;
	fma.rn.f32 	%f768, %f371, %f763, %f766;
	mov.b32 	 %r73, %f768;
	setp.ltu.f32	%p95, %f196, 0f42B40000;
	selp.b32	%r74, %r73, 2139095040, %p95;
	mov.b32 	 %r75, %f184;
	and.b32  	%r76, %r75, -2147483648;
	or.b32  	%r77, %r74, %r76;
	mov.b32 	 %f1498, %r77;

BB0_104:
	mov.f32 	%f1390, 0f00000000;
	mov.f32 	%f1389, 0f35BFBE8E;
	mov.f32 	%f1388, 0f3F317200;
	mov.f32 	%f1387, 0f3DAAAABD;
	mov.f32 	%f1386, 0f3C4CAF63;
	mov.f32 	%f1385, 0f3B18F0FE;
	rcp.rn.f32 	%f200, %f1498;
	abs.f32 	%f201, %f200;
	setp.lt.f32	%p96, %f201, 0f00800000;
	mul.f32 	%f777, %f201, 0f4B800000;
	selp.f32	%f778, %f777, %f201, %p96;
	selp.f32	%f779, 0fC3170000, 0fC2FE0000, %p96;
	mov.b32 	 %r78, %f778;
	and.b32  	%r79, %r78, 8388607;
	or.b32  	%r80, %r79, 1065353216;
	mov.b32 	 %f780, %r80;
	shr.u32 	%r81, %r78, 23;
	cvt.rn.f32.u32	%f781, %r81;
	add.f32 	%f782, %f779, %f781;
	setp.gt.f32	%p97, %f780, 0f3FB504F3;
	mul.f32 	%f783, %f780, 0f3F000000;
	add.f32 	%f784, %f782, 0f3F800000;
	selp.f32	%f785, %f784, %f782, %p97;
	selp.f32	%f786, %f783, %f780, %p97;
	add.f32 	%f787, %f786, 0fBF800000;
	add.f32 	%f788, %f786, 0f3F800000;
	rcp.approx.ftz.f32 	%f789, %f788;
	add.f32 	%f790, %f787, %f787;
	mul.f32 	%f791, %f789, %f790;
	mul.f32 	%f792, %f791, %f791;
	fma.rn.f32 	%f795, %f1385, %f792, %f1386;
	fma.rn.f32 	%f797, %f795, %f792, %f1387;
	mul.rn.f32 	%f798, %f797, %f792;
	mul.rn.f32 	%f799, %f798, %f791;
	sub.f32 	%f800, %f787, %f791;
	neg.f32 	%f801, %f791;
	add.f32 	%f802, %f800, %f800;
	fma.rn.f32 	%f803, %f801, %f787, %f802;
	mul.rn.f32 	%f804, %f789, %f803;
	add.f32 	%f805, %f799, %f791;
	sub.f32 	%f806, %f791, %f805;
	add.f32 	%f807, %f799, %f806;
	add.f32 	%f808, %f804, %f807;
	add.f32 	%f809, %f805, %f808;
	sub.f32 	%f810, %f805, %f809;
	add.f32 	%f811, %f808, %f810;
	mul.rn.f32 	%f813, %f785, %f1388;
	mul.rn.f32 	%f815, %f785, %f1389;
	add.f32 	%f816, %f813, %f809;
	sub.f32 	%f817, %f813, %f816;
	add.f32 	%f818, %f809, %f817;
	add.f32 	%f819, %f811, %f818;
	add.f32 	%f820, %f815, %f819;
	add.f32 	%f821, %f816, %f820;
	sub.f32 	%f822, %f816, %f821;
	add.f32 	%f823, %f820, %f822;
	mul.rn.f32 	%f825, %f371, %f821;
	neg.f32 	%f826, %f825;
	fma.rn.f32 	%f827, %f371, %f821, %f826;
	fma.rn.f32 	%f828, %f371, %f823, %f827;
	fma.rn.f32 	%f830, %f1390, %f821, %f828;
	add.rn.f32 	%f831, %f825, %f830;
	neg.f32 	%f832, %f831;
	add.rn.f32 	%f833, %f825, %f832;
	add.rn.f32 	%f834, %f833, %f830;
	mov.b32 	 %r82, %f831;
	setp.eq.s32	%p98, %r82, 1118925336;
	add.s32 	%r83, %r82, -1;
	mov.b32 	 %f835, %r83;
	add.f32 	%f836, %f834, 0f37000000;
	selp.f32	%f202, %f836, %f834, %p98;
	selp.f32	%f837, %f835, %f831, %p98;
	mul.rn.f32 	%f839, %f837, %f433;
	cvt.rzi.f32.f32	%f840, %f839;
	abs.f32 	%f841, %f840;
	setp.gt.f32	%p99, %f841, 0f42FC0000;
	mov.b32 	 %r84, %f840;
	and.b32  	%r85, %r84, -2147483648;
	or.b32  	%r86, %r85, 1123811328;
	mov.b32 	 %f842, %r86;
	selp.f32	%f843, %f842, %f840, %p99;
	fma.rn.f32 	%f845, %f843, %f439, %f837;
	fma.rn.f32 	%f847, %f843, %f441, %f845;
	mul.f32 	%f848, %f847, 0f3FB8AA3B;
	add.f32 	%f849, %f843, 0f4B40007F;
	mov.b32 	 %r87, %f849;
	shl.b32 	%r88, %r87, 23;
	mov.b32 	 %f850, %r88;
	ex2.approx.ftz.f32 	%f851, %f848;
	mul.f32 	%f1499, %f851, %f850;
	setp.eq.f32	%p100, %f1499, 0f7F800000;
	@%p100 bra 	BB0_106;

	fma.rn.f32 	%f1499, %f1499, %f202, %f1499;

BB0_106:
	setp.geu.f32	%p102, %f200, 0f00000000;
	or.pred  	%p3, %p102, %p33;
	setp.eq.f32	%p103, %f200, 0f00000000;
	@%p103 bra 	BB0_110;
	bra.uni 	BB0_107;

BB0_110:
	mov.f32 	%f1444, 0f3F800000;
	cvt.rzi.f32.f32	%f1443, %f1444;
	add.f32 	%f1442, %f1443, %f1443;
	mov.f32 	%f1441, 0f40000000;
	sub.f32 	%f1440, %f1441, %f1442;
	abs.f32 	%f1439, %f1440;
	setp.eq.f32	%p106, %f1439, 0f3F800000;
	add.f32 	%f856, %f200, %f200;
	selp.f32	%f1501, %f856, 0f00000000, %p106;
	bra.uni 	BB0_111;

BB0_107:
	mov.b32 	 %r89, %f1499;
	xor.b32  	%r90, %r89, -2147483648;
	mov.b32 	 %f852, %r90;
	selp.f32	%f1501, %f1499, %f852, %p3;
	@%p102 bra 	BB0_111;

	mov.f32 	%f1447, 0f40000000;
	cvt.rzi.f32.f32	%f854, %f1447;
	setp.eq.f32	%p105, %f854, 0f40000000;
	@%p105 bra 	BB0_111;

	mov.f32 	%f1501, 0f7FFFFFFF;

BB0_111:
	abs.f32 	%f1351, %f200;
	add.f32 	%f857, %f1351, 0f40000000;
	mov.b32 	 %r91, %f857;
	setp.lt.s32	%p107, %r91, 2139095040;
	@%p107 bra 	BB0_116;

	abs.f32 	%f1376, %f200;
	setp.gtu.f32	%p108, %f1376, 0f7F800000;
	@%p108 bra 	BB0_115;
	bra.uni 	BB0_113;

BB0_115:
	add.f32 	%f1501, %f200, 0f40000000;
	bra.uni 	BB0_116;

BB0_113:
	abs.f32 	%f1377, %f200;
	setp.neu.f32	%p109, %f1377, 0f7F800000;
	@%p109 bra 	BB0_116;

	selp.f32	%f1501, 0f7F800000, 0fFF800000, %p3;

BB0_116:
	setp.eq.f32	%p110, %f200, 0f3F800000;
	selp.f32	%f858, 0f3F800000, %f1501, %p110;
	rcp.rn.f32 	%f859, %f195;
	sub.f32 	%f212, %f859, %f858;
	mul.f32 	%f213, %f186, %f186;
	abs.f32 	%f214, %f186;
	setp.ltu.f32	%p111, %f214, 0f3F800000;
	@%p111 bra 	BB0_118;
	bra.uni 	BB0_117;

BB0_118:
	mov.f32 	%f880, 0f394FFF49;
	mov.f32 	%f881, 0f363D0ADA;
	fma.rn.f32 	%f882, %f881, %f213, %f880;
	mov.f32 	%f883, 0f3C08889A;
	fma.rn.f32 	%f884, %f882, %f213, %f883;
	mov.f32 	%f885, 0f3E2AAAAB;
	fma.rn.f32 	%f886, %f884, %f213, %f885;
	mul.f32 	%f887, %f213, %f886;
	fma.rn.f32 	%f1502, %f887, %f186, %f186;
	bra.uni 	BB0_119;

BB0_117:
	mov.f32 	%f1445, 0f40000000;
	mov.f32 	%f1354, 0f3102E308;
	mov.f32 	%f1353, 0fBF317218;
	mov.f32 	%f1352, 0f3FB8AA3B;
	mul.rn.f32 	%f861, %f214, %f1352;
	cvt.rzi.f32.f32	%f862, %f861;
	abs.f32 	%f863, %f862;
	setp.gt.f32	%p112, %f863, 0f42FC0000;
	mov.b32 	 %r92, %f862;
	and.b32  	%r93, %r92, -2147483648;
	or.b32  	%r94, %r93, 1123811328;
	mov.b32 	 %f864, %r94;
	selp.f32	%f865, %f864, %f862, %p112;
	fma.rn.f32 	%f867, %f865, %f1353, %f214;
	fma.rn.f32 	%f869, %f865, %f1354, %f867;
	mul.f32 	%f870, %f869, 0f3FB8AA3B;
	add.f32 	%f871, %f865, 0f4B40007D;
	mov.b32 	 %r95, %f871;
	shl.b32 	%r96, %r95, 23;
	mov.b32 	 %f872, %r96;
	ex2.approx.ftz.f32 	%f873, %f870;
	mul.f32 	%f874, %f873, %f872;
	mov.f32 	%f875, 0f3E000000;
	div.approx.f32 	%f876, %f875, %f874;
	neg.f32 	%f877, %f876;
	fma.rn.f32 	%f879, %f1445, %f874, %f877;
	mov.b32 	 %r97, %f879;
	setp.ltu.f32	%p113, %f214, 0f42B40000;
	selp.b32	%r98, %r97, 2139095040, %p113;
	mov.b32 	 %r99, %f186;
	and.b32  	%r100, %r99, -2147483648;
	or.b32  	%r101, %r98, %r100;
	mov.b32 	 %f1502, %r101;

BB0_119:
	mov.f32 	%f1446, 0f40000000;
	mov.f32 	%f1363, 0f3102E308;
	mov.f32 	%f1362, 0fBF317218;
	mov.f32 	%f1361, 0f3FB8AA3B;
	mov.f32 	%f1360, 0f00000000;
	mov.f32 	%f1359, 0f35BFBE8E;
	mov.f32 	%f1358, 0f3F317200;
	mov.f32 	%f1357, 0f3DAAAABD;
	mov.f32 	%f1356, 0f3C4CAF63;
	mov.f32 	%f1355, 0f3B18F0FE;
	rcp.rn.f32 	%f218, %f1502;
	abs.f32 	%f219, %f218;
	setp.lt.f32	%p114, %f219, 0f00800000;
	mul.f32 	%f888, %f219, 0f4B800000;
	selp.f32	%f889, %f888, %f219, %p114;
	selp.f32	%f890, 0fC3170000, 0fC2FE0000, %p114;
	mov.b32 	 %r102, %f889;
	and.b32  	%r103, %r102, 8388607;
	or.b32  	%r104, %r103, 1065353216;
	mov.b32 	 %f891, %r104;
	shr.u32 	%r105, %r102, 23;
	cvt.rn.f32.u32	%f892, %r105;
	add.f32 	%f893, %f890, %f892;
	setp.gt.f32	%p115, %f891, 0f3FB504F3;
	mul.f32 	%f894, %f891, 0f3F000000;
	add.f32 	%f895, %f893, 0f3F800000;
	selp.f32	%f896, %f895, %f893, %p115;
	selp.f32	%f897, %f894, %f891, %p115;
	add.f32 	%f898, %f897, 0fBF800000;
	add.f32 	%f899, %f897, 0f3F800000;
	rcp.approx.ftz.f32 	%f900, %f899;
	add.f32 	%f901, %f898, %f898;
	mul.f32 	%f902, %f900, %f901;
	mul.f32 	%f903, %f902, %f902;
	fma.rn.f32 	%f906, %f1355, %f903, %f1356;
	fma.rn.f32 	%f908, %f906, %f903, %f1357;
	mul.rn.f32 	%f909, %f908, %f903;
	mul.rn.f32 	%f910, %f909, %f902;
	sub.f32 	%f911, %f898, %f902;
	neg.f32 	%f912, %f902;
	add.f32 	%f913, %f911, %f911;
	fma.rn.f32 	%f914, %f912, %f898, %f913;
	mul.rn.f32 	%f915, %f900, %f914;
	add.f32 	%f916, %f910, %f902;
	sub.f32 	%f917, %f902, %f916;
	add.f32 	%f918, %f910, %f917;
	add.f32 	%f919, %f915, %f918;
	add.f32 	%f920, %f916, %f919;
	sub.f32 	%f921, %f916, %f920;
	add.f32 	%f922, %f919, %f921;
	mul.rn.f32 	%f924, %f896, %f1358;
	mul.rn.f32 	%f926, %f896, %f1359;
	add.f32 	%f927, %f924, %f920;
	sub.f32 	%f928, %f924, %f927;
	add.f32 	%f929, %f920, %f928;
	add.f32 	%f930, %f922, %f929;
	add.f32 	%f931, %f926, %f930;
	add.f32 	%f932, %f927, %f931;
	sub.f32 	%f933, %f927, %f932;
	add.f32 	%f934, %f931, %f933;
	mul.rn.f32 	%f936, %f1446, %f932;
	neg.f32 	%f937, %f936;
	fma.rn.f32 	%f938, %f1446, %f932, %f937;
	fma.rn.f32 	%f939, %f1446, %f934, %f938;
	fma.rn.f32 	%f941, %f1360, %f932, %f939;
	add.rn.f32 	%f942, %f936, %f941;
	neg.f32 	%f943, %f942;
	add.rn.f32 	%f944, %f936, %f943;
	add.rn.f32 	%f945, %f944, %f941;
	mov.b32 	 %r106, %f942;
	setp.eq.s32	%p116, %r106, 1118925336;
	add.s32 	%r107, %r106, -1;
	mov.b32 	 %f946, %r107;
	add.f32 	%f947, %f945, 0f37000000;
	selp.f32	%f220, %f947, %f945, %p116;
	selp.f32	%f948, %f946, %f942, %p116;
	mul.rn.f32 	%f950, %f948, %f1361;
	cvt.rzi.f32.f32	%f951, %f950;
	abs.f32 	%f952, %f951;
	setp.gt.f32	%p117, %f952, 0f42FC0000;
	mov.b32 	 %r108, %f951;
	and.b32  	%r109, %r108, -2147483648;
	or.b32  	%r110, %r109, 1123811328;
	mov.b32 	 %f953, %r110;
	selp.f32	%f954, %f953, %f951, %p117;
	fma.rn.f32 	%f956, %f954, %f1362, %f948;
	fma.rn.f32 	%f958, %f954, %f1363, %f956;
	mul.f32 	%f959, %f958, 0f3FB8AA3B;
	add.f32 	%f960, %f954, 0f4B40007F;
	mov.b32 	 %r111, %f960;
	shl.b32 	%r112, %r111, 23;
	mov.b32 	 %f961, %r112;
	ex2.approx.ftz.f32 	%f962, %f959;
	mul.f32 	%f1503, %f962, %f961;
	setp.eq.f32	%p118, %f1503, 0f7F800000;
	@%p118 bra 	BB0_121;

	fma.rn.f32 	%f1503, %f1503, %f220, %f1503;

BB0_121:
	setp.geu.f32	%p120, %f218, 0f00000000;
	or.pred  	%p4, %p120, %p33;
	setp.eq.f32	%p121, %f218, 0f00000000;
	@%p121 bra 	BB0_125;
	bra.uni 	BB0_122;

BB0_125:
	mov.f32 	%f1410, 0f3F800000;
	cvt.rzi.f32.f32	%f1409, %f1410;
	add.f32 	%f1408, %f1409, %f1409;
	mov.f32 	%f1407, 0f40000000;
	sub.f32 	%f1406, %f1407, %f1408;
	abs.f32 	%f1405, %f1406;
	setp.eq.f32	%p124, %f1405, 0f3F800000;
	add.f32 	%f967, %f218, %f218;
	selp.f32	%f1505, %f967, 0f00000000, %p124;
	bra.uni 	BB0_126;

BB0_122:
	mov.b32 	 %r113, %f1503;
	xor.b32  	%r114, %r113, -2147483648;
	mov.b32 	 %f963, %r114;
	selp.f32	%f1505, %f1503, %f963, %p4;
	@%p120 bra 	BB0_126;

	mov.f32 	%f1404, 0f40000000;
	cvt.rzi.f32.f32	%f965, %f1404;
	setp.eq.f32	%p123, %f965, 0f40000000;
	@%p123 bra 	BB0_126;

	mov.f32 	%f1505, 0f7FFFFFFF;

BB0_126:
	abs.f32 	%f1398, %f218;
	add.f32 	%f968, %f1398, 0f40000000;
	mov.b32 	 %r115, %f968;
	setp.lt.s32	%p125, %r115, 2139095040;
	@%p125 bra 	BB0_131;

	abs.f32 	%f1402, %f218;
	setp.gtu.f32	%p126, %f1402, 0f7F800000;
	@%p126 bra 	BB0_130;
	bra.uni 	BB0_128;

BB0_130:
	add.f32 	%f1505, %f218, 0f40000000;
	bra.uni 	BB0_131;

BB0_128:
	abs.f32 	%f1403, %f218;
	setp.neu.f32	%p127, %f1403, 0f7F800000;
	@%p127 bra 	BB0_131;

	selp.f32	%f1505, 0f7F800000, 0fFF800000, %p4;

BB0_131:
	mul.f32 	%f1399, %f1495, 0f19858734;
	mov.f32 	%f1364, 0f3F800000;
	setp.eq.f32	%p128, %f218, 0f3F800000;
	selp.f32	%f969, 0f3F800000, %f1505, %p128;
	rcp.rn.f32 	%f970, %f213;
	sub.f32 	%f971, %f970, %f969;
	mul.f32 	%f972, %f187, %f212;
	mul.f32 	%f973, %f1494, %f972;
	div.rn.f32 	%f974, %f973, %f1399;
	mul.f32 	%f975, %f189, %f971;
	sub.f32 	%f977, %f1364, %f975;
	mul.f32 	%f978, %f188, %f212;
	mul.f32 	%f979, %f978, %f977;
	fma.rn.f32 	%f980, %f974, %f971, %f979;
	mul.f32 	%f981, %f190, %f212;
	sub.f32 	%f982, %f1364, %f981;
	mul.f32 	%f983, %f982, %f977;
	mul.f32 	%f984, %f191, %f212;
	mul.f32 	%f985, %f1494, %f984;
	div.rn.f32 	%f986, %f985, %f1399;
	mul.f32 	%f987, %f986, %f971;
	sub.f32 	%f988, %f983, %f987;
	div.rn.f32 	%f1506, %f980, %f988;
	mul.f32 	%f989, %f188, %f971;
	mul.f32 	%f990, %f1493, %f989;
	div.rn.f32 	%f991, %f990, %f1399;
	mul.f32 	%f992, %f187, %f971;
	mul.f32 	%f993, %f192, %f971;
	mul.f32 	%f994, %f1493, %f993;
	div.rn.f32 	%f995, %f994, %f1399;
	mul.f32 	%f996, %f212, %f995;
	mul.f32 	%f997, %f982, %f992;
	fma.rn.f32 	%f998, %f212, %f991, %f997;
	sub.f32 	%f999, %f983, %f996;
	div.rn.f32 	%f1507, %f998, %f999;

BB0_132:
	mul.f32 	%f1000, %f2, %f5;
	fma.rn.f32 	%f1001, %f1, %f4, %f1000;
	fma.rn.f32 	%f1002, %f3, %f6, %f1001;
	abs.f32 	%f1003, %f1002;
	div.rn.f32 	%f1512, %f1003, %f54;
	div.rn.f32 	%f235, %f1003, %f53;
	div.rn.f32 	%f236, %f1494, %f1460;
	mul.f32 	%f1004, %f1507, %f236;
	div.rn.f32 	%f1005, %f1004, %f1506;
	rcp.rn.f32 	%f1006, %f1506;
	add.f32 	%f237, %f1006, %f1005;
	div.rn.f32 	%f238, %f1493, %f1461;
	mul.f32 	%f1007, %f1506, %f238;
	div.rn.f32 	%f1008, %f1007, %f1507;
	rcp.rn.f32 	%f1009, %f1507;
	add.f32 	%f1513, %f1009, %f1008;
	setp.gt.f32	%p129, %f1495, %f94;
	@%p129 bra 	BB0_134;
	bra.uni 	BB0_133;

BB0_134:
	mul.f32 	%f1028, %f1, %f237;
	mul.f32 	%f1029, %f2, %f237;
	mul.f32 	%f1030, %f3, %f237;
	mul.f32 	%f1031, %f235, %f236;
	div.rn.f32 	%f1032, %f1031, %f53;
	mul.f32 	%f1033, %f1, %f1032;
	mul.f32 	%f1034, %f2, %f1032;
	mul.f32 	%f1035, %f3, %f1032;
	sub.f32 	%f1508, %f1033, %f1028;
	sub.f32 	%f1509, %f1034, %f1029;
	sub.f32 	%f1510, %f1035, %f1030;
	mov.f32 	%f1511, %f54;
	bra.uni 	BB0_135;

BB0_133:
	sub.f32 	%f1010, %f53, %f180;
	div.rn.f32 	%f1011, %f1010, %f180;
	mul.f32 	%f1012, %f237, %f1011;
	mul.f32 	%f1013, %f1, %f1012;
	mul.f32 	%f1014, %f2, %f1012;
	mul.f32 	%f1015, %f3, %f1012;
	mul.f32 	%f1016, %f181, %f235;
	div.rn.f32 	%f1017, %f1016, %f54;
	sub.f32 	%f1018, %f235, %f1017;
	mul.f32 	%f1019, %f1018, %f236;
	div.rn.f32 	%f1020, %f1019, %f180;
	mul.f32 	%f1021, %f1, %f1020;
	mul.f32 	%f1022, %f2, %f1020;
	mul.f32 	%f1023, %f3, %f1020;
	sub.f32 	%f1508, %f1021, %f1013;
	sub.f32 	%f1509, %f1022, %f1014;
	sub.f32 	%f1510, %f1023, %f1015;
	sub.f32 	%f1024, %f54, %f181;
	div.rn.f32 	%f1025, %f1024, %f181;
	mul.f32 	%f1513, %f1513, %f1025;
	mul.f32 	%f1026, %f180, %f1512;
	div.rn.f32 	%f1027, %f1026, %f53;
	sub.f32 	%f1512, %f1512, %f1027;
	mov.f32 	%f1511, %f181;

BB0_135:
	setp.lt.f32	%p139, %f1495, %f94;
	mul.f32 	%f1036, %f4, %f1513;
	mul.f32 	%f1037, %f5, %f1513;
	mul.f32 	%f1038, %f6, %f1513;
	mul.f32 	%f1039, %f238, %f1512;
	div.rn.f32 	%f1040, %f1039, %f1511;
	mul.f32 	%f1041, %f4, %f1040;
	mul.f32 	%f1042, %f5, %f1040;
	mul.f32 	%f1043, %f6, %f1040;
	sub.f32 	%f254, %f1041, %f1036;
	sub.f32 	%f255, %f1042, %f1037;
	sub.f32 	%f256, %f1043, %f1038;
	add.f32 	%f257, %f1452, %f1452;
	add.f32 	%f258, %f1453, %f1453;
	@%p139 bra 	BB0_137;
	bra.uni 	BB0_136;

BB0_137:
	mul.f32 	%f1401, %f1495, 0f19858734;
	mov.f32 	%f1375, 0f3F800000;
	mul.f32 	%f1047, %f257, 0f19858734;
	mul.f32 	%f1048, %f1047, %f1495;
	mul.f32 	%f1049, %f1048, %f180;
	div.rn.f32 	%f1514, %f1049, %f182;
	mul.f32 	%f1050, %f258, 0f19858734;
	mul.f32 	%f1051, %f1050, %f1495;
	mul.f32 	%f1052, %f1051, %f181;
	div.rn.f32 	%f1515, %f1052, %f185;
	mul.f32 	%f1053, %f1401, %f180;
	div.rn.f32 	%f1054, %f1053, %f182;
	sub.f32 	%f1056, %f1375, %f1054;
	mul.f32 	%f1516, %f1452, %f1056;
	mul.f32 	%f1057, %f1401, %f181;
	div.rn.f32 	%f1058, %f1057, %f185;
	sub.f32 	%f1059, %f1375, %f1058;
	mul.f32 	%f1517, %f1453, %f1059;
	bra.uni 	BB0_138;

BB0_136:
	mul.f32 	%f1044, %f257, %f1495;
	mul.f32 	%f1045, %f94, 0f40400000;
	div.rn.f32 	%f1514, %f1044, %f1045;
	mul.f32 	%f1046, %f258, %f1495;
	div.rn.f32 	%f1515, %f1046, %f1045;
	mov.f32 	%f1516, %f1514;
	mov.f32 	%f1517, %f1515;

BB0_138:
	sub.f32 	%f1060, %f1516, %f1514;
	div.rn.f32 	%f1061, %f1455, %f1456;
	mul.f32 	%f1062, %f1060, %f1061;
	mul.f32 	%f1063, %f1451, %f1516;
	mul.f32 	%f1064, %f1516, %f1063;
	div.rn.f32 	%f1065, %f1062, %f1064;
	sqrt.rn.f32 	%f269, %f1065;
	sub.f32 	%f1066, %f1517, %f1515;
	div.rn.f32 	%f1067, %f1455, %f1457;
	mul.f32 	%f1068, %f1066, %f1067;
	mul.f32 	%f1069, %f1451, %f1517;
	mul.f32 	%f1070, %f1517, %f1069;
	div.rn.f32 	%f1071, %f1068, %f1070;
	sqrt.rn.f32 	%f270, %f1071;
	mul.f32 	%f1072, %f1514, %f1061;
	div.rn.f32 	%f1073, %f1072, %f1451;
	sqrt.rn.f32 	%f271, %f1073;
	mul.f32 	%f1074, %f1515, %f1067;
	div.rn.f32 	%f1075, %f1074, %f1451;
	sqrt.rn.f32 	%f272, %f1075;
	setp.gt.f32	%p131, %f1466, 0f00000000;
	@%p131 bra 	BB0_146;
	bra.uni 	BB0_139;

BB0_146:
	mov.f32 	%f1395, 0f3F800000;
	sub.f32 	%f1394, %f1395, %f1458;
	mul.f32 	%f1158, %f1394, %f1461;
	div.rn.f32 	%f1159, %f1158, %f1458;
	div.rn.f32 	%f1160, %f1159, %f1460;
	fma.rn.f32 	%f1161, %f54, %f1160, %f53;
	mul.f32 	%f1162, %f1466, %f1161;
	div.rn.f32 	%f1163, %f1162, %f53;
	div.rn.f32 	%f1164, %f1163, %f54;
	div.rn.f32 	%f1165, %f1460, %f1461;
	mul.f32 	%f1166, %f1508, %f1165;
	mul.f32 	%f1167, %f1509, %f1165;
	mul.f32 	%f1168, %f1510, %f1165;
	sub.f32 	%f1169, %f1166, %f254;
	sub.f32 	%f1170, %f1167, %f255;
	sub.f32 	%f1171, %f1168, %f256;
	mul.f32 	%f1172, %f1164, %f1169;
	mul.f32 	%f1173, %f1164, %f1170;
	mul.f32 	%f1174, %f1164, %f1171;
	mul.f32 	%f1518, %f1172, 0f00000000;
	mul.f32 	%f1519, %f1173, 0f00000000;
	mul.f32 	%f1520, %f1174, 0f00000000;
	add.f32 	%f1527, %f1527, %f1172;
	add.f32 	%f1528, %f1528, %f1173;
	add.f32 	%f1529, %f1529, %f1174;
	sub.f32 	%f1524, %f1524, %f1172;
	sub.f32 	%f1525, %f1525, %f1173;
	sub.f32 	%f1526, %f1526, %f1174;
	mov.f32 	%f1521, %f1518;
	mov.f32 	%f1522, %f1519;
	mov.f32 	%f1523, %f1520;
	bra.uni 	BB0_147;

BB0_139:
	mul.f32 	%f1400, %f1495, 0f19858734;
	mov.f32 	%f1372, 0f3F800000;
	mul.f32 	%f1371, %f1459, %f1463;
	sub.f32 	%f1370, %f1372, %f1458;
	mul.f32 	%f1369, %f1370, %f1371;
	mul.f32 	%f1368, %f1459, %f1462;
	mul.f32 	%f1367, %f1458, %f1368;
	mov.f32 	%f1366, 0f3F000000;
	mov.f32 	%f1365, 0f3FB8AA3B;
	rcp.rn.f32 	%f1076, %f1400;
	div.rn.f32 	%f1077, %f1367, %f1460;
	fma.rn.f32 	%f1078, %f1, %f1077, %f1527;
	fma.rn.f32 	%f1079, %f2, %f1077, %f1528;
	fma.rn.f32 	%f1080, %f3, %f1077, %f1529;
	div.rn.f32 	%f1081, %f44, %f1460;
	fma.rn.f32 	%f1082, %f4, %f1081, %f1078;
	fma.rn.f32 	%f1083, %f5, %f1081, %f1079;
	fma.rn.f32 	%f1084, %f6, %f1081, %f1080;
	div.rn.f32 	%f1085, %f1369, %f1461;
	fma.rn.f32 	%f1086, %f4, %f1085, %f1524;
	fma.rn.f32 	%f1087, %f5, %f1085, %f1525;
	fma.rn.f32 	%f1088, %f6, %f1085, %f1526;
	div.rn.f32 	%f1089, %f47, %f1461;
	fma.rn.f32 	%f1090, %f1, %f1089, %f1086;
	fma.rn.f32 	%f1091, %f2, %f1089, %f1087;
	fma.rn.f32 	%f1092, %f3, %f1089, %f1088;
	mul.f32 	%f1093, %f1460, %f1076;
	mul.f32 	%f1094, %f1093, %f1082;
	mul.f32 	%f1095, %f1093, %f1083;
	mul.f32 	%f1096, %f1093, %f1084;
	mul.f32 	%f1097, %f1461, %f1076;
	mul.f32 	%f1098, %f1097, %f1090;
	mul.f32 	%f1099, %f1097, %f1091;
	mul.f32 	%f1100, %f1097, %f1092;
	mul.f32 	%f1101, %f1095, %f1095;
	fma.rn.f32 	%f1102, %f1094, %f1094, %f1101;
	fma.rn.f32 	%f1103, %f1096, %f1096, %f1102;
	sqrt.rn.f32 	%f273, %f1103;
	mul.f32 	%f1104, %f1099, %f1099;
	fma.rn.f32 	%f1105, %f1098, %f1098, %f1104;
	fma.rn.f32 	%f1106, %f1100, %f1100, %f1105;
	sqrt.rn.f32 	%f274, %f1106;
	add.f32 	%f1107, %f273, %f273;
	mov.f32 	%f1109, 0f3BBB989D;
	fma.rn.f32 	%f1110, %f1107, %f1109, %f1366;
	cvt.sat.f32.f32	%f1111, %f1110;
	mov.f32 	%f1112, 0f4B400001;
	mov.f32 	%f1113, 0f437C0000;
	fma.rm.f32 	%f1114, %f1111, %f1113, %f1112;
	add.f32 	%f1115, %f1114, 0fCB40007F;
	neg.f32 	%f1116, %f1115;
	fma.rn.f32 	%f1118, %f1107, %f1365, %f1116;
	mov.f32 	%f1119, 0f32A57060;
	fma.rn.f32 	%f1120, %f1107, %f1119, %f1118;
	mov.b32 	 %r116, %f1114;
	shl.b32 	%r117, %r116, 23;
	mov.b32 	 %f1121, %r117;
	ex2.approx.ftz.f32 	%f1122, %f1120;
	mul.f32 	%f1123, %f1122, %f1121;
	cvt.f64.f32	%fd38, %f1123;
	add.f64 	%fd4, %fd38, 0d3FF0000000000000;
	abs.f64 	%fd39, %fd4;
	setp.gt.f64	%p132, %fd39, 0d7FE1CCF385EBC8A0;
	@%p132 bra 	BB0_141;
	bra.uni 	BB0_140;

BB0_141:
	setp.gt.f32	%p134, %f273, 0f00000000;
	selp.f64	%fd54, 0d3FF0000000000000, 0dBFF0000000000000, %p134;
	bra.uni 	BB0_142;

BB0_140:
	add.f64 	%fd40, %fd4, 0dC000000000000000;
	div.rn.f64 	%fd41, %fd4, %fd40;
	cvt.f64.f32	%fd42, %f273;
	mov.f64 	%fd43, 0dBFF0000000000000;
	div.rn.f64 	%fd44, %fd43, %fd42;
	add.f64 	%fd45, %fd41, %fd44;
	setp.lt.f64	%p133, %fd45, 0d3F9EB851EB851EB8;
	selp.f64	%fd54, 0d3F9EB851EB851EB8, %fd45, %p133;

BB0_142:
	mov.f32 	%f1374, 0f3F000000;
	mov.f32 	%f1373, 0f3FB8AA3B;
	cvt.rn.f32.f64	%f1124, %fd54;
	mul.f32 	%f1125, %f257, %f1124;
	div.rn.f32 	%f275, %f1125, %f273;
	add.f32 	%f1126, %f274, %f274;
	fma.rn.f32 	%f1129, %f1126, %f1109, %f1374;
	cvt.sat.f32.f32	%f1130, %f1129;
	fma.rm.f32 	%f1133, %f1130, %f1113, %f1112;
	add.f32 	%f1134, %f1133, 0fCB40007F;
	neg.f32 	%f1135, %f1134;
	fma.rn.f32 	%f1137, %f1126, %f1373, %f1135;
	fma.rn.f32 	%f1139, %f1126, %f1119, %f1137;
	mov.b32 	 %r118, %f1133;
	shl.b32 	%r119, %r118, 23;
	mov.b32 	 %f1140, %r119;
	ex2.approx.ftz.f32 	%f1141, %f1139;
	mul.f32 	%f1142, %f1141, %f1140;
	cvt.f64.f32	%fd46, %f1142;
	add.f64 	%fd8, %fd46, 0d3FF0000000000000;
	abs.f64 	%fd47, %fd8;
	setp.gt.f64	%p135, %fd47, 0d7FE1CCF385EBC8A0;
	@%p135 bra 	BB0_144;
	bra.uni 	BB0_143;

BB0_144:
	setp.gt.f32	%p137, %f274, 0f00000000;
	selp.f64	%fd55, 0d3FF0000000000000, 0dBFF0000000000000, %p137;
	bra.uni 	BB0_145;

BB0_143:
	add.f64 	%fd48, %fd8, 0dC000000000000000;
	div.rn.f64 	%fd49, %fd8, %fd48;
	cvt.f64.f32	%fd50, %f274;
	mov.f64 	%fd51, 0dBFF0000000000000;
	div.rn.f64 	%fd52, %fd51, %fd50;
	add.f64 	%fd53, %fd49, %fd52;
	setp.lt.f64	%p136, %fd53, 0d3F9EB851EB851EB8;
	selp.f64	%fd55, 0d3F9EB851EB851EB8, %fd53, %p136;

BB0_145:
	mov.f32 	%f1393, 0f3F800000;
	sub.f32 	%f1392, %f1393, %f1458;
	cvt.rn.f32.f64	%f1143, %fd55;
	mul.f32 	%f1144, %f258, %f1143;
	div.rn.f32 	%f1145, %f1144, %f274;
	div.rn.f32 	%f1146, %f275, %f1459;
	div.rn.f32 	%f1147, %f1146, %f1458;
	div.rn.f32 	%f1148, %f1147, %f53;
	div.rn.f32 	%f1151, %f1145, %f1392;
	div.rn.f32 	%f1152, %f1151, %f1459;
	div.rn.f32 	%f1153, %f1152, %f54;
	add.f32 	%f1154, %f1148, %f1153;
	mul.f32 	%f1155, %f1154, 0f3F000000;
	setp.gt.f32	%p138, %f1155, 0f41200000;
	selp.f32	%f1466, 0f41200000, %f1155, %p138;
	neg.f32 	%f1521, %f1508;
	neg.f32 	%f1522, %f1509;
	neg.f32 	%f1523, %f1510;
	neg.f32 	%f1518, %f254;
	neg.f32 	%f1519, %f255;
	neg.f32 	%f1520, %f256;

BB0_147:
	neg.f32 	%f1175, %f44;
	mul.f32 	%f1176, %f1460, %f53;
	mul.f32 	%f1177, %f53, %f1176;
	div.rn.f32 	%f1178, %f1175, %f1177;
	mul.f32 	%f1179, %f3, %f5;
	mul.f32 	%f1180, %f2, %f6;
	sub.f32 	%f1181, %f1180, %f1179;
	mul.f32 	%f1182, %f1, %f6;
	mul.f32 	%f1183, %f3, %f4;
	sub.f32 	%f1184, %f1183, %f1182;
	mul.f32 	%f1185, %f2, %f4;
	mul.f32 	%f1186, %f1, %f5;
	sub.f32 	%f1187, %f1186, %f1185;
	neg.f32 	%f1188, %f47;
	mul.f32 	%f1189, %f1461, %f54;
	mul.f32 	%f1190, %f54, %f1189;
	div.rn.f32 	%f1191, %f1188, %f1190;
	sub.f32 	%f1192, %f1179, %f1180;
	sub.f32 	%f1193, %f1182, %f1183;
	sub.f32 	%f1194, %f1185, %f1186;
	add.f32 	%f1195, %f1508, %f1527;
	mul.f32 	%f1196, %f3, %f1184;
	mul.f32 	%f1197, %f2, %f1187;
	sub.f32 	%f1198, %f1197, %f1196;
	fma.rn.f32 	%f1199, %f1198, %f1178, %f1195;
	add.f32 	%f1200, %f1509, %f1528;
	mul.f32 	%f1201, %f1, %f1187;
	mul.f32 	%f1202, %f3, %f1181;
	sub.f32 	%f1203, %f1202, %f1201;
	fma.rn.f32 	%f1204, %f1203, %f1178, %f1200;
	add.f32 	%f1205, %f1510, %f1529;
	mul.f32 	%f1206, %f2, %f1181;
	mul.f32 	%f1207, %f1, %f1184;
	sub.f32 	%f1208, %f1207, %f1206;
	fma.rn.f32 	%f1209, %f1208, %f1178, %f1205;
	add.f32 	%f1210, %f254, %f1524;
	mul.f32 	%f1211, %f6, %f1193;
	mul.f32 	%f1212, %f5, %f1194;
	sub.f32 	%f1213, %f1212, %f1211;
	fma.rn.f32 	%f1214, %f1213, %f1191, %f1210;
	add.f32 	%f1215, %f255, %f1525;
	mul.f32 	%f1216, %f4, %f1194;
	mul.f32 	%f1217, %f6, %f1192;
	sub.f32 	%f1218, %f1217, %f1216;
	fma.rn.f32 	%f1219, %f1218, %f1191, %f1215;
	add.f32 	%f1220, %f256, %f1526;
	mul.f32 	%f1221, %f5, %f1192;
	mul.f32 	%f1222, %f4, %f1193;
	sub.f32 	%f1223, %f1222, %f1221;
	fma.rn.f32 	%f1224, %f1223, %f1191, %f1220;
	fma.rn.f32 	%f1225, %f55, %f269, %f1199;
	fma.rn.f32 	%f1226, %f56, %f269, %f1204;
	fma.rn.f32 	%f1227, %f57, %f269, %f1209;
	fma.rn.f32 	%f1228, %f61, %f270, %f1214;
	fma.rn.f32 	%f1229, %f62, %f270, %f1219;
	fma.rn.f32 	%f1230, %f63, %f270, %f1224;
	mul.f32 	%f1231, %f2, %f1209;
	mul.f32 	%f1232, %f3, %f1204;
	sub.f32 	%f1233, %f1231, %f1232;
	mul.f32 	%f1234, %f3, %f1199;
	mul.f32 	%f1235, %f1, %f1209;
	sub.f32 	%f1236, %f1234, %f1235;
	mul.f32 	%f1237, %f1, %f1204;
	mul.f32 	%f1238, %f2, %f1199;
	sub.f32 	%f1239, %f1237, %f1238;
	mul.f32 	%f1240, %f5, %f1224;
	mul.f32 	%f1241, %f6, %f1219;
	sub.f32 	%f1242, %f1240, %f1241;
	mul.f32 	%f1243, %f6, %f1214;
	mul.f32 	%f1244, %f4, %f1224;
	sub.f32 	%f1245, %f1243, %f1244;
	mul.f32 	%f1246, %f4, %f1219;
	mul.f32 	%f1247, %f5, %f1214;
	sub.f32 	%f1248, %f1246, %f1247;
	mul.f32 	%f1249, %f2, %f1204;
	fma.rn.f32 	%f1250, %f1, %f1199, %f1249;
	fma.rn.f32 	%f1251, %f3, %f1209, %f1250;
	mul.f32 	%f1252, %f5, %f1219;
	fma.rn.f32 	%f1253, %f4, %f1214, %f1252;
	fma.rn.f32 	%f1254, %f6, %f1224, %f1253;
	mul.f32 	%f1255, %f2, %f1227;
	mul.f32 	%f1256, %f3, %f1226;
	sub.f32 	%f1257, %f1255, %f1256;
	mul.f32 	%f1258, %f3, %f1225;
	mul.f32 	%f1259, %f1, %f1227;
	sub.f32 	%f1260, %f1258, %f1259;
	mul.f32 	%f1261, %f1, %f1226;
	mul.f32 	%f1262, %f2, %f1225;
	sub.f32 	%f1263, %f1261, %f1262;
	mul.f32 	%f1264, %f5, %f1230;
	mul.f32 	%f1265, %f6, %f1229;
	sub.f32 	%f1266, %f1264, %f1265;
	mul.f32 	%f1267, %f6, %f1228;
	mul.f32 	%f1268, %f4, %f1230;
	sub.f32 	%f1269, %f1267, %f1268;
	mul.f32 	%f1270, %f4, %f1229;
	mul.f32 	%f1271, %f5, %f1228;
	sub.f32 	%f1272, %f1270, %f1271;
	mul.f32 	%f1273, %f2, %f1263;
	mul.f32 	%f1274, %f3, %f1260;
	sub.f32 	%f1275, %f1273, %f1274;
	mul.f32 	%f1276, %f3, %f1257;
	mul.f32 	%f1277, %f1, %f1263;
	sub.f32 	%f1278, %f1276, %f1277;
	mul.f32 	%f1279, %f1, %f1260;
	mul.f32 	%f1280, %f2, %f1257;
	sub.f32 	%f1281, %f1279, %f1280;
	mul.f32 	%f1282, %f5, %f1272;
	mul.f32 	%f1283, %f6, %f1269;
	sub.f32 	%f1284, %f1282, %f1283;
	mul.f32 	%f1285, %f6, %f1266;
	mul.f32 	%f1286, %f4, %f1272;
	sub.f32 	%f1287, %f1285, %f1286;
	mul.f32 	%f1288, %f4, %f1269;
	mul.f32 	%f1289, %f5, %f1266;
	sub.f32 	%f1290, %f1288, %f1289;
	fma.rn.f32 	%f1291, %f1516, %f1516, 0f3F800000;
	rcp.rn.f32 	%f1292, %f1291;
	fma.rn.f32 	%f1293, %f1517, %f1517, 0f3F800000;
	rcp.rn.f32 	%f1294, %f1293;
	mul.f32 	%f1295, %f1233, %f1292;
	mul.f32 	%f1296, %f1236, %f1292;
	mul.f32 	%f1297, %f1239, %f1292;
	mul.f32 	%f1298, %f1514, %f1292;
	div.rn.f32 	%f1299, %f1298, %f53;
	div.rn.f32 	%f1300, %f1299, %f53;
	mul.f32 	%f1301, %f1251, %f1300;
	mul.f32 	%f1302, %f1, %f1301;
	mul.f32 	%f1303, %f2, %f1301;
	mul.f32 	%f1304, %f3, %f1301;
	sub.f32 	%f1305, %f1302, %f1295;
	sub.f32 	%f1306, %f1303, %f1296;
	sub.f32 	%f1307, %f1304, %f1297;
	mul.f32 	%f1308, %f1516, %f1292;
	div.rn.f32 	%f1309, %f1308, %f53;
	div.rn.f32 	%f1310, %f1309, %f53;
	mul.f32 	%f1311, %f1310, %f1275;
	mul.f32 	%f1312, %f1310, %f1278;
	mul.f32 	%f1313, %f1310, %f1281;
	sub.f32 	%f1314, %f1305, %f1311;
	sub.f32 	%f1315, %f1306, %f1312;
	sub.f32 	%f1316, %f1307, %f1313;
	fma.rn.f32 	%f1317, %f58, %f271, %f1314;
	fma.rn.f32 	%f1318, %f59, %f271, %f1315;
	fma.rn.f32 	%f1319, %f60, %f271, %f1316;
	sub.f32 	%f1320, %f1521, %f1518;
	mul.f32 	%f1321, %f1320, %f1466;
	sub.f32 	%f1322, %f1522, %f1519;
	mul.f32 	%f1323, %f1322, %f1466;
	sub.f32 	%f1324, %f1523, %f1520;
	mul.f32 	%f1325, %f1324, %f1466;
	sub.f32 	%f1534, %f1317, %f1321;
	sub.f32 	%f1535, %f1318, %f1323;
	sub.f32 	%f1536, %f1319, %f1325;
	mul.f32 	%f1326, %f1242, %f1294;
	mul.f32 	%f1327, %f1245, %f1294;
	mul.f32 	%f1328, %f1248, %f1294;
	mul.f32 	%f1329, %f1515, %f1294;
	div.rn.f32 	%f1330, %f1329, %f54;
	div.rn.f32 	%f1331, %f1330, %f54;
	mul.f32 	%f1332, %f1254, %f1331;
	mul.f32 	%f1333, %f4, %f1332;
	mul.f32 	%f1334, %f5, %f1332;
	mul.f32 	%f1335, %f6, %f1332;
	sub.f32 	%f1336, %f1333, %f1326;
	sub.f32 	%f1337, %f1334, %f1327;
	sub.f32 	%f1338, %f1335, %f1328;
	mul.f32 	%f1339, %f1517, %f1294;
	div.rn.f32 	%f1340, %f1339, %f54;
	div.rn.f32 	%f1341, %f1340, %f54;
	mul.f32 	%f1342, %f1284, %f1341;
	mul.f32 	%f1343, %f1287, %f1341;
	mul.f32 	%f1344, %f1290, %f1341;
	sub.f32 	%f1345, %f1336, %f1342;
	sub.f32 	%f1346, %f1337, %f1343;
	sub.f32 	%f1347, %f1338, %f1344;
	fma.rn.f32 	%f1348, %f64, %f272, %f1345;
	fma.rn.f32 	%f1349, %f65, %f272, %f1346;
	fma.rn.f32 	%f1350, %f66, %f272, %f1347;
	add.f32 	%f1531, %f1321, %f1348;
	add.f32 	%f1532, %f1323, %f1349;
	add.f32 	%f1533, %f1325, %f1350;

BB0_149:
	ld.param.u64 	%rd164, [LLBtorqueAF2TPRB054401_param_8];
	ld.param.u64 	%rd163, [LLBtorqueAF2TPRB054401_param_7];
	ld.param.u64 	%rd162, [LLBtorqueAF2TPRB054401_param_6];
	ld.param.u64 	%rd161, [LLBtorqueAF2TPRB054401_param_2];
	ld.param.u64 	%rd160, [LLBtorqueAF2TPRB054401_param_1];
	ld.param.u64 	%rd159, [LLBtorqueAF2TPRB054401_param_0];
	mov.u32 	%r133, %ctaid.x;
	mov.u32 	%r132, %ctaid.y;
	mov.u32 	%r131, %nctaid.x;
	mov.u32 	%r130, %tid.x;
	mov.u32 	%r129, %ntid.x;
	mad.lo.s32 	%r128, %r131, %r132, %r133;
	mad.lo.s32 	%r127, %r128, %r129, %r130;
	mul.wide.s32 	%rd158, %r127, 4;
	cvta.to.global.u64 	%rd145, %rd159;
	add.s64 	%rd147, %rd145, %rd158;
	st.global.f32 	[%rd147], %f1534;
	cvta.to.global.u64 	%rd148, %rd160;
	add.s64 	%rd149, %rd148, %rd158;
	st.global.f32 	[%rd149], %f1535;
	cvta.to.global.u64 	%rd150, %rd161;
	add.s64 	%rd151, %rd150, %rd158;
	st.global.f32 	[%rd151], %f1536;
	cvta.to.global.u64 	%rd152, %rd162;
	add.s64 	%rd153, %rd152, %rd158;
	st.global.f32 	[%rd153], %f1531;
	cvta.to.global.u64 	%rd154, %rd163;
	add.s64 	%rd155, %rd154, %rd158;
	st.global.f32 	[%rd155], %f1532;
	cvta.to.global.u64 	%rd156, %rd164;
	add.s64 	%rd157, %rd156, %rd158;
	st.global.f32 	[%rd157], %f1533;

BB0_150:
	ret;
}


`
)
