package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for addexchangeato kernel
var addexchangeato_code cu.Function

// Stores the arguments for addexchangeato kernel invocation
type addexchangeato_args_t struct {
	arg_Bx       unsafe.Pointer
	arg_By       unsafe.Pointer
	arg_Bz       unsafe.Pointer
	arg_mx       unsafe.Pointer
	arg_my       unsafe.Pointer
	arg_mz       unsafe.Pointer
	arg_Mu_      unsafe.Pointer
	arg_Mu_mul   float32
	arg_Nv_      unsafe.Pointer
	arg_Nv_mul   float32
	arg_aLUT2d   unsafe.Pointer
	arg_dmiLUT2d unsafe.Pointer
	arg_regions  unsafe.Pointer
	arg_Nx       int
	arg_Ny       int
	arg_Nz       int
	arg_PBC      byte
	argptr       [17]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addexchangeato kernel invocation
var addexchangeato_args addexchangeato_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addexchangeato_args.argptr[0] = unsafe.Pointer(&addexchangeato_args.arg_Bx)
	addexchangeato_args.argptr[1] = unsafe.Pointer(&addexchangeato_args.arg_By)
	addexchangeato_args.argptr[2] = unsafe.Pointer(&addexchangeato_args.arg_Bz)
	addexchangeato_args.argptr[3] = unsafe.Pointer(&addexchangeato_args.arg_mx)
	addexchangeato_args.argptr[4] = unsafe.Pointer(&addexchangeato_args.arg_my)
	addexchangeato_args.argptr[5] = unsafe.Pointer(&addexchangeato_args.arg_mz)
	addexchangeato_args.argptr[6] = unsafe.Pointer(&addexchangeato_args.arg_Mu_)
	addexchangeato_args.argptr[7] = unsafe.Pointer(&addexchangeato_args.arg_Mu_mul)
	addexchangeato_args.argptr[8] = unsafe.Pointer(&addexchangeato_args.arg_Nv_)
	addexchangeato_args.argptr[9] = unsafe.Pointer(&addexchangeato_args.arg_Nv_mul)
	addexchangeato_args.argptr[10] = unsafe.Pointer(&addexchangeato_args.arg_aLUT2d)
	addexchangeato_args.argptr[11] = unsafe.Pointer(&addexchangeato_args.arg_dmiLUT2d)
	addexchangeato_args.argptr[12] = unsafe.Pointer(&addexchangeato_args.arg_regions)
	addexchangeato_args.argptr[13] = unsafe.Pointer(&addexchangeato_args.arg_Nx)
	addexchangeato_args.argptr[14] = unsafe.Pointer(&addexchangeato_args.arg_Ny)
	addexchangeato_args.argptr[15] = unsafe.Pointer(&addexchangeato_args.arg_Nz)
	addexchangeato_args.argptr[16] = unsafe.Pointer(&addexchangeato_args.arg_PBC)
}

// Wrapper for addexchangeato CUDA kernel, asynchronous.
func k_addexchangeato_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Mu_ unsafe.Pointer, Mu_mul float32, Nv_ unsafe.Pointer, Nv_mul float32, aLUT2d unsafe.Pointer, dmiLUT2d unsafe.Pointer, regions unsafe.Pointer, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addexchangeato")
	}

	addexchangeato_args.Lock()
	defer addexchangeato_args.Unlock()

	if addexchangeato_code == 0 {
		addexchangeato_code = fatbinLoad(addexchangeato_map, "addexchangeato")
	}

	addexchangeato_args.arg_Bx = Bx
	addexchangeato_args.arg_By = By
	addexchangeato_args.arg_Bz = Bz
	addexchangeato_args.arg_mx = mx
	addexchangeato_args.arg_my = my
	addexchangeato_args.arg_mz = mz
	addexchangeato_args.arg_Mu_ = Mu_
	addexchangeato_args.arg_Mu_mul = Mu_mul
	addexchangeato_args.arg_Nv_ = Nv_
	addexchangeato_args.arg_Nv_mul = Nv_mul
	addexchangeato_args.arg_aLUT2d = aLUT2d
	addexchangeato_args.arg_dmiLUT2d = dmiLUT2d
	addexchangeato_args.arg_regions = regions
	addexchangeato_args.arg_Nx = Nx
	addexchangeato_args.arg_Ny = Ny
	addexchangeato_args.arg_Nz = Nz
	addexchangeato_args.arg_PBC = PBC

	args := addexchangeato_args.argptr[:]
	cu.LaunchKernel(addexchangeato_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addexchangeato")
	}
}

// maps compute capability on PTX code for addexchangeato kernel.
var addexchangeato_map = map[int]string{0: "",
	30: addexchangeato_ptx_30}

// addexchangeato PTX code for various compute capabilities.
const (
	addexchangeato_ptx_30 = `
.version 6.5
.target sm_30
.address_size 64

	// .globl	addexchangeato

.visible .entry addexchangeato(
	.param .u64 addexchangeato_param_0,
	.param .u64 addexchangeato_param_1,
	.param .u64 addexchangeato_param_2,
	.param .u64 addexchangeato_param_3,
	.param .u64 addexchangeato_param_4,
	.param .u64 addexchangeato_param_5,
	.param .u64 addexchangeato_param_6,
	.param .f32 addexchangeato_param_7,
	.param .u64 addexchangeato_param_8,
	.param .f32 addexchangeato_param_9,
	.param .u64 addexchangeato_param_10,
	.param .u64 addexchangeato_param_11,
	.param .u64 addexchangeato_param_12,
	.param .u32 addexchangeato_param_13,
	.param .u32 addexchangeato_param_14,
	.param .u32 addexchangeato_param_15,
	.param .u8 addexchangeato_param_16
)
{
	.reg .pred 	%p<49>;
	.reg .b16 	%rs<14>;
	.reg .f32 	%f<125>;
	.reg .b32 	%r<159>;
	.reg .f64 	%fd<13>;
	.reg .b64 	%rd<55>;


	ld.param.u64 	%rd4, [addexchangeato_param_3];
	ld.param.u64 	%rd5, [addexchangeato_param_4];
	ld.param.u64 	%rd6, [addexchangeato_param_5];
	ld.param.u64 	%rd8, [addexchangeato_param_8];
	ld.param.f32 	%f98, [addexchangeato_param_9];
	ld.param.u64 	%rd9, [addexchangeato_param_10];
	ld.param.u64 	%rd10, [addexchangeato_param_11];
	ld.param.u64 	%rd11, [addexchangeato_param_12];
	ld.param.u32 	%r34, [addexchangeato_param_13];
	ld.param.u32 	%r35, [addexchangeato_param_14];
	ld.param.u32 	%r36, [addexchangeato_param_15];
	ld.param.u8 	%rs3, [addexchangeato_param_16];
	mov.u32 	%r37, %ntid.x;
	mov.u32 	%r38, %ctaid.x;
	mov.u32 	%r39, %tid.x;
	mad.lo.s32 	%r1, %r37, %r38, %r39;
	mov.u32 	%r40, %ntid.y;
	mov.u32 	%r41, %ctaid.y;
	mov.u32 	%r42, %tid.y;
	mad.lo.s32 	%r2, %r40, %r41, %r42;
	mov.u32 	%r43, %ntid.z;
	mov.u32 	%r44, %ctaid.z;
	mov.u32 	%r45, %tid.z;
	mad.lo.s32 	%r3, %r43, %r44, %r45;
	setp.ge.s32	%p3, %r2, %r35;
	setp.ge.s32	%p4, %r1, %r34;
	or.pred  	%p5, %p3, %p4;
	setp.ge.s32	%p6, %r3, %r36;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	BB0_52;

	cvta.to.global.u64 	%rd12, %rd6;
	cvta.to.global.u64 	%rd13, %rd5;
	cvta.to.global.u64 	%rd14, %rd4;
	mad.lo.s32 	%r46, %r3, %r35, %r2;
	mad.lo.s32 	%r4, %r46, %r34, %r1;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	add.s64 	%rd17, %rd13, %rd15;
	add.s64 	%rd18, %rd12, %rd15;
	ld.global.f32 	%f55, [%rd16];
	ld.global.f32 	%f56, [%rd17];
	mul.f32 	%f57, %f56, %f56;
	fma.rn.f32 	%f58, %f55, %f55, %f57;
	ld.global.f32 	%f59, [%rd18];
	fma.rn.f32 	%f60, %f59, %f59, %f58;
	setp.eq.f32	%p8, %f60, 0f00000000;
	@%p8 bra 	BB0_52;

	cvta.to.global.u64 	%rd19, %rd11;
	cvt.s64.s32	%rd20, %r4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.u8 	%rs1, [%rd21];
	setp.eq.s64	%p9, %rd8, 0;
	@%p9 bra 	BB0_4;

	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd24, %rd22, %rd15;
	ld.global.f32 	%f61, [%rd24];
	mul.f32 	%f98, %f61, %f98;

BB0_4:
	add.s32 	%r5, %r1, -1;
	mov.u32 	%r47, -1;
	add.s32 	%r6, %r2, -1;
	add.s32 	%r7, %r3, -1;
	mov.f32 	%f122, 0f00000000;
	cvta.to.global.u64 	%rd35, %rd9;
	cvta.to.global.u64 	%rd38, %rd10;
	mov.u32 	%r150, %r47;
	mov.f32 	%f121, %f122;
	mov.f32 	%f120, %f122;

BB0_5:
	mov.u32 	%r151, %r47;

BB0_6:
	cvt.rn.f64.s32	%fd9, %r150;
	mul.f64 	%fd8, %fd9, %fd9;
	mov.u32 	%r152, %r47;

BB0_7:
	or.b32  	%r55, %r151, %r150;
	or.b32  	%r56, %r55, %r152;
	setp.eq.s32	%p14, %r56, 0;
	@%p14 bra 	BB0_44;

	setp.neu.f32	%p15, %f98, 0f40C00000;
	@%p15 bra 	BB0_10;

	mul.lo.s32 	%r124, %r151, %r151;
	mad.lo.s32 	%r123, %r150, %r150, %r124;
	mad.lo.s32 	%r57, %r152, %r152, %r123;
	setp.ne.s32	%p16, %r57, 1;
	@%p16 bra 	BB0_44;

BB0_10:
	setp.ne.s32	%p17, %r150, -1;
	mov.u32 	%r154, %r1;
	@%p17 bra 	BB0_14;

	and.b16  	%rs4, %rs3, 1;
	setp.eq.b16	%p18, %rs4, 1;
	@!%p18 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	mov.u32 	%r60, 0;
	max.s32 	%r154, %r5, %r60;
	bra.uni 	BB0_14;

BB0_12:
	rem.s32 	%r58, %r5, %r34;
	add.s32 	%r59, %r58, %r34;
	rem.s32 	%r154, %r59, %r34;

BB0_14:
	setp.ne.s32	%p19, %r150, 1;
	@%p19 bra 	BB0_18;

	and.b16  	%rs5, %rs3, 1;
	setp.eq.b16	%p20, %rs5, 1;
	@!%p20 bra 	BB0_17;
	bra.uni 	BB0_16;

BB0_17:
	add.s32 	%r130, %r34, -1;
	add.s32 	%r64, %r5, 2;
	min.s32 	%r154, %r64, %r130;
	bra.uni 	BB0_18;

BB0_16:
	add.s32 	%r61, %r5, 2;
	rem.s32 	%r62, %r61, %r34;
	add.s32 	%r63, %r62, %r34;
	rem.s32 	%r154, %r63, %r34;

BB0_18:
	setp.ne.s32	%p21, %r151, -1;
	mov.u32 	%r156, %r2;
	@%p21 bra 	BB0_22;

	and.b16  	%rs6, %rs3, 2;
	setp.eq.s16	%p22, %rs6, 0;
	@%p22 bra 	BB0_21;
	bra.uni 	BB0_20;

BB0_21:
	mov.u32 	%r68, 0;
	max.s32 	%r156, %r6, %r68;
	bra.uni 	BB0_22;

BB0_20:
	rem.s32 	%r66, %r6, %r35;
	add.s32 	%r67, %r66, %r35;
	rem.s32 	%r156, %r67, %r35;

BB0_22:
	setp.ne.s32	%p23, %r151, 1;
	@%p23 bra 	BB0_26;

	and.b16  	%rs7, %rs3, 2;
	setp.eq.s16	%p24, %rs7, 0;
	@%p24 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r129, %r35, -1;
	add.s32 	%r72, %r6, 2;
	min.s32 	%r156, %r72, %r129;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r69, %r6, 2;
	rem.s32 	%r70, %r69, %r35;
	add.s32 	%r71, %r70, %r35;
	rem.s32 	%r156, %r71, %r35;

BB0_26:
	setp.ne.s32	%p25, %r152, -1;
	mov.u32 	%r158, %r3;
	@%p25 bra 	BB0_30;

	and.b16  	%rs8, %rs3, 4;
	setp.eq.s16	%p26, %rs8, 0;
	@%p26 bra 	BB0_29;
	bra.uni 	BB0_28;

BB0_29:
	mov.u32 	%r76, 0;
	max.s32 	%r158, %r7, %r76;
	bra.uni 	BB0_30;

BB0_28:
	rem.s32 	%r74, %r7, %r36;
	add.s32 	%r75, %r74, %r36;
	rem.s32 	%r158, %r75, %r36;

BB0_30:
	setp.ne.s32	%p27, %r152, 1;
	@%p27 bra 	BB0_34;

	and.b16  	%rs9, %rs3, 4;
	setp.eq.s16	%p28, %rs9, 0;
	@%p28 bra 	BB0_33;
	bra.uni 	BB0_32;

BB0_33:
	add.s32 	%r80, %r7, 2;
	add.s32 	%r81, %r36, -1;
	min.s32 	%r158, %r80, %r81;
	bra.uni 	BB0_34;

BB0_32:
	add.s32 	%r77, %r7, 2;
	rem.s32 	%r78, %r77, %r36;
	add.s32 	%r79, %r78, %r36;
	rem.s32 	%r158, %r79, %r36;

BB0_34:
	mad.lo.s32 	%r82, %r158, %r35, %r156;
	mad.lo.s32 	%r30, %r82, %r34, %r154;
	cvt.s64.s32	%rd26, %r30;
	add.s64 	%rd27, %rd19, %rd26;
	ld.global.u8 	%rs2, [%rd27];
	setp.eq.s16	%p29, %rs2, 255;
	@%p29 bra 	BB0_44;

	mul.wide.s32 	%rd29, %r30, 4;
	add.s64 	%rd30, %rd14, %rd29;
	ld.global.f32 	%f111, [%rd30];
	add.s64 	%rd32, %rd13, %rd29;
	ld.global.f32 	%f112, [%rd32];
	add.s64 	%rd34, %rd12, %rd29;
	ld.global.f32 	%f113, [%rd34];
	and.b16  	%rs10, %rs3, 1;
	setp.eq.b16	%p30, %rs10, 1;
	@%p30 bra 	BB0_37;

	add.s32 	%r128, %r34, -1;
	add.s32 	%r127, %r150, %r1;
	setp.gt.s32	%p48, %r127, %r128;
	setp.lt.s32	%p47, %r127, 0;
	or.pred  	%p46, %p47, %p48;
	selp.f32	%f111, 0f00000000, %f111, %p46;
	selp.f32	%f112, 0f00000000, %f112, %p46;
	selp.f32	%f113, 0f00000000, %f113, %p46;

BB0_37:
	and.b16  	%rs11, %rs3, 2;
	setp.ne.s16	%p31, %rs11, 0;
	@%p31 bra 	BB0_39;

	add.s32 	%r126, %r35, -1;
	add.s32 	%r125, %r151, %r2;
	setp.gt.s32	%p45, %r125, %r126;
	setp.lt.s32	%p44, %r125, 0;
	or.pred  	%p43, %p44, %p45;
	selp.f32	%f111, 0f00000000, %f111, %p43;
	selp.f32	%f112, 0f00000000, %f112, %p43;
	selp.f32	%f113, 0f00000000, %f113, %p43;

BB0_39:
	and.b16  	%rs12, %rs3, 4;
	setp.ne.s16	%p32, %rs12, 0;
	@%p32 bra 	BB0_41;

	add.s32 	%r83, %r152, %r3;
	setp.lt.s32	%p33, %r83, 0;
	add.s32 	%r84, %r36, -1;
	setp.gt.s32	%p34, %r83, %r84;
	or.pred  	%p35, %p33, %p34;
	selp.f32	%f111, 0f00000000, %f111, %p35;
	selp.f32	%f112, 0f00000000, %f112, %p35;
	selp.f32	%f113, 0f00000000, %f113, %p35;

BB0_41:
	cvt.u32.u16	%r85, %rs2;
	cvt.u32.u16	%r86, %rs1;
	and.b32  	%r87, %r86, 255;
	setp.gt.u16	%p36, %rs2, %rs1;
	selp.b32	%r88, %r87, %r85, %p36;
	selp.b32	%r89, %r85, %r87, %p36;
	add.s32 	%r90, %r89, 1;
	mul.lo.s32 	%r91, %r90, %r89;
	shr.u32 	%r92, %r91, 1;
	add.s32 	%r93, %r92, %r88;
	mul.wide.s32 	%rd36, %r93, 4;
	add.s64 	%rd37, %rd35, %rd36;
	ld.global.f32 	%f35, [%rd37];
	add.s64 	%rd39, %rd38, %rd36;
	ld.global.f32 	%f36, [%rd39];
	setp.eq.f32	%p37, %f36, 0f00000000;
	@%p37 bra 	BB0_43;

	cvt.rn.f32.s32	%f97, %r151;
	cvt.rn.f32.s32	%f96, %r150;
	mul.lo.s32 	%r149, %r151, %r151;
	cvt.rn.f64.s32	%fd11, %r149;
	add.f64 	%fd10, %fd8, %fd11;
	mul.lo.s32 	%r94, %r152, %r152;
	cvt.rn.f64.s32	%fd5, %r94;
	add.f64 	%fd6, %fd10, %fd5;
	sqrt.rn.f64 	%fd7, %fd6;
	cvt.rn.f32.f64	%f65, %fd7;
	rcp.rn.f32 	%f66, %f65;
	mul.f32 	%f67, %f96, %f66;
	mul.f32 	%f68, %f97, %f66;
	cvt.rn.f32.s32	%f69, %r152;
	mul.f32 	%f70, %f69, %f66;
	mul.f32 	%f71, %f70, 0f00000000;
	sub.f32 	%f72, %f71, %f68;
	sub.f32 	%f73, %f67, %f71;
	mul.f32 	%f74, %f68, 0f00000000;
	mul.f32 	%f75, %f67, 0f00000000;
	sub.f32 	%f76, %f74, %f75;
	mul.f32 	%f77, %f113, %f73;
	mul.f32 	%f78, %f112, %f76;
	sub.f32 	%f79, %f77, %f78;
	mul.f32 	%f80, %f111, %f76;
	mul.f32 	%f81, %f113, %f72;
	sub.f32 	%f82, %f80, %f81;
	mul.f32 	%f83, %f112, %f72;
	mul.f32 	%f84, %f111, %f73;
	sub.f32 	%f85, %f83, %f84;
	fma.rn.f32 	%f120, %f36, %f79, %f120;
	fma.rn.f32 	%f121, %f36, %f82, %f121;
	fma.rn.f32 	%f122, %f36, %f85, %f122;

BB0_43:
	fma.rn.f32 	%f120, %f111, %f35, %f120;
	fma.rn.f32 	%f121, %f112, %f35, %f121;
	fma.rn.f32 	%f122, %f113, %f35, %f122;

BB0_44:
	add.s32 	%r152, %r152, 1;
	setp.ne.s32	%p38, %r152, 2;
	@%p38 bra 	BB0_7;

	add.s32 	%r151, %r151, 1;
	setp.lt.s32	%p39, %r151, 2;
	@%p39 bra 	BB0_6;

	add.s32 	%r150, %r150, 1;
	setp.lt.s32	%p40, %r150, 2;
	@%p40 bra 	BB0_5;

	ld.param.u64 	%rd52, [addexchangeato_param_6];
	ld.param.f32 	%f123, [addexchangeato_param_7];
	setp.eq.s64	%p41, %rd52, 0;
	@%p41 bra 	BB0_49;

	ld.param.u64 	%rd53, [addexchangeato_param_6];
	ld.param.f32 	%f95, [addexchangeato_param_7];
	mov.u32 	%r139, %tid.x;
	mov.u32 	%r138, %ctaid.x;
	mov.u32 	%r137, %ntid.x;
	mov.u32 	%r136, %tid.y;
	mov.u32 	%r135, %ctaid.y;
	mov.u32 	%r134, %ntid.y;
	mov.u32 	%r133, %tid.z;
	mov.u32 	%r132, %ctaid.z;
	mov.u32 	%r131, %ntid.z;
	mad.lo.s32 	%r98, %r131, %r132, %r133;
	mad.lo.s32 	%r102, %r134, %r135, %r136;
	mad.lo.s32 	%r103, %r98, %r35, %r102;
	mad.lo.s32 	%r107, %r137, %r138, %r139;
	mad.lo.s32 	%r108, %r103, %r34, %r107;
	cvta.to.global.u64 	%rd40, %rd53;
	mul.wide.s32 	%rd41, %r108, 4;
	add.s64 	%rd42, %rd40, %rd41;
	ld.global.f32 	%f86, [%rd42];
	mul.f32 	%f123, %f86, %f95;

BB0_49:
	setp.eq.f32	%p42, %f123, 0f00000000;
	mov.f32 	%f124, 0f00000000;
	@%p42 bra 	BB0_51;

	rcp.rn.f32 	%f124, %f123;

BB0_51:
	ld.param.u64 	%rd54, [addexchangeato_param_2];
	ld.param.u64 	%rd51, [addexchangeato_param_1];
	ld.param.u64 	%rd50, [addexchangeato_param_0];
	mov.u32 	%r148, %tid.x;
	mov.u32 	%r147, %ctaid.x;
	mov.u32 	%r146, %ntid.x;
	mov.u32 	%r145, %tid.y;
	mov.u32 	%r144, %ctaid.y;
	mov.u32 	%r143, %ntid.y;
	mov.u32 	%r142, %tid.z;
	mov.u32 	%r141, %ctaid.z;
	mov.u32 	%r140, %ntid.z;
	mad.lo.s32 	%r112, %r140, %r141, %r142;
	mad.lo.s32 	%r116, %r143, %r144, %r145;
	mad.lo.s32 	%r117, %r112, %r35, %r116;
	mad.lo.s32 	%r121, %r146, %r147, %r148;
	mad.lo.s32 	%r122, %r117, %r34, %r121;
	cvta.to.global.u64 	%rd43, %rd50;
	mul.wide.s32 	%rd44, %r122, 4;
	add.s64 	%rd45, %rd43, %rd44;
	ld.global.f32 	%f88, [%rd45];
	fma.rn.f32 	%f89, %f120, %f124, %f88;
	st.global.f32 	[%rd45], %f89;
	cvta.to.global.u64 	%rd46, %rd51;
	add.s64 	%rd47, %rd46, %rd44;
	ld.global.f32 	%f90, [%rd47];
	fma.rn.f32 	%f91, %f121, %f124, %f90;
	st.global.f32 	[%rd47], %f91;
	cvta.to.global.u64 	%rd48, %rd54;
	add.s64 	%rd49, %rd48, %rd44;
	ld.global.f32 	%f92, [%rd49];
	fma.rn.f32 	%f93, %f122, %f124, %f92;
	st.global.f32 	[%rd49], %f93;

BB0_52:
	ret;
}


`
)
