package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for LLBtorqueAFMFA kernel
var LLBtorqueAFMFA_code cu.Function

// Stores the arguments for LLBtorqueAFMFA kernel invocation
type LLBtorqueAFMFA_args_t struct {
	arg_t1x         unsafe.Pointer
	arg_t1y         unsafe.Pointer
	arg_t1z         unsafe.Pointer
	arg_mx1         unsafe.Pointer
	arg_my1         unsafe.Pointer
	arg_mz1         unsafe.Pointer
	arg_t2x         unsafe.Pointer
	arg_t2y         unsafe.Pointer
	arg_t2z         unsafe.Pointer
	arg_mx2         unsafe.Pointer
	arg_my2         unsafe.Pointer
	arg_mz2         unsafe.Pointer
	arg_hx1         unsafe.Pointer
	arg_hy1         unsafe.Pointer
	arg_hz1         unsafe.Pointer
	arg_hx2         unsafe.Pointer
	arg_hy2         unsafe.Pointer
	arg_hz2         unsafe.Pointer
	arg_alpha_      unsafe.Pointer
	arg_alpha_mul   float32
	arg_alpha1_     unsafe.Pointer
	arg_alpha1_mul  float32
	arg_alpha2_     unsafe.Pointer
	arg_alpha2_mul  float32
	arg_TCurie_     unsafe.Pointer
	arg_TCurie_mul  float32
	arg_Msat_       unsafe.Pointer
	arg_Msat_mul    float32
	arg_Msat1_      unsafe.Pointer
	arg_Msat1_mul   float32
	arg_Msat2_      unsafe.Pointer
	arg_Msat2_mul   float32
	arg_hth11x      unsafe.Pointer
	arg_hth11y      unsafe.Pointer
	arg_hth11z      unsafe.Pointer
	arg_hth21x      unsafe.Pointer
	arg_hth21y      unsafe.Pointer
	arg_hth21z      unsafe.Pointer
	arg_hth12x      unsafe.Pointer
	arg_hth12y      unsafe.Pointer
	arg_hth12z      unsafe.Pointer
	arg_hth22x      unsafe.Pointer
	arg_hth22y      unsafe.Pointer
	arg_hth22z      unsafe.Pointer
	arg_temp_       unsafe.Pointer
	arg_temp_mul    float32
	arg_x_          unsafe.Pointer
	arg_x_mul       float32
	arg_nv_         unsafe.Pointer
	arg_nv_mul      float32
	arg_mua_        unsafe.Pointer
	arg_mua_mul     float32
	arg_mub_        unsafe.Pointer
	arg_mub_mul     float32
	arg_J0aa_       unsafe.Pointer
	arg_J0aa_mul    float32
	arg_J0bb_       unsafe.Pointer
	arg_J0bb_mul    float32
	arg_J0ab_       unsafe.Pointer
	arg_J0ab_mul    float32
	arg_lambda0_    unsafe.Pointer
	arg_lambda0_mul float32
	arg_N           int
	argptr          [63]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for LLBtorqueAFMFA kernel invocation
var LLBtorqueAFMFA_args LLBtorqueAFMFA_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	LLBtorqueAFMFA_args.argptr[0] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_t1x)
	LLBtorqueAFMFA_args.argptr[1] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_t1y)
	LLBtorqueAFMFA_args.argptr[2] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_t1z)
	LLBtorqueAFMFA_args.argptr[3] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mx1)
	LLBtorqueAFMFA_args.argptr[4] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_my1)
	LLBtorqueAFMFA_args.argptr[5] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mz1)
	LLBtorqueAFMFA_args.argptr[6] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_t2x)
	LLBtorqueAFMFA_args.argptr[7] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_t2y)
	LLBtorqueAFMFA_args.argptr[8] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_t2z)
	LLBtorqueAFMFA_args.argptr[9] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mx2)
	LLBtorqueAFMFA_args.argptr[10] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_my2)
	LLBtorqueAFMFA_args.argptr[11] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mz2)
	LLBtorqueAFMFA_args.argptr[12] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hx1)
	LLBtorqueAFMFA_args.argptr[13] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hy1)
	LLBtorqueAFMFA_args.argptr[14] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hz1)
	LLBtorqueAFMFA_args.argptr[15] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hx2)
	LLBtorqueAFMFA_args.argptr[16] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hy2)
	LLBtorqueAFMFA_args.argptr[17] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hz2)
	LLBtorqueAFMFA_args.argptr[18] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_alpha_)
	LLBtorqueAFMFA_args.argptr[19] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_alpha_mul)
	LLBtorqueAFMFA_args.argptr[20] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_alpha1_)
	LLBtorqueAFMFA_args.argptr[21] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_alpha1_mul)
	LLBtorqueAFMFA_args.argptr[22] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_alpha2_)
	LLBtorqueAFMFA_args.argptr[23] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_alpha2_mul)
	LLBtorqueAFMFA_args.argptr[24] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_TCurie_)
	LLBtorqueAFMFA_args.argptr[25] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_TCurie_mul)
	LLBtorqueAFMFA_args.argptr[26] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_Msat_)
	LLBtorqueAFMFA_args.argptr[27] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_Msat_mul)
	LLBtorqueAFMFA_args.argptr[28] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_Msat1_)
	LLBtorqueAFMFA_args.argptr[29] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_Msat1_mul)
	LLBtorqueAFMFA_args.argptr[30] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_Msat2_)
	LLBtorqueAFMFA_args.argptr[31] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_Msat2_mul)
	LLBtorqueAFMFA_args.argptr[32] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth11x)
	LLBtorqueAFMFA_args.argptr[33] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth11y)
	LLBtorqueAFMFA_args.argptr[34] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth11z)
	LLBtorqueAFMFA_args.argptr[35] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth21x)
	LLBtorqueAFMFA_args.argptr[36] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth21y)
	LLBtorqueAFMFA_args.argptr[37] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth21z)
	LLBtorqueAFMFA_args.argptr[38] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth12x)
	LLBtorqueAFMFA_args.argptr[39] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth12y)
	LLBtorqueAFMFA_args.argptr[40] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth12z)
	LLBtorqueAFMFA_args.argptr[41] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth22x)
	LLBtorqueAFMFA_args.argptr[42] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth22y)
	LLBtorqueAFMFA_args.argptr[43] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_hth22z)
	LLBtorqueAFMFA_args.argptr[44] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_temp_)
	LLBtorqueAFMFA_args.argptr[45] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_temp_mul)
	LLBtorqueAFMFA_args.argptr[46] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_x_)
	LLBtorqueAFMFA_args.argptr[47] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_x_mul)
	LLBtorqueAFMFA_args.argptr[48] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_nv_)
	LLBtorqueAFMFA_args.argptr[49] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_nv_mul)
	LLBtorqueAFMFA_args.argptr[50] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mua_)
	LLBtorqueAFMFA_args.argptr[51] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mua_mul)
	LLBtorqueAFMFA_args.argptr[52] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mub_)
	LLBtorqueAFMFA_args.argptr[53] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_mub_mul)
	LLBtorqueAFMFA_args.argptr[54] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_J0aa_)
	LLBtorqueAFMFA_args.argptr[55] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_J0aa_mul)
	LLBtorqueAFMFA_args.argptr[56] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_J0bb_)
	LLBtorqueAFMFA_args.argptr[57] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_J0bb_mul)
	LLBtorqueAFMFA_args.argptr[58] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_J0ab_)
	LLBtorqueAFMFA_args.argptr[59] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_J0ab_mul)
	LLBtorqueAFMFA_args.argptr[60] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_lambda0_)
	LLBtorqueAFMFA_args.argptr[61] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_lambda0_mul)
	LLBtorqueAFMFA_args.argptr[62] = unsafe.Pointer(&LLBtorqueAFMFA_args.arg_N)
}

// Wrapper for LLBtorqueAFMFA CUDA kernel, asynchronous.
func k_LLBtorqueAFMFA_async(t1x unsafe.Pointer, t1y unsafe.Pointer, t1z unsafe.Pointer, mx1 unsafe.Pointer, my1 unsafe.Pointer, mz1 unsafe.Pointer, t2x unsafe.Pointer, t2y unsafe.Pointer, t2z unsafe.Pointer, mx2 unsafe.Pointer, my2 unsafe.Pointer, mz2 unsafe.Pointer, hx1 unsafe.Pointer, hy1 unsafe.Pointer, hz1 unsafe.Pointer, hx2 unsafe.Pointer, hy2 unsafe.Pointer, hz2 unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, alpha1_ unsafe.Pointer, alpha1_mul float32, alpha2_ unsafe.Pointer, alpha2_mul float32, TCurie_ unsafe.Pointer, TCurie_mul float32, Msat_ unsafe.Pointer, Msat_mul float32, Msat1_ unsafe.Pointer, Msat1_mul float32, Msat2_ unsafe.Pointer, Msat2_mul float32, hth11x unsafe.Pointer, hth11y unsafe.Pointer, hth11z unsafe.Pointer, hth21x unsafe.Pointer, hth21y unsafe.Pointer, hth21z unsafe.Pointer, hth12x unsafe.Pointer, hth12y unsafe.Pointer, hth12z unsafe.Pointer, hth22x unsafe.Pointer, hth22y unsafe.Pointer, hth22z unsafe.Pointer, temp_ unsafe.Pointer, temp_mul float32, x_ unsafe.Pointer, x_mul float32, nv_ unsafe.Pointer, nv_mul float32, mua_ unsafe.Pointer, mua_mul float32, mub_ unsafe.Pointer, mub_mul float32, J0aa_ unsafe.Pointer, J0aa_mul float32, J0bb_ unsafe.Pointer, J0bb_mul float32, J0ab_ unsafe.Pointer, J0ab_mul float32, lambda0_ unsafe.Pointer, lambda0_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("LLBtorqueAFMFA")
	}

	LLBtorqueAFMFA_args.Lock()
	defer LLBtorqueAFMFA_args.Unlock()

	if LLBtorqueAFMFA_code == 0 {
		LLBtorqueAFMFA_code = fatbinLoad(LLBtorqueAFMFA_map, "LLBtorqueAFMFA")
	}

	LLBtorqueAFMFA_args.arg_t1x = t1x
	LLBtorqueAFMFA_args.arg_t1y = t1y
	LLBtorqueAFMFA_args.arg_t1z = t1z
	LLBtorqueAFMFA_args.arg_mx1 = mx1
	LLBtorqueAFMFA_args.arg_my1 = my1
	LLBtorqueAFMFA_args.arg_mz1 = mz1
	LLBtorqueAFMFA_args.arg_t2x = t2x
	LLBtorqueAFMFA_args.arg_t2y = t2y
	LLBtorqueAFMFA_args.arg_t2z = t2z
	LLBtorqueAFMFA_args.arg_mx2 = mx2
	LLBtorqueAFMFA_args.arg_my2 = my2
	LLBtorqueAFMFA_args.arg_mz2 = mz2
	LLBtorqueAFMFA_args.arg_hx1 = hx1
	LLBtorqueAFMFA_args.arg_hy1 = hy1
	LLBtorqueAFMFA_args.arg_hz1 = hz1
	LLBtorqueAFMFA_args.arg_hx2 = hx2
	LLBtorqueAFMFA_args.arg_hy2 = hy2
	LLBtorqueAFMFA_args.arg_hz2 = hz2
	LLBtorqueAFMFA_args.arg_alpha_ = alpha_
	LLBtorqueAFMFA_args.arg_alpha_mul = alpha_mul
	LLBtorqueAFMFA_args.arg_alpha1_ = alpha1_
	LLBtorqueAFMFA_args.arg_alpha1_mul = alpha1_mul
	LLBtorqueAFMFA_args.arg_alpha2_ = alpha2_
	LLBtorqueAFMFA_args.arg_alpha2_mul = alpha2_mul
	LLBtorqueAFMFA_args.arg_TCurie_ = TCurie_
	LLBtorqueAFMFA_args.arg_TCurie_mul = TCurie_mul
	LLBtorqueAFMFA_args.arg_Msat_ = Msat_
	LLBtorqueAFMFA_args.arg_Msat_mul = Msat_mul
	LLBtorqueAFMFA_args.arg_Msat1_ = Msat1_
	LLBtorqueAFMFA_args.arg_Msat1_mul = Msat1_mul
	LLBtorqueAFMFA_args.arg_Msat2_ = Msat2_
	LLBtorqueAFMFA_args.arg_Msat2_mul = Msat2_mul
	LLBtorqueAFMFA_args.arg_hth11x = hth11x
	LLBtorqueAFMFA_args.arg_hth11y = hth11y
	LLBtorqueAFMFA_args.arg_hth11z = hth11z
	LLBtorqueAFMFA_args.arg_hth21x = hth21x
	LLBtorqueAFMFA_args.arg_hth21y = hth21y
	LLBtorqueAFMFA_args.arg_hth21z = hth21z
	LLBtorqueAFMFA_args.arg_hth12x = hth12x
	LLBtorqueAFMFA_args.arg_hth12y = hth12y
	LLBtorqueAFMFA_args.arg_hth12z = hth12z
	LLBtorqueAFMFA_args.arg_hth22x = hth22x
	LLBtorqueAFMFA_args.arg_hth22y = hth22y
	LLBtorqueAFMFA_args.arg_hth22z = hth22z
	LLBtorqueAFMFA_args.arg_temp_ = temp_
	LLBtorqueAFMFA_args.arg_temp_mul = temp_mul
	LLBtorqueAFMFA_args.arg_x_ = x_
	LLBtorqueAFMFA_args.arg_x_mul = x_mul
	LLBtorqueAFMFA_args.arg_nv_ = nv_
	LLBtorqueAFMFA_args.arg_nv_mul = nv_mul
	LLBtorqueAFMFA_args.arg_mua_ = mua_
	LLBtorqueAFMFA_args.arg_mua_mul = mua_mul
	LLBtorqueAFMFA_args.arg_mub_ = mub_
	LLBtorqueAFMFA_args.arg_mub_mul = mub_mul
	LLBtorqueAFMFA_args.arg_J0aa_ = J0aa_
	LLBtorqueAFMFA_args.arg_J0aa_mul = J0aa_mul
	LLBtorqueAFMFA_args.arg_J0bb_ = J0bb_
	LLBtorqueAFMFA_args.arg_J0bb_mul = J0bb_mul
	LLBtorqueAFMFA_args.arg_J0ab_ = J0ab_
	LLBtorqueAFMFA_args.arg_J0ab_mul = J0ab_mul
	LLBtorqueAFMFA_args.arg_lambda0_ = lambda0_
	LLBtorqueAFMFA_args.arg_lambda0_mul = lambda0_mul
	LLBtorqueAFMFA_args.arg_N = N

	args := LLBtorqueAFMFA_args.argptr[:]
	cu.LaunchKernel(LLBtorqueAFMFA_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("LLBtorqueAFMFA")
	}
}

// maps compute capability on PTX code for LLBtorqueAFMFA kernel.
var LLBtorqueAFMFA_map = map[int]string{0: "",
	70: LLBtorqueAFMFA_ptx_70}

// LLBtorqueAFMFA PTX code for various compute capabilities.
const (
	LLBtorqueAFMFA_ptx_70 = `
.version 7.2
.target sm_70
.address_size 64

	// .globl	LLBtorqueAFMFA

.visible .entry LLBtorqueAFMFA(
	.param .u64 LLBtorqueAFMFA_param_0,
	.param .u64 LLBtorqueAFMFA_param_1,
	.param .u64 LLBtorqueAFMFA_param_2,
	.param .u64 LLBtorqueAFMFA_param_3,
	.param .u64 LLBtorqueAFMFA_param_4,
	.param .u64 LLBtorqueAFMFA_param_5,
	.param .u64 LLBtorqueAFMFA_param_6,
	.param .u64 LLBtorqueAFMFA_param_7,
	.param .u64 LLBtorqueAFMFA_param_8,
	.param .u64 LLBtorqueAFMFA_param_9,
	.param .u64 LLBtorqueAFMFA_param_10,
	.param .u64 LLBtorqueAFMFA_param_11,
	.param .u64 LLBtorqueAFMFA_param_12,
	.param .u64 LLBtorqueAFMFA_param_13,
	.param .u64 LLBtorqueAFMFA_param_14,
	.param .u64 LLBtorqueAFMFA_param_15,
	.param .u64 LLBtorqueAFMFA_param_16,
	.param .u64 LLBtorqueAFMFA_param_17,
	.param .u64 LLBtorqueAFMFA_param_18,
	.param .f32 LLBtorqueAFMFA_param_19,
	.param .u64 LLBtorqueAFMFA_param_20,
	.param .f32 LLBtorqueAFMFA_param_21,
	.param .u64 LLBtorqueAFMFA_param_22,
	.param .f32 LLBtorqueAFMFA_param_23,
	.param .u64 LLBtorqueAFMFA_param_24,
	.param .f32 LLBtorqueAFMFA_param_25,
	.param .u64 LLBtorqueAFMFA_param_26,
	.param .f32 LLBtorqueAFMFA_param_27,
	.param .u64 LLBtorqueAFMFA_param_28,
	.param .f32 LLBtorqueAFMFA_param_29,
	.param .u64 LLBtorqueAFMFA_param_30,
	.param .f32 LLBtorqueAFMFA_param_31,
	.param .u64 LLBtorqueAFMFA_param_32,
	.param .u64 LLBtorqueAFMFA_param_33,
	.param .u64 LLBtorqueAFMFA_param_34,
	.param .u64 LLBtorqueAFMFA_param_35,
	.param .u64 LLBtorqueAFMFA_param_36,
	.param .u64 LLBtorqueAFMFA_param_37,
	.param .u64 LLBtorqueAFMFA_param_38,
	.param .u64 LLBtorqueAFMFA_param_39,
	.param .u64 LLBtorqueAFMFA_param_40,
	.param .u64 LLBtorqueAFMFA_param_41,
	.param .u64 LLBtorqueAFMFA_param_42,
	.param .u64 LLBtorqueAFMFA_param_43,
	.param .u64 LLBtorqueAFMFA_param_44,
	.param .f32 LLBtorqueAFMFA_param_45,
	.param .u64 LLBtorqueAFMFA_param_46,
	.param .f32 LLBtorqueAFMFA_param_47,
	.param .u64 LLBtorqueAFMFA_param_48,
	.param .f32 LLBtorqueAFMFA_param_49,
	.param .u64 LLBtorqueAFMFA_param_50,
	.param .f32 LLBtorqueAFMFA_param_51,
	.param .u64 LLBtorqueAFMFA_param_52,
	.param .f32 LLBtorqueAFMFA_param_53,
	.param .u64 LLBtorqueAFMFA_param_54,
	.param .f32 LLBtorqueAFMFA_param_55,
	.param .u64 LLBtorqueAFMFA_param_56,
	.param .f32 LLBtorqueAFMFA_param_57,
	.param .u64 LLBtorqueAFMFA_param_58,
	.param .f32 LLBtorqueAFMFA_param_59,
	.param .u64 LLBtorqueAFMFA_param_60,
	.param .f32 LLBtorqueAFMFA_param_61,
	.param .u32 LLBtorqueAFMFA_param_62
)
{
	.reg .pred 	%p<143>;
	.reg .f32 	%f<1408>;
	.reg .b32 	%r<129>;
	.reg .f64 	%fd<82>;
	.reg .b64 	%rd<177>;


	ld.param.u64 	%rd20, [LLBtorqueAFMFA_param_18];
	ld.param.u64 	%rd21, [LLBtorqueAFMFA_param_20];
	ld.param.u64 	%rd22, [LLBtorqueAFMFA_param_22];
	ld.param.u64 	%rd23, [LLBtorqueAFMFA_param_26];
	ld.param.u64 	%rd24, [LLBtorqueAFMFA_param_28];
	ld.param.u64 	%rd25, [LLBtorqueAFMFA_param_30];
	ld.param.u64 	%rd29, [LLBtorqueAFMFA_param_35];
	ld.param.u64 	%rd30, [LLBtorqueAFMFA_param_36];
	ld.param.u64 	%rd31, [LLBtorqueAFMFA_param_37];
	ld.param.u64 	%rd32, [LLBtorqueAFMFA_param_38];
	ld.param.u64 	%rd33, [LLBtorqueAFMFA_param_39];
	ld.param.u64 	%rd34, [LLBtorqueAFMFA_param_40];
	ld.param.u64 	%rd35, [LLBtorqueAFMFA_param_41];
	ld.param.u64 	%rd36, [LLBtorqueAFMFA_param_42];
	ld.param.u64 	%rd37, [LLBtorqueAFMFA_param_43];
	ld.param.u64 	%rd38, [LLBtorqueAFMFA_param_44];
	ld.param.u64 	%rd39, [LLBtorqueAFMFA_param_46];
	ld.param.u64 	%rd40, [LLBtorqueAFMFA_param_48];
	ld.param.u64 	%rd41, [LLBtorqueAFMFA_param_50];
	ld.param.u64 	%rd42, [LLBtorqueAFMFA_param_52];
	ld.param.u64 	%rd43, [LLBtorqueAFMFA_param_54];
	ld.param.u64 	%rd44, [LLBtorqueAFMFA_param_56];
	ld.param.f32 	%f1351, [LLBtorqueAFMFA_param_59];
	ld.param.u64 	%rd46, [LLBtorqueAFMFA_param_60];
	ld.param.u32 	%r2, [LLBtorqueAFMFA_param_62];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p5, %r1, %r2;
	@%p5 bra 	LBB0_145;

	ld.param.f32 	%f1338, [LLBtorqueAFMFA_param_19];
	ld.param.u64 	%rd172, [LLBtorqueAFMFA_param_17];
	ld.param.u64 	%rd171, [LLBtorqueAFMFA_param_16];
	ld.param.u64 	%rd170, [LLBtorqueAFMFA_param_15];
	ld.param.u64 	%rd169, [LLBtorqueAFMFA_param_14];
	ld.param.u64 	%rd168, [LLBtorqueAFMFA_param_13];
	ld.param.u64 	%rd167, [LLBtorqueAFMFA_param_12];
	ld.param.u64 	%rd166, [LLBtorqueAFMFA_param_11];
	ld.param.u64 	%rd165, [LLBtorqueAFMFA_param_10];
	ld.param.u64 	%rd164, [LLBtorqueAFMFA_param_9];
	ld.param.u64 	%rd163, [LLBtorqueAFMFA_param_5];
	ld.param.u64 	%rd162, [LLBtorqueAFMFA_param_4];
	ld.param.u64 	%rd161, [LLBtorqueAFMFA_param_3];
	cvta.to.global.u64 	%rd47, %rd161;
	mul.wide.s32 	%rd48, %r1, 4;
	add.s64 	%rd49, %rd47, %rd48;
	ld.global.nc.f32 	%f1, [%rd49];
	cvta.to.global.u64 	%rd50, %rd162;
	add.s64 	%rd51, %rd50, %rd48;
	ld.global.nc.f32 	%f2, [%rd51];
	cvta.to.global.u64 	%rd52, %rd163;
	add.s64 	%rd53, %rd52, %rd48;
	ld.global.nc.f32 	%f3, [%rd53];
	cvta.to.global.u64 	%rd54, %rd164;
	add.s64 	%rd55, %rd54, %rd48;
	ld.global.nc.f32 	%f4, [%rd55];
	cvta.to.global.u64 	%rd56, %rd165;
	add.s64 	%rd57, %rd56, %rd48;
	ld.global.nc.f32 	%f5, [%rd57];
	cvta.to.global.u64 	%rd58, %rd166;
	add.s64 	%rd59, %rd58, %rd48;
	ld.global.nc.f32 	%f6, [%rd59];
	cvta.to.global.u64 	%rd60, %rd167;
	add.s64 	%rd61, %rd60, %rd48;
	ld.global.nc.f32 	%f7, [%rd61];
	cvta.to.global.u64 	%rd62, %rd168;
	add.s64 	%rd63, %rd62, %rd48;
	ld.global.nc.f32 	%f8, [%rd63];
	cvta.to.global.u64 	%rd64, %rd169;
	add.s64 	%rd65, %rd64, %rd48;
	ld.global.nc.f32 	%f9, [%rd65];
	cvta.to.global.u64 	%rd66, %rd170;
	add.s64 	%rd67, %rd66, %rd48;
	ld.global.nc.f32 	%f10, [%rd67];
	cvta.to.global.u64 	%rd68, %rd171;
	add.s64 	%rd69, %rd68, %rd48;
	ld.global.nc.f32 	%f11, [%rd69];
	cvta.to.global.u64 	%rd70, %rd172;
	add.s64 	%rd71, %rd70, %rd48;
	ld.global.nc.f32 	%f12, [%rd71];
	setp.eq.s64 	%p6, %rd20, 0;
	@%p6 bra 	LBB0_3;

	ld.param.f32 	%f1296, [LLBtorqueAFMFA_param_19];
	cvta.to.global.u64 	%rd72, %rd20;
	add.s64 	%rd74, %rd72, %rd48;
	ld.global.nc.f32 	%f336, [%rd74];
	mul.f32 	%f1338, %f336, %f1296;

LBB0_3:
	ld.param.f32 	%f1339, [LLBtorqueAFMFA_param_21];
	setp.eq.s64 	%p7, %rd21, 0;
	@%p7 bra 	LBB0_5;

	ld.param.f32 	%f1298, [LLBtorqueAFMFA_param_21];
	cvta.to.global.u64 	%rd75, %rd21;
	add.s64 	%rd77, %rd75, %rd48;
	ld.global.nc.f32 	%f337, [%rd77];
	mul.f32 	%f1339, %f337, %f1298;

LBB0_5:
	ld.param.f32 	%f1340, [LLBtorqueAFMFA_param_23];
	setp.eq.s64 	%p8, %rd22, 0;
	@%p8 bra 	LBB0_7;

	ld.param.f32 	%f1300, [LLBtorqueAFMFA_param_23];
	cvta.to.global.u64 	%rd78, %rd22;
	add.s64 	%rd80, %rd78, %rd48;
	ld.global.nc.f32 	%f338, [%rd80];
	mul.f32 	%f1340, %f338, %f1300;

LBB0_7:
	ld.param.f32 	%f1341, [LLBtorqueAFMFA_param_27];
	setp.eq.s64 	%p9, %rd23, 0;
	@%p9 bra 	LBB0_9;

	ld.param.f32 	%f1302, [LLBtorqueAFMFA_param_27];
	cvta.to.global.u64 	%rd81, %rd23;
	add.s64 	%rd83, %rd81, %rd48;
	ld.global.nc.f32 	%f339, [%rd83];
	mul.f32 	%f1341, %f339, %f1302;

LBB0_9:
	ld.param.f32 	%f1342, [LLBtorqueAFMFA_param_29];
	setp.eq.s64 	%p10, %rd24, 0;
	@%p10 bra 	LBB0_11;

	ld.param.f32 	%f1304, [LLBtorqueAFMFA_param_29];
	cvta.to.global.u64 	%rd84, %rd24;
	add.s64 	%rd86, %rd84, %rd48;
	ld.global.nc.f32 	%f340, [%rd86];
	mul.f32 	%f1342, %f340, %f1304;

LBB0_11:
	ld.param.f32 	%f1343, [LLBtorqueAFMFA_param_31];
	setp.eq.s64 	%p11, %rd25, 0;
	@%p11 bra 	LBB0_13;

	ld.param.f32 	%f1306, [LLBtorqueAFMFA_param_31];
	cvta.to.global.u64 	%rd87, %rd25;
	add.s64 	%rd89, %rd87, %rd48;
	ld.global.nc.f32 	%f341, [%rd89];
	mul.f32 	%f1343, %f341, %f1306;

LBB0_13:
	ld.param.f32 	%f1344, [LLBtorqueAFMFA_param_47];
	setp.eq.s64 	%p12, %rd39, 0;
	@%p12 bra 	LBB0_15;

	ld.param.f32 	%f1308, [LLBtorqueAFMFA_param_47];
	cvta.to.global.u64 	%rd90, %rd39;
	add.s64 	%rd92, %rd90, %rd48;
	ld.global.nc.f32 	%f342, [%rd92];
	mul.f32 	%f1344, %f342, %f1308;

LBB0_15:
	ld.param.f32 	%f1345, [LLBtorqueAFMFA_param_49];
	setp.eq.s64 	%p13, %rd40, 0;
	@%p13 bra 	LBB0_17;

	ld.param.f32 	%f1310, [LLBtorqueAFMFA_param_49];
	cvta.to.global.u64 	%rd93, %rd40;
	add.s64 	%rd95, %rd93, %rd48;
	ld.global.nc.f32 	%f343, [%rd95];
	mul.f32 	%f1345, %f343, %f1310;

LBB0_17:
	ld.param.f32 	%f1346, [LLBtorqueAFMFA_param_51];
	setp.eq.s64 	%p14, %rd41, 0;
	@%p14 bra 	LBB0_19;

	ld.param.f32 	%f1312, [LLBtorqueAFMFA_param_51];
	cvta.to.global.u64 	%rd96, %rd41;
	add.s64 	%rd98, %rd96, %rd48;
	ld.global.nc.f32 	%f344, [%rd98];
	mul.f32 	%f1346, %f344, %f1312;

LBB0_19:
	ld.param.f32 	%f1347, [LLBtorqueAFMFA_param_53];
	setp.eq.s64 	%p15, %rd42, 0;
	@%p15 bra 	LBB0_21;

	ld.param.f32 	%f1314, [LLBtorqueAFMFA_param_53];
	cvta.to.global.u64 	%rd99, %rd42;
	add.s64 	%rd101, %rd99, %rd48;
	ld.global.nc.f32 	%f345, [%rd101];
	mul.f32 	%f1347, %f345, %f1314;

LBB0_21:
	ld.param.f32 	%f1348, [LLBtorqueAFMFA_param_55];
	setp.eq.s64 	%p16, %rd43, 0;
	@%p16 bra 	LBB0_23;

	ld.param.f32 	%f1316, [LLBtorqueAFMFA_param_55];
	cvta.to.global.u64 	%rd102, %rd43;
	add.s64 	%rd104, %rd102, %rd48;
	ld.global.nc.f32 	%f346, [%rd104];
	mul.f32 	%f1348, %f346, %f1316;

LBB0_23:
	ld.param.f32 	%f1349, [LLBtorqueAFMFA_param_57];
	mul.f32 	%f347, %f1345, %f1348;
	mul.f32 	%f35, %f1344, %f347;
	setp.eq.s64 	%p17, %rd44, 0;
	@%p17 bra 	LBB0_25;

	ld.param.f32 	%f1318, [LLBtorqueAFMFA_param_57];
	cvta.to.global.u64 	%rd105, %rd44;
	add.s64 	%rd107, %rd105, %rd48;
	ld.global.nc.f32 	%f348, [%rd107];
	mul.f32 	%f1349, %f348, %f1318;

LBB0_25:
	ld.param.u64 	%rd173, [LLBtorqueAFMFA_param_58];
	mov.f32 	%f349, 0f3F800000;
	sub.f32 	%f38, %f349, %f1344;
	mul.f32 	%f350, %f1345, %f1349;
	mul.f32 	%f39, %f38, %f350;
	cvta.to.global.u64 	%rd108, %rd173;
	add.s64 	%rd1, %rd108, %rd48;
	setp.eq.s64 	%p18, %rd173, 0;
	mov.f32 	%f1350, %f1351;
	@%p18 bra 	LBB0_27;

	ld.global.nc.f32 	%f351, [%rd1];
	mul.f32 	%f1350, %f351, %f1351;

LBB0_27:
	mul.f32 	%f352, %f38, %f1350;
	mul.f32 	%f42, %f1345, %f352;
	@%p18 bra 	LBB0_29;

	ld.global.nc.f32 	%f353, [%rd1];
	mul.f32 	%f1351, %f353, %f1351;

LBB0_29:
	ld.param.f32 	%f1352, [LLBtorqueAFMFA_param_45];
	mul.f32 	%f354, %f1344, %f1351;
	mul.f32 	%f45, %f1345, %f354;
	setp.eq.s64 	%p20, %rd38, 0;
	@%p20 bra 	LBB0_31;

	ld.param.f32 	%f1320, [LLBtorqueAFMFA_param_45];
	cvta.to.global.u64 	%rd110, %rd38;
	add.s64 	%rd112, %rd110, %rd48;
	ld.global.nc.f32 	%f355, [%rd112];
	mul.f32 	%f1352, %f355, %f1320;

LBB0_31:
	ld.param.f32 	%f1353, [LLBtorqueAFMFA_param_61];
	setp.eq.s64 	%p21, %rd46, 0;
	@%p21 bra 	LBB0_33;

	ld.param.f32 	%f1322, [LLBtorqueAFMFA_param_61];
	cvta.to.global.u64 	%rd113, %rd46;
	add.s64 	%rd115, %rd113, %rd48;
	ld.global.nc.f32 	%f356, [%rd115];
	mul.f32 	%f1353, %f356, %f1322;

LBB0_33:
	mul.f32 	%f357, %f1344, %f1353;
	mul.f32 	%f50, %f1345, %f357;
	mul.f32 	%f358, %f2, %f2;
	fma.rn.f32 	%f359, %f1, %f1, %f358;
	fma.rn.f32 	%f360, %f3, %f3, %f359;
	sqrt.rn.f32 	%f51, %f360;
	mul.f32 	%f361, %f5, %f5;
	fma.rn.f32 	%f362, %f4, %f4, %f361;
	fma.rn.f32 	%f363, %f6, %f6, %f362;
	sqrt.rn.f32 	%f52, %f363;
	setp.eq.f32 	%p22, %f51, 0f00000000;
	setp.eq.f32 	%p23, %f52, 0f00000000;
	or.pred  	%p24, %p22, %p23;
	@%p24 bra 	LBB0_143;
	bra.uni 	LBB0_34;

LBB0_143:
	mul.f32 	%f1405, %f1, 0f00000000;
	mul.f32 	%f1406, %f2, 0f00000000;
	mul.f32 	%f1407, %f3, 0f00000000;
	mul.f32 	%f1402, %f4, 0f00000000;
	mul.f32 	%f1403, %f5, 0f00000000;
	mul.f32 	%f1404, %f6, 0f00000000;
	bra.uni 	LBB0_144;

LBB0_34:
	ld.param.u64 	%rd176, [LLBtorqueAFMFA_param_34];
	ld.param.u64 	%rd175, [LLBtorqueAFMFA_param_33];
	ld.param.u64 	%rd174, [LLBtorqueAFMFA_param_32];
	setp.eq.f32 	%p25, %f1352, 0f00000000;
	mov.f32 	%f365, 0f00000000;
	selp.f32 	%f53, 0f38D1B717, %f1352, %p25;
	cvta.to.global.u64 	%rd116, %rd174;
	add.s64 	%rd118, %rd116, %rd48;
	ld.global.nc.f32 	%f54, [%rd118];
	cvta.to.global.u64 	%rd119, %rd175;
	add.s64 	%rd120, %rd119, %rd48;
	ld.global.nc.f32 	%f55, [%rd120];
	cvta.to.global.u64 	%rd121, %rd176;
	add.s64 	%rd122, %rd121, %rd48;
	ld.global.nc.f32 	%f56, [%rd122];
	cvta.to.global.u64 	%rd123, %rd29;
	add.s64 	%rd124, %rd123, %rd48;
	ld.global.nc.f32 	%f57, [%rd124];
	cvta.to.global.u64 	%rd125, %rd30;
	add.s64 	%rd126, %rd125, %rd48;
	ld.global.nc.f32 	%f58, [%rd126];
	cvta.to.global.u64 	%rd127, %rd31;
	add.s64 	%rd128, %rd127, %rd48;
	ld.global.nc.f32 	%f59, [%rd128];
	cvta.to.global.u64 	%rd129, %rd32;
	add.s64 	%rd130, %rd129, %rd48;
	ld.global.nc.f32 	%f60, [%rd130];
	cvta.to.global.u64 	%rd131, %rd33;
	add.s64 	%rd132, %rd131, %rd48;
	ld.global.nc.f32 	%f61, [%rd132];
	cvta.to.global.u64 	%rd133, %rd34;
	add.s64 	%rd134, %rd133, %rd48;
	ld.global.nc.f32 	%f62, [%rd134];
	cvta.to.global.u64 	%rd135, %rd35;
	add.s64 	%rd136, %rd135, %rd48;
	ld.global.nc.f32 	%f63, [%rd136];
	cvta.to.global.u64 	%rd137, %rd36;
	add.s64 	%rd138, %rd137, %rd48;
	ld.global.nc.f32 	%f64, [%rd138];
	cvta.to.global.u64 	%rd139, %rd37;
	add.s64 	%rd140, %rd139, %rd48;
	ld.global.nc.f32 	%f65, [%rd140];
	add.f32 	%f66, %f35, %f39;
	mov.f32 	%f369, 0f40000000;
	sub.f32 	%f68, %f35, %f39;
	abs.f32 	%f69, %f68;
	setp.lt.f32 	%p26, %f69, 0f00800000;
	mul.f32 	%f371, %f69, 0f4B800000;
	selp.f32 	%f372, %f371, %f69, %p26;
	selp.f32 	%f373, 0fC3170000, 0fC2FE0000, %p26;
	mov.b32 	%r9, %f372;
	and.b32  	%r10, %r9, 8388607;
	or.b32  	%r11, %r10, 1065353216;
	mov.b32 	%f374, %r11;
	shr.u32 	%r12, %r9, 23;
	cvt.rn.f32.u32 	%f375, %r12;
	add.f32 	%f376, %f373, %f375;
	setp.gt.f32 	%p27, %f374, 0f3FB504F3;
	mul.f32 	%f377, %f374, 0f3F000000;
	add.f32 	%f378, %f376, 0f3F800000;
	selp.f32 	%f379, %f378, %f376, %p27;
	selp.f32 	%f380, %f377, %f374, %p27;
	add.f32 	%f381, %f380, 0fBF800000;
	add.f32 	%f382, %f380, 0f3F800000;
	rcp.approx.ftz.f32 	%f383, %f382;
	add.f32 	%f384, %f381, %f381;
	mul.f32 	%f385, %f384, %f383;
	mul.f32 	%f386, %f385, %f385;
	mov.f32 	%f387, 0f3C4CAF63;
	mov.f32 	%f388, 0f3B18F0FE;
	fma.rn.f32 	%f389, %f388, %f386, %f387;
	mov.f32 	%f390, 0f3DAAAABD;
	fma.rn.f32 	%f391, %f389, %f386, %f390;
	mul.rn.f32 	%f392, %f391, %f386;
	mul.rn.f32 	%f393, %f392, %f385;
	sub.f32 	%f394, %f381, %f385;
	add.f32 	%f395, %f394, %f394;
	neg.f32 	%f396, %f385;
	fma.rn.f32 	%f397, %f396, %f381, %f395;
	mul.rn.f32 	%f398, %f383, %f397;
	add.f32 	%f399, %f393, %f385;
	sub.f32 	%f400, %f385, %f399;
	add.f32 	%f401, %f393, %f400;
	add.f32 	%f402, %f398, %f401;
	add.f32 	%f403, %f399, %f402;
	sub.f32 	%f404, %f399, %f403;
	add.f32 	%f405, %f402, %f404;
	mov.f32 	%f406, 0f3F317200;
	mul.rn.f32 	%f407, %f379, %f406;
	mov.f32 	%f408, 0f35BFBE8E;
	mul.rn.f32 	%f409, %f379, %f408;
	add.f32 	%f410, %f407, %f403;
	sub.f32 	%f411, %f407, %f410;
	add.f32 	%f412, %f403, %f411;
	add.f32 	%f413, %f405, %f412;
	add.f32 	%f414, %f409, %f413;
	add.f32 	%f415, %f410, %f414;
	sub.f32 	%f416, %f410, %f415;
	add.f32 	%f417, %f414, %f416;
	mul.rn.f32 	%f418, %f369, %f415;
	neg.f32 	%f419, %f418;
	fma.rn.f32 	%f420, %f369, %f415, %f419;
	fma.rn.f32 	%f421, %f369, %f417, %f420;
	fma.rn.f32 	%f422, %f365, %f415, %f421;
	add.rn.f32 	%f423, %f418, %f422;
	neg.f32 	%f424, %f423;
	add.rn.f32 	%f425, %f418, %f424;
	add.rn.f32 	%f426, %f425, %f422;
	mov.b32 	%r13, %f423;
	setp.eq.s32 	%p28, %r13, 1118925336;
	add.s32 	%r14, %r13, -1;
	mov.b32 	%f427, %r14;
	add.f32 	%f428, %f426, 0f37000000;
	selp.f32 	%f70, %f428, %f426, %p28;
	selp.f32 	%f429, %f427, %f423, %p28;
	mov.f32 	%f430, 0f3FB8AA3B;
	mul.rn.f32 	%f431, %f429, %f430;
	cvt.rzi.f32.f32 	%f432, %f431;
	abs.f32 	%f433, %f432;
	setp.gt.f32 	%p29, %f433, 0f42FC0000;
	mov.b32 	%r15, %f432;
	and.b32  	%r16, %r15, -2147483648;
	or.b32  	%r17, %r16, 1123811328;
	mov.b32 	%f434, %r17;
	selp.f32 	%f435, %f434, %f432, %p29;
	mov.f32 	%f436, 0fBF317218;
	fma.rn.f32 	%f437, %f435, %f436, %f429;
	mov.f32 	%f438, 0f3102E308;
	fma.rn.f32 	%f439, %f435, %f438, %f437;
	mul.f32 	%f440, %f439, 0f3FB8AA3B;
	add.f32 	%f441, %f435, 0f4B40007F;
	mov.b32 	%r18, %f441;
	shl.b32 	%r19, %r18, 23;
	mov.b32 	%f442, %r19;
	ex2.approx.ftz.f32 	%f443, %f440;
	mul.f32 	%f71, %f443, %f442;
	setp.eq.f32 	%p30, %f71, 0f7F800000;
	mov.f32 	%f1354, 0f7F800000;
	@%p30 bra 	LBB0_36;

	fma.rn.f32 	%f1354, %f71, %f70, %f71;

LBB0_36:
	mov.f32 	%f1334, 0f3F800000;
	cvt.rzi.f32.f32 	%f1333, %f1334;
	add.f32 	%f1332, %f1333, %f1333;
	mov.f32 	%f1331, 0f40000000;
	sub.f32 	%f1330, %f1331, %f1332;
	abs.f32 	%f1329, %f1330;
	setp.lt.f32 	%p31, %f68, 0f00000000;
	setp.eq.f32 	%p32, %f1329, 0f3F800000;
	and.pred  	%p1, %p31, %p32;
	setp.eq.f32 	%p33, %f68, 0f00000000;
	@%p33 bra 	LBB0_40;
	bra.uni 	LBB0_37;

LBB0_40:
	add.f32 	%f448, %f68, %f68;
	selp.f32 	%f1356, %f448, 0f00000000, %p32;
	bra.uni 	LBB0_41;

LBB0_37:
	mov.b32 	%r20, %f1354;
	xor.b32  	%r21, %r20, -2147483648;
	mov.b32 	%f444, %r21;
	selp.f32 	%f1356, %f444, %f1354, %p1;
	setp.geu.f32 	%p34, %f68, 0f00000000;
	@%p34 bra 	LBB0_41;

	cvt.rzi.f32.f32 	%f446, %f369;
	setp.eq.f32 	%p35, %f446, 0f40000000;
	@%p35 bra 	LBB0_41;

	mov.f32 	%f1356, 0f7FFFFFFF;

LBB0_41:
	abs.f32 	%f1335, %f68;
	add.f32 	%f449, %f1335, 0f40000000;
	mov.b32 	%r22, %f449;
	setp.lt.s32 	%p37, %r22, 2139095040;
	@%p37 bra 	LBB0_46;

	abs.f32 	%f1336, %f68;
	setp.gtu.f32 	%p38, %f1336, 0f7F800000;
	@%p38 bra 	LBB0_45;
	bra.uni 	LBB0_43;

LBB0_45:
	add.f32 	%f1356, %f68, 0f40000000;
	bra.uni 	LBB0_46;

LBB0_43:
	abs.f32 	%f1337, %f68;
	setp.neu.f32 	%p39, %f1337, 0f7F800000;
	@%p39 bra 	LBB0_46;

	selp.f32 	%f1356, 0fFF800000, 0f7F800000, %p1;

LBB0_46:
	mov.f32 	%f1267, 0f00000000;
	mov.f32 	%f1266, 0f35BFBE8E;
	mov.f32 	%f1265, 0f3F317200;
	mov.f32 	%f1264, 0f3DAAAABD;
	mov.f32 	%f1263, 0f3C4CAF63;
	mov.f32 	%f1262, 0f3B18F0FE;
	setp.eq.f32 	%p40, %f68, 0f3F800000;
	selp.f32 	%f451, 0f3F800000, %f1356, %p40;
	mul.f32 	%f452, %f42, 0f40800000;
	fma.rn.f32 	%f80, %f452, %f45, %f451;
	mov.f32 	%f456, 0f3F000000;
	abs.f32 	%f82, %f80;
	setp.lt.f32 	%p41, %f82, 0f00800000;
	mul.f32 	%f458, %f82, 0f4B800000;
	selp.f32 	%f459, %f458, %f82, %p41;
	selp.f32 	%f460, 0fC3170000, 0fC2FE0000, %p41;
	mov.b32 	%r23, %f459;
	and.b32  	%r24, %r23, 8388607;
	or.b32  	%r25, %r24, 1065353216;
	mov.b32 	%f461, %r25;
	shr.u32 	%r26, %r23, 23;
	cvt.rn.f32.u32 	%f462, %r26;
	add.f32 	%f463, %f460, %f462;
	setp.gt.f32 	%p42, %f461, 0f3FB504F3;
	mul.f32 	%f464, %f461, 0f3F000000;
	add.f32 	%f465, %f463, 0f3F800000;
	selp.f32 	%f466, %f465, %f463, %p42;
	selp.f32 	%f467, %f464, %f461, %p42;
	add.f32 	%f468, %f467, 0fBF800000;
	add.f32 	%f469, %f467, 0f3F800000;
	rcp.approx.ftz.f32 	%f470, %f469;
	add.f32 	%f471, %f468, %f468;
	mul.f32 	%f472, %f471, %f470;
	mul.f32 	%f473, %f472, %f472;
	fma.rn.f32 	%f476, %f1262, %f473, %f1263;
	fma.rn.f32 	%f478, %f476, %f473, %f1264;
	mul.rn.f32 	%f479, %f478, %f473;
	mul.rn.f32 	%f480, %f479, %f472;
	sub.f32 	%f481, %f468, %f472;
	add.f32 	%f482, %f481, %f481;
	neg.f32 	%f483, %f472;
	fma.rn.f32 	%f484, %f483, %f468, %f482;
	mul.rn.f32 	%f485, %f470, %f484;
	add.f32 	%f486, %f480, %f472;
	sub.f32 	%f487, %f472, %f486;
	add.f32 	%f488, %f480, %f487;
	add.f32 	%f489, %f485, %f488;
	add.f32 	%f490, %f486, %f489;
	sub.f32 	%f491, %f486, %f490;
	add.f32 	%f492, %f489, %f491;
	mul.rn.f32 	%f494, %f466, %f1265;
	mul.rn.f32 	%f496, %f466, %f1266;
	add.f32 	%f497, %f494, %f490;
	sub.f32 	%f498, %f494, %f497;
	add.f32 	%f499, %f490, %f498;
	add.f32 	%f500, %f492, %f499;
	add.f32 	%f501, %f496, %f500;
	add.f32 	%f502, %f497, %f501;
	sub.f32 	%f503, %f497, %f502;
	add.f32 	%f504, %f501, %f503;
	mul.rn.f32 	%f505, %f456, %f502;
	neg.f32 	%f506, %f505;
	fma.rn.f32 	%f507, %f456, %f502, %f506;
	fma.rn.f32 	%f508, %f456, %f504, %f507;
	fma.rn.f32 	%f510, %f1267, %f502, %f508;
	add.rn.f32 	%f511, %f505, %f510;
	neg.f32 	%f512, %f511;
	add.rn.f32 	%f513, %f505, %f512;
	add.rn.f32 	%f514, %f513, %f510;
	mov.b32 	%r27, %f511;
	setp.eq.s32 	%p43, %r27, 1118925336;
	add.s32 	%r28, %r27, -1;
	mov.b32 	%f515, %r28;
	add.f32 	%f516, %f514, 0f37000000;
	selp.f32 	%f83, %f516, %f514, %p43;
	selp.f32 	%f517, %f515, %f511, %p43;
	mul.rn.f32 	%f519, %f517, %f430;
	cvt.rzi.f32.f32 	%f520, %f519;
	abs.f32 	%f521, %f520;
	setp.gt.f32 	%p44, %f521, 0f42FC0000;
	mov.b32 	%r29, %f520;
	and.b32  	%r30, %r29, -2147483648;
	or.b32  	%r31, %r30, 1123811328;
	mov.b32 	%f522, %r31;
	selp.f32 	%f523, %f522, %f520, %p44;
	fma.rn.f32 	%f525, %f523, %f436, %f517;
	fma.rn.f32 	%f527, %f523, %f438, %f525;
	mul.f32 	%f528, %f527, 0f3FB8AA3B;
	add.f32 	%f529, %f523, 0f4B40007F;
	mov.b32 	%r32, %f529;
	shl.b32 	%r33, %r32, 23;
	mov.b32 	%f530, %r33;
	ex2.approx.ftz.f32 	%f531, %f528;
	mul.f32 	%f84, %f531, %f530;
	setp.eq.f32 	%p45, %f84, 0f7F800000;
	mov.f32 	%f1357, 0f7F800000;
	@%p45 bra 	LBB0_48;

	fma.rn.f32 	%f1357, %f84, %f83, %f84;

LBB0_48:
	mov.f32 	%f1328, 0f3E800000;
	cvt.rzi.f32.f32 	%f1327, %f1328;
	add.f32 	%f1326, %f1327, %f1327;
	mov.f32 	%f1325, 0f3F000000;
	sub.f32 	%f1324, %f1325, %f1326;
	abs.f32 	%f1323, %f1324;
	setp.lt.f32 	%p46, %f80, 0f00000000;
	setp.eq.f32 	%p47, %f1323, 0f3F800000;
	and.pred  	%p2, %p46, %p47;
	setp.eq.f32 	%p48, %f80, 0f00000000;
	@%p48 bra 	LBB0_52;
	bra.uni 	LBB0_49;

LBB0_52:
	add.f32 	%f536, %f80, %f80;
	selp.f32 	%f1359, %f536, 0f00000000, %p47;
	bra.uni 	LBB0_53;

LBB0_49:
	mov.b32 	%r34, %f1357;
	xor.b32  	%r35, %r34, -2147483648;
	mov.b32 	%f532, %r35;
	selp.f32 	%f1359, %f532, %f1357, %p2;
	setp.geu.f32 	%p49, %f80, 0f00000000;
	@%p49 bra 	LBB0_53;

	cvt.rzi.f32.f32 	%f534, %f456;
	setp.eq.f32 	%p50, %f534, 0f3F000000;
	@%p50 bra 	LBB0_53;

	mov.f32 	%f1359, 0f7FFFFFFF;

LBB0_53:
	abs.f32 	%f1275, %f80;
	add.f32 	%f537, %f1275, 0f3F000000;
	mov.b32 	%r36, %f537;
	setp.lt.s32 	%p52, %r36, 2139095040;
	@%p52 bra 	LBB0_58;

	abs.f32 	%f1276, %f80;
	setp.gtu.f32 	%p53, %f1276, 0f7F800000;
	@%p53 bra 	LBB0_57;
	bra.uni 	LBB0_55;

LBB0_57:
	add.f32 	%f1359, %f80, 0f3F000000;
	bra.uni 	LBB0_58;

LBB0_55:
	abs.f32 	%f1277, %f80;
	setp.neu.f32 	%p54, %f1277, 0f7F800000;
	@%p54 bra 	LBB0_58;

	selp.f32 	%f1359, 0fFF800000, 0f7F800000, %p2;

LBB0_58:
	setp.eq.f32 	%p55, %f80, 0f3F800000;
	selp.f32 	%f540, 0f3F800000, %f1359, %p55;
	add.f32 	%f541, %f66, %f540;
	div.rn.f32 	%f93, %f541, 0f1AC84ACE;
	sub.f32 	%f542, %f53, %f93;
	abs.f32 	%f543, %f542;
	cvt.f64.f32 	%fd22, %f543;
	cvt.f64.f32 	%fd1, %f93;
	mul.f64 	%fd23, %fd1, 0d3F7CAC083126E979;
	setp.gt.f64 	%p56, %fd23, %fd22;
	setp.lt.f32 	%p57, %f53, %f93;
	mul.f32 	%f544, %f93, 0f3F7E353F;
	selp.f32 	%f545, %f544, %f53, %p56;
	selp.f32 	%f546, %f545, %f53, %p57;
	cvt.f64.f32 	%fd24, %f546;
	add.f64 	%fd25, %fd1, %fd1;
	setp.lt.f64 	%p58, %fd25, %fd24;
	add.f32 	%f547, %f93, %f93;
	selp.f32 	%f1377, %f547, %f546, %p58;
	setp.geu.f32 	%p59, %f1377, %f93;
	mov.f32 	%f1378, 0f3C23D70A;
	mov.f32 	%f1379, %f1378;
	@%p59 bra 	LBB0_92;

	div.rn.f32 	%f95, %f93, 0f41200000;
	setp.lt.f32 	%p60, %f1377, %f95;
	selp.f32 	%f548, %f95, %f1377, %p60;
	cvt.f64.f32 	%fd2, %f548;
	mul.f64 	%fd3, %fd1, 0d3FEFD70A3D70A3D7;
	setp.lt.f64 	%p61, %fd3, %fd2;
	cvt.rn.f32.f64 	%f549, %fd3;
	selp.f32 	%f1374, %f549, %f548, %p61;
	selp.f32 	%f97, %f548, %f1377, %p61;
	mul.f32 	%f550, %f1374, 0f19858734;
	rcp.rn.f32 	%f551, %f550;
	mul.f32 	%f98, %f35, %f551;
	abs.f32 	%f552, %f42;
	mul.f32 	%f99, %f551, %f552;
	abs.f32 	%f553, %f45;
	mul.f32 	%f100, %f551, %f553;
	mul.f32 	%f101, %f39, %f551;
	mul.f32 	%f554, %f99, 0f3F666666;
	fma.rn.f32 	%f102, %f98, 0f3F666666, %f554;
	add.f32 	%f555, %f102, %f102;
	mov.f32 	%f557, 0f3BBB989D;
	fma.rn.f32 	%f558, %f555, %f557, %f456;
	mov.f32 	%f560, 0f437C0000;
	cvt.sat.f32.f32 	%f561, %f558;
	mov.f32 	%f562, 0f4B400001;
	fma.rm.f32 	%f563, %f561, %f560, %f562;
	add.f32 	%f564, %f563, 0fCB40007F;
	neg.f32 	%f565, %f564;
	fma.rn.f32 	%f566, %f555, %f430, %f565;
	mov.f32 	%f567, 0f32A57060;
	fma.rn.f32 	%f568, %f555, %f567, %f566;
	mov.b32 	%r37, %f563;
	shl.b32 	%r38, %r37, 23;
	mov.b32 	%f569, %r38;
	ex2.approx.ftz.f32 	%f570, %f568;
	fma.rn.f32 	%f103, %f570, %f569, 0f3F800000;
	abs.f32 	%f571, %f103;
	cvt.f64.f32 	%fd26, %f571;
	setp.gt.f64 	%p62, %fd26, 0d6974E718D7D7625A;
	@%p62 bra 	LBB0_61;
	bra.uni 	LBB0_60;

LBB0_61:
	setp.gt.f32 	%p63, %f102, 0f00000000;
	selp.f32 	%f1360, 0f3F800000, 0fBF800000, %p63;
	bra.uni 	LBB0_62;

LBB0_60:
	add.f32 	%f572, %f103, 0fC0000000;
	div.rn.f32 	%f573, %f103, %f572;
	mov.f32 	%f574, 0fBF800000;
	div.rn.f32 	%f575, %f574, %f102;
	add.f32 	%f1360, %f573, %f575;

LBB0_62:
	mul.f32 	%f576, %f100, 0f3F666666;
	fma.rn.f32 	%f107, %f101, 0f3F666666, %f576;
	add.f32 	%f577, %f107, %f107;
	fma.rn.f32 	%f580, %f577, %f557, %f456;
	cvt.sat.f32.f32 	%f583, %f580;
	fma.rm.f32 	%f585, %f583, %f560, %f562;
	add.f32 	%f586, %f585, 0fCB40007F;
	neg.f32 	%f587, %f586;
	fma.rn.f32 	%f588, %f577, %f430, %f587;
	fma.rn.f32 	%f590, %f577, %f567, %f588;
	mov.b32 	%r39, %f585;
	shl.b32 	%r40, %r39, 23;
	mov.b32 	%f591, %r40;
	ex2.approx.ftz.f32 	%f592, %f590;
	fma.rn.f32 	%f108, %f592, %f591, 0f3F800000;
	abs.f32 	%f593, %f108;
	cvt.f64.f32 	%fd27, %f593;
	setp.gt.f64 	%p64, %fd27, 0d6974E718D7D7625A;
	@%p64 bra 	LBB0_64;
	bra.uni 	LBB0_63;

LBB0_64:
	setp.gt.f32 	%p65, %f107, 0f00000000;
	selp.f32 	%f1361, 0f3F800000, 0fBF800000, %p65;
	bra.uni 	LBB0_65;

LBB0_63:
	add.f32 	%f594, %f108, 0fC0000000;
	div.rn.f32 	%f595, %f108, %f594;
	mov.f32 	%f596, 0fBF800000;
	div.rn.f32 	%f597, %f596, %f107;
	add.f32 	%f1361, %f595, %f597;

LBB0_65:
	add.f32 	%f1365, %f1361, 0fBF666666;
	add.f32 	%f1364, %f1360, 0fBF666666;
	mov.f32 	%f1372, 0f3F666666;
	mov.f32 	%f600, 0f3EAAAAAB;
	mov.f32 	%f1373, %f1372;

LBB0_66:
	mul.f32 	%f601, %f99, %f1373;
	fma.rn.f32 	%f118, %f98, %f1372, %f601;
	abs.f32 	%f119, %f118;
	cvt.f64.f32 	%fd28, %f119;
	setp.lt.f64 	%p66, %fd28, 0d39B4484BFEEBC2A0;
	mov.f32 	%f1367, %f600;
	@%p66 bra 	LBB0_73;

	setp.ltu.f32 	%p67, %f119, 0f3F800000;
	mul.f32 	%f120, %f118, %f118;
	@%p67 bra 	LBB0_69;
	bra.uni 	LBB0_68;

LBB0_69:
	mov.f32 	%f623, 0f394FFF49;
	mov.f32 	%f624, 0f363D0ADA;
	fma.rn.f32 	%f625, %f624, %f120, %f623;
	mov.f32 	%f626, 0f3C08889A;
	fma.rn.f32 	%f627, %f625, %f120, %f626;
	mov.f32 	%f628, 0f3E2AAAAB;
	fma.rn.f32 	%f629, %f627, %f120, %f628;
	mul.f32 	%f630, %f120, %f629;
	fma.rn.f32 	%f1366, %f630, %f118, %f118;
	bra.uni 	LBB0_70;

LBB0_68:
	mul.rn.f32 	%f603, %f119, %f430;
	cvt.rzi.f32.f32 	%f604, %f603;
	abs.f32 	%f605, %f604;
	setp.gt.f32 	%p68, %f605, 0f42FC0000;
	mov.b32 	%r41, %f604;
	and.b32  	%r42, %r41, -2147483648;
	or.b32  	%r43, %r42, 1123811328;
	mov.b32 	%f606, %r43;
	selp.f32 	%f607, %f606, %f604, %p68;
	fma.rn.f32 	%f609, %f607, %f436, %f119;
	fma.rn.f32 	%f611, %f607, %f438, %f609;
	mul.f32 	%f612, %f611, 0f3FB8AA3B;
	add.f32 	%f613, %f607, 0f4B40007D;
	mov.b32 	%r44, %f613;
	shl.b32 	%r45, %r44, 23;
	mov.b32 	%f614, %r45;
	ex2.approx.ftz.f32 	%f615, %f612;
	mul.f32 	%f616, %f615, %f614;
	mov.f32 	%f617, 0f3E000000;
	div.approx.f32 	%f618, %f617, %f616;
	neg.f32 	%f619, %f618;
	fma.rn.f32 	%f621, %f369, %f616, %f619;
	setp.ge.f32 	%p69, %f119, 0f42B40000;
	selp.f32 	%f622, 0f7F800000, %f621, %p69;
	mov.b32 	%r46, %f622;
	mov.b32 	%r47, %f118;
	and.b32  	%r48, %r47, -2147483648;
	or.b32  	%r49, %r48, %r46;
	mov.b32 	%f1366, %r49;

LBB0_70:
	abs.f32 	%f631, %f1366;
	cvt.f64.f32 	%fd29, %f631;
	setp.gt.f64 	%p70, %fd29, 0d6974E718D7D7625A;
	@%p70 bra 	LBB0_72;
	bra.uni 	LBB0_71;

LBB0_72:
	rcp.rn.f32 	%f1367, %f120;
	bra.uni 	LBB0_73;

LBB0_71:
	mul.f32 	%f632, %f1366, %f1366;
	cvt.f64.f32 	%fd30, %f632;
	rcp.rn.f64 	%fd31, %fd30;
	cvt.f64.f32 	%fd32, %f120;
	rcp.rn.f64 	%fd33, %fd32;
	sub.f64 	%fd34, %fd33, %fd31;
	cvt.rn.f32.f64 	%f1367, %fd34;

LBB0_73:
	mul.f32 	%f634, %f101, %f1373;
	fma.rn.f32 	%f127, %f100, %f1372, %f634;
	abs.f32 	%f128, %f127;
	cvt.f64.f32 	%fd35, %f128;
	setp.lt.f64 	%p71, %fd35, 0d39B4484BFEEBC2A0;
	mov.f32 	%f1369, %f600;
	@%p71 bra 	LBB0_80;

	setp.ltu.f32 	%p72, %f128, 0f3F800000;
	mul.f32 	%f129, %f127, %f127;
	@%p72 bra 	LBB0_76;
	bra.uni 	LBB0_75;

LBB0_76:
	mov.f32 	%f656, 0f394FFF49;
	mov.f32 	%f657, 0f363D0ADA;
	fma.rn.f32 	%f658, %f657, %f129, %f656;
	mov.f32 	%f659, 0f3C08889A;
	fma.rn.f32 	%f660, %f658, %f129, %f659;
	mov.f32 	%f661, 0f3E2AAAAB;
	fma.rn.f32 	%f662, %f660, %f129, %f661;
	mul.f32 	%f663, %f129, %f662;
	fma.rn.f32 	%f1368, %f663, %f127, %f127;
	bra.uni 	LBB0_77;

LBB0_75:
	mul.rn.f32 	%f636, %f128, %f430;
	cvt.rzi.f32.f32 	%f637, %f636;
	abs.f32 	%f638, %f637;
	setp.gt.f32 	%p73, %f638, 0f42FC0000;
	mov.b32 	%r50, %f637;
	and.b32  	%r51, %r50, -2147483648;
	or.b32  	%r52, %r51, 1123811328;
	mov.b32 	%f639, %r52;
	selp.f32 	%f640, %f639, %f637, %p73;
	fma.rn.f32 	%f642, %f640, %f436, %f128;
	fma.rn.f32 	%f644, %f640, %f438, %f642;
	mul.f32 	%f645, %f644, 0f3FB8AA3B;
	add.f32 	%f646, %f640, 0f4B40007D;
	mov.b32 	%r53, %f646;
	shl.b32 	%r54, %r53, 23;
	mov.b32 	%f647, %r54;
	ex2.approx.ftz.f32 	%f648, %f645;
	mul.f32 	%f649, %f648, %f647;
	mov.f32 	%f650, 0f3E000000;
	div.approx.f32 	%f651, %f650, %f649;
	neg.f32 	%f652, %f651;
	fma.rn.f32 	%f654, %f369, %f649, %f652;
	setp.ge.f32 	%p74, %f128, 0f42B40000;
	selp.f32 	%f655, 0f7F800000, %f654, %p74;
	mov.b32 	%r55, %f655;
	mov.b32 	%r56, %f127;
	and.b32  	%r57, %r56, -2147483648;
	or.b32  	%r58, %r57, %r55;
	mov.b32 	%f1368, %r58;

LBB0_77:
	abs.f32 	%f664, %f1368;
	cvt.f64.f32 	%fd36, %f664;
	setp.gt.f64 	%p75, %fd36, 0d6974E718D7D7625A;
	@%p75 bra 	LBB0_79;
	bra.uni 	LBB0_78;

LBB0_79:
	rcp.rn.f32 	%f1369, %f129;
	bra.uni 	LBB0_80;

LBB0_78:
	mul.f32 	%f665, %f1368, %f1368;
	cvt.f64.f32 	%fd37, %f665;
	rcp.rn.f64 	%fd38, %fd37;
	cvt.f64.f32 	%fd39, %f129;
	rcp.rn.f64 	%fd40, %fd39;
	sub.f64 	%fd41, %fd40, %fd38;
	cvt.rn.f32.f64 	%f1369, %fd41;

LBB0_80:
	fma.rn.f32 	%f136, %f98, %f1367, 0fBF800000;
	fma.rn.f32 	%f137, %f101, %f1369, 0fBF800000;
	mul.f32 	%f666, %f136, %f137;
	mul.f32 	%f138, %f100, %f1369;
	mul.f32 	%f139, %f99, %f1367;
	mul.f32 	%f667, %f139, %f138;
	sub.f32 	%f140, %f666, %f667;
	setp.eq.f32 	%p76, %f140, 0f00000000;
	@%p76 bra 	LBB0_88;

	rcp.rn.f32 	%f668, %f140;
	mul.f32 	%f669, %f1365, %f139;
	mul.f32 	%f670, %f1364, %f137;
	sub.f32 	%f671, %f670, %f669;
	mul.f32 	%f141, %f671, %f668;
	mul.f32 	%f672, %f1365, %f136;
	mul.f32 	%f673, %f1364, %f138;
	sub.f32 	%f674, %f672, %f673;
	mul.f32 	%f142, %f674, %f668;
	sub.f32 	%f1372, %f1372, %f141;
	sub.f32 	%f1373, %f1373, %f142;
	mul.f32 	%f675, %f99, %f1373;
	fma.rn.f32 	%f145, %f98, %f1372, %f675;
	add.f32 	%f676, %f145, %f145;
	fma.rn.f32 	%f679, %f676, %f557, %f456;
	cvt.sat.f32.f32 	%f682, %f679;
	fma.rm.f32 	%f684, %f682, %f560, %f562;
	add.f32 	%f685, %f684, 0fCB40007F;
	neg.f32 	%f686, %f685;
	fma.rn.f32 	%f687, %f676, %f430, %f686;
	fma.rn.f32 	%f689, %f676, %f567, %f687;
	mov.b32 	%r59, %f684;
	shl.b32 	%r60, %r59, 23;
	mov.b32 	%f690, %r60;
	ex2.approx.ftz.f32 	%f691, %f689;
	fma.rn.f32 	%f146, %f691, %f690, 0f3F800000;
	abs.f32 	%f692, %f146;
	cvt.f64.f32 	%fd42, %f692;
	setp.gt.f64 	%p77, %fd42, 0d6974E718D7D7625A;
	@%p77 bra 	LBB0_83;
	bra.uni 	LBB0_82;

LBB0_83:
	setp.gt.f32 	%p78, %f145, 0f00000000;
	selp.f32 	%f1370, 0f3F800000, 0fBF800000, %p78;
	bra.uni 	LBB0_84;

LBB0_82:
	add.f32 	%f693, %f146, 0fC0000000;
	div.rn.f32 	%f694, %f146, %f693;
	mov.f32 	%f695, 0fBF800000;
	div.rn.f32 	%f696, %f695, %f145;
	add.f32 	%f1370, %f694, %f696;

LBB0_84:
	mul.f32 	%f697, %f101, %f1373;
	fma.rn.f32 	%f150, %f100, %f1372, %f697;
	add.f32 	%f698, %f150, %f150;
	fma.rn.f32 	%f701, %f698, %f557, %f456;
	cvt.sat.f32.f32 	%f704, %f701;
	fma.rm.f32 	%f706, %f704, %f560, %f562;
	add.f32 	%f707, %f706, 0fCB40007F;
	neg.f32 	%f708, %f707;
	fma.rn.f32 	%f709, %f698, %f430, %f708;
	fma.rn.f32 	%f711, %f698, %f567, %f709;
	mov.b32 	%r61, %f706;
	shl.b32 	%r62, %r61, 23;
	mov.b32 	%f712, %r62;
	ex2.approx.ftz.f32 	%f713, %f711;
	fma.rn.f32 	%f151, %f713, %f712, 0f3F800000;
	abs.f32 	%f714, %f151;
	cvt.f64.f32 	%fd43, %f714;
	setp.gt.f64 	%p79, %fd43, 0d6974E718D7D7625A;
	@%p79 bra 	LBB0_86;
	bra.uni 	LBB0_85;

LBB0_86:
	setp.gt.f32 	%p80, %f150, 0f00000000;
	selp.f32 	%f1371, 0f3F800000, 0fBF800000, %p80;
	bra.uni 	LBB0_87;

LBB0_85:
	add.f32 	%f715, %f151, 0fC0000000;
	div.rn.f32 	%f716, %f151, %f715;
	mov.f32 	%f717, 0fBF800000;
	div.rn.f32 	%f718, %f717, %f150;
	add.f32 	%f1371, %f716, %f718;

LBB0_87:
	sub.f32 	%f1365, %f1371, %f1373;
	mul.f32 	%f719, %f141, %f141;
	setp.gt.f32 	%p81, %f719, 0f38D1B717;
	mul.f32 	%f720, %f142, %f142;
	setp.gt.f32 	%p82, %f720, 0f38D1B717;
	or.pred  	%p83, %p81, %p82;
	sub.f32 	%f1364, %f1370, %f1372;
	@%p83 bra 	LBB0_66;

LBB0_88:
	setp.gt.f32 	%p84, %f1372, 0f38D1B717;
	selp.f32 	%f1378, %f1372, 0f3A83126F, %p84;
	setp.gt.f32 	%p85, %f1373, 0f38D1B717;
	selp.f32 	%f1379, %f1373, 0f3A83126F, %p85;
	setp.geu.f32 	%p86, %f1377, %f95;
	@%p86 bra 	LBB0_90;

	add.f32 	%f721, %f1378, 0fBF800000;
	div.rn.f32 	%f722, %f721, %f1374;
	fma.rn.f32 	%f1378, %f97, %f722, 0f3F800000;
	add.f32 	%f723, %f1379, 0fBF800000;
	div.rn.f32 	%f724, %f723, %f1374;
	fma.rn.f32 	%f1379, %f97, %f724, 0f3F800000;
	mov.f32 	%f1374, %f97;

LBB0_90:
	setp.geu.f64 	%p87, %fd3, %fd2;
	mov.f32 	%f1377, %f1374;
	@%p87 bra 	LBB0_92;

	sub.f32 	%f725, %f93, %f97;
	mul.f32 	%f726, %f725, %f1378;
	mul.f32 	%f727, %f93, 0f3BA3D70A;
	div.rn.f32 	%f1378, %f726, %f727;
	mul.f32 	%f728, %f725, %f1379;
	div.rn.f32 	%f1379, %f728, %f727;
	mov.f32 	%f1377, %f97;

LBB0_92:
	setp.lt.f32 	%p88, %f1378, 0f3C23D70A;
	selp.f32 	%f171, 0f3C23D70A, %f1378, %p88;
	setp.lt.f32 	%p89, %f1379, 0f3C23D70A;
	selp.f32 	%f172, 0f3C23D70A, %f1379, %p89;
	mul.f32 	%f173, %f1377, 0f19858734;
	add.f32 	%f174, %f1339, %f1339;
	mul.f32 	%f729, %f174, 0f19858734;
	mul.f32 	%f175, %f729, %f1377;
	add.f32 	%f176, %f1340, %f1340;
	mul.f32 	%f730, %f176, 0f19858734;
	mul.f32 	%f177, %f730, %f1377;
	setp.lt.f32 	%p90, %f1377, %f93;
	@%p90 bra 	LBB0_94;
	bra.uni 	LBB0_93;

LBB0_94:
	mov.f32 	%f1274, 0f3F800000;
	mul.f32 	%f734, %f175, %f171;
	abs.f32 	%f735, %f42;
	mul.f32 	%f736, %f172, %f735;
	fma.rn.f32 	%f737, %f35, %f171, %f736;
	div.rn.f32 	%f1380, %f734, %f737;
	abs.f32 	%f738, %f45;
	mul.f32 	%f739, %f171, %f738;
	fma.rn.f32 	%f740, %f39, %f172, %f739;
	mul.f32 	%f741, %f177, %f172;
	div.rn.f32 	%f1381, %f741, %f740;
	mul.f32 	%f742, %f173, %f171;
	div.rn.f32 	%f743, %f742, %f737;
	sub.f32 	%f745, %f1274, %f743;
	mul.f32 	%f1382, %f1339, %f745;
	mul.f32 	%f746, %f173, %f172;
	div.rn.f32 	%f747, %f746, %f740;
	sub.f32 	%f748, %f1274, %f747;
	mul.f32 	%f1383, %f1340, %f748;
	bra.uni 	LBB0_95;

LBB0_93:
	mul.f32 	%f731, %f174, %f1377;
	mul.f32 	%f732, %f93, 0f40400000;
	div.rn.f32 	%f1380, %f731, %f732;
	mul.f32 	%f733, %f176, %f1377;
	div.rn.f32 	%f1381, %f733, %f732;
	mov.f32 	%f1382, %f1380;
	mov.f32 	%f1383, %f1381;

LBB0_95:
	div.rn.f32 	%f749, %f35, %f1346;
	fma.rn.f32 	%f750, %f1, %f749, %f7;
	fma.rn.f32 	%f751, %f2, %f749, %f8;
	fma.rn.f32 	%f752, %f3, %f749, %f9;
	div.rn.f32 	%f753, %f42, %f1346;
	fma.rn.f32 	%f188, %f4, %f753, %f750;
	fma.rn.f32 	%f189, %f5, %f753, %f751;
	fma.rn.f32 	%f190, %f6, %f753, %f752;
	div.rn.f32 	%f754, %f39, %f1347;
	fma.rn.f32 	%f755, %f4, %f754, %f10;
	fma.rn.f32 	%f756, %f5, %f754, %f11;
	fma.rn.f32 	%f757, %f6, %f754, %f12;
	div.rn.f32 	%f758, %f45, %f1347;
	fma.rn.f32 	%f191, %f1, %f758, %f755;
	fma.rn.f32 	%f192, %f2, %f758, %f756;
	fma.rn.f32 	%f193, %f3, %f758, %f757;
	rcp.rn.f32 	%f759, %f173;
	mul.f32 	%f194, %f1346, %f759;
	mul.f32 	%f195, %f188, %f194;
	mul.f32 	%f196, %f189, %f194;
	mul.f32 	%f197, %f190, %f194;
	mul.f32 	%f198, %f1347, %f759;
	mul.f32 	%f199, %f191, %f198;
	mul.f32 	%f200, %f192, %f198;
	mul.f32 	%f201, %f193, %f198;
	mul.f32 	%f760, %f196, %f196;
	fma.rn.f32 	%f761, %f195, %f195, %f760;
	fma.rn.f32 	%f762, %f197, %f197, %f761;
	sqrt.rn.f32 	%f202, %f762;
	mul.f32 	%f763, %f200, %f200;
	fma.rn.f32 	%f764, %f199, %f199, %f763;
	fma.rn.f32 	%f765, %f201, %f201, %f764;
	sqrt.rn.f32 	%f203, %f765;
	div.rn.f32 	%f204, %f175, %f1346;
	div.rn.f32 	%f205, %f177, %f1347;
	mul.f32 	%f206, %f202, %f202;
	abs.f32 	%f207, %f202;
	setp.ltu.f32 	%p91, %f207, 0f3F800000;
	@%p91 bra 	LBB0_97;
	bra.uni 	LBB0_96;

LBB0_97:
	mov.f32 	%f787, 0f394FFF49;
	mov.f32 	%f788, 0f363D0ADA;
	fma.rn.f32 	%f789, %f788, %f206, %f787;
	mov.f32 	%f790, 0f3C08889A;
	fma.rn.f32 	%f791, %f789, %f206, %f790;
	mov.f32 	%f792, 0f3E2AAAAB;
	fma.rn.f32 	%f793, %f791, %f206, %f792;
	mul.f32 	%f794, %f206, %f793;
	fma.rn.f32 	%f1384, %f794, %f202, %f202;
	bra.uni 	LBB0_98;

LBB0_96:
	mul.rn.f32 	%f767, %f207, %f430;
	cvt.rzi.f32.f32 	%f768, %f767;
	abs.f32 	%f769, %f768;
	setp.gt.f32 	%p92, %f769, 0f42FC0000;
	mov.b32 	%r63, %f768;
	and.b32  	%r64, %r63, -2147483648;
	or.b32  	%r65, %r64, 1123811328;
	mov.b32 	%f770, %r65;
	selp.f32 	%f771, %f770, %f768, %p92;
	fma.rn.f32 	%f773, %f771, %f436, %f207;
	fma.rn.f32 	%f775, %f771, %f438, %f773;
	mul.f32 	%f776, %f775, 0f3FB8AA3B;
	add.f32 	%f777, %f771, 0f4B40007D;
	mov.b32 	%r66, %f777;
	shl.b32 	%r67, %r66, 23;
	mov.b32 	%f778, %r67;
	ex2.approx.ftz.f32 	%f779, %f776;
	mul.f32 	%f780, %f779, %f778;
	mov.f32 	%f781, 0f3E000000;
	div.approx.f32 	%f782, %f781, %f780;
	neg.f32 	%f783, %f782;
	fma.rn.f32 	%f785, %f369, %f780, %f783;
	setp.ge.f32 	%p93, %f207, 0f42B40000;
	selp.f32 	%f786, 0f7F800000, %f785, %p93;
	mov.b32 	%r68, %f786;
	mov.b32 	%r69, %f202;
	and.b32  	%r70, %r69, -2147483648;
	or.b32  	%r71, %r70, %r68;
	mov.b32 	%f1384, %r71;

LBB0_98:
	mov.f32 	%f1273, 0f00000000;
	mov.f32 	%f1272, 0f35BFBE8E;
	mov.f32 	%f1271, 0f3F317200;
	mov.f32 	%f1270, 0f3DAAAABD;
	mov.f32 	%f1269, 0f3C4CAF63;
	mov.f32 	%f1268, 0f3B18F0FE;
	rcp.rn.f32 	%f211, %f1384;
	abs.f32 	%f212, %f211;
	setp.lt.f32 	%p94, %f212, 0f00800000;
	mul.f32 	%f796, %f212, 0f4B800000;
	selp.f32 	%f797, %f796, %f212, %p94;
	selp.f32 	%f798, 0fC3170000, 0fC2FE0000, %p94;
	mov.b32 	%r72, %f797;
	and.b32  	%r73, %r72, 8388607;
	or.b32  	%r74, %r73, 1065353216;
	mov.b32 	%f799, %r74;
	shr.u32 	%r75, %r72, 23;
	cvt.rn.f32.u32 	%f800, %r75;
	add.f32 	%f801, %f798, %f800;
	setp.gt.f32 	%p95, %f799, 0f3FB504F3;
	mul.f32 	%f802, %f799, 0f3F000000;
	add.f32 	%f803, %f801, 0f3F800000;
	selp.f32 	%f804, %f803, %f801, %p95;
	selp.f32 	%f805, %f802, %f799, %p95;
	add.f32 	%f806, %f805, 0fBF800000;
	add.f32 	%f807, %f805, 0f3F800000;
	rcp.approx.ftz.f32 	%f808, %f807;
	add.f32 	%f809, %f806, %f806;
	mul.f32 	%f811, %f809, %f808;
	mul.f32 	%f812, %f811, %f811;
	fma.rn.f32 	%f815, %f1268, %f812, %f1269;
	fma.rn.f32 	%f817, %f815, %f812, %f1270;
	mul.rn.f32 	%f818, %f817, %f812;
	mul.rn.f32 	%f819, %f818, %f811;
	sub.f32 	%f820, %f806, %f811;
	add.f32 	%f821, %f820, %f820;
	neg.f32 	%f822, %f811;
	fma.rn.f32 	%f823, %f822, %f806, %f821;
	mul.rn.f32 	%f824, %f808, %f823;
	add.f32 	%f825, %f819, %f811;
	sub.f32 	%f826, %f811, %f825;
	add.f32 	%f827, %f819, %f826;
	add.f32 	%f828, %f824, %f827;
	add.f32 	%f829, %f825, %f828;
	sub.f32 	%f830, %f825, %f829;
	add.f32 	%f831, %f828, %f830;
	mul.rn.f32 	%f833, %f804, %f1271;
	mul.rn.f32 	%f835, %f804, %f1272;
	add.f32 	%f836, %f833, %f829;
	sub.f32 	%f837, %f833, %f836;
	add.f32 	%f838, %f829, %f837;
	add.f32 	%f839, %f831, %f838;
	add.f32 	%f840, %f835, %f839;
	add.f32 	%f841, %f836, %f840;
	sub.f32 	%f842, %f836, %f841;
	add.f32 	%f843, %f840, %f842;
	mul.rn.f32 	%f844, %f369, %f841;
	neg.f32 	%f845, %f844;
	fma.rn.f32 	%f846, %f369, %f841, %f845;
	fma.rn.f32 	%f847, %f369, %f843, %f846;
	fma.rn.f32 	%f849, %f1273, %f841, %f847;
	add.rn.f32 	%f850, %f844, %f849;
	neg.f32 	%f851, %f850;
	add.rn.f32 	%f852, %f844, %f851;
	add.rn.f32 	%f853, %f852, %f849;
	mov.b32 	%r76, %f850;
	setp.eq.s32 	%p96, %r76, 1118925336;
	add.s32 	%r77, %r76, -1;
	mov.b32 	%f854, %r77;
	add.f32 	%f855, %f853, 0f37000000;
	selp.f32 	%f213, %f855, %f853, %p96;
	selp.f32 	%f856, %f854, %f850, %p96;
	mul.rn.f32 	%f858, %f856, %f430;
	cvt.rzi.f32.f32 	%f859, %f858;
	abs.f32 	%f860, %f859;
	setp.gt.f32 	%p97, %f860, 0f42FC0000;
	mov.b32 	%r78, %f859;
	and.b32  	%r79, %r78, -2147483648;
	or.b32  	%r80, %r79, 1123811328;
	mov.b32 	%f861, %r80;
	selp.f32 	%f862, %f861, %f859, %p97;
	fma.rn.f32 	%f864, %f862, %f436, %f856;
	fma.rn.f32 	%f866, %f862, %f438, %f864;
	mul.f32 	%f867, %f866, 0f3FB8AA3B;
	add.f32 	%f868, %f862, 0f4B40007F;
	mov.b32 	%r81, %f868;
	shl.b32 	%r82, %r81, 23;
	mov.b32 	%f869, %r82;
	ex2.approx.ftz.f32 	%f870, %f867;
	mul.f32 	%f214, %f870, %f869;
	setp.eq.f32 	%p98, %f214, 0f7F800000;
	mov.f32 	%f1385, 0f7F800000;
	@%p98 bra 	LBB0_100;

	fma.rn.f32 	%f1385, %f214, %f213, %f214;

LBB0_100:
	setp.lt.f32 	%p99, %f211, 0f00000000;
	and.pred  	%p3, %p99, %p32;
	setp.eq.f32 	%p101, %f211, 0f00000000;
	@%p101 bra 	LBB0_104;
	bra.uni 	LBB0_101;

LBB0_104:
	add.f32 	%f875, %f211, %f211;
	selp.f32 	%f1387, %f875, 0f00000000, %p32;
	bra.uni 	LBB0_105;

LBB0_101:
	mov.b32 	%r83, %f1385;
	xor.b32  	%r84, %r83, -2147483648;
	mov.b32 	%f871, %r84;
	selp.f32 	%f1387, %f871, %f1385, %p3;
	setp.geu.f32 	%p102, %f211, 0f00000000;
	@%p102 bra 	LBB0_105;

	mov.f32 	%f1294, 0f40000000;
	cvt.rzi.f32.f32 	%f873, %f1294;
	setp.eq.f32 	%p103, %f873, 0f40000000;
	@%p103 bra 	LBB0_105;

	mov.f32 	%f1387, 0f7FFFFFFF;

LBB0_105:
	abs.f32 	%f1244, %f211;
	add.f32 	%f876, %f1244, 0f40000000;
	mov.b32 	%r85, %f876;
	setp.lt.s32 	%p105, %r85, 2139095040;
	@%p105 bra 	LBB0_110;

	abs.f32 	%f1260, %f211;
	setp.gtu.f32 	%p106, %f1260, 0f7F800000;
	@%p106 bra 	LBB0_109;
	bra.uni 	LBB0_107;

LBB0_109:
	add.f32 	%f1387, %f211, 0f40000000;
	bra.uni 	LBB0_110;

LBB0_107:
	abs.f32 	%f1261, %f211;
	setp.neu.f32 	%p107, %f1261, 0f7F800000;
	@%p107 bra 	LBB0_110;

	selp.f32 	%f1387, 0fFF800000, 0f7F800000, %p3;

LBB0_110:
	mul.f32 	%f1245, %f202, %f202;
	setp.eq.f32 	%p108, %f211, 0f3F800000;
	selp.f32 	%f877, 0f3F800000, %f1387, %p108;
	rcp.rn.f32 	%f878, %f1245;
	sub.f32 	%f223, %f878, %f877;
	cvt.f64.f32 	%fd4, %f223;
	mul.f32 	%f224, %f203, %f203;
	abs.f32 	%f225, %f203;
	setp.ltu.f32 	%p109, %f225, 0f3F800000;
	@%p109 bra 	LBB0_112;
	bra.uni 	LBB0_111;

LBB0_112:
	mov.f32 	%f900, 0f394FFF49;
	mov.f32 	%f901, 0f363D0ADA;
	fma.rn.f32 	%f902, %f901, %f224, %f900;
	mov.f32 	%f903, 0f3C08889A;
	fma.rn.f32 	%f904, %f902, %f224, %f903;
	mov.f32 	%f905, 0f3E2AAAAB;
	fma.rn.f32 	%f906, %f904, %f224, %f905;
	mul.f32 	%f907, %f224, %f906;
	fma.rn.f32 	%f1388, %f907, %f203, %f203;
	bra.uni 	LBB0_113;

LBB0_111:
	mov.f32 	%f1290, 0fBF317218;
	mov.f32 	%f1289, 0f3FB8AA3B;
	mov.f32 	%f1288, 0f40000000;
	mov.f32 	%f1246, 0f3102E308;
	mul.rn.f32 	%f880, %f225, %f1289;
	cvt.rzi.f32.f32 	%f881, %f880;
	abs.f32 	%f882, %f881;
	setp.gt.f32 	%p110, %f882, 0f42FC0000;
	mov.b32 	%r86, %f881;
	and.b32  	%r87, %r86, -2147483648;
	or.b32  	%r88, %r87, 1123811328;
	mov.b32 	%f883, %r88;
	selp.f32 	%f884, %f883, %f881, %p110;
	fma.rn.f32 	%f886, %f884, %f1290, %f225;
	fma.rn.f32 	%f888, %f884, %f1246, %f886;
	mul.f32 	%f889, %f888, 0f3FB8AA3B;
	add.f32 	%f890, %f884, 0f4B40007D;
	mov.b32 	%r89, %f890;
	shl.b32 	%r90, %r89, 23;
	mov.b32 	%f891, %r90;
	ex2.approx.ftz.f32 	%f892, %f889;
	mul.f32 	%f893, %f892, %f891;
	mov.f32 	%f894, 0f3E000000;
	div.approx.f32 	%f895, %f894, %f893;
	neg.f32 	%f896, %f895;
	fma.rn.f32 	%f898, %f1288, %f893, %f896;
	setp.ge.f32 	%p111, %f225, 0f42B40000;
	selp.f32 	%f899, 0f7F800000, %f898, %p111;
	mov.b32 	%r91, %f899;
	mov.b32 	%r92, %f203;
	and.b32  	%r93, %r92, -2147483648;
	or.b32  	%r94, %r93, %r91;
	mov.b32 	%f1388, %r94;

LBB0_113:
	mov.f32 	%f1293, 0fBF317218;
	mov.f32 	%f1292, 0f3FB8AA3B;
	mov.f32 	%f1291, 0f40000000;
	mov.f32 	%f1253, 0f3102E308;
	mov.f32 	%f1252, 0f00000000;
	mov.f32 	%f1251, 0f35BFBE8E;
	mov.f32 	%f1250, 0f3F317200;
	mov.f32 	%f1249, 0f3DAAAABD;
	mov.f32 	%f1248, 0f3C4CAF63;
	mov.f32 	%f1247, 0f3B18F0FE;
	rcp.rn.f32 	%f229, %f1388;
	abs.f32 	%f230, %f229;
	setp.lt.f32 	%p112, %f230, 0f00800000;
	mul.f32 	%f909, %f230, 0f4B800000;
	selp.f32 	%f910, %f909, %f230, %p112;
	selp.f32 	%f911, 0fC3170000, 0fC2FE0000, %p112;
	mov.b32 	%r95, %f910;
	and.b32  	%r96, %r95, 8388607;
	or.b32  	%r97, %r96, 1065353216;
	mov.b32 	%f912, %r97;
	shr.u32 	%r98, %r95, 23;
	cvt.rn.f32.u32 	%f913, %r98;
	add.f32 	%f914, %f911, %f913;
	setp.gt.f32 	%p113, %f912, 0f3FB504F3;
	mul.f32 	%f915, %f912, 0f3F000000;
	add.f32 	%f916, %f914, 0f3F800000;
	selp.f32 	%f917, %f916, %f914, %p113;
	selp.f32 	%f918, %f915, %f912, %p113;
	add.f32 	%f919, %f918, 0fBF800000;
	add.f32 	%f920, %f918, 0f3F800000;
	rcp.approx.ftz.f32 	%f921, %f920;
	add.f32 	%f922, %f919, %f919;
	mul.f32 	%f924, %f922, %f921;
	mul.f32 	%f925, %f924, %f924;
	fma.rn.f32 	%f928, %f1247, %f925, %f1248;
	fma.rn.f32 	%f930, %f928, %f925, %f1249;
	mul.rn.f32 	%f931, %f930, %f925;
	mul.rn.f32 	%f932, %f931, %f924;
	sub.f32 	%f933, %f919, %f924;
	add.f32 	%f934, %f933, %f933;
	neg.f32 	%f935, %f924;
	fma.rn.f32 	%f936, %f935, %f919, %f934;
	mul.rn.f32 	%f937, %f921, %f936;
	add.f32 	%f938, %f932, %f924;
	sub.f32 	%f939, %f924, %f938;
	add.f32 	%f940, %f932, %f939;
	add.f32 	%f941, %f937, %f940;
	add.f32 	%f942, %f938, %f941;
	sub.f32 	%f943, %f938, %f942;
	add.f32 	%f944, %f941, %f943;
	mul.rn.f32 	%f946, %f917, %f1250;
	mul.rn.f32 	%f948, %f917, %f1251;
	add.f32 	%f949, %f946, %f942;
	sub.f32 	%f950, %f946, %f949;
	add.f32 	%f951, %f942, %f950;
	add.f32 	%f952, %f944, %f951;
	add.f32 	%f953, %f948, %f952;
	add.f32 	%f954, %f949, %f953;
	sub.f32 	%f955, %f949, %f954;
	add.f32 	%f956, %f953, %f955;
	mul.rn.f32 	%f957, %f1291, %f954;
	neg.f32 	%f958, %f957;
	fma.rn.f32 	%f959, %f1291, %f954, %f958;
	fma.rn.f32 	%f960, %f1291, %f956, %f959;
	fma.rn.f32 	%f962, %f1252, %f954, %f960;
	add.rn.f32 	%f963, %f957, %f962;
	neg.f32 	%f964, %f963;
	add.rn.f32 	%f965, %f957, %f964;
	add.rn.f32 	%f966, %f965, %f962;
	mov.b32 	%r99, %f963;
	setp.eq.s32 	%p114, %r99, 1118925336;
	add.s32 	%r100, %r99, -1;
	mov.b32 	%f967, %r100;
	add.f32 	%f968, %f966, 0f37000000;
	selp.f32 	%f231, %f968, %f966, %p114;
	selp.f32 	%f969, %f967, %f963, %p114;
	mul.rn.f32 	%f971, %f969, %f1292;
	cvt.rzi.f32.f32 	%f972, %f971;
	abs.f32 	%f973, %f972;
	setp.gt.f32 	%p115, %f973, 0f42FC0000;
	mov.b32 	%r101, %f972;
	and.b32  	%r102, %r101, -2147483648;
	or.b32  	%r103, %r102, 1123811328;
	mov.b32 	%f974, %r103;
	selp.f32 	%f975, %f974, %f972, %p115;
	fma.rn.f32 	%f977, %f975, %f1293, %f969;
	fma.rn.f32 	%f979, %f975, %f1253, %f977;
	mul.f32 	%f980, %f979, 0f3FB8AA3B;
	add.f32 	%f981, %f975, 0f4B40007F;
	mov.b32 	%r104, %f981;
	shl.b32 	%r105, %r104, 23;
	mov.b32 	%f982, %r105;
	ex2.approx.ftz.f32 	%f983, %f980;
	mul.f32 	%f232, %f983, %f982;
	setp.eq.f32 	%p116, %f232, 0f7F800000;
	mov.f32 	%f1389, 0f7F800000;
	@%p116 bra 	LBB0_115;

	fma.rn.f32 	%f1389, %f232, %f231, %f232;

LBB0_115:
	setp.lt.f32 	%p117, %f229, 0f00000000;
	and.pred  	%p4, %p117, %p32;
	setp.eq.f32 	%p119, %f229, 0f00000000;
	@%p119 bra 	LBB0_119;
	bra.uni 	LBB0_116;

LBB0_119:
	add.f32 	%f988, %f229, %f229;
	selp.f32 	%f1391, %f988, 0f00000000, %p32;
	bra.uni 	LBB0_120;

LBB0_116:
	mov.b32 	%r106, %f1389;
	xor.b32  	%r107, %r106, -2147483648;
	mov.b32 	%f984, %r107;
	selp.f32 	%f1391, %f984, %f1389, %p4;
	setp.geu.f32 	%p120, %f229, 0f00000000;
	@%p120 bra 	LBB0_120;

	mov.f32 	%f1287, 0f40000000;
	cvt.rzi.f32.f32 	%f986, %f1287;
	setp.eq.f32 	%p121, %f986, 0f40000000;
	@%p121 bra 	LBB0_120;

	mov.f32 	%f1391, 0f7FFFFFFF;

LBB0_120:
	abs.f32 	%f1278, %f229;
	add.f32 	%f989, %f1278, 0f40000000;
	mov.b32 	%r108, %f989;
	setp.lt.s32 	%p123, %r108, 2139095040;
	@%p123 bra 	LBB0_125;

	abs.f32 	%f1285, %f229;
	setp.gtu.f32 	%p124, %f1285, 0f7F800000;
	@%p124 bra 	LBB0_124;
	bra.uni 	LBB0_122;

LBB0_124:
	add.f32 	%f1391, %f229, 0f40000000;
	bra.uni 	LBB0_125;

LBB0_122:
	abs.f32 	%f1286, %f229;
	setp.neu.f32 	%p125, %f1286, 0f7F800000;
	@%p125 bra 	LBB0_125;

	selp.f32 	%f1391, 0fFF800000, 0f7F800000, %p4;

LBB0_125:
	mul.f32 	%f1280, %f203, %f203;
	mov.f32 	%f1279, 0f3FB8AA3B;
	mov.f32 	%f1254, 0f3F000000;
	setp.eq.f32 	%p126, %f229, 0f3F800000;
	selp.f32 	%f990, 0f3F800000, %f1391, %p126;
	rcp.rn.f32 	%f991, %f1280;
	sub.f32 	%f241, %f991, %f990;
	cvt.f64.f32 	%fd5, %f241;
	add.f32 	%f992, %f202, %f202;
	mov.f32 	%f994, 0f3BBB989D;
	fma.rn.f32 	%f995, %f992, %f994, %f1254;
	mov.f32 	%f997, 0f437C0000;
	cvt.sat.f32.f32 	%f998, %f995;
	mov.f32 	%f999, 0f4B400001;
	fma.rm.f32 	%f1000, %f998, %f997, %f999;
	add.f32 	%f1001, %f1000, 0fCB40007F;
	neg.f32 	%f1002, %f1001;
	fma.rn.f32 	%f1003, %f992, %f1279, %f1002;
	mov.f32 	%f1004, 0f32A57060;
	fma.rn.f32 	%f1005, %f992, %f1004, %f1003;
	mov.b32 	%r109, %f1000;
	shl.b32 	%r110, %r109, 23;
	mov.b32 	%f1006, %r110;
	ex2.approx.ftz.f32 	%f1007, %f1005;
	mul.f32 	%f1008, %f1007, %f1006;
	cvt.f64.f32 	%fd44, %f1008;
	add.f64 	%fd6, %fd44, 0d3FF0000000000000;
	abs.f64 	%fd7, %fd6;
	div.rn.f32 	%f1009, %f93, 0f40A00000;
	setp.lt.f32 	%p127, %f1377, %f1009;
	@%p127 bra 	LBB0_133;
	bra.uni 	LBB0_126;

LBB0_133:
	setp.gt.f64 	%p136, %fd7, 0d7FE1CCF385EBC8A0;
	@%p136 bra 	LBB0_135;
	bra.uni 	LBB0_134;

LBB0_135:
	setp.gt.f32 	%p137, %f202, 0f00000000;
	selp.f64 	%fd80, 0d3FF0000000000000, 0dBFF0000000000000, %p137;
	bra.uni 	LBB0_136;

LBB0_126:
	setp.gt.f64 	%p128, %fd7, 0d7FE1CCF385EBC8A0;
	@%p128 bra 	LBB0_128;
	bra.uni 	LBB0_127;

LBB0_128:
	setp.gt.f32 	%p130, %f202, 0f00000000;
	selp.f64 	%fd78, 0d3FF0000000000000, 0dBFF0000000000000, %p130;
	bra.uni 	LBB0_129;

LBB0_134:
	add.f64 	%fd61, %fd6, 0dC000000000000000;
	div.rn.f64 	%fd62, %fd6, %fd61;
	cvt.f64.f32 	%fd63, %f202;
	mov.f64 	%fd64, 0dBFF0000000000000;
	div.rn.f64 	%fd65, %fd64, %fd63;
	add.f64 	%fd80, %fd62, %fd65;

LBB0_136:
	mov.f32 	%f1284, 0f3FB8AA3B;
	mov.f32 	%f1259, 0f3F000000;
	cvt.rn.f32.f64 	%f1400, %fd80;
	div.rn.f32 	%f1035, %f1400, %f202;
	mul.f32 	%f1394, %f197, %f1035;
	mul.f32 	%f1393, %f196, %f1035;
	mul.f32 	%f1392, %f195, %f1035;
	add.f32 	%f1036, %f203, %f203;
	fma.rn.f32 	%f1039, %f1036, %f994, %f1259;
	cvt.sat.f32.f32 	%f1042, %f1039;
	fma.rm.f32 	%f1044, %f1042, %f997, %f999;
	add.f32 	%f1045, %f1044, 0fCB40007F;
	neg.f32 	%f1046, %f1045;
	fma.rn.f32 	%f1047, %f1036, %f1284, %f1046;
	fma.rn.f32 	%f1049, %f1036, %f1004, %f1047;
	mov.b32 	%r113, %f1044;
	shl.b32 	%r114, %r113, 23;
	mov.b32 	%f1050, %r114;
	ex2.approx.ftz.f32 	%f1051, %f1049;
	mul.f32 	%f1052, %f1051, %f1050;
	cvt.f64.f32 	%fd66, %f1052;
	add.f64 	%fd18, %fd66, 0d3FF0000000000000;
	abs.f64 	%fd67, %fd18;
	setp.gt.f64 	%p138, %fd67, 0d7FE1CCF385EBC8A0;
	@%p138 bra 	LBB0_138;
	bra.uni 	LBB0_137;

LBB0_138:
	setp.gt.f32 	%p139, %f203, 0f00000000;
	selp.f64 	%fd81, 0d3FF0000000000000, 0dBFF0000000000000, %p139;
	bra.uni 	LBB0_139;

LBB0_127:
	add.f64 	%fd45, %fd6, 0dC000000000000000;
	div.rn.f64 	%fd46, %fd6, %fd45;
	cvt.f64.f32 	%fd47, %f202;
	mov.f64 	%fd48, 0dBFF0000000000000;
	div.rn.f64 	%fd49, %fd48, %fd47;
	add.f64 	%fd50, %fd46, %fd49;
	setp.lt.f64 	%p129, %fd50, 0d3F9EB851EB851EB8;
	selp.f64 	%fd78, 0d3F9EB851EB851EB8, %fd50, %p129;

LBB0_129:
	mov.f32 	%f1281, 0f3FB8AA3B;
	mov.f32 	%f1255, 0f3F000000;
	cvt.rn.f32.f64 	%f1400, %fd78;
	div.rn.f32 	%f1010, %f1400, %f202;
	mul.f32 	%f1394, %f197, %f1010;
	mul.f32 	%f1393, %f196, %f1010;
	mul.f32 	%f1392, %f195, %f1010;
	add.f32 	%f1011, %f203, %f203;
	fma.rn.f32 	%f1014, %f1011, %f994, %f1255;
	cvt.sat.f32.f32 	%f1017, %f1014;
	fma.rm.f32 	%f1019, %f1017, %f997, %f999;
	add.f32 	%f1020, %f1019, 0fCB40007F;
	neg.f32 	%f1021, %f1020;
	fma.rn.f32 	%f1022, %f1011, %f1281, %f1021;
	fma.rn.f32 	%f1024, %f1011, %f1004, %f1022;
	mov.b32 	%r111, %f1019;
	shl.b32 	%r112, %r111, 23;
	mov.b32 	%f1025, %r112;
	ex2.approx.ftz.f32 	%f1026, %f1024;
	mul.f32 	%f1027, %f1026, %f1025;
	cvt.f64.f32 	%fd51, %f1027;
	add.f64 	%fd11, %fd51, 0d3FF0000000000000;
	abs.f64 	%fd52, %fd11;
	setp.gt.f64 	%p131, %fd52, 0d7FE1CCF385EBC8A0;
	@%p131 bra 	LBB0_131;
	bra.uni 	LBB0_130;

LBB0_131:
	setp.gt.f32 	%p133, %f203, 0f00000000;
	selp.f64 	%fd79, 0d3FF0000000000000, 0dBFF0000000000000, %p133;
	bra.uni 	LBB0_132;

LBB0_137:
	add.f64 	%fd68, %fd18, 0dC000000000000000;
	div.rn.f64 	%fd69, %fd18, %fd68;
	cvt.f64.f32 	%fd70, %f203;
	mov.f64 	%fd71, 0dBFF0000000000000;
	div.rn.f64 	%fd72, %fd71, %fd70;
	add.f64 	%fd81, %fd69, %fd72;

LBB0_139:
	cvt.rn.f32.f64 	%f1401, %fd81;
	div.rn.f32 	%f1053, %f1401, %f203;
	mul.f32 	%f1397, %f201, %f1053;
	mul.f32 	%f1396, %f200, %f1053;
	mul.f32 	%f1395, %f199, %f1053;
	mul.f32 	%f1054, %f202, %f223;
	mul.f32 	%f1055, %f204, %f1400;
	div.rn.f32 	%f1398, %f1055, %f1054;
	mul.f32 	%f1056, %f205, %f1401;
	mul.f32 	%f1057, %f203, %f241;
	div.rn.f32 	%f1399, %f1056, %f1057;
	bra.uni 	LBB0_140;

LBB0_130:
	add.f64 	%fd53, %fd11, 0dC000000000000000;
	div.rn.f64 	%fd54, %fd11, %fd53;
	cvt.f64.f32 	%fd55, %f203;
	mov.f64 	%fd56, 0dBFF0000000000000;
	div.rn.f64 	%fd57, %fd56, %fd55;
	add.f64 	%fd58, %fd54, %fd57;
	setp.lt.f64 	%p132, %fd58, 0d3F9EB851EB851EB8;
	selp.f64 	%fd79, 0d3F9EB851EB851EB8, %fd58, %p132;

LBB0_132:
	cvt.rn.f32.f64 	%f1401, %fd79;
	div.rn.f32 	%f1028, %f1401, %f203;
	mul.f32 	%f1397, %f201, %f1028;
	mul.f32 	%f1396, %f200, %f1028;
	mul.f32 	%f1395, %f199, %f1028;
	setp.lt.f64 	%p134, %fd4, 0d3F9EB851EB851EB8;
	selp.f64 	%fd59, 0d3F9EB851EB851EB8, %fd4, %p134;
	cvt.rn.f32.f64 	%f1029, %fd59;
	mul.f32 	%f1030, %f202, %f1029;
	mul.f32 	%f1031, %f204, %f1400;
	div.rn.f32 	%f1398, %f1031, %f1030;
	mul.f32 	%f1032, %f205, %f1401;
	setp.lt.f64 	%p135, %fd5, 0d3F9EB851EB851EB8;
	selp.f64 	%fd60, 0d3F9EB851EB851EB8, %fd5, %p135;
	cvt.rn.f32.f64 	%f1033, %fd60;
	mul.f32 	%f1034, %f203, %f1033;
	div.rn.f32 	%f1399, %f1032, %f1034;

LBB0_140:
	mul.f32 	%f1283, %f1347, %f759;
	mul.f32 	%f1282, %f1346, %f759;
	cvt.f64.f32 	%fd77, %f93;
	mov.f32 	%f1257, 0f3F800000;
	sub.f32 	%f1256, %f1257, %f1344;
	div.rn.f32 	%f1058, %f203, %f1401;
	add.f32 	%f1059, %f1058, 0fBF800000;
	div.rn.f32 	%f1060, %f202, %f1400;
	add.f32 	%f1061, %f1060, 0fBF800000;
	mul.f32 	%f1062, %f205, 0f3F000000;
	mul.f32 	%f1063, %f1062, %f1059;
	mul.f32 	%f1064, %f204, 0f3F000000;
	mul.f32 	%f1065, %f1064, %f1061;
	setp.lt.f64 	%p140, %fd4, 0d3F9EB851EB851EB8;
	selp.f64 	%fd73, 0d3F9EB851EB851EB8, %fd4, %p140;
	cvt.rn.f32.f64 	%f1066, %fd73;
	mul.f32 	%f1067, %f1282, %f1066;
	rcp.rn.f32 	%f1068, %f1067;
	div.rn.f32 	%f1070, %f171, %f51;
	mul.f32 	%f1071, %f1, %f1070;
	mul.f32 	%f1072, %f2, %f1070;
	mul.f32 	%f1073, %f3, %f1070;
	sub.f32 	%f1074, %f1, %f1071;
	sub.f32 	%f1075, %f2, %f1072;
	sub.f32 	%f1076, %f3, %f1073;
	mul.f32 	%f1077, %f1074, %f1068;
	mul.f32 	%f1078, %f1075, %f1068;
	mul.f32 	%f1079, %f1076, %f1068;
	setp.lt.f64 	%p141, %fd5, 0d3F9EB851EB851EB8;
	selp.f64 	%fd74, 0d3F9EB851EB851EB8, %fd5, %p141;
	cvt.rn.f32.f64 	%f1080, %fd74;
	mul.f32 	%f1081, %f1283, %f1080;
	rcp.rn.f32 	%f1082, %f1081;
	div.rn.f32 	%f1083, %f172, %f52;
	mul.f32 	%f1084, %f4, %f1083;
	mul.f32 	%f1085, %f5, %f1083;
	mul.f32 	%f1086, %f6, %f1083;
	sub.f32 	%f1087, %f4, %f1084;
	sub.f32 	%f1088, %f5, %f1085;
	sub.f32 	%f1089, %f6, %f1086;
	mul.f32 	%f1090, %f1087, %f1082;
	mul.f32 	%f1091, %f1088, %f1082;
	mul.f32 	%f1092, %f1089, %f1082;
	mul.f32 	%f1094, %f1256, %f1347;
	div.rn.f32 	%f1095, %f1094, %f1344;
	div.rn.f32 	%f1096, %f1095, %f1346;
	fma.rn.f32 	%f1097, %f1096, %f52, %f51;
	mul.f32 	%f1098, %f50, %f1097;
	div.rn.f32 	%f1099, %f1098, %f51;
	div.rn.f32 	%f1100, %f1099, %f52;
	div.rn.f32 	%f1101, %f1346, %f1347;
	mul.f32 	%f1102, %f1101, %f1077;
	mul.f32 	%f1103, %f1101, %f1078;
	mul.f32 	%f1104, %f1101, %f1079;
	sub.f32 	%f1105, %f1102, %f1090;
	sub.f32 	%f1106, %f1103, %f1091;
	sub.f32 	%f1107, %f1104, %f1092;
	mul.f32 	%f272, %f1100, %f1105;
	mul.f32 	%f273, %f1100, %f1106;
	mul.f32 	%f274, %f1100, %f1107;
	sub.f32 	%f1108, %f1382, %f1380;
	div.rn.f32 	%f1109, %f1341, %f1342;
	mul.f32 	%f1110, %f1109, %f1108;
	mul.f32 	%f1111, %f1338, %f1382;
	mul.f32 	%f1112, %f1382, %f1111;
	div.rn.f32 	%f1113, %f1110, %f1112;
	sqrt.rn.f32 	%f1114, %f1113;
	mul.f32 	%f1115, %f1114, 0f00000000;
	sub.f32 	%f1116, %f1383, %f1381;
	div.rn.f32 	%f1117, %f1341, %f1343;
	mul.f32 	%f1118, %f1117, %f1116;
	mul.f32 	%f1119, %f1338, %f1383;
	mul.f32 	%f1120, %f1383, %f1119;
	div.rn.f32 	%f1121, %f1118, %f1120;
	sqrt.rn.f32 	%f1122, %f1121;
	mul.f32 	%f1123, %f1122, 0f00000000;
	mul.f32 	%f1124, %f1109, %f1380;
	div.rn.f32 	%f1125, %f1124, %f1338;
	sqrt.rn.f32 	%f1126, %f1125;
	mul.f32 	%f1127, %f1117, %f1381;
	div.rn.f32 	%f1128, %f1127, %f1338;
	sqrt.rn.f32 	%f1129, %f1128;
	fma.rn.f32 	%f1130, %f54, %f1115, %f1392;
	fma.rn.f32 	%f1131, %f55, %f1115, %f1393;
	fma.rn.f32 	%f1132, %f56, %f1115, %f1394;
	fma.rn.f32 	%f1133, %f60, %f1123, %f1395;
	fma.rn.f32 	%f1134, %f61, %f1123, %f1396;
	fma.rn.f32 	%f1135, %f62, %f1123, %f1397;
	mul.f32 	%f1136, %f3, %f189;
	mul.f32 	%f1137, %f2, %f190;
	sub.f32 	%f275, %f1137, %f1136;
	mul.f32 	%f1138, %f1, %f190;
	mul.f32 	%f1139, %f3, %f188;
	sub.f32 	%f276, %f1139, %f1138;
	mul.f32 	%f1140, %f2, %f188;
	mul.f32 	%f1141, %f1, %f189;
	sub.f32 	%f277, %f1141, %f1140;
	mul.f32 	%f1142, %f6, %f192;
	mul.f32 	%f1143, %f5, %f193;
	sub.f32 	%f278, %f1143, %f1142;
	mul.f32 	%f1144, %f4, %f193;
	mul.f32 	%f1145, %f6, %f191;
	sub.f32 	%f279, %f1145, %f1144;
	mul.f32 	%f1146, %f5, %f191;
	mul.f32 	%f1147, %f4, %f192;
	sub.f32 	%f280, %f1147, %f1146;
	mul.f32 	%f1148, %f2, %f1393;
	fma.rn.f32 	%f1149, %f1, %f1392, %f1148;
	fma.rn.f32 	%f281, %f3, %f1394, %f1149;
	mul.f32 	%f1150, %f5, %f1396;
	fma.rn.f32 	%f1151, %f4, %f1395, %f1150;
	fma.rn.f32 	%f282, %f6, %f1397, %f1151;
	mul.f32 	%f1152, %f2, %f1132;
	mul.f32 	%f1153, %f3, %f1131;
	sub.f32 	%f1154, %f1152, %f1153;
	mul.f32 	%f1155, %f3, %f1130;
	mul.f32 	%f1156, %f1, %f1132;
	sub.f32 	%f1157, %f1155, %f1156;
	mul.f32 	%f1158, %f1, %f1131;
	mul.f32 	%f1159, %f2, %f1130;
	sub.f32 	%f1160, %f1158, %f1159;
	mul.f32 	%f1161, %f5, %f1135;
	mul.f32 	%f1162, %f6, %f1134;
	sub.f32 	%f1163, %f1161, %f1162;
	mul.f32 	%f1164, %f6, %f1133;
	mul.f32 	%f1165, %f4, %f1135;
	sub.f32 	%f1166, %f1164, %f1165;
	mul.f32 	%f1167, %f4, %f1134;
	mul.f32 	%f1168, %f5, %f1133;
	sub.f32 	%f1169, %f1167, %f1168;
	mul.f32 	%f1170, %f2, %f1160;
	mul.f32 	%f1171, %f3, %f1157;
	sub.f32 	%f1172, %f1170, %f1171;
	mul.f32 	%f1173, %f3, %f1154;
	mul.f32 	%f1174, %f1, %f1160;
	sub.f32 	%f1175, %f1173, %f1174;
	mul.f32 	%f1176, %f1, %f1157;
	mul.f32 	%f1177, %f2, %f1154;
	sub.f32 	%f1178, %f1176, %f1177;
	mul.f32 	%f1179, %f5, %f1169;
	mul.f32 	%f1180, %f6, %f1166;
	sub.f32 	%f1181, %f1179, %f1180;
	mul.f32 	%f1182, %f6, %f1163;
	mul.f32 	%f1183, %f4, %f1169;
	sub.f32 	%f1184, %f1182, %f1183;
	mul.f32 	%f1185, %f4, %f1166;
	mul.f32 	%f1186, %f5, %f1163;
	sub.f32 	%f1187, %f1185, %f1186;
	fma.rn.f32 	%f1188, %f1339, %f1339, 0f3F800000;
	rcp.rn.f32 	%f1189, %f1188;
	fma.rn.f32 	%f1190, %f1340, %f1340, 0f3F800000;
	rcp.rn.f32 	%f1191, %f1190;
	div.rn.f64 	%fd75, %fd77, 0d4014000000000000;
	cvt.f64.f32 	%fd76, %f1377;
	setp.lt.f64 	%p142, %fd75, %fd76;
	neg.f32 	%f283, %f1189;
	div.rn.f32 	%f1192, %f1065, %f51;
	div.rn.f32 	%f1193, %f1192, %f51;
	mul.f32 	%f284, %f1193, %f1172;
	mul.f32 	%f285, %f1193, %f1175;
	mul.f32 	%f286, %f1193, %f1178;
	mul.f32 	%f287, %f57, %f1126;
	mul.f32 	%f288, %f58, %f1126;
	mul.f32 	%f289, %f59, %f1126;
	neg.f32 	%f290, %f1191;
	div.rn.f32 	%f1194, %f1063, %f52;
	div.rn.f32 	%f1195, %f1194, %f52;
	mul.f32 	%f291, %f1195, %f1181;
	mul.f32 	%f292, %f1195, %f1184;
	mul.f32 	%f293, %f1195, %f1187;
	mul.f32 	%f294, %f63, %f1129;
	mul.f32 	%f295, %f64, %f1129;
	mul.f32 	%f296, %f65, %f1129;
	@%p142 bra 	LBB0_142;
	bra.uni 	LBB0_141;

LBB0_142:
	mov.f32 	%f1258, 0f3F800000;
	div.rn.f32 	%f1214, %f281, %f51;
	div.rn.f32 	%f1215, %f1214, %f51;
	sub.f32 	%f1217, %f1258, %f1215;
	mul.f32 	%f1218, %f1398, %f1217;
	fma.rn.f32 	%f1219, %f1, %f1218, %f275;
	fma.rn.f32 	%f1220, %f2, %f1218, %f276;
	fma.rn.f32 	%f1221, %f3, %f1218, %f277;
	add.f32 	%f1222, %f1219, %f284;
	add.f32 	%f1223, %f1220, %f285;
	add.f32 	%f1224, %f1221, %f286;
	fma.rn.f32 	%f1225, %f1222, %f283, %f287;
	fma.rn.f32 	%f1226, %f1223, %f283, %f288;
	fma.rn.f32 	%f1227, %f1224, %f283, %f289;
	mul.f32 	%f1228, %f1339, %f272;
	sub.f32 	%f1405, %f1225, %f1228;
	mul.f32 	%f1229, %f1339, %f273;
	sub.f32 	%f1406, %f1226, %f1229;
	mul.f32 	%f1230, %f1339, %f274;
	sub.f32 	%f1407, %f1227, %f1230;
	div.rn.f32 	%f1231, %f282, %f52;
	div.rn.f32 	%f1232, %f1231, %f52;
	sub.f32 	%f1233, %f1258, %f1232;
	mul.f32 	%f1234, %f1399, %f1233;
	fma.rn.f32 	%f1235, %f4, %f1234, %f278;
	fma.rn.f32 	%f1236, %f5, %f1234, %f279;
	fma.rn.f32 	%f1237, %f6, %f1234, %f280;
	add.f32 	%f1238, %f1235, %f291;
	add.f32 	%f1239, %f1236, %f292;
	add.f32 	%f1240, %f1237, %f293;
	fma.rn.f32 	%f1241, %f1238, %f290, %f294;
	fma.rn.f32 	%f1242, %f1239, %f290, %f295;
	fma.rn.f32 	%f1243, %f1240, %f290, %f296;
	fma.rn.f32 	%f1402, %f1340, %f272, %f1241;
	fma.rn.f32 	%f1403, %f1340, %f273, %f1242;
	fma.rn.f32 	%f1404, %f1340, %f274, %f1243;
	bra.uni 	LBB0_144;

LBB0_141:
	sub.f32 	%f1196, %f51, %f171;
	div.rn.f32 	%f1197, %f1196, %f171;
	mul.f32 	%f1198, %f1197, %f1398;
	fma.rn.f32 	%f1199, %f1, %f1198, %f275;
	fma.rn.f32 	%f1200, %f2, %f1198, %f276;
	fma.rn.f32 	%f1201, %f3, %f1198, %f277;
	add.f32 	%f1202, %f1199, %f284;
	add.f32 	%f1203, %f1200, %f285;
	add.f32 	%f1204, %f1201, %f286;
	fma.rn.f32 	%f1405, %f1202, %f283, %f287;
	fma.rn.f32 	%f1406, %f1203, %f283, %f288;
	fma.rn.f32 	%f1407, %f1204, %f283, %f289;
	sub.f32 	%f1205, %f52, %f172;
	div.rn.f32 	%f1206, %f1205, %f172;
	mul.f32 	%f1207, %f1206, %f1399;
	fma.rn.f32 	%f1208, %f4, %f1207, %f278;
	fma.rn.f32 	%f1209, %f5, %f1207, %f279;
	fma.rn.f32 	%f1210, %f6, %f1207, %f280;
	add.f32 	%f1211, %f1208, %f291;
	add.f32 	%f1212, %f1209, %f292;
	add.f32 	%f1213, %f1210, %f293;
	fma.rn.f32 	%f1402, %f1211, %f290, %f294;
	fma.rn.f32 	%f1403, %f1212, %f290, %f295;
	fma.rn.f32 	%f1404, %f1213, %f290, %f296;

LBB0_144:
	ld.param.u64 	%rd160, [LLBtorqueAFMFA_param_8];
	ld.param.u64 	%rd159, [LLBtorqueAFMFA_param_7];
	ld.param.u64 	%rd158, [LLBtorqueAFMFA_param_6];
	ld.param.u64 	%rd157, [LLBtorqueAFMFA_param_2];
	ld.param.u64 	%rd156, [LLBtorqueAFMFA_param_1];
	ld.param.u64 	%rd155, [LLBtorqueAFMFA_param_0];
	mov.u32 	%r128, %ctaid.x;
	mov.u32 	%r127, %nctaid.x;
	mov.u32 	%r126, %ctaid.y;
	mov.u32 	%r125, %tid.x;
	mov.u32 	%r124, %ntid.x;
	mad.lo.s32 	%r123, %r126, %r127, %r128;
	mad.lo.s32 	%r122, %r123, %r124, %r125;
	mul.wide.s32 	%rd154, %r122, 4;
	cvta.to.global.u64 	%rd141, %rd155;
	add.s64 	%rd143, %rd141, %rd154;
	st.global.f32 	[%rd143], %f1405;
	cvta.to.global.u64 	%rd144, %rd156;
	add.s64 	%rd145, %rd144, %rd154;
	st.global.f32 	[%rd145], %f1406;
	cvta.to.global.u64 	%rd146, %rd157;
	add.s64 	%rd147, %rd146, %rd154;
	st.global.f32 	[%rd147], %f1407;
	cvta.to.global.u64 	%rd148, %rd158;
	add.s64 	%rd149, %rd148, %rd154;
	st.global.f32 	[%rd149], %f1402;
	cvta.to.global.u64 	%rd150, %rd159;
	add.s64 	%rd151, %rd150, %rd154;
	st.global.f32 	[%rd151], %f1403;
	cvta.to.global.u64 	%rd152, %rd160;
	add.s64 	%rd153, %rd152, %rd154;
	st.global.f32 	[%rd153], %f1404;

LBB0_145:
	ret;

}

`
)
