package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for LLBtorqueAFPRB054401 kernel
var LLBtorqueAFPRB054401_code cu.Function

// Stores the arguments for LLBtorqueAFPRB054401 kernel invocation
type LLBtorqueAFPRB054401_args_t struct {
	arg_t1x         unsafe.Pointer
	arg_t1y         unsafe.Pointer
	arg_t1z         unsafe.Pointer
	arg_mx1         unsafe.Pointer
	arg_my1         unsafe.Pointer
	arg_mz1         unsafe.Pointer
	arg_t2x         unsafe.Pointer
	arg_t2y         unsafe.Pointer
	arg_t2z         unsafe.Pointer
	arg_mx2         unsafe.Pointer
	arg_my2         unsafe.Pointer
	arg_mz2         unsafe.Pointer
	arg_hx1         unsafe.Pointer
	arg_hy1         unsafe.Pointer
	arg_hz1         unsafe.Pointer
	arg_hx2         unsafe.Pointer
	arg_hy2         unsafe.Pointer
	arg_hz2         unsafe.Pointer
	arg_alpha_      unsafe.Pointer
	arg_alpha_mul   float32
	arg_alpha1_     unsafe.Pointer
	arg_alpha1_mul  float32
	arg_alpha2_     unsafe.Pointer
	arg_alpha2_mul  float32
	arg_TCurie_     unsafe.Pointer
	arg_TCurie_mul  float32
	arg_Msat_       unsafe.Pointer
	arg_Msat_mul    float32
	arg_Msat1_      unsafe.Pointer
	arg_Msat1_mul   float32
	arg_Msat2_      unsafe.Pointer
	arg_Msat2_mul   float32
	arg_hth11x      unsafe.Pointer
	arg_hth11y      unsafe.Pointer
	arg_hth11z      unsafe.Pointer
	arg_hth21x      unsafe.Pointer
	arg_hth21y      unsafe.Pointer
	arg_hth21z      unsafe.Pointer
	arg_hth12x      unsafe.Pointer
	arg_hth12y      unsafe.Pointer
	arg_hth12z      unsafe.Pointer
	arg_hth22x      unsafe.Pointer
	arg_hth22y      unsafe.Pointer
	arg_hth22z      unsafe.Pointer
	arg_temp_       unsafe.Pointer
	arg_temp_mul    float32
	arg_x_          unsafe.Pointer
	arg_x_mul       float32
	arg_nv_         unsafe.Pointer
	arg_nv_mul      float32
	arg_mua_        unsafe.Pointer
	arg_mua_mul     float32
	arg_mub_        unsafe.Pointer
	arg_mub_mul     float32
	arg_J0aa_       unsafe.Pointer
	arg_J0aa_mul    float32
	arg_J0bb_       unsafe.Pointer
	arg_J0bb_mul    float32
	arg_J0ab_       unsafe.Pointer
	arg_J0ab_mul    float32
	arg_lambda0_    unsafe.Pointer
	arg_lambda0_mul float32
	arg_N           int
	argptr          [63]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for LLBtorqueAFPRB054401 kernel invocation
var LLBtorqueAFPRB054401_args LLBtorqueAFPRB054401_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	LLBtorqueAFPRB054401_args.argptr[0] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_t1x)
	LLBtorqueAFPRB054401_args.argptr[1] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_t1y)
	LLBtorqueAFPRB054401_args.argptr[2] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_t1z)
	LLBtorqueAFPRB054401_args.argptr[3] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mx1)
	LLBtorqueAFPRB054401_args.argptr[4] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_my1)
	LLBtorqueAFPRB054401_args.argptr[5] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mz1)
	LLBtorqueAFPRB054401_args.argptr[6] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_t2x)
	LLBtorqueAFPRB054401_args.argptr[7] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_t2y)
	LLBtorqueAFPRB054401_args.argptr[8] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_t2z)
	LLBtorqueAFPRB054401_args.argptr[9] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mx2)
	LLBtorqueAFPRB054401_args.argptr[10] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_my2)
	LLBtorqueAFPRB054401_args.argptr[11] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mz2)
	LLBtorqueAFPRB054401_args.argptr[12] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hx1)
	LLBtorqueAFPRB054401_args.argptr[13] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hy1)
	LLBtorqueAFPRB054401_args.argptr[14] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hz1)
	LLBtorqueAFPRB054401_args.argptr[15] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hx2)
	LLBtorqueAFPRB054401_args.argptr[16] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hy2)
	LLBtorqueAFPRB054401_args.argptr[17] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hz2)
	LLBtorqueAFPRB054401_args.argptr[18] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_alpha_)
	LLBtorqueAFPRB054401_args.argptr[19] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_alpha_mul)
	LLBtorqueAFPRB054401_args.argptr[20] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_alpha1_)
	LLBtorqueAFPRB054401_args.argptr[21] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_alpha1_mul)
	LLBtorqueAFPRB054401_args.argptr[22] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_alpha2_)
	LLBtorqueAFPRB054401_args.argptr[23] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_alpha2_mul)
	LLBtorqueAFPRB054401_args.argptr[24] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_TCurie_)
	LLBtorqueAFPRB054401_args.argptr[25] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_TCurie_mul)
	LLBtorqueAFPRB054401_args.argptr[26] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_Msat_)
	LLBtorqueAFPRB054401_args.argptr[27] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_Msat_mul)
	LLBtorqueAFPRB054401_args.argptr[28] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_Msat1_)
	LLBtorqueAFPRB054401_args.argptr[29] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_Msat1_mul)
	LLBtorqueAFPRB054401_args.argptr[30] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_Msat2_)
	LLBtorqueAFPRB054401_args.argptr[31] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_Msat2_mul)
	LLBtorqueAFPRB054401_args.argptr[32] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth11x)
	LLBtorqueAFPRB054401_args.argptr[33] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth11y)
	LLBtorqueAFPRB054401_args.argptr[34] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth11z)
	LLBtorqueAFPRB054401_args.argptr[35] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth21x)
	LLBtorqueAFPRB054401_args.argptr[36] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth21y)
	LLBtorqueAFPRB054401_args.argptr[37] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth21z)
	LLBtorqueAFPRB054401_args.argptr[38] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth12x)
	LLBtorqueAFPRB054401_args.argptr[39] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth12y)
	LLBtorqueAFPRB054401_args.argptr[40] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth12z)
	LLBtorqueAFPRB054401_args.argptr[41] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth22x)
	LLBtorqueAFPRB054401_args.argptr[42] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth22y)
	LLBtorqueAFPRB054401_args.argptr[43] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_hth22z)
	LLBtorqueAFPRB054401_args.argptr[44] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_temp_)
	LLBtorqueAFPRB054401_args.argptr[45] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_temp_mul)
	LLBtorqueAFPRB054401_args.argptr[46] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_x_)
	LLBtorqueAFPRB054401_args.argptr[47] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_x_mul)
	LLBtorqueAFPRB054401_args.argptr[48] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_nv_)
	LLBtorqueAFPRB054401_args.argptr[49] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_nv_mul)
	LLBtorqueAFPRB054401_args.argptr[50] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mua_)
	LLBtorqueAFPRB054401_args.argptr[51] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mua_mul)
	LLBtorqueAFPRB054401_args.argptr[52] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mub_)
	LLBtorqueAFPRB054401_args.argptr[53] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_mub_mul)
	LLBtorqueAFPRB054401_args.argptr[54] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_J0aa_)
	LLBtorqueAFPRB054401_args.argptr[55] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_J0aa_mul)
	LLBtorqueAFPRB054401_args.argptr[56] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_J0bb_)
	LLBtorqueAFPRB054401_args.argptr[57] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_J0bb_mul)
	LLBtorqueAFPRB054401_args.argptr[58] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_J0ab_)
	LLBtorqueAFPRB054401_args.argptr[59] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_J0ab_mul)
	LLBtorqueAFPRB054401_args.argptr[60] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_lambda0_)
	LLBtorqueAFPRB054401_args.argptr[61] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_lambda0_mul)
	LLBtorqueAFPRB054401_args.argptr[62] = unsafe.Pointer(&LLBtorqueAFPRB054401_args.arg_N)
}

// Wrapper for LLBtorqueAFPRB054401 CUDA kernel, asynchronous.
func k_LLBtorqueAFPRB054401_async(t1x unsafe.Pointer, t1y unsafe.Pointer, t1z unsafe.Pointer, mx1 unsafe.Pointer, my1 unsafe.Pointer, mz1 unsafe.Pointer, t2x unsafe.Pointer, t2y unsafe.Pointer, t2z unsafe.Pointer, mx2 unsafe.Pointer, my2 unsafe.Pointer, mz2 unsafe.Pointer, hx1 unsafe.Pointer, hy1 unsafe.Pointer, hz1 unsafe.Pointer, hx2 unsafe.Pointer, hy2 unsafe.Pointer, hz2 unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, alpha1_ unsafe.Pointer, alpha1_mul float32, alpha2_ unsafe.Pointer, alpha2_mul float32, TCurie_ unsafe.Pointer, TCurie_mul float32, Msat_ unsafe.Pointer, Msat_mul float32, Msat1_ unsafe.Pointer, Msat1_mul float32, Msat2_ unsafe.Pointer, Msat2_mul float32, hth11x unsafe.Pointer, hth11y unsafe.Pointer, hth11z unsafe.Pointer, hth21x unsafe.Pointer, hth21y unsafe.Pointer, hth21z unsafe.Pointer, hth12x unsafe.Pointer, hth12y unsafe.Pointer, hth12z unsafe.Pointer, hth22x unsafe.Pointer, hth22y unsafe.Pointer, hth22z unsafe.Pointer, temp_ unsafe.Pointer, temp_mul float32, x_ unsafe.Pointer, x_mul float32, nv_ unsafe.Pointer, nv_mul float32, mua_ unsafe.Pointer, mua_mul float32, mub_ unsafe.Pointer, mub_mul float32, J0aa_ unsafe.Pointer, J0aa_mul float32, J0bb_ unsafe.Pointer, J0bb_mul float32, J0ab_ unsafe.Pointer, J0ab_mul float32, lambda0_ unsafe.Pointer, lambda0_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("LLBtorqueAFPRB054401")
	}

	LLBtorqueAFPRB054401_args.Lock()
	defer LLBtorqueAFPRB054401_args.Unlock()

	if LLBtorqueAFPRB054401_code == 0 {
		LLBtorqueAFPRB054401_code = fatbinLoad(LLBtorqueAFPRB054401_map, "LLBtorqueAFPRB054401")
	}

	LLBtorqueAFPRB054401_args.arg_t1x = t1x
	LLBtorqueAFPRB054401_args.arg_t1y = t1y
	LLBtorqueAFPRB054401_args.arg_t1z = t1z
	LLBtorqueAFPRB054401_args.arg_mx1 = mx1
	LLBtorqueAFPRB054401_args.arg_my1 = my1
	LLBtorqueAFPRB054401_args.arg_mz1 = mz1
	LLBtorqueAFPRB054401_args.arg_t2x = t2x
	LLBtorqueAFPRB054401_args.arg_t2y = t2y
	LLBtorqueAFPRB054401_args.arg_t2z = t2z
	LLBtorqueAFPRB054401_args.arg_mx2 = mx2
	LLBtorqueAFPRB054401_args.arg_my2 = my2
	LLBtorqueAFPRB054401_args.arg_mz2 = mz2
	LLBtorqueAFPRB054401_args.arg_hx1 = hx1
	LLBtorqueAFPRB054401_args.arg_hy1 = hy1
	LLBtorqueAFPRB054401_args.arg_hz1 = hz1
	LLBtorqueAFPRB054401_args.arg_hx2 = hx2
	LLBtorqueAFPRB054401_args.arg_hy2 = hy2
	LLBtorqueAFPRB054401_args.arg_hz2 = hz2
	LLBtorqueAFPRB054401_args.arg_alpha_ = alpha_
	LLBtorqueAFPRB054401_args.arg_alpha_mul = alpha_mul
	LLBtorqueAFPRB054401_args.arg_alpha1_ = alpha1_
	LLBtorqueAFPRB054401_args.arg_alpha1_mul = alpha1_mul
	LLBtorqueAFPRB054401_args.arg_alpha2_ = alpha2_
	LLBtorqueAFPRB054401_args.arg_alpha2_mul = alpha2_mul
	LLBtorqueAFPRB054401_args.arg_TCurie_ = TCurie_
	LLBtorqueAFPRB054401_args.arg_TCurie_mul = TCurie_mul
	LLBtorqueAFPRB054401_args.arg_Msat_ = Msat_
	LLBtorqueAFPRB054401_args.arg_Msat_mul = Msat_mul
	LLBtorqueAFPRB054401_args.arg_Msat1_ = Msat1_
	LLBtorqueAFPRB054401_args.arg_Msat1_mul = Msat1_mul
	LLBtorqueAFPRB054401_args.arg_Msat2_ = Msat2_
	LLBtorqueAFPRB054401_args.arg_Msat2_mul = Msat2_mul
	LLBtorqueAFPRB054401_args.arg_hth11x = hth11x
	LLBtorqueAFPRB054401_args.arg_hth11y = hth11y
	LLBtorqueAFPRB054401_args.arg_hth11z = hth11z
	LLBtorqueAFPRB054401_args.arg_hth21x = hth21x
	LLBtorqueAFPRB054401_args.arg_hth21y = hth21y
	LLBtorqueAFPRB054401_args.arg_hth21z = hth21z
	LLBtorqueAFPRB054401_args.arg_hth12x = hth12x
	LLBtorqueAFPRB054401_args.arg_hth12y = hth12y
	LLBtorqueAFPRB054401_args.arg_hth12z = hth12z
	LLBtorqueAFPRB054401_args.arg_hth22x = hth22x
	LLBtorqueAFPRB054401_args.arg_hth22y = hth22y
	LLBtorqueAFPRB054401_args.arg_hth22z = hth22z
	LLBtorqueAFPRB054401_args.arg_temp_ = temp_
	LLBtorqueAFPRB054401_args.arg_temp_mul = temp_mul
	LLBtorqueAFPRB054401_args.arg_x_ = x_
	LLBtorqueAFPRB054401_args.arg_x_mul = x_mul
	LLBtorqueAFPRB054401_args.arg_nv_ = nv_
	LLBtorqueAFPRB054401_args.arg_nv_mul = nv_mul
	LLBtorqueAFPRB054401_args.arg_mua_ = mua_
	LLBtorqueAFPRB054401_args.arg_mua_mul = mua_mul
	LLBtorqueAFPRB054401_args.arg_mub_ = mub_
	LLBtorqueAFPRB054401_args.arg_mub_mul = mub_mul
	LLBtorqueAFPRB054401_args.arg_J0aa_ = J0aa_
	LLBtorqueAFPRB054401_args.arg_J0aa_mul = J0aa_mul
	LLBtorqueAFPRB054401_args.arg_J0bb_ = J0bb_
	LLBtorqueAFPRB054401_args.arg_J0bb_mul = J0bb_mul
	LLBtorqueAFPRB054401_args.arg_J0ab_ = J0ab_
	LLBtorqueAFPRB054401_args.arg_J0ab_mul = J0ab_mul
	LLBtorqueAFPRB054401_args.arg_lambda0_ = lambda0_
	LLBtorqueAFPRB054401_args.arg_lambda0_mul = lambda0_mul
	LLBtorqueAFPRB054401_args.arg_N = N

	args := LLBtorqueAFPRB054401_args.argptr[:]
	cu.LaunchKernel(LLBtorqueAFPRB054401_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("LLBtorqueAFPRB054401")
	}
}

// maps compute capability on PTX code for LLBtorqueAFPRB054401 kernel.
var LLBtorqueAFPRB054401_map = map[int]string{0: "",
	70: LLBtorqueAFPRB054401_ptx_70}

// LLBtorqueAFPRB054401 PTX code for various compute capabilities.
const (
	LLBtorqueAFPRB054401_ptx_70 = `
.version 7.1
.target sm_70
.address_size 64

	// .globl	LLBtorqueAFPRB054401

.visible .entry LLBtorqueAFPRB054401(
	.param .u64 LLBtorqueAFPRB054401_param_0,
	.param .u64 LLBtorqueAFPRB054401_param_1,
	.param .u64 LLBtorqueAFPRB054401_param_2,
	.param .u64 LLBtorqueAFPRB054401_param_3,
	.param .u64 LLBtorqueAFPRB054401_param_4,
	.param .u64 LLBtorqueAFPRB054401_param_5,
	.param .u64 LLBtorqueAFPRB054401_param_6,
	.param .u64 LLBtorqueAFPRB054401_param_7,
	.param .u64 LLBtorqueAFPRB054401_param_8,
	.param .u64 LLBtorqueAFPRB054401_param_9,
	.param .u64 LLBtorqueAFPRB054401_param_10,
	.param .u64 LLBtorqueAFPRB054401_param_11,
	.param .u64 LLBtorqueAFPRB054401_param_12,
	.param .u64 LLBtorqueAFPRB054401_param_13,
	.param .u64 LLBtorqueAFPRB054401_param_14,
	.param .u64 LLBtorqueAFPRB054401_param_15,
	.param .u64 LLBtorqueAFPRB054401_param_16,
	.param .u64 LLBtorqueAFPRB054401_param_17,
	.param .u64 LLBtorqueAFPRB054401_param_18,
	.param .f32 LLBtorqueAFPRB054401_param_19,
	.param .u64 LLBtorqueAFPRB054401_param_20,
	.param .f32 LLBtorqueAFPRB054401_param_21,
	.param .u64 LLBtorqueAFPRB054401_param_22,
	.param .f32 LLBtorqueAFPRB054401_param_23,
	.param .u64 LLBtorqueAFPRB054401_param_24,
	.param .f32 LLBtorqueAFPRB054401_param_25,
	.param .u64 LLBtorqueAFPRB054401_param_26,
	.param .f32 LLBtorqueAFPRB054401_param_27,
	.param .u64 LLBtorqueAFPRB054401_param_28,
	.param .f32 LLBtorqueAFPRB054401_param_29,
	.param .u64 LLBtorqueAFPRB054401_param_30,
	.param .f32 LLBtorqueAFPRB054401_param_31,
	.param .u64 LLBtorqueAFPRB054401_param_32,
	.param .u64 LLBtorqueAFPRB054401_param_33,
	.param .u64 LLBtorqueAFPRB054401_param_34,
	.param .u64 LLBtorqueAFPRB054401_param_35,
	.param .u64 LLBtorqueAFPRB054401_param_36,
	.param .u64 LLBtorqueAFPRB054401_param_37,
	.param .u64 LLBtorqueAFPRB054401_param_38,
	.param .u64 LLBtorqueAFPRB054401_param_39,
	.param .u64 LLBtorqueAFPRB054401_param_40,
	.param .u64 LLBtorqueAFPRB054401_param_41,
	.param .u64 LLBtorqueAFPRB054401_param_42,
	.param .u64 LLBtorqueAFPRB054401_param_43,
	.param .u64 LLBtorqueAFPRB054401_param_44,
	.param .f32 LLBtorqueAFPRB054401_param_45,
	.param .u64 LLBtorqueAFPRB054401_param_46,
	.param .f32 LLBtorqueAFPRB054401_param_47,
	.param .u64 LLBtorqueAFPRB054401_param_48,
	.param .f32 LLBtorqueAFPRB054401_param_49,
	.param .u64 LLBtorqueAFPRB054401_param_50,
	.param .f32 LLBtorqueAFPRB054401_param_51,
	.param .u64 LLBtorqueAFPRB054401_param_52,
	.param .f32 LLBtorqueAFPRB054401_param_53,
	.param .u64 LLBtorqueAFPRB054401_param_54,
	.param .f32 LLBtorqueAFPRB054401_param_55,
	.param .u64 LLBtorqueAFPRB054401_param_56,
	.param .f32 LLBtorqueAFPRB054401_param_57,
	.param .u64 LLBtorqueAFPRB054401_param_58,
	.param .f32 LLBtorqueAFPRB054401_param_59,
	.param .u64 LLBtorqueAFPRB054401_param_60,
	.param .f32 LLBtorqueAFPRB054401_param_61,
	.param .u32 LLBtorqueAFPRB054401_param_62
)
{
	.reg .pred 	%p<133>;
	.reg .f32 	%f<1401>;
	.reg .b32 	%r<131>;
	.reg .f64 	%fd<30>;
	.reg .b64 	%rd<190>;


	ld.param.u64 	%rd20, [LLBtorqueAFPRB054401_param_18];
	ld.param.u64 	%rd21, [LLBtorqueAFPRB054401_param_20];
	ld.param.u64 	%rd22, [LLBtorqueAFPRB054401_param_22];
	ld.param.u64 	%rd23, [LLBtorqueAFPRB054401_param_24];
	ld.param.u64 	%rd24, [LLBtorqueAFPRB054401_param_26];
	ld.param.u64 	%rd25, [LLBtorqueAFPRB054401_param_28];
	ld.param.u64 	%rd26, [LLBtorqueAFPRB054401_param_30];
	ld.param.u64 	%rd39, [LLBtorqueAFPRB054401_param_44];
	ld.param.u64 	%rd40, [LLBtorqueAFPRB054401_param_46];
	ld.param.u64 	%rd41, [LLBtorqueAFPRB054401_param_48];
	ld.param.u64 	%rd42, [LLBtorqueAFPRB054401_param_50];
	ld.param.u64 	%rd43, [LLBtorqueAFPRB054401_param_52];
	ld.param.u64 	%rd44, [LLBtorqueAFPRB054401_param_54];
	ld.param.u64 	%rd45, [LLBtorqueAFPRB054401_param_56];
	ld.param.f32 	%f1341, [LLBtorqueAFPRB054401_param_59];
	ld.param.u64 	%rd47, [LLBtorqueAFPRB054401_param_60];
	ld.param.u32 	%r3, [LLBtorqueAFPRB054401_param_62];
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ctaid.x;
	mad.lo.s32 	%r7, %r4, %r5, %r6;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	setp.ge.s32	%p5, %r1, %r3;
	@%p5 bra 	BB0_143;

	ld.param.f32 	%f1327, [LLBtorqueAFPRB054401_param_19];
	ld.param.u64 	%rd176, [LLBtorqueAFPRB054401_param_17];
	ld.param.u64 	%rd175, [LLBtorqueAFPRB054401_param_16];
	ld.param.u64 	%rd174, [LLBtorqueAFPRB054401_param_15];
	ld.param.u64 	%rd173, [LLBtorqueAFPRB054401_param_14];
	ld.param.u64 	%rd172, [LLBtorqueAFPRB054401_param_13];
	ld.param.u64 	%rd171, [LLBtorqueAFPRB054401_param_12];
	ld.param.u64 	%rd170, [LLBtorqueAFPRB054401_param_11];
	ld.param.u64 	%rd169, [LLBtorqueAFPRB054401_param_10];
	ld.param.u64 	%rd168, [LLBtorqueAFPRB054401_param_9];
	ld.param.u64 	%rd167, [LLBtorqueAFPRB054401_param_5];
	ld.param.u64 	%rd166, [LLBtorqueAFPRB054401_param_4];
	ld.param.u64 	%rd165, [LLBtorqueAFPRB054401_param_3];
	cvta.to.global.u64 	%rd48, %rd165;
	mul.wide.s32 	%rd49, %r1, 4;
	add.s64 	%rd50, %rd48, %rd49;
	ld.global.nc.f32 	%f1, [%rd50];
	cvta.to.global.u64 	%rd51, %rd166;
	add.s64 	%rd52, %rd51, %rd49;
	ld.global.nc.f32 	%f2, [%rd52];
	cvta.to.global.u64 	%rd53, %rd167;
	add.s64 	%rd54, %rd53, %rd49;
	ld.global.nc.f32 	%f3, [%rd54];
	cvta.to.global.u64 	%rd55, %rd168;
	add.s64 	%rd56, %rd55, %rd49;
	ld.global.nc.f32 	%f4, [%rd56];
	cvta.to.global.u64 	%rd57, %rd169;
	add.s64 	%rd58, %rd57, %rd49;
	ld.global.nc.f32 	%f5, [%rd58];
	cvta.to.global.u64 	%rd59, %rd170;
	add.s64 	%rd60, %rd59, %rd49;
	ld.global.nc.f32 	%f6, [%rd60];
	cvta.to.global.u64 	%rd61, %rd171;
	add.s64 	%rd62, %rd61, %rd49;
	ld.global.nc.f32 	%f7, [%rd62];
	cvta.to.global.u64 	%rd63, %rd172;
	add.s64 	%rd64, %rd63, %rd49;
	ld.global.nc.f32 	%f8, [%rd64];
	cvta.to.global.u64 	%rd65, %rd173;
	add.s64 	%rd66, %rd65, %rd49;
	ld.global.nc.f32 	%f9, [%rd66];
	cvta.to.global.u64 	%rd67, %rd174;
	add.s64 	%rd68, %rd67, %rd49;
	ld.global.nc.f32 	%f10, [%rd68];
	cvta.to.global.u64 	%rd69, %rd175;
	add.s64 	%rd70, %rd69, %rd49;
	ld.global.nc.f32 	%f11, [%rd70];
	cvta.to.global.u64 	%rd71, %rd176;
	add.s64 	%rd72, %rd71, %rd49;
	ld.global.nc.f32 	%f12, [%rd72];
	setp.eq.s64	%p6, %rd20, 0;
	@%p6 bra 	BB0_3;

	ld.param.f32 	%f1295, [LLBtorqueAFPRB054401_param_19];
	cvta.to.global.u64 	%rd73, %rd20;
	add.s64 	%rd75, %rd73, %rd49;
	ld.global.nc.f32 	%f309, [%rd75];
	mul.f32 	%f1327, %f309, %f1295;

BB0_3:
	ld.param.f32 	%f1328, [LLBtorqueAFPRB054401_param_21];
	setp.eq.s64	%p7, %rd21, 0;
	@%p7 bra 	BB0_5;

	ld.param.f32 	%f1297, [LLBtorqueAFPRB054401_param_21];
	cvta.to.global.u64 	%rd76, %rd21;
	add.s64 	%rd78, %rd76, %rd49;
	ld.global.nc.f32 	%f310, [%rd78];
	mul.f32 	%f1328, %f310, %f1297;

BB0_5:
	ld.param.f32 	%f1329, [LLBtorqueAFPRB054401_param_23];
	setp.eq.s64	%p8, %rd22, 0;
	@%p8 bra 	BB0_7;

	ld.param.f32 	%f1299, [LLBtorqueAFPRB054401_param_23];
	cvta.to.global.u64 	%rd79, %rd22;
	add.s64 	%rd81, %rd79, %rd49;
	ld.global.nc.f32 	%f311, [%rd81];
	mul.f32 	%f1329, %f311, %f1299;

BB0_7:
	ld.param.f32 	%f1330, [LLBtorqueAFPRB054401_param_25];
	setp.eq.s64	%p9, %rd23, 0;
	@%p9 bra 	BB0_9;

	ld.param.f32 	%f1301, [LLBtorqueAFPRB054401_param_25];
	cvta.to.global.u64 	%rd82, %rd23;
	add.s64 	%rd84, %rd82, %rd49;
	ld.global.nc.f32 	%f312, [%rd84];
	mul.f32 	%f1330, %f312, %f1301;

BB0_9:
	ld.param.f32 	%f1331, [LLBtorqueAFPRB054401_param_27];
	setp.eq.s64	%p10, %rd24, 0;
	@%p10 bra 	BB0_11;

	ld.param.f32 	%f1303, [LLBtorqueAFPRB054401_param_27];
	cvta.to.global.u64 	%rd85, %rd24;
	add.s64 	%rd87, %rd85, %rd49;
	ld.global.nc.f32 	%f313, [%rd87];
	mul.f32 	%f1331, %f313, %f1303;

BB0_11:
	ld.param.f32 	%f1332, [LLBtorqueAFPRB054401_param_29];
	setp.eq.s64	%p11, %rd25, 0;
	@%p11 bra 	BB0_13;

	ld.param.f32 	%f1305, [LLBtorqueAFPRB054401_param_29];
	cvta.to.global.u64 	%rd88, %rd25;
	add.s64 	%rd90, %rd88, %rd49;
	ld.global.nc.f32 	%f314, [%rd90];
	mul.f32 	%f1332, %f314, %f1305;

BB0_13:
	ld.param.f32 	%f1333, [LLBtorqueAFPRB054401_param_31];
	setp.eq.s64	%p12, %rd26, 0;
	@%p12 bra 	BB0_15;

	ld.param.f32 	%f1307, [LLBtorqueAFPRB054401_param_31];
	cvta.to.global.u64 	%rd91, %rd26;
	add.s64 	%rd93, %rd91, %rd49;
	ld.global.nc.f32 	%f315, [%rd93];
	mul.f32 	%f1333, %f315, %f1307;

BB0_15:
	ld.param.f32 	%f1334, [LLBtorqueAFPRB054401_param_47];
	setp.eq.s64	%p13, %rd40, 0;
	@%p13 bra 	BB0_17;

	ld.param.f32 	%f1309, [LLBtorqueAFPRB054401_param_47];
	cvta.to.global.u64 	%rd94, %rd40;
	add.s64 	%rd96, %rd94, %rd49;
	ld.global.nc.f32 	%f316, [%rd96];
	mul.f32 	%f1334, %f316, %f1309;

BB0_17:
	ld.param.f32 	%f1335, [LLBtorqueAFPRB054401_param_49];
	setp.eq.s64	%p14, %rd41, 0;
	@%p14 bra 	BB0_19;

	ld.param.f32 	%f1311, [LLBtorqueAFPRB054401_param_49];
	cvta.to.global.u64 	%rd97, %rd41;
	add.s64 	%rd99, %rd97, %rd49;
	ld.global.nc.f32 	%f317, [%rd99];
	mul.f32 	%f1335, %f317, %f1311;

BB0_19:
	ld.param.f32 	%f1336, [LLBtorqueAFPRB054401_param_51];
	setp.eq.s64	%p15, %rd42, 0;
	@%p15 bra 	BB0_21;

	ld.param.f32 	%f1313, [LLBtorqueAFPRB054401_param_51];
	cvta.to.global.u64 	%rd100, %rd42;
	add.s64 	%rd102, %rd100, %rd49;
	ld.global.nc.f32 	%f318, [%rd102];
	mul.f32 	%f1336, %f318, %f1313;

BB0_21:
	ld.param.f32 	%f1337, [LLBtorqueAFPRB054401_param_53];
	setp.eq.s64	%p16, %rd43, 0;
	@%p16 bra 	BB0_23;

	ld.param.f32 	%f1315, [LLBtorqueAFPRB054401_param_53];
	cvta.to.global.u64 	%rd103, %rd43;
	add.s64 	%rd105, %rd103, %rd49;
	ld.global.nc.f32 	%f319, [%rd105];
	mul.f32 	%f1337, %f319, %f1315;

BB0_23:
	ld.param.f32 	%f1338, [LLBtorqueAFPRB054401_param_55];
	setp.eq.s64	%p17, %rd44, 0;
	@%p17 bra 	BB0_25;

	ld.param.f32 	%f1317, [LLBtorqueAFPRB054401_param_55];
	cvta.to.global.u64 	%rd106, %rd44;
	add.s64 	%rd108, %rd106, %rd49;
	ld.global.nc.f32 	%f320, [%rd108];
	mul.f32 	%f1338, %f320, %f1317;

BB0_25:
	ld.param.f32 	%f1339, [LLBtorqueAFPRB054401_param_57];
	mul.f32 	%f321, %f1335, %f1338;
	mul.f32 	%f37, %f1334, %f321;
	setp.eq.s64	%p18, %rd45, 0;
	@%p18 bra 	BB0_27;

	ld.param.f32 	%f1319, [LLBtorqueAFPRB054401_param_57];
	cvta.to.global.u64 	%rd109, %rd45;
	add.s64 	%rd111, %rd109, %rd49;
	ld.global.nc.f32 	%f322, [%rd111];
	mul.f32 	%f1339, %f322, %f1319;

BB0_27:
	ld.param.u64 	%rd177, [LLBtorqueAFPRB054401_param_58];
	mov.f32 	%f323, 0f3F800000;
	sub.f32 	%f40, %f323, %f1334;
	mul.f32 	%f324, %f1335, %f1339;
	mul.f32 	%f41, %f40, %f324;
	cvta.to.global.u64 	%rd112, %rd177;
	add.s64 	%rd1, %rd112, %rd49;
	setp.eq.s64	%p19, %rd177, 0;
	mov.f32 	%f1340, %f1341;
	@%p19 bra 	BB0_29;

	ld.global.nc.f32 	%f325, [%rd1];
	mul.f32 	%f1340, %f325, %f1341;

BB0_29:
	mul.f32 	%f326, %f40, %f1340;
	mul.f32 	%f44, %f1335, %f326;
	@%p19 bra 	BB0_31;

	ld.global.nc.f32 	%f327, [%rd1];
	mul.f32 	%f1341, %f327, %f1341;

BB0_31:
	ld.param.f32 	%f1342, [LLBtorqueAFPRB054401_param_45];
	mul.f32 	%f328, %f1334, %f1341;
	mul.f32 	%f47, %f1335, %f328;
	setp.eq.s64	%p21, %rd39, 0;
	@%p21 bra 	BB0_33;

	ld.param.f32 	%f1321, [LLBtorqueAFPRB054401_param_45];
	cvta.to.global.u64 	%rd114, %rd39;
	add.s64 	%rd116, %rd114, %rd49;
	ld.global.nc.f32 	%f329, [%rd116];
	mul.f32 	%f1342, %f329, %f1321;

BB0_33:
	ld.param.f32 	%f1343, [LLBtorqueAFPRB054401_param_61];
	setp.eq.s64	%p22, %rd47, 0;
	@%p22 bra 	BB0_35;

	ld.param.f32 	%f1323, [LLBtorqueAFPRB054401_param_61];
	cvta.to.global.u64 	%rd117, %rd47;
	add.s64 	%rd119, %rd117, %rd49;
	ld.global.nc.f32 	%f330, [%rd119];
	mul.f32 	%f1343, %f330, %f1323;

BB0_35:
	mul.f32 	%f331, %f1334, %f1343;
	mul.f32 	%f52, %f1335, %f331;
	setp.eq.f32	%p23, %f1342, 0f00000000;
	selp.f32	%f332, 0f38D1B717, %f1342, %p23;
	cvt.f64.f32	%fd4, %f332;
	cvt.f64.f32	%fd1, %f1330;
	add.f64 	%fd5, %fd1, %fd1;
	setp.gt.f64	%p24, %fd4, %fd5;
	add.f32 	%f333, %f1330, %f1330;
	selp.f32	%f1344, %f333, %f332, %p24;
	setp.neu.f32	%p25, %f1344, %f1330;
	@%p25 bra 	BB0_37;

	add.f64 	%fd6, %fd1, 0dBFB999999999999A;
	cvt.rn.f32.f64	%f1344, %fd6;

BB0_37:
	mul.f32 	%f334, %f2, %f2;
	fma.rn.f32 	%f335, %f1, %f1, %f334;
	fma.rn.f32 	%f336, %f3, %f3, %f335;
	sqrt.rn.f32 	%f56, %f336;
	mul.f32 	%f337, %f5, %f5;
	fma.rn.f32 	%f338, %f4, %f4, %f337;
	fma.rn.f32 	%f339, %f6, %f6, %f338;
	sqrt.rn.f32 	%f57, %f339;
	setp.eq.f32	%p26, %f56, 0f00000000;
	setp.eq.f32	%p27, %f57, 0f00000000;
	or.pred  	%p28, %p26, %p27;
	@%p28 bra 	BB0_141;
	bra.uni 	BB0_38;

BB0_141:
	mul.f32 	%f1398, %f1, 0f00000000;
	mul.f32 	%f1399, %f2, 0f00000000;
	mul.f32 	%f1400, %f3, 0f00000000;
	mul.f32 	%f1395, %f4, 0f00000000;
	mul.f32 	%f1396, %f5, 0f00000000;
	mul.f32 	%f1397, %f6, 0f00000000;
	bra.uni 	BB0_142;

BB0_38:
	ld.param.u64 	%rd189, [LLBtorqueAFPRB054401_param_43];
	ld.param.u64 	%rd188, [LLBtorqueAFPRB054401_param_42];
	ld.param.u64 	%rd187, [LLBtorqueAFPRB054401_param_41];
	ld.param.u64 	%rd186, [LLBtorqueAFPRB054401_param_40];
	ld.param.u64 	%rd185, [LLBtorqueAFPRB054401_param_39];
	ld.param.u64 	%rd184, [LLBtorqueAFPRB054401_param_38];
	ld.param.u64 	%rd183, [LLBtorqueAFPRB054401_param_37];
	ld.param.u64 	%rd182, [LLBtorqueAFPRB054401_param_36];
	ld.param.u64 	%rd181, [LLBtorqueAFPRB054401_param_35];
	ld.param.u64 	%rd180, [LLBtorqueAFPRB054401_param_34];
	ld.param.u64 	%rd179, [LLBtorqueAFPRB054401_param_33];
	ld.param.u64 	%rd178, [LLBtorqueAFPRB054401_param_32];
	cvta.to.global.u64 	%rd120, %rd178;
	add.s64 	%rd122, %rd120, %rd49;
	ld.global.nc.f32 	%f58, [%rd122];
	cvta.to.global.u64 	%rd123, %rd179;
	add.s64 	%rd124, %rd123, %rd49;
	ld.global.nc.f32 	%f59, [%rd124];
	cvta.to.global.u64 	%rd125, %rd180;
	add.s64 	%rd126, %rd125, %rd49;
	ld.global.nc.f32 	%f60, [%rd126];
	cvta.to.global.u64 	%rd127, %rd181;
	add.s64 	%rd128, %rd127, %rd49;
	ld.global.nc.f32 	%f61, [%rd128];
	cvta.to.global.u64 	%rd129, %rd182;
	add.s64 	%rd130, %rd129, %rd49;
	ld.global.nc.f32 	%f62, [%rd130];
	cvta.to.global.u64 	%rd131, %rd183;
	add.s64 	%rd132, %rd131, %rd49;
	ld.global.nc.f32 	%f63, [%rd132];
	cvta.to.global.u64 	%rd133, %rd184;
	add.s64 	%rd134, %rd133, %rd49;
	ld.global.nc.f32 	%f64, [%rd134];
	cvta.to.global.u64 	%rd135, %rd185;
	add.s64 	%rd136, %rd135, %rd49;
	ld.global.nc.f32 	%f65, [%rd136];
	cvta.to.global.u64 	%rd137, %rd186;
	add.s64 	%rd138, %rd137, %rd49;
	ld.global.nc.f32 	%f66, [%rd138];
	cvta.to.global.u64 	%rd139, %rd187;
	add.s64 	%rd140, %rd139, %rd49;
	ld.global.nc.f32 	%f67, [%rd140];
	cvta.to.global.u64 	%rd141, %rd188;
	add.s64 	%rd142, %rd141, %rd49;
	ld.global.nc.f32 	%f68, [%rd142];
	cvta.to.global.u64 	%rd143, %rd189;
	add.s64 	%rd144, %rd143, %rd49;
	ld.global.nc.f32 	%f69, [%rd144];
	add.f32 	%f70, %f37, %f41;
	cvt.rzi.f32.f32	%f341, %f323;
	add.f32 	%f342, %f341, %f341;
	mov.f32 	%f343, 0f40000000;
	sub.f32 	%f344, %f343, %f342;
	abs.f32 	%f71, %f344;
	sub.f32 	%f72, %f37, %f41;
	abs.f32 	%f73, %f72;
	setp.lt.f32	%p29, %f73, 0f00800000;
	mul.f32 	%f345, %f73, 0f4B800000;
	selp.f32	%f346, %f345, %f73, %p29;
	selp.f32	%f347, 0fC3170000, 0fC2FE0000, %p29;
	mov.b32 	 %r10, %f346;
	and.b32  	%r11, %r10, 8388607;
	or.b32  	%r12, %r11, 1065353216;
	mov.b32 	 %f348, %r12;
	shr.u32 	%r13, %r10, 23;
	cvt.rn.f32.u32	%f349, %r13;
	add.f32 	%f350, %f347, %f349;
	setp.gt.f32	%p30, %f348, 0f3FB504F3;
	mul.f32 	%f351, %f348, 0f3F000000;
	add.f32 	%f352, %f350, 0f3F800000;
	selp.f32	%f353, %f352, %f350, %p30;
	selp.f32	%f354, %f351, %f348, %p30;
	add.f32 	%f355, %f354, 0fBF800000;
	add.f32 	%f356, %f354, 0f3F800000;
	rcp.approx.ftz.f32 	%f357, %f356;
	add.f32 	%f358, %f355, %f355;
	mul.f32 	%f359, %f357, %f358;
	mul.f32 	%f360, %f359, %f359;
	mov.f32 	%f361, 0f3C4CAF63;
	mov.f32 	%f362, 0f3B18F0FE;
	fma.rn.f32 	%f363, %f362, %f360, %f361;
	mov.f32 	%f364, 0f3DAAAABD;
	fma.rn.f32 	%f365, %f363, %f360, %f364;
	mul.rn.f32 	%f366, %f365, %f360;
	mul.rn.f32 	%f367, %f366, %f359;
	sub.f32 	%f368, %f355, %f359;
	neg.f32 	%f369, %f359;
	add.f32 	%f370, %f368, %f368;
	fma.rn.f32 	%f371, %f369, %f355, %f370;
	mul.rn.f32 	%f372, %f357, %f371;
	add.f32 	%f373, %f367, %f359;
	sub.f32 	%f374, %f359, %f373;
	add.f32 	%f375, %f367, %f374;
	add.f32 	%f376, %f372, %f375;
	add.f32 	%f377, %f373, %f376;
	sub.f32 	%f378, %f373, %f377;
	add.f32 	%f379, %f376, %f378;
	mov.f32 	%f380, 0f3F317200;
	mul.rn.f32 	%f381, %f353, %f380;
	mov.f32 	%f382, 0f35BFBE8E;
	mul.rn.f32 	%f383, %f353, %f382;
	add.f32 	%f384, %f381, %f377;
	sub.f32 	%f385, %f381, %f384;
	add.f32 	%f386, %f377, %f385;
	add.f32 	%f387, %f379, %f386;
	add.f32 	%f388, %f383, %f387;
	add.f32 	%f389, %f384, %f388;
	sub.f32 	%f390, %f384, %f389;
	add.f32 	%f391, %f388, %f390;
	mul.rn.f32 	%f392, %f343, %f389;
	neg.f32 	%f393, %f392;
	fma.rn.f32 	%f394, %f343, %f389, %f393;
	fma.rn.f32 	%f395, %f343, %f391, %f394;
	mov.f32 	%f396, 0f00000000;
	fma.rn.f32 	%f397, %f396, %f389, %f395;
	add.rn.f32 	%f398, %f392, %f397;
	neg.f32 	%f399, %f398;
	add.rn.f32 	%f400, %f392, %f399;
	add.rn.f32 	%f401, %f400, %f397;
	mov.b32 	 %r14, %f398;
	setp.eq.s32	%p31, %r14, 1118925336;
	add.s32 	%r15, %r14, -1;
	mov.b32 	 %f402, %r15;
	add.f32 	%f403, %f401, 0f37000000;
	selp.f32	%f74, %f403, %f401, %p31;
	selp.f32	%f404, %f402, %f398, %p31;
	mov.f32 	%f405, 0f3FB8AA3B;
	mul.rn.f32 	%f406, %f404, %f405;
	cvt.rzi.f32.f32	%f407, %f406;
	abs.f32 	%f408, %f407;
	setp.gt.f32	%p32, %f408, 0f42FC0000;
	mov.b32 	 %r16, %f407;
	and.b32  	%r17, %r16, -2147483648;
	or.b32  	%r18, %r17, 1123811328;
	mov.b32 	 %f409, %r18;
	selp.f32	%f410, %f409, %f407, %p32;
	mov.f32 	%f411, 0fBF317218;
	fma.rn.f32 	%f412, %f410, %f411, %f404;
	mov.f32 	%f413, 0f3102E308;
	fma.rn.f32 	%f414, %f410, %f413, %f412;
	mul.f32 	%f415, %f414, 0f3FB8AA3B;
	add.f32 	%f416, %f410, 0f4B40007F;
	mov.b32 	 %r19, %f416;
	shl.b32 	%r20, %r19, 23;
	mov.b32 	 %f417, %r20;
	ex2.approx.ftz.f32 	%f418, %f415;
	mul.f32 	%f1345, %f418, %f417;
	setp.eq.f32	%p33, %f1345, 0f7F800000;
	@%p33 bra 	BB0_40;

	fma.rn.f32 	%f1345, %f1345, %f74, %f1345;

BB0_40:
	setp.neu.f32	%p34, %f71, 0f3F800000;
	setp.geu.f32	%p35, %f72, 0f00000000;
	or.pred  	%p1, %p35, %p34;
	setp.eq.f32	%p36, %f72, 0f00000000;
	@%p36 bra 	BB0_44;
	bra.uni 	BB0_41;

BB0_44:
	setp.eq.f32	%p39, %f71, 0f3F800000;
	add.f32 	%f423, %f72, %f72;
	selp.f32	%f1347, %f423, 0f00000000, %p39;
	bra.uni 	BB0_45;

BB0_41:
	mov.b32 	 %r21, %f1345;
	xor.b32  	%r22, %r21, -2147483648;
	mov.b32 	 %f419, %r22;
	selp.f32	%f1347, %f1345, %f419, %p1;
	@%p35 bra 	BB0_45;

	cvt.rzi.f32.f32	%f421, %f343;
	setp.eq.f32	%p38, %f421, 0f40000000;
	@%p38 bra 	BB0_45;

	mov.f32 	%f1347, 0f7FFFFFFF;

BB0_45:
	abs.f32 	%f1324, %f72;
	add.f32 	%f424, %f1324, 0f40000000;
	mov.b32 	 %r23, %f424;
	setp.lt.s32	%p40, %r23, 2139095040;
	@%p40 bra 	BB0_50;

	abs.f32 	%f1325, %f72;
	setp.gtu.f32	%p41, %f1325, 0f7F800000;
	@%p41 bra 	BB0_49;
	bra.uni 	BB0_47;

BB0_49:
	add.f32 	%f1347, %f72, 0f40000000;
	bra.uni 	BB0_50;

BB0_47:
	abs.f32 	%f1326, %f72;
	setp.neu.f32	%p42, %f1326, 0f7F800000;
	@%p42 bra 	BB0_50;

	selp.f32	%f1347, 0f7F800000, 0fFF800000, %p1;

BB0_50:
	mov.f32 	%f1258, 0f00000000;
	mov.f32 	%f1257, 0f35BFBE8E;
	mov.f32 	%f1256, 0f3F317200;
	mov.f32 	%f1255, 0f3DAAAABD;
	mov.f32 	%f1254, 0f3C4CAF63;
	mov.f32 	%f1253, 0f3B18F0FE;
	setp.eq.f32	%p43, %f72, 0f3F800000;
	selp.f32	%f425, 0f3F800000, %f1347, %p43;
	mul.f32 	%f426, %f44, 0f40800000;
	fma.rn.f32 	%f84, %f426, %f47, %f425;
	mov.f32 	%f427, 0f3E800000;
	cvt.rzi.f32.f32	%f428, %f427;
	fma.rn.f32 	%f429, %f428, 0fC0000000, 0f3F000000;
	abs.f32 	%f85, %f429;
	abs.f32 	%f86, %f84;
	setp.lt.f32	%p44, %f86, 0f00800000;
	mul.f32 	%f430, %f86, 0f4B800000;
	selp.f32	%f431, %f430, %f86, %p44;
	selp.f32	%f432, 0fC3170000, 0fC2FE0000, %p44;
	mov.b32 	 %r24, %f431;
	and.b32  	%r25, %r24, 8388607;
	or.b32  	%r26, %r25, 1065353216;
	mov.b32 	 %f433, %r26;
	shr.u32 	%r27, %r24, 23;
	cvt.rn.f32.u32	%f434, %r27;
	add.f32 	%f435, %f432, %f434;
	setp.gt.f32	%p45, %f433, 0f3FB504F3;
	mul.f32 	%f436, %f433, 0f3F000000;
	add.f32 	%f437, %f435, 0f3F800000;
	selp.f32	%f438, %f437, %f435, %p45;
	selp.f32	%f439, %f436, %f433, %p45;
	add.f32 	%f440, %f439, 0fBF800000;
	add.f32 	%f441, %f439, 0f3F800000;
	rcp.approx.ftz.f32 	%f442, %f441;
	add.f32 	%f443, %f440, %f440;
	mul.f32 	%f444, %f442, %f443;
	mul.f32 	%f445, %f444, %f444;
	fma.rn.f32 	%f448, %f1253, %f445, %f1254;
	fma.rn.f32 	%f450, %f448, %f445, %f1255;
	mul.rn.f32 	%f451, %f450, %f445;
	mul.rn.f32 	%f452, %f451, %f444;
	sub.f32 	%f453, %f440, %f444;
	neg.f32 	%f454, %f444;
	add.f32 	%f455, %f453, %f453;
	fma.rn.f32 	%f456, %f454, %f440, %f455;
	mul.rn.f32 	%f457, %f442, %f456;
	add.f32 	%f458, %f452, %f444;
	sub.f32 	%f459, %f444, %f458;
	add.f32 	%f460, %f452, %f459;
	add.f32 	%f461, %f457, %f460;
	add.f32 	%f462, %f458, %f461;
	sub.f32 	%f463, %f458, %f462;
	add.f32 	%f464, %f461, %f463;
	mul.rn.f32 	%f466, %f438, %f1256;
	mul.rn.f32 	%f468, %f438, %f1257;
	add.f32 	%f469, %f466, %f462;
	sub.f32 	%f470, %f466, %f469;
	add.f32 	%f471, %f462, %f470;
	add.f32 	%f472, %f464, %f471;
	add.f32 	%f473, %f468, %f472;
	add.f32 	%f474, %f469, %f473;
	sub.f32 	%f475, %f469, %f474;
	add.f32 	%f476, %f473, %f475;
	mov.f32 	%f477, 0f3F000000;
	mul.rn.f32 	%f478, %f477, %f474;
	neg.f32 	%f479, %f478;
	fma.rn.f32 	%f480, %f477, %f474, %f479;
	fma.rn.f32 	%f481, %f477, %f476, %f480;
	fma.rn.f32 	%f483, %f1258, %f474, %f481;
	add.rn.f32 	%f484, %f478, %f483;
	neg.f32 	%f485, %f484;
	add.rn.f32 	%f486, %f478, %f485;
	add.rn.f32 	%f487, %f486, %f483;
	mov.b32 	 %r28, %f484;
	setp.eq.s32	%p46, %r28, 1118925336;
	add.s32 	%r29, %r28, -1;
	mov.b32 	 %f488, %r29;
	add.f32 	%f489, %f487, 0f37000000;
	selp.f32	%f87, %f489, %f487, %p46;
	selp.f32	%f490, %f488, %f484, %p46;
	mul.rn.f32 	%f492, %f490, %f405;
	cvt.rzi.f32.f32	%f493, %f492;
	abs.f32 	%f494, %f493;
	setp.gt.f32	%p47, %f494, 0f42FC0000;
	mov.b32 	 %r30, %f493;
	and.b32  	%r31, %r30, -2147483648;
	or.b32  	%r32, %r31, 1123811328;
	mov.b32 	 %f495, %r32;
	selp.f32	%f496, %f495, %f493, %p47;
	fma.rn.f32 	%f498, %f496, %f411, %f490;
	fma.rn.f32 	%f500, %f496, %f413, %f498;
	mul.f32 	%f501, %f500, 0f3FB8AA3B;
	add.f32 	%f502, %f496, 0f4B40007F;
	mov.b32 	 %r33, %f502;
	shl.b32 	%r34, %r33, 23;
	mov.b32 	 %f503, %r34;
	ex2.approx.ftz.f32 	%f504, %f501;
	mul.f32 	%f1348, %f504, %f503;
	setp.eq.f32	%p48, %f1348, 0f7F800000;
	@%p48 bra 	BB0_52;

	fma.rn.f32 	%f1348, %f1348, %f87, %f1348;

BB0_52:
	setp.neu.f32	%p49, %f85, 0f3F800000;
	setp.geu.f32	%p50, %f84, 0f00000000;
	or.pred  	%p2, %p50, %p49;
	setp.eq.f32	%p51, %f84, 0f00000000;
	@%p51 bra 	BB0_56;
	bra.uni 	BB0_53;

BB0_56:
	setp.eq.f32	%p54, %f85, 0f3F800000;
	add.f32 	%f509, %f84, %f84;
	selp.f32	%f1350, %f509, 0f00000000, %p54;
	bra.uni 	BB0_57;

BB0_53:
	mov.b32 	 %r35, %f1348;
	xor.b32  	%r36, %r35, -2147483648;
	mov.b32 	 %f505, %r36;
	selp.f32	%f1350, %f1348, %f505, %p2;
	@%p50 bra 	BB0_57;

	cvt.rzi.f32.f32	%f507, %f477;
	setp.eq.f32	%p53, %f507, 0f3F000000;
	@%p53 bra 	BB0_57;

	mov.f32 	%f1350, 0f7FFFFFFF;

BB0_57:
	abs.f32 	%f1266, %f84;
	add.f32 	%f510, %f1266, 0f3F000000;
	mov.b32 	 %r37, %f510;
	setp.lt.s32	%p55, %r37, 2139095040;
	@%p55 bra 	BB0_62;

	abs.f32 	%f1267, %f84;
	setp.gtu.f32	%p56, %f1267, 0f7F800000;
	@%p56 bra 	BB0_61;
	bra.uni 	BB0_59;

BB0_61:
	add.f32 	%f1350, %f84, 0f3F000000;
	bra.uni 	BB0_62;

BB0_59:
	abs.f32 	%f1268, %f84;
	setp.neu.f32	%p57, %f1268, 0f7F800000;
	@%p57 bra 	BB0_62;

	selp.f32	%f1350, 0f7F800000, 0fFF800000, %p2;

BB0_62:
	setp.eq.f32	%p58, %f84, 0f3F800000;
	selp.f32	%f511, 0f3F800000, %f1350, %p58;
	add.f32 	%f512, %f70, %f511;
	div.rn.f32 	%f97, %f512, 0f1AC84ACE;
	sub.f32 	%f513, %f1344, %f97;
	abs.f32 	%f514, %f513;
	cvt.f64.f32	%fd7, %f514;
	cvt.f64.f32	%fd2, %f97;
	mul.f64 	%fd8, %fd2, 0d3F7CAC083126E979;
	setp.lt.f64	%p59, %fd7, %fd8;
	setp.lt.f32	%p60, %f1344, %f97;
	and.pred  	%p61, %p59, %p60;
	mul.f32 	%f515, %f97, 0f3F7E353F;
	selp.f32	%f1372, %f515, %f1344, %p61;
	setp.lt.f32	%p62, %f1372, %f97;
	@%p62 bra 	BB0_64;
	bra.uni 	BB0_63;

BB0_64:
	div.rn.f32 	%f101, %f97, 0f41200000;
	setp.lt.f32	%p63, %f1372, %f101;
	selp.f32	%f1352, %f101, %f1372, %p63;
	cvt.f64.f32	%fd9, %f1352;
	mul.f64 	%fd3, %fd2, 0d3FEFD70A3D70A3D7;
	mov.u32 	%r130, 0;
	setp.leu.f64	%p64, %fd9, %fd3;
	@%p64 bra 	BB0_65;

	cvt.rn.f32.f64	%f1351, %fd3;
	mov.u32 	%r130, 1;
	bra.uni 	BB0_67;

BB0_63:
	abs.f32 	%f1371, %f44;
	abs.f32 	%f1370, %f47;
	mov.f32 	%f1373, 0f3C23D70A;
	mov.f32 	%f1374, %f1373;
	bra.uni 	BB0_101;

BB0_65:
	mov.f32 	%f1351, %f1352;
	mov.f32 	%f1352, %f1372;

BB0_67:
	mul.f32 	%f518, %f1351, 0f19858734;
	rcp.rn.f32 	%f519, %f518;
	mul.f32 	%f106, %f37, %f519;
	abs.f32 	%f1371, %f44;
	mul.f32 	%f108, %f519, %f1371;
	abs.f32 	%f1370, %f47;
	mul.f32 	%f110, %f519, %f1370;
	mul.f32 	%f111, %f41, %f519;
	mul.f32 	%f520, %f108, 0f3F666666;
	fma.rn.f32 	%f112, %f106, 0f3F666666, %f520;
	add.f32 	%f521, %f112, %f112;
	mov.f32 	%f523, 0f3BBB989D;
	fma.rn.f32 	%f524, %f521, %f523, %f477;
	cvt.sat.f32.f32	%f525, %f524;
	mov.f32 	%f526, 0f4B400001;
	mov.f32 	%f527, 0f437C0000;
	fma.rm.f32 	%f528, %f525, %f527, %f526;
	add.f32 	%f529, %f528, 0fCB40007F;
	neg.f32 	%f530, %f529;
	fma.rn.f32 	%f532, %f521, %f405, %f530;
	mov.f32 	%f533, 0f32A57060;
	fma.rn.f32 	%f534, %f521, %f533, %f532;
	mov.b32 	 %r40, %f528;
	shl.b32 	%r41, %r40, 23;
	mov.b32 	 %f535, %r41;
	ex2.approx.ftz.f32 	%f536, %f534;
	fma.rn.f32 	%f113, %f536, %f535, 0f3F800000;
	abs.f32 	%f537, %f113;
	cvt.f64.f32	%fd10, %f537;
	setp.gt.f64	%p65, %fd10, 0d6974E718D7D7625A;
	@%p65 bra 	BB0_69;
	bra.uni 	BB0_68;

BB0_69:
	setp.gt.f32	%p66, %f112, 0f00000000;
	selp.f32	%f1353, 0f3F800000, 0fBF800000, %p66;
	bra.uni 	BB0_70;

BB0_68:
	add.f32 	%f538, %f113, 0fC0000000;
	div.rn.f32 	%f539, %f113, %f538;
	mov.f32 	%f540, 0fBF800000;
	div.rn.f32 	%f541, %f540, %f112;
	add.f32 	%f1353, %f539, %f541;

BB0_70:
	mul.f32 	%f542, %f110, 0f3F666666;
	fma.rn.f32 	%f117, %f111, 0f3F666666, %f542;
	add.f32 	%f543, %f117, %f117;
	fma.rn.f32 	%f546, %f543, %f523, %f477;
	cvt.sat.f32.f32	%f547, %f546;
	fma.rm.f32 	%f550, %f547, %f527, %f526;
	add.f32 	%f551, %f550, 0fCB40007F;
	neg.f32 	%f552, %f551;
	fma.rn.f32 	%f554, %f543, %f405, %f552;
	fma.rn.f32 	%f556, %f543, %f533, %f554;
	mov.b32 	 %r42, %f550;
	shl.b32 	%r43, %r42, 23;
	mov.b32 	 %f557, %r43;
	ex2.approx.ftz.f32 	%f558, %f556;
	fma.rn.f32 	%f118, %f558, %f557, 0f3F800000;
	abs.f32 	%f559, %f118;
	cvt.f64.f32	%fd11, %f559;
	setp.gt.f64	%p67, %fd11, 0d6974E718D7D7625A;
	@%p67 bra 	BB0_72;
	bra.uni 	BB0_71;

BB0_72:
	setp.gt.f32	%p68, %f117, 0f00000000;
	selp.f32	%f1354, 0f3F800000, 0fBF800000, %p68;
	bra.uni 	BB0_73;

BB0_71:
	add.f32 	%f560, %f118, 0fC0000000;
	div.rn.f32 	%f561, %f118, %f560;
	mov.f32 	%f562, 0fBF800000;
	div.rn.f32 	%f563, %f562, %f117;
	add.f32 	%f1354, %f561, %f563;

BB0_73:
	add.f32 	%f1358, %f1354, 0fBF666666;
	add.f32 	%f1357, %f1353, 0fBF666666;
	mov.f32 	%f1355, 0f3F666666;
	mov.f32 	%f1356, %f1355;

BB0_74:
	mul.f32 	%f567, %f108, %f1356;
	fma.rn.f32 	%f128, %f106, %f1355, %f567;
	abs.f32 	%f129, %f128;
	cvt.f64.f32	%fd12, %f129;
	setp.lt.f64	%p69, %fd12, 0d39B4484BFEEBC2A0;
	mov.f32 	%f1362, 0f3EAAAAAB;
	mov.f32 	%f1360, %f1362;
	@%p69 bra 	BB0_81;

	setp.ltu.f32	%p70, %f129, 0f3F800000;
	mul.f32 	%f130, %f128, %f128;
	@%p70 bra 	BB0_77;
	bra.uni 	BB0_76;

BB0_77:
	mov.f32 	%f588, 0f394FFF49;
	mov.f32 	%f589, 0f363D0ADA;
	fma.rn.f32 	%f590, %f589, %f130, %f588;
	mov.f32 	%f591, 0f3C08889A;
	fma.rn.f32 	%f592, %f590, %f130, %f591;
	mov.f32 	%f593, 0f3E2AAAAB;
	fma.rn.f32 	%f594, %f592, %f130, %f593;
	mul.f32 	%f595, %f130, %f594;
	fma.rn.f32 	%f1359, %f595, %f128, %f128;
	bra.uni 	BB0_78;

BB0_76:
	mul.rn.f32 	%f569, %f129, %f405;
	cvt.rzi.f32.f32	%f570, %f569;
	abs.f32 	%f571, %f570;
	setp.gt.f32	%p71, %f571, 0f42FC0000;
	mov.b32 	 %r44, %f570;
	and.b32  	%r45, %r44, -2147483648;
	or.b32  	%r46, %r45, 1123811328;
	mov.b32 	 %f572, %r46;
	selp.f32	%f573, %f572, %f570, %p71;
	fma.rn.f32 	%f575, %f573, %f411, %f129;
	fma.rn.f32 	%f577, %f573, %f413, %f575;
	mul.f32 	%f578, %f577, 0f3FB8AA3B;
	add.f32 	%f579, %f573, 0f4B40007D;
	mov.b32 	 %r47, %f579;
	shl.b32 	%r48, %r47, 23;
	mov.b32 	 %f580, %r48;
	ex2.approx.ftz.f32 	%f581, %f578;
	mul.f32 	%f582, %f581, %f580;
	mov.f32 	%f583, 0f3E000000;
	div.approx.f32 	%f584, %f583, %f582;
	neg.f32 	%f585, %f584;
	fma.rn.f32 	%f587, %f343, %f582, %f585;
	mov.b32 	 %r49, %f587;
	setp.ltu.f32	%p72, %f129, 0f42B40000;
	selp.b32	%r50, %r49, 2139095040, %p72;
	mov.b32 	 %r51, %f128;
	and.b32  	%r52, %r51, -2147483648;
	or.b32  	%r53, %r50, %r52;
	mov.b32 	 %f1359, %r53;

BB0_78:
	abs.f32 	%f596, %f1359;
	cvt.f64.f32	%fd13, %f596;
	setp.gt.f64	%p73, %fd13, 0d6974E718D7D7625A;
	@%p73 bra 	BB0_80;
	bra.uni 	BB0_79;

BB0_80:
	rcp.rn.f32 	%f1360, %f130;
	bra.uni 	BB0_81;

BB0_79:
	mul.f32 	%f597, %f1359, %f1359;
	cvt.f64.f32	%fd14, %f597;
	mov.f64 	%fd15, 0dBFF0000000000000;
	div.rn.f64 	%fd16, %fd15, %fd14;
	cvt.f64.f32	%fd17, %f130;
	rcp.rn.f64 	%fd18, %fd17;
	add.f64 	%fd19, %fd16, %fd18;
	cvt.rn.f32.f64	%f1360, %fd19;

BB0_81:
	mul.f32 	%f599, %f111, %f1356;
	fma.rn.f32 	%f137, %f110, %f1355, %f599;
	abs.f32 	%f138, %f137;
	cvt.f64.f32	%fd20, %f138;
	setp.lt.f64	%p74, %fd20, 0d39B4484BFEEBC2A0;
	@%p74 bra 	BB0_88;

	setp.ltu.f32	%p75, %f138, 0f3F800000;
	mul.f32 	%f139, %f137, %f137;
	@%p75 bra 	BB0_84;
	bra.uni 	BB0_83;

BB0_84:
	mov.f32 	%f620, 0f394FFF49;
	mov.f32 	%f621, 0f363D0ADA;
	fma.rn.f32 	%f622, %f621, %f139, %f620;
	mov.f32 	%f623, 0f3C08889A;
	fma.rn.f32 	%f624, %f622, %f139, %f623;
	mov.f32 	%f625, 0f3E2AAAAB;
	fma.rn.f32 	%f626, %f624, %f139, %f625;
	mul.f32 	%f627, %f139, %f626;
	fma.rn.f32 	%f1361, %f627, %f137, %f137;
	bra.uni 	BB0_85;

BB0_83:
	mul.rn.f32 	%f601, %f138, %f405;
	cvt.rzi.f32.f32	%f602, %f601;
	abs.f32 	%f603, %f602;
	setp.gt.f32	%p76, %f603, 0f42FC0000;
	mov.b32 	 %r54, %f602;
	and.b32  	%r55, %r54, -2147483648;
	or.b32  	%r56, %r55, 1123811328;
	mov.b32 	 %f604, %r56;
	selp.f32	%f605, %f604, %f602, %p76;
	fma.rn.f32 	%f607, %f605, %f411, %f138;
	fma.rn.f32 	%f609, %f605, %f413, %f607;
	mul.f32 	%f610, %f609, 0f3FB8AA3B;
	add.f32 	%f611, %f605, 0f4B40007D;
	mov.b32 	 %r57, %f611;
	shl.b32 	%r58, %r57, 23;
	mov.b32 	 %f612, %r58;
	ex2.approx.ftz.f32 	%f613, %f610;
	mul.f32 	%f614, %f613, %f612;
	mov.f32 	%f615, 0f3E000000;
	div.approx.f32 	%f616, %f615, %f614;
	neg.f32 	%f617, %f616;
	fma.rn.f32 	%f619, %f343, %f614, %f617;
	mov.b32 	 %r59, %f619;
	setp.ltu.f32	%p77, %f138, 0f42B40000;
	selp.b32	%r60, %r59, 2139095040, %p77;
	mov.b32 	 %r61, %f137;
	and.b32  	%r62, %r61, -2147483648;
	or.b32  	%r63, %r60, %r62;
	mov.b32 	 %f1361, %r63;

BB0_85:
	abs.f32 	%f628, %f1361;
	cvt.f64.f32	%fd21, %f628;
	setp.gt.f64	%p78, %fd21, 0d6974E718D7D7625A;
	@%p78 bra 	BB0_87;
	bra.uni 	BB0_86;

BB0_87:
	rcp.rn.f32 	%f1362, %f139;
	bra.uni 	BB0_88;

BB0_86:
	mul.f32 	%f629, %f1361, %f1361;
	cvt.f64.f32	%fd22, %f629;
	mov.f64 	%fd23, 0dBFF0000000000000;
	div.rn.f64 	%fd24, %fd23, %fd22;
	cvt.f64.f32	%fd25, %f139;
	rcp.rn.f64 	%fd26, %fd25;
	add.f64 	%fd27, %fd24, %fd26;
	cvt.rn.f32.f64	%f1362, %fd27;

BB0_88:
	fma.rn.f32 	%f146, %f106, %f1360, 0fBF800000;
	fma.rn.f32 	%f147, %f111, %f1362, 0fBF800000;
	mul.f32 	%f630, %f146, %f147;
	mul.f32 	%f148, %f110, %f1362;
	mul.f32 	%f149, %f108, %f1360;
	mul.f32 	%f631, %f149, %f148;
	sub.f32 	%f150, %f630, %f631;
	setp.eq.f32	%p79, %f150, 0f00000000;
	@%p79 bra 	BB0_96;

	rcp.rn.f32 	%f632, %f150;
	mul.f32 	%f633, %f1358, %f149;
	mul.f32 	%f634, %f1357, %f147;
	sub.f32 	%f635, %f634, %f633;
	mul.f32 	%f151, %f635, %f632;
	mul.f32 	%f636, %f1358, %f146;
	mul.f32 	%f637, %f1357, %f148;
	sub.f32 	%f638, %f636, %f637;
	mul.f32 	%f152, %f638, %f632;
	sub.f32 	%f1355, %f1355, %f151;
	sub.f32 	%f1356, %f1356, %f152;
	mul.f32 	%f639, %f108, %f1356;
	fma.rn.f32 	%f155, %f106, %f1355, %f639;
	add.f32 	%f640, %f155, %f155;
	fma.rn.f32 	%f643, %f640, %f523, %f477;
	cvt.sat.f32.f32	%f644, %f643;
	fma.rm.f32 	%f647, %f644, %f527, %f526;
	add.f32 	%f648, %f647, 0fCB40007F;
	neg.f32 	%f649, %f648;
	fma.rn.f32 	%f651, %f640, %f405, %f649;
	fma.rn.f32 	%f653, %f640, %f533, %f651;
	mov.b32 	 %r64, %f647;
	shl.b32 	%r65, %r64, 23;
	mov.b32 	 %f654, %r65;
	ex2.approx.ftz.f32 	%f655, %f653;
	fma.rn.f32 	%f156, %f655, %f654, 0f3F800000;
	abs.f32 	%f656, %f156;
	cvt.f64.f32	%fd28, %f656;
	setp.gt.f64	%p80, %fd28, 0d6974E718D7D7625A;
	@%p80 bra 	BB0_91;
	bra.uni 	BB0_90;

BB0_91:
	setp.gt.f32	%p81, %f155, 0f00000000;
	selp.f32	%f1363, 0f3F800000, 0fBF800000, %p81;
	bra.uni 	BB0_92;

BB0_90:
	add.f32 	%f657, %f156, 0fC0000000;
	div.rn.f32 	%f658, %f156, %f657;
	mov.f32 	%f659, 0fBF800000;
	div.rn.f32 	%f660, %f659, %f155;
	add.f32 	%f1363, %f658, %f660;

BB0_92:
	mul.f32 	%f661, %f111, %f1356;
	fma.rn.f32 	%f160, %f110, %f1355, %f661;
	add.f32 	%f662, %f160, %f160;
	fma.rn.f32 	%f665, %f662, %f523, %f477;
	cvt.sat.f32.f32	%f666, %f665;
	fma.rm.f32 	%f669, %f666, %f527, %f526;
	add.f32 	%f670, %f669, 0fCB40007F;
	neg.f32 	%f671, %f670;
	fma.rn.f32 	%f673, %f662, %f405, %f671;
	fma.rn.f32 	%f675, %f662, %f533, %f673;
	mov.b32 	 %r66, %f669;
	shl.b32 	%r67, %r66, 23;
	mov.b32 	 %f676, %r67;
	ex2.approx.ftz.f32 	%f677, %f675;
	fma.rn.f32 	%f161, %f677, %f676, 0f3F800000;
	abs.f32 	%f678, %f161;
	cvt.f64.f32	%fd29, %f678;
	setp.gt.f64	%p82, %fd29, 0d6974E718D7D7625A;
	@%p82 bra 	BB0_94;
	bra.uni 	BB0_93;

BB0_94:
	setp.gt.f32	%p83, %f160, 0f00000000;
	selp.f32	%f1364, 0f3F800000, 0fBF800000, %p83;
	bra.uni 	BB0_95;

BB0_93:
	add.f32 	%f679, %f161, 0fC0000000;
	div.rn.f32 	%f680, %f161, %f679;
	mov.f32 	%f681, 0fBF800000;
	div.rn.f32 	%f682, %f681, %f160;
	add.f32 	%f1364, %f680, %f682;

BB0_95:
	sub.f32 	%f1358, %f1364, %f1356;
	mul.f32 	%f683, %f151, %f151;
	setp.gt.f32	%p84, %f683, 0f38D1B717;
	mul.f32 	%f684, %f152, %f152;
	setp.gt.f32	%p85, %f684, 0f38D1B717;
	or.pred  	%p86, %p84, %p85;
	sub.f32 	%f1357, %f1363, %f1355;
	@%p86 bra 	BB0_74;

BB0_96:
	setp.gt.f32	%p87, %f1355, 0f38D1B717;
	selp.f32	%f1373, %f1355, 0f3A83126F, %p87;
	setp.gt.f32	%p88, %f1356, 0f38D1B717;
	selp.f32	%f1374, %f1356, 0f3A83126F, %p88;
	setp.geu.f32	%p89, %f1372, %f101;
	@%p89 bra 	BB0_98;

	add.f32 	%f685, %f1373, 0fBF800000;
	div.rn.f32 	%f686, %f685, %f1351;
	fma.rn.f32 	%f1373, %f1352, %f686, 0f3F800000;
	add.f32 	%f687, %f1374, 0fBF800000;
	div.rn.f32 	%f688, %f687, %f1351;
	fma.rn.f32 	%f1374, %f1352, %f688, 0f3F800000;
	mov.f32 	%f1351, %f1352;

BB0_98:
	setp.eq.s32	%p90, %r130, 0;
	@%p90 bra 	BB0_99;

	sub.f32 	%f689, %f97, %f1352;
	mul.f32 	%f690, %f689, %f1373;
	mul.f32 	%f691, %f97, 0f3BA3D70A;
	div.rn.f32 	%f1373, %f690, %f691;
	mul.f32 	%f692, %f689, %f1374;
	div.rn.f32 	%f1374, %f692, %f691;
	mov.f32 	%f1372, %f1352;
	bra.uni 	BB0_101;

BB0_99:
	mov.f32 	%f1372, %f1351;

BB0_101:
	setp.lt.f32	%p91, %f1373, 0f3C23D70A;
	selp.f32	%f183, 0f3C23D70A, %f1373, %p91;
	setp.lt.f32	%p92, %f1374, 0f3C23D70A;
	selp.f32	%f184, 0f3C23D70A, %f1374, %p92;
	mul.f32 	%f693, %f1371, %f184;
	fma.rn.f32 	%f185, %f37, %f183, %f693;
	mul.f32 	%f186, %f1372, 0f19858734;
	div.rn.f32 	%f187, %f185, %f186;
	mul.f32 	%f694, %f41, %f184;
	fma.rn.f32 	%f188, %f1370, %f183, %f694;
	div.rn.f32 	%f189, %f188, %f186;
	div.rn.f32 	%f190, %f1337, %f186;
	div.rn.f32 	%f191, %f1336, %f186;
	div.rn.f32 	%f192, %f41, %f186;
	div.rn.f32 	%f193, %f37, %f186;
	div.rn.f32 	%f194, %f1370, %f186;
	div.rn.f32 	%f195, %f1371, %f186;
	setp.lt.f32	%p93, %f1372, %f97;
	@%p93 bra 	BB0_103;
	bra.uni 	BB0_102;

BB0_103:
	mul.f32 	%f198, %f187, %f187;
	abs.f32 	%f199, %f187;
	setp.ltu.f32	%p94, %f199, 0f3F800000;
	@%p94 bra 	BB0_105;
	bra.uni 	BB0_104;

BB0_105:
	mov.f32 	%f741, 0f394FFF49;
	mov.f32 	%f742, 0f363D0ADA;
	fma.rn.f32 	%f743, %f742, %f198, %f741;
	mov.f32 	%f744, 0f3C08889A;
	fma.rn.f32 	%f745, %f743, %f198, %f744;
	mov.f32 	%f746, 0f3E2AAAAB;
	fma.rn.f32 	%f747, %f745, %f198, %f746;
	mul.f32 	%f748, %f198, %f747;
	fma.rn.f32 	%f1375, %f748, %f187, %f187;
	bra.uni 	BB0_106;

BB0_102:
	mov.f32 	%f1259, 0f3F800000;
	div.rn.f32 	%f695, %f190, 0f40400000;
	mul.f32 	%f696, %f1371, %f695;
	div.rn.f32 	%f697, %f696, %f186;
	div.rn.f32 	%f698, %f697, 0f40400000;
	div.rn.f32 	%f699, %f192, 0f40400000;
	sub.f32 	%f701, %f1259, %f699;
	div.rn.f32 	%f702, %f191, 0f40400000;
	fma.rn.f32 	%f703, %f702, %f701, %f698;
	div.rn.f32 	%f704, %f193, 0f40400000;
	sub.f32 	%f705, %f1259, %f704;
	mul.f32 	%f706, %f701, %f705;
	div.rn.f32 	%f707, %f194, 0f40400000;
	mul.f32 	%f708, %f1371, %f707;
	div.rn.f32 	%f709, %f708, %f186;
	div.rn.f32 	%f710, %f709, 0f40400000;
	sub.f32 	%f711, %f706, %f710;
	div.rn.f32 	%f1383, %f703, %f711;
	mul.f32 	%f712, %f1370, %f702;
	div.rn.f32 	%f713, %f712, %f186;
	div.rn.f32 	%f714, %f713, 0f40400000;
	div.rn.f32 	%f715, %f195, 0f40400000;
	mul.f32 	%f716, %f1370, %f715;
	div.rn.f32 	%f717, %f716, %f186;
	div.rn.f32 	%f718, %f717, 0f40400000;
	fma.rn.f32 	%f719, %f695, %f705, %f714;
	sub.f32 	%f720, %f706, %f718;
	div.rn.f32 	%f1384, %f719, %f720;
	bra.uni 	BB0_134;

BB0_104:
	mul.rn.f32 	%f722, %f199, %f405;
	cvt.rzi.f32.f32	%f723, %f722;
	abs.f32 	%f724, %f723;
	setp.gt.f32	%p95, %f724, 0f42FC0000;
	mov.b32 	 %r68, %f723;
	and.b32  	%r69, %r68, -2147483648;
	or.b32  	%r70, %r69, 1123811328;
	mov.b32 	 %f725, %r70;
	selp.f32	%f726, %f725, %f723, %p95;
	fma.rn.f32 	%f728, %f726, %f411, %f199;
	fma.rn.f32 	%f730, %f726, %f413, %f728;
	mul.f32 	%f731, %f730, 0f3FB8AA3B;
	add.f32 	%f732, %f726, 0f4B40007D;
	mov.b32 	 %r71, %f732;
	shl.b32 	%r72, %r71, 23;
	mov.b32 	 %f733, %r72;
	ex2.approx.ftz.f32 	%f734, %f731;
	mul.f32 	%f735, %f734, %f733;
	mov.f32 	%f736, 0f3E000000;
	div.approx.f32 	%f737, %f736, %f735;
	neg.f32 	%f738, %f737;
	fma.rn.f32 	%f740, %f343, %f735, %f738;
	mov.b32 	 %r73, %f740;
	setp.ltu.f32	%p96, %f199, 0f42B40000;
	selp.b32	%r74, %r73, 2139095040, %p96;
	mov.b32 	 %r75, %f187;
	and.b32  	%r76, %r75, -2147483648;
	or.b32  	%r77, %r74, %r76;
	mov.b32 	 %f1375, %r77;

BB0_106:
	mov.f32 	%f1265, 0f00000000;
	mov.f32 	%f1264, 0f35BFBE8E;
	mov.f32 	%f1263, 0f3F317200;
	mov.f32 	%f1262, 0f3DAAAABD;
	mov.f32 	%f1261, 0f3C4CAF63;
	mov.f32 	%f1260, 0f3B18F0FE;
	rcp.rn.f32 	%f203, %f1375;
	abs.f32 	%f204, %f203;
	setp.lt.f32	%p97, %f204, 0f00800000;
	mul.f32 	%f749, %f204, 0f4B800000;
	selp.f32	%f750, %f749, %f204, %p97;
	selp.f32	%f751, 0fC3170000, 0fC2FE0000, %p97;
	mov.b32 	 %r78, %f750;
	and.b32  	%r79, %r78, 8388607;
	or.b32  	%r80, %r79, 1065353216;
	mov.b32 	 %f752, %r80;
	shr.u32 	%r81, %r78, 23;
	cvt.rn.f32.u32	%f753, %r81;
	add.f32 	%f754, %f751, %f753;
	setp.gt.f32	%p98, %f752, 0f3FB504F3;
	mul.f32 	%f755, %f752, 0f3F000000;
	add.f32 	%f756, %f754, 0f3F800000;
	selp.f32	%f757, %f756, %f754, %p98;
	selp.f32	%f758, %f755, %f752, %p98;
	add.f32 	%f759, %f758, 0fBF800000;
	add.f32 	%f760, %f758, 0f3F800000;
	rcp.approx.ftz.f32 	%f761, %f760;
	add.f32 	%f762, %f759, %f759;
	mul.f32 	%f763, %f761, %f762;
	mul.f32 	%f764, %f763, %f763;
	fma.rn.f32 	%f767, %f1260, %f764, %f1261;
	fma.rn.f32 	%f769, %f767, %f764, %f1262;
	mul.rn.f32 	%f770, %f769, %f764;
	mul.rn.f32 	%f771, %f770, %f763;
	sub.f32 	%f772, %f759, %f763;
	neg.f32 	%f773, %f763;
	add.f32 	%f774, %f772, %f772;
	fma.rn.f32 	%f775, %f773, %f759, %f774;
	mul.rn.f32 	%f776, %f761, %f775;
	add.f32 	%f777, %f771, %f763;
	sub.f32 	%f778, %f763, %f777;
	add.f32 	%f779, %f771, %f778;
	add.f32 	%f780, %f776, %f779;
	add.f32 	%f781, %f777, %f780;
	sub.f32 	%f782, %f777, %f781;
	add.f32 	%f783, %f780, %f782;
	mul.rn.f32 	%f785, %f757, %f1263;
	mul.rn.f32 	%f787, %f757, %f1264;
	add.f32 	%f788, %f785, %f781;
	sub.f32 	%f789, %f785, %f788;
	add.f32 	%f790, %f781, %f789;
	add.f32 	%f791, %f783, %f790;
	add.f32 	%f792, %f787, %f791;
	add.f32 	%f793, %f788, %f792;
	sub.f32 	%f794, %f788, %f793;
	add.f32 	%f795, %f792, %f794;
	mul.rn.f32 	%f797, %f343, %f793;
	neg.f32 	%f798, %f797;
	fma.rn.f32 	%f799, %f343, %f793, %f798;
	fma.rn.f32 	%f800, %f343, %f795, %f799;
	fma.rn.f32 	%f802, %f1265, %f793, %f800;
	add.rn.f32 	%f803, %f797, %f802;
	neg.f32 	%f804, %f803;
	add.rn.f32 	%f805, %f797, %f804;
	add.rn.f32 	%f806, %f805, %f802;
	mov.b32 	 %r82, %f803;
	setp.eq.s32	%p99, %r82, 1118925336;
	add.s32 	%r83, %r82, -1;
	mov.b32 	 %f807, %r83;
	add.f32 	%f808, %f806, 0f37000000;
	selp.f32	%f205, %f808, %f806, %p99;
	selp.f32	%f809, %f807, %f803, %p99;
	mul.rn.f32 	%f811, %f809, %f405;
	cvt.rzi.f32.f32	%f812, %f811;
	abs.f32 	%f813, %f812;
	setp.gt.f32	%p100, %f813, 0f42FC0000;
	mov.b32 	 %r84, %f812;
	and.b32  	%r85, %r84, -2147483648;
	or.b32  	%r86, %r85, 1123811328;
	mov.b32 	 %f814, %r86;
	selp.f32	%f815, %f814, %f812, %p100;
	fma.rn.f32 	%f817, %f815, %f411, %f809;
	fma.rn.f32 	%f819, %f815, %f413, %f817;
	mul.f32 	%f820, %f819, 0f3FB8AA3B;
	add.f32 	%f821, %f815, 0f4B40007F;
	mov.b32 	 %r87, %f821;
	shl.b32 	%r88, %r87, 23;
	mov.b32 	 %f822, %r88;
	ex2.approx.ftz.f32 	%f823, %f820;
	mul.f32 	%f1376, %f823, %f822;
	setp.eq.f32	%p101, %f1376, 0f7F800000;
	@%p101 bra 	BB0_108;

	fma.rn.f32 	%f1376, %f1376, %f205, %f1376;

BB0_108:
	setp.geu.f32	%p103, %f203, 0f00000000;
	or.pred  	%p3, %p103, %p34;
	setp.eq.f32	%p104, %f203, 0f00000000;
	@%p104 bra 	BB0_112;
	bra.uni 	BB0_109;

BB0_112:
	mov.f32 	%f1293, 0f3F800000;
	cvt.rzi.f32.f32	%f1292, %f1293;
	add.f32 	%f1291, %f1292, %f1292;
	mov.f32 	%f1290, 0f40000000;
	sub.f32 	%f1289, %f1290, %f1291;
	abs.f32 	%f1288, %f1289;
	setp.eq.f32	%p107, %f1288, 0f3F800000;
	add.f32 	%f828, %f203, %f203;
	selp.f32	%f1378, %f828, 0f00000000, %p107;
	bra.uni 	BB0_113;

BB0_109:
	mov.b32 	 %r89, %f1376;
	xor.b32  	%r90, %r89, -2147483648;
	mov.b32 	 %f824, %r90;
	selp.f32	%f1378, %f1376, %f824, %p3;
	@%p103 bra 	BB0_113;

	mov.f32 	%f1287, 0f40000000;
	cvt.rzi.f32.f32	%f826, %f1287;
	setp.eq.f32	%p106, %f826, 0f40000000;
	@%p106 bra 	BB0_113;

	mov.f32 	%f1378, 0f7FFFFFFF;

BB0_113:
	abs.f32 	%f1238, %f203;
	add.f32 	%f829, %f1238, 0f40000000;
	mov.b32 	 %r91, %f829;
	setp.lt.s32	%p108, %r91, 2139095040;
	@%p108 bra 	BB0_118;

	abs.f32 	%f1251, %f203;
	setp.gtu.f32	%p109, %f1251, 0f7F800000;
	@%p109 bra 	BB0_117;
	bra.uni 	BB0_115;

BB0_117:
	add.f32 	%f1378, %f203, 0f40000000;
	bra.uni 	BB0_118;

BB0_115:
	abs.f32 	%f1252, %f203;
	setp.neu.f32	%p110, %f1252, 0f7F800000;
	@%p110 bra 	BB0_118;

	selp.f32	%f1378, 0f7F800000, 0fFF800000, %p3;

BB0_118:
	setp.eq.f32	%p111, %f203, 0f3F800000;
	selp.f32	%f830, 0f3F800000, %f1378, %p111;
	rcp.rn.f32 	%f831, %f198;
	sub.f32 	%f215, %f831, %f830;
	mul.f32 	%f216, %f189, %f189;
	abs.f32 	%f217, %f189;
	setp.ltu.f32	%p112, %f217, 0f3F800000;
	@%p112 bra 	BB0_120;
	bra.uni 	BB0_119;

BB0_120:
	mov.f32 	%f852, 0f394FFF49;
	mov.f32 	%f853, 0f363D0ADA;
	fma.rn.f32 	%f854, %f853, %f216, %f852;
	mov.f32 	%f855, 0f3C08889A;
	fma.rn.f32 	%f856, %f854, %f216, %f855;
	mov.f32 	%f857, 0f3E2AAAAB;
	fma.rn.f32 	%f858, %f856, %f216, %f857;
	mul.f32 	%f859, %f216, %f858;
	fma.rn.f32 	%f1379, %f859, %f189, %f189;
	bra.uni 	BB0_121;

BB0_119:
	mov.f32 	%f1283, 0fBF317218;
	mov.f32 	%f1282, 0f3FB8AA3B;
	mov.f32 	%f1281, 0f40000000;
	mov.f32 	%f1239, 0f3102E308;
	mul.rn.f32 	%f833, %f217, %f1282;
	cvt.rzi.f32.f32	%f834, %f833;
	abs.f32 	%f835, %f834;
	setp.gt.f32	%p113, %f835, 0f42FC0000;
	mov.b32 	 %r92, %f834;
	and.b32  	%r93, %r92, -2147483648;
	or.b32  	%r94, %r93, 1123811328;
	mov.b32 	 %f836, %r94;
	selp.f32	%f837, %f836, %f834, %p113;
	fma.rn.f32 	%f839, %f837, %f1283, %f217;
	fma.rn.f32 	%f841, %f837, %f1239, %f839;
	mul.f32 	%f842, %f841, 0f3FB8AA3B;
	add.f32 	%f843, %f837, 0f4B40007D;
	mov.b32 	 %r95, %f843;
	shl.b32 	%r96, %r95, 23;
	mov.b32 	 %f844, %r96;
	ex2.approx.ftz.f32 	%f845, %f842;
	mul.f32 	%f846, %f845, %f844;
	mov.f32 	%f847, 0f3E000000;
	div.approx.f32 	%f848, %f847, %f846;
	neg.f32 	%f849, %f848;
	fma.rn.f32 	%f851, %f1281, %f846, %f849;
	mov.b32 	 %r97, %f851;
	setp.ltu.f32	%p114, %f217, 0f42B40000;
	selp.b32	%r98, %r97, 2139095040, %p114;
	mov.b32 	 %r99, %f189;
	and.b32  	%r100, %r99, -2147483648;
	or.b32  	%r101, %r98, %r100;
	mov.b32 	 %f1379, %r101;

BB0_121:
	mov.f32 	%f1286, 0fBF317218;
	mov.f32 	%f1285, 0f3FB8AA3B;
	mov.f32 	%f1284, 0f40000000;
	mov.f32 	%f1246, 0f3102E308;
	mov.f32 	%f1245, 0f00000000;
	mov.f32 	%f1244, 0f35BFBE8E;
	mov.f32 	%f1243, 0f3F317200;
	mov.f32 	%f1242, 0f3DAAAABD;
	mov.f32 	%f1241, 0f3C4CAF63;
	mov.f32 	%f1240, 0f3B18F0FE;
	rcp.rn.f32 	%f221, %f1379;
	abs.f32 	%f222, %f221;
	setp.lt.f32	%p115, %f222, 0f00800000;
	mul.f32 	%f860, %f222, 0f4B800000;
	selp.f32	%f861, %f860, %f222, %p115;
	selp.f32	%f862, 0fC3170000, 0fC2FE0000, %p115;
	mov.b32 	 %r102, %f861;
	and.b32  	%r103, %r102, 8388607;
	or.b32  	%r104, %r103, 1065353216;
	mov.b32 	 %f863, %r104;
	shr.u32 	%r105, %r102, 23;
	cvt.rn.f32.u32	%f864, %r105;
	add.f32 	%f865, %f862, %f864;
	setp.gt.f32	%p116, %f863, 0f3FB504F3;
	mul.f32 	%f866, %f863, 0f3F000000;
	add.f32 	%f867, %f865, 0f3F800000;
	selp.f32	%f868, %f867, %f865, %p116;
	selp.f32	%f869, %f866, %f863, %p116;
	add.f32 	%f870, %f869, 0fBF800000;
	add.f32 	%f871, %f869, 0f3F800000;
	rcp.approx.ftz.f32 	%f872, %f871;
	add.f32 	%f873, %f870, %f870;
	mul.f32 	%f874, %f872, %f873;
	mul.f32 	%f875, %f874, %f874;
	fma.rn.f32 	%f878, %f1240, %f875, %f1241;
	fma.rn.f32 	%f880, %f878, %f875, %f1242;
	mul.rn.f32 	%f881, %f880, %f875;
	mul.rn.f32 	%f882, %f881, %f874;
	sub.f32 	%f883, %f870, %f874;
	neg.f32 	%f884, %f874;
	add.f32 	%f885, %f883, %f883;
	fma.rn.f32 	%f886, %f884, %f870, %f885;
	mul.rn.f32 	%f887, %f872, %f886;
	add.f32 	%f888, %f882, %f874;
	sub.f32 	%f889, %f874, %f888;
	add.f32 	%f890, %f882, %f889;
	add.f32 	%f891, %f887, %f890;
	add.f32 	%f892, %f888, %f891;
	sub.f32 	%f893, %f888, %f892;
	add.f32 	%f894, %f891, %f893;
	mul.rn.f32 	%f896, %f868, %f1243;
	mul.rn.f32 	%f898, %f868, %f1244;
	add.f32 	%f899, %f896, %f892;
	sub.f32 	%f900, %f896, %f899;
	add.f32 	%f901, %f892, %f900;
	add.f32 	%f902, %f894, %f901;
	add.f32 	%f903, %f898, %f902;
	add.f32 	%f904, %f899, %f903;
	sub.f32 	%f905, %f899, %f904;
	add.f32 	%f906, %f903, %f905;
	mul.rn.f32 	%f908, %f1284, %f904;
	neg.f32 	%f909, %f908;
	fma.rn.f32 	%f910, %f1284, %f904, %f909;
	fma.rn.f32 	%f911, %f1284, %f906, %f910;
	fma.rn.f32 	%f913, %f1245, %f904, %f911;
	add.rn.f32 	%f914, %f908, %f913;
	neg.f32 	%f915, %f914;
	add.rn.f32 	%f916, %f908, %f915;
	add.rn.f32 	%f917, %f916, %f913;
	mov.b32 	 %r106, %f914;
	setp.eq.s32	%p117, %r106, 1118925336;
	add.s32 	%r107, %r106, -1;
	mov.b32 	 %f918, %r107;
	add.f32 	%f919, %f917, 0f37000000;
	selp.f32	%f223, %f919, %f917, %p117;
	selp.f32	%f920, %f918, %f914, %p117;
	mul.rn.f32 	%f922, %f920, %f1285;
	cvt.rzi.f32.f32	%f923, %f922;
	abs.f32 	%f924, %f923;
	setp.gt.f32	%p118, %f924, 0f42FC0000;
	mov.b32 	 %r108, %f923;
	and.b32  	%r109, %r108, -2147483648;
	or.b32  	%r110, %r109, 1123811328;
	mov.b32 	 %f925, %r110;
	selp.f32	%f926, %f925, %f923, %p118;
	fma.rn.f32 	%f928, %f926, %f1286, %f920;
	fma.rn.f32 	%f930, %f926, %f1246, %f928;
	mul.f32 	%f931, %f930, 0f3FB8AA3B;
	add.f32 	%f932, %f926, 0f4B40007F;
	mov.b32 	 %r111, %f932;
	shl.b32 	%r112, %r111, 23;
	mov.b32 	 %f933, %r112;
	ex2.approx.ftz.f32 	%f934, %f931;
	mul.f32 	%f1380, %f934, %f933;
	setp.eq.f32	%p119, %f1380, 0f7F800000;
	@%p119 bra 	BB0_123;

	fma.rn.f32 	%f1380, %f1380, %f223, %f1380;

BB0_123:
	setp.geu.f32	%p121, %f221, 0f00000000;
	or.pred  	%p4, %p121, %p34;
	setp.eq.f32	%p122, %f221, 0f00000000;
	@%p122 bra 	BB0_127;
	bra.uni 	BB0_124;

BB0_127:
	mov.f32 	%f1280, 0f3F800000;
	cvt.rzi.f32.f32	%f1279, %f1280;
	add.f32 	%f1278, %f1279, %f1279;
	mov.f32 	%f1277, 0f40000000;
	sub.f32 	%f1276, %f1277, %f1278;
	abs.f32 	%f1275, %f1276;
	setp.eq.f32	%p125, %f1275, 0f3F800000;
	add.f32 	%f939, %f221, %f221;
	selp.f32	%f1382, %f939, 0f00000000, %p125;
	bra.uni 	BB0_128;

BB0_124:
	mov.b32 	 %r113, %f1380;
	xor.b32  	%r114, %r113, -2147483648;
	mov.b32 	 %f935, %r114;
	selp.f32	%f1382, %f1380, %f935, %p4;
	@%p121 bra 	BB0_128;

	mov.f32 	%f1274, 0f40000000;
	cvt.rzi.f32.f32	%f937, %f1274;
	setp.eq.f32	%p124, %f937, 0f40000000;
	@%p124 bra 	BB0_128;

	mov.f32 	%f1382, 0f7FFFFFFF;

BB0_128:
	abs.f32 	%f1269, %f221;
	add.f32 	%f940, %f1269, 0f40000000;
	mov.b32 	 %r115, %f940;
	setp.lt.s32	%p126, %r115, 2139095040;
	@%p126 bra 	BB0_133;

	abs.f32 	%f1272, %f221;
	setp.gtu.f32	%p127, %f1272, 0f7F800000;
	@%p127 bra 	BB0_132;
	bra.uni 	BB0_130;

BB0_132:
	add.f32 	%f1382, %f221, 0f40000000;
	bra.uni 	BB0_133;

BB0_130:
	abs.f32 	%f1273, %f221;
	setp.neu.f32	%p128, %f1273, 0f7F800000;
	@%p128 bra 	BB0_133;

	selp.f32	%f1382, 0f7F800000, 0fFF800000, %p4;

BB0_133:
	mul.f32 	%f1270, %f1372, 0f19858734;
	mov.f32 	%f1247, 0f3F800000;
	setp.eq.f32	%p129, %f221, 0f3F800000;
	selp.f32	%f941, 0f3F800000, %f1382, %p129;
	rcp.rn.f32 	%f942, %f216;
	sub.f32 	%f943, %f942, %f941;
	mul.f32 	%f944, %f190, %f215;
	mul.f32 	%f945, %f1371, %f944;
	div.rn.f32 	%f946, %f945, %f1270;
	mul.f32 	%f947, %f192, %f943;
	sub.f32 	%f949, %f1247, %f947;
	mul.f32 	%f950, %f191, %f215;
	mul.f32 	%f951, %f950, %f949;
	fma.rn.f32 	%f952, %f946, %f943, %f951;
	mul.f32 	%f953, %f193, %f215;
	sub.f32 	%f954, %f1247, %f953;
	mul.f32 	%f955, %f954, %f949;
	mul.f32 	%f956, %f194, %f215;
	mul.f32 	%f957, %f1371, %f956;
	div.rn.f32 	%f958, %f957, %f1270;
	mul.f32 	%f959, %f958, %f943;
	sub.f32 	%f960, %f955, %f959;
	div.rn.f32 	%f1383, %f952, %f960;
	mul.f32 	%f961, %f191, %f943;
	mul.f32 	%f962, %f1370, %f961;
	div.rn.f32 	%f963, %f962, %f1270;
	mul.f32 	%f964, %f190, %f943;
	mul.f32 	%f965, %f195, %f943;
	mul.f32 	%f966, %f1370, %f965;
	div.rn.f32 	%f967, %f966, %f1270;
	mul.f32 	%f968, %f215, %f967;
	mul.f32 	%f969, %f954, %f964;
	fma.rn.f32 	%f970, %f215, %f963, %f969;
	sub.f32 	%f971, %f955, %f968;
	div.rn.f32 	%f1384, %f970, %f971;

BB0_134:
	mul.f32 	%f972, %f2, %f5;
	fma.rn.f32 	%f973, %f1, %f4, %f972;
	fma.rn.f32 	%f974, %f3, %f6, %f973;
	abs.f32 	%f975, %f974;
	div.rn.f32 	%f1389, %f975, %f57;
	div.rn.f32 	%f238, %f975, %f56;
	div.rn.f32 	%f239, %f1371, %f1336;
	mul.f32 	%f976, %f1384, %f239;
	div.rn.f32 	%f977, %f976, %f1383;
	rcp.rn.f32 	%f978, %f1383;
	add.f32 	%f240, %f978, %f977;
	div.rn.f32 	%f241, %f1370, %f1337;
	mul.f32 	%f979, %f1383, %f241;
	div.rn.f32 	%f980, %f979, %f1384;
	rcp.rn.f32 	%f981, %f1384;
	add.f32 	%f1390, %f981, %f980;
	setp.gt.f32	%p130, %f1372, %f97;
	@%p130 bra 	BB0_136;
	bra.uni 	BB0_135;

BB0_136:
	mul.f32 	%f1000, %f1, %f240;
	mul.f32 	%f1001, %f2, %f240;
	mul.f32 	%f1002, %f3, %f240;
	mul.f32 	%f1003, %f238, %f239;
	div.rn.f32 	%f1004, %f1003, %f56;
	mul.f32 	%f1005, %f1, %f1004;
	mul.f32 	%f1006, %f2, %f1004;
	mul.f32 	%f1007, %f3, %f1004;
	sub.f32 	%f1385, %f1005, %f1000;
	sub.f32 	%f1386, %f1006, %f1001;
	sub.f32 	%f1387, %f1007, %f1002;
	mov.f32 	%f1388, %f57;
	bra.uni 	BB0_137;

BB0_135:
	sub.f32 	%f982, %f56, %f183;
	div.rn.f32 	%f983, %f982, %f183;
	mul.f32 	%f984, %f240, %f983;
	mul.f32 	%f985, %f1, %f984;
	mul.f32 	%f986, %f2, %f984;
	mul.f32 	%f987, %f3, %f984;
	mul.f32 	%f988, %f184, %f238;
	div.rn.f32 	%f989, %f988, %f57;
	sub.f32 	%f990, %f238, %f989;
	mul.f32 	%f991, %f990, %f239;
	div.rn.f32 	%f992, %f991, %f183;
	mul.f32 	%f993, %f1, %f992;
	mul.f32 	%f994, %f2, %f992;
	mul.f32 	%f995, %f3, %f992;
	sub.f32 	%f1385, %f993, %f985;
	sub.f32 	%f1386, %f994, %f986;
	sub.f32 	%f1387, %f995, %f987;
	sub.f32 	%f996, %f57, %f184;
	div.rn.f32 	%f997, %f996, %f184;
	mul.f32 	%f1390, %f1390, %f997;
	mul.f32 	%f998, %f183, %f1389;
	div.rn.f32 	%f999, %f998, %f56;
	sub.f32 	%f1389, %f1389, %f999;
	mov.f32 	%f1388, %f184;

BB0_137:
	setp.lt.f32	%p132, %f1372, %f97;
	mov.f32 	%f1249, 0f3F800000;
	sub.f32 	%f1248, %f1249, %f1334;
	neg.f32 	%f1008, %f44;
	mul.f32 	%f1009, %f1336, %f56;
	mul.f32 	%f1010, %f56, %f1009;
	div.rn.f32 	%f257, %f1008, %f1010;
	mul.f32 	%f1011, %f4, %f1390;
	mul.f32 	%f1012, %f5, %f1390;
	mul.f32 	%f1013, %f6, %f1390;
	mul.f32 	%f1014, %f241, %f1389;
	div.rn.f32 	%f1015, %f1014, %f1388;
	mul.f32 	%f1016, %f4, %f1015;
	mul.f32 	%f1017, %f5, %f1015;
	mul.f32 	%f1018, %f6, %f1015;
	sub.f32 	%f258, %f1016, %f1011;
	sub.f32 	%f259, %f1017, %f1012;
	sub.f32 	%f260, %f1018, %f1013;
	mul.f32 	%f1021, %f1248, %f1337;
	div.rn.f32 	%f1022, %f1021, %f1334;
	div.rn.f32 	%f1023, %f1022, %f1336;
	fma.rn.f32 	%f261, %f57, %f1023, %f56;
	div.rn.f32 	%f262, %f1336, %f1337;
	add.f32 	%f263, %f1328, %f1328;
	add.f32 	%f264, %f1329, %f1329;
	@%p132 bra 	BB0_139;
	bra.uni 	BB0_138;

BB0_139:
	mul.f32 	%f1271, %f1372, 0f19858734;
	mov.f32 	%f1250, 0f3F800000;
	mul.f32 	%f1027, %f263, 0f19858734;
	mul.f32 	%f1028, %f1027, %f1372;
	mul.f32 	%f1029, %f1028, %f183;
	div.rn.f32 	%f1391, %f1029, %f185;
	mul.f32 	%f1030, %f264, 0f19858734;
	mul.f32 	%f1031, %f1030, %f1372;
	mul.f32 	%f1032, %f1031, %f184;
	div.rn.f32 	%f1392, %f1032, %f188;
	mul.f32 	%f1033, %f1271, %f183;
	div.rn.f32 	%f1034, %f1033, %f185;
	sub.f32 	%f1036, %f1250, %f1034;
	mul.f32 	%f1393, %f1328, %f1036;
	mul.f32 	%f1037, %f1271, %f184;
	div.rn.f32 	%f1038, %f1037, %f188;
	sub.f32 	%f1039, %f1250, %f1038;
	mul.f32 	%f1394, %f1329, %f1039;
	bra.uni 	BB0_140;

BB0_138:
	mul.f32 	%f1024, %f263, %f1372;
	mul.f32 	%f1025, %f97, 0f40400000;
	div.rn.f32 	%f1391, %f1024, %f1025;
	mul.f32 	%f1026, %f264, %f1372;
	div.rn.f32 	%f1392, %f1026, %f1025;
	mov.f32 	%f1393, %f1391;
	mov.f32 	%f1394, %f1392;

BB0_140:
	mul.f32 	%f1040, %f3, %f5;
	mul.f32 	%f1041, %f2, %f6;
	sub.f32 	%f1042, %f1041, %f1040;
	mul.f32 	%f1043, %f1, %f6;
	mul.f32 	%f1044, %f3, %f4;
	sub.f32 	%f1045, %f1044, %f1043;
	mul.f32 	%f1046, %f2, %f4;
	mul.f32 	%f1047, %f1, %f5;
	sub.f32 	%f1048, %f1047, %f1046;
	mul.f32 	%f1049, %f1337, %f57;
	mul.f32 	%f1050, %f57, %f1049;
	neg.f32 	%f1051, %f47;
	div.rn.f32 	%f1052, %f1051, %f1050;
	sub.f32 	%f1053, %f1040, %f1041;
	sub.f32 	%f1054, %f1043, %f1044;
	sub.f32 	%f1055, %f1046, %f1047;
	mul.f32 	%f1056, %f52, %f261;
	div.rn.f32 	%f1057, %f1056, %f56;
	div.rn.f32 	%f1058, %f1057, %f57;
	mul.f32 	%f1059, %f1385, %f262;
	sub.f32 	%f1060, %f1059, %f258;
	mul.f32 	%f1061, %f1058, %f1060;
	mul.f32 	%f1062, %f1386, %f262;
	sub.f32 	%f1063, %f1062, %f259;
	mul.f32 	%f1064, %f1058, %f1063;
	mul.f32 	%f1065, %f1387, %f262;
	sub.f32 	%f1066, %f1065, %f260;
	mul.f32 	%f1067, %f1058, %f1066;
	sub.f32 	%f1068, %f1393, %f1391;
	div.rn.f32 	%f1069, %f1331, %f1332;
	mul.f32 	%f1070, %f1068, %f1069;
	mul.f32 	%f1071, %f1327, %f1393;
	mul.f32 	%f1072, %f1393, %f1071;
	div.rn.f32 	%f1073, %f1070, %f1072;
	sqrt.rn.f32 	%f1074, %f1073;
	sub.f32 	%f1075, %f1394, %f1392;
	div.rn.f32 	%f1076, %f1331, %f1333;
	mul.f32 	%f1077, %f1075, %f1076;
	mul.f32 	%f1078, %f1327, %f1394;
	mul.f32 	%f1079, %f1394, %f1078;
	div.rn.f32 	%f1080, %f1077, %f1079;
	sqrt.rn.f32 	%f1081, %f1080;
	mul.f32 	%f1082, %f1391, %f1069;
	div.rn.f32 	%f1083, %f1082, %f1327;
	sqrt.rn.f32 	%f1084, %f1083;
	mul.f32 	%f1085, %f1392, %f1076;
	div.rn.f32 	%f1086, %f1085, %f1327;
	sqrt.rn.f32 	%f1087, %f1086;
	add.f32 	%f1088, %f7, %f1385;
	mul.f32 	%f1089, %f2, %f1048;
	mul.f32 	%f1090, %f3, %f1045;
	sub.f32 	%f1091, %f1089, %f1090;
	fma.rn.f32 	%f1092, %f1091, %f257, %f1088;
	add.f32 	%f1093, %f8, %f1386;
	mul.f32 	%f1094, %f3, %f1042;
	mul.f32 	%f1095, %f1, %f1048;
	sub.f32 	%f1096, %f1094, %f1095;
	fma.rn.f32 	%f1097, %f1096, %f257, %f1093;
	add.f32 	%f1098, %f9, %f1387;
	mul.f32 	%f1099, %f1, %f1045;
	mul.f32 	%f1100, %f2, %f1042;
	sub.f32 	%f1101, %f1099, %f1100;
	fma.rn.f32 	%f1102, %f1101, %f257, %f1098;
	add.f32 	%f1103, %f1092, %f1061;
	add.f32 	%f1104, %f1097, %f1064;
	add.f32 	%f1105, %f1102, %f1067;
	add.f32 	%f1106, %f10, %f258;
	mul.f32 	%f1107, %f5, %f1055;
	mul.f32 	%f1108, %f6, %f1054;
	sub.f32 	%f1109, %f1107, %f1108;
	fma.rn.f32 	%f1110, %f1109, %f1052, %f1106;
	add.f32 	%f1111, %f11, %f259;
	mul.f32 	%f1112, %f6, %f1053;
	mul.f32 	%f1113, %f4, %f1055;
	sub.f32 	%f1114, %f1112, %f1113;
	fma.rn.f32 	%f1115, %f1114, %f1052, %f1111;
	add.f32 	%f1116, %f12, %f260;
	mul.f32 	%f1117, %f4, %f1054;
	mul.f32 	%f1118, %f5, %f1053;
	sub.f32 	%f1119, %f1117, %f1118;
	fma.rn.f32 	%f1120, %f1119, %f1052, %f1116;
	sub.f32 	%f1121, %f1110, %f1061;
	sub.f32 	%f1122, %f1115, %f1064;
	sub.f32 	%f1123, %f1120, %f1067;
	fma.rn.f32 	%f1124, %f58, %f1074, %f1103;
	fma.rn.f32 	%f1125, %f59, %f1074, %f1104;
	fma.rn.f32 	%f1126, %f60, %f1074, %f1105;
	fma.rn.f32 	%f1127, %f64, %f1081, %f1121;
	fma.rn.f32 	%f1128, %f65, %f1081, %f1122;
	fma.rn.f32 	%f1129, %f66, %f1081, %f1123;
	mul.f32 	%f1130, %f2, %f1105;
	mul.f32 	%f1131, %f3, %f1104;
	sub.f32 	%f1132, %f1130, %f1131;
	mul.f32 	%f1133, %f3, %f1103;
	mul.f32 	%f1134, %f1, %f1105;
	sub.f32 	%f1135, %f1133, %f1134;
	mul.f32 	%f1136, %f1, %f1104;
	mul.f32 	%f1137, %f2, %f1103;
	sub.f32 	%f1138, %f1136, %f1137;
	mul.f32 	%f1139, %f5, %f1123;
	mul.f32 	%f1140, %f6, %f1122;
	sub.f32 	%f1141, %f1139, %f1140;
	mul.f32 	%f1142, %f6, %f1121;
	mul.f32 	%f1143, %f4, %f1123;
	sub.f32 	%f1144, %f1142, %f1143;
	mul.f32 	%f1145, %f4, %f1122;
	mul.f32 	%f1146, %f5, %f1121;
	sub.f32 	%f1147, %f1145, %f1146;
	mul.f32 	%f1148, %f2, %f1104;
	fma.rn.f32 	%f1149, %f1, %f1103, %f1148;
	fma.rn.f32 	%f1150, %f3, %f1105, %f1149;
	mul.f32 	%f1151, %f5, %f1122;
	fma.rn.f32 	%f1152, %f4, %f1121, %f1151;
	fma.rn.f32 	%f1153, %f6, %f1123, %f1152;
	mul.f32 	%f1154, %f2, %f1126;
	mul.f32 	%f1155, %f3, %f1125;
	sub.f32 	%f1156, %f1154, %f1155;
	mul.f32 	%f1157, %f3, %f1124;
	mul.f32 	%f1158, %f1, %f1126;
	sub.f32 	%f1159, %f1157, %f1158;
	mul.f32 	%f1160, %f1, %f1125;
	mul.f32 	%f1161, %f2, %f1124;
	sub.f32 	%f1162, %f1160, %f1161;
	mul.f32 	%f1163, %f5, %f1129;
	mul.f32 	%f1164, %f6, %f1128;
	sub.f32 	%f1165, %f1163, %f1164;
	mul.f32 	%f1166, %f6, %f1127;
	mul.f32 	%f1167, %f4, %f1129;
	sub.f32 	%f1168, %f1166, %f1167;
	mul.f32 	%f1169, %f4, %f1128;
	mul.f32 	%f1170, %f5, %f1127;
	sub.f32 	%f1171, %f1169, %f1170;
	mul.f32 	%f1172, %f2, %f1162;
	mul.f32 	%f1173, %f3, %f1159;
	sub.f32 	%f1174, %f1172, %f1173;
	mul.f32 	%f1175, %f3, %f1156;
	mul.f32 	%f1176, %f1, %f1162;
	sub.f32 	%f1177, %f1175, %f1176;
	mul.f32 	%f1178, %f1, %f1159;
	mul.f32 	%f1179, %f2, %f1156;
	sub.f32 	%f1180, %f1178, %f1179;
	mul.f32 	%f1181, %f5, %f1171;
	mul.f32 	%f1182, %f6, %f1168;
	sub.f32 	%f1183, %f1181, %f1182;
	mul.f32 	%f1184, %f6, %f1165;
	mul.f32 	%f1185, %f4, %f1171;
	sub.f32 	%f1186, %f1184, %f1185;
	mul.f32 	%f1187, %f4, %f1168;
	mul.f32 	%f1188, %f5, %f1165;
	sub.f32 	%f1189, %f1187, %f1188;
	fma.rn.f32 	%f1190, %f1393, %f1393, 0f3F800000;
	rcp.rn.f32 	%f1191, %f1190;
	fma.rn.f32 	%f1192, %f1394, %f1394, 0f3F800000;
	rcp.rn.f32 	%f1193, %f1192;
	mul.f32 	%f1194, %f1132, %f1191;
	mul.f32 	%f1195, %f1135, %f1191;
	mul.f32 	%f1196, %f1138, %f1191;
	mul.f32 	%f1197, %f1391, %f1191;
	div.rn.f32 	%f1198, %f1197, %f56;
	div.rn.f32 	%f1199, %f1198, %f56;
	mul.f32 	%f1200, %f1150, %f1199;
	mul.f32 	%f1201, %f1, %f1200;
	mul.f32 	%f1202, %f2, %f1200;
	mul.f32 	%f1203, %f3, %f1200;
	sub.f32 	%f1204, %f1201, %f1194;
	sub.f32 	%f1205, %f1202, %f1195;
	sub.f32 	%f1206, %f1203, %f1196;
	mul.f32 	%f1207, %f1393, %f1191;
	div.rn.f32 	%f1208, %f1207, %f56;
	div.rn.f32 	%f1209, %f1208, %f56;
	mul.f32 	%f1210, %f1174, %f1209;
	mul.f32 	%f1211, %f1177, %f1209;
	mul.f32 	%f1212, %f1180, %f1209;
	sub.f32 	%f1213, %f1204, %f1210;
	sub.f32 	%f1214, %f1205, %f1211;
	sub.f32 	%f1215, %f1206, %f1212;
	fma.rn.f32 	%f1398, %f61, %f1084, %f1213;
	fma.rn.f32 	%f1399, %f62, %f1084, %f1214;
	fma.rn.f32 	%f1400, %f63, %f1084, %f1215;
	mul.f32 	%f1216, %f1141, %f1193;
	mul.f32 	%f1217, %f1144, %f1193;
	mul.f32 	%f1218, %f1147, %f1193;
	mul.f32 	%f1219, %f1392, %f1193;
	div.rn.f32 	%f1220, %f1219, %f57;
	div.rn.f32 	%f1221, %f1220, %f57;
	mul.f32 	%f1222, %f1153, %f1221;
	mul.f32 	%f1223, %f4, %f1222;
	mul.f32 	%f1224, %f5, %f1222;
	mul.f32 	%f1225, %f6, %f1222;
	sub.f32 	%f1226, %f1223, %f1216;
	sub.f32 	%f1227, %f1224, %f1217;
	sub.f32 	%f1228, %f1225, %f1218;
	mul.f32 	%f1229, %f1394, %f1193;
	div.rn.f32 	%f1230, %f1229, %f57;
	div.rn.f32 	%f1231, %f1230, %f57;
	mul.f32 	%f1232, %f1183, %f1231;
	mul.f32 	%f1233, %f1186, %f1231;
	mul.f32 	%f1234, %f1189, %f1231;
	sub.f32 	%f1235, %f1226, %f1232;
	sub.f32 	%f1236, %f1227, %f1233;
	sub.f32 	%f1237, %f1228, %f1234;
	fma.rn.f32 	%f1395, %f67, %f1087, %f1235;
	fma.rn.f32 	%f1396, %f68, %f1087, %f1236;
	fma.rn.f32 	%f1397, %f69, %f1087, %f1237;

BB0_142:
	ld.param.u64 	%rd164, [LLBtorqueAFPRB054401_param_8];
	ld.param.u64 	%rd163, [LLBtorqueAFPRB054401_param_7];
	ld.param.u64 	%rd162, [LLBtorqueAFPRB054401_param_6];
	ld.param.u64 	%rd161, [LLBtorqueAFPRB054401_param_2];
	ld.param.u64 	%rd160, [LLBtorqueAFPRB054401_param_1];
	ld.param.u64 	%rd159, [LLBtorqueAFPRB054401_param_0];
	mov.u32 	%r129, %ctaid.x;
	mov.u32 	%r128, %ctaid.y;
	mov.u32 	%r127, %nctaid.x;
	mov.u32 	%r126, %tid.x;
	mov.u32 	%r125, %ntid.x;
	mad.lo.s32 	%r124, %r127, %r128, %r129;
	mad.lo.s32 	%r123, %r124, %r125, %r126;
	mul.wide.s32 	%rd158, %r123, 4;
	cvta.to.global.u64 	%rd145, %rd159;
	add.s64 	%rd147, %rd145, %rd158;
	st.global.f32 	[%rd147], %f1398;
	cvta.to.global.u64 	%rd148, %rd160;
	add.s64 	%rd149, %rd148, %rd158;
	st.global.f32 	[%rd149], %f1399;
	cvta.to.global.u64 	%rd150, %rd161;
	add.s64 	%rd151, %rd150, %rd158;
	st.global.f32 	[%rd151], %f1400;
	cvta.to.global.u64 	%rd152, %rd162;
	add.s64 	%rd153, %rd152, %rd158;
	st.global.f32 	[%rd153], %f1395;
	cvta.to.global.u64 	%rd154, %rd163;
	add.s64 	%rd155, %rd154, %rd158;
	st.global.f32 	[%rd155], %f1396;
	cvta.to.global.u64 	%rd156, %rd164;
	add.s64 	%rd157, %rd156, %rd158;
	st.global.f32 	[%rd157], %f1397;

BB0_143:
	ret;
}


`
)
