package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for LLBtorque2 kernel
var LLBtorque2_code cu.Function

// Stores the arguments for LLBtorque2 kernel invocation
type LLBtorque2_args_t struct {
	arg_tx         unsafe.Pointer
	arg_ty         unsafe.Pointer
	arg_tz         unsafe.Pointer
	arg_mx         unsafe.Pointer
	arg_my         unsafe.Pointer
	arg_mz         unsafe.Pointer
	arg_hx         unsafe.Pointer
	arg_hy         unsafe.Pointer
	arg_hz         unsafe.Pointer
	arg_alpha_     unsafe.Pointer
	arg_alpha_mul  float32
	arg_TCurie_    unsafe.Pointer
	arg_TCurie_mul float32
	arg_Msat_      unsafe.Pointer
	arg_Msat_mul   float32
	arg_hth1x      unsafe.Pointer
	arg_hth1y      unsafe.Pointer
	arg_hth1z      unsafe.Pointer
	arg_hth2x      unsafe.Pointer
	arg_hth2y      unsafe.Pointer
	arg_hth2z      unsafe.Pointer
	arg_temp_      unsafe.Pointer
	arg_temp_mul   float32
	arg_N          int
	argptr         [24]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for LLBtorque2 kernel invocation
var LLBtorque2_args LLBtorque2_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	LLBtorque2_args.argptr[0] = unsafe.Pointer(&LLBtorque2_args.arg_tx)
	LLBtorque2_args.argptr[1] = unsafe.Pointer(&LLBtorque2_args.arg_ty)
	LLBtorque2_args.argptr[2] = unsafe.Pointer(&LLBtorque2_args.arg_tz)
	LLBtorque2_args.argptr[3] = unsafe.Pointer(&LLBtorque2_args.arg_mx)
	LLBtorque2_args.argptr[4] = unsafe.Pointer(&LLBtorque2_args.arg_my)
	LLBtorque2_args.argptr[5] = unsafe.Pointer(&LLBtorque2_args.arg_mz)
	LLBtorque2_args.argptr[6] = unsafe.Pointer(&LLBtorque2_args.arg_hx)
	LLBtorque2_args.argptr[7] = unsafe.Pointer(&LLBtorque2_args.arg_hy)
	LLBtorque2_args.argptr[8] = unsafe.Pointer(&LLBtorque2_args.arg_hz)
	LLBtorque2_args.argptr[9] = unsafe.Pointer(&LLBtorque2_args.arg_alpha_)
	LLBtorque2_args.argptr[10] = unsafe.Pointer(&LLBtorque2_args.arg_alpha_mul)
	LLBtorque2_args.argptr[11] = unsafe.Pointer(&LLBtorque2_args.arg_TCurie_)
	LLBtorque2_args.argptr[12] = unsafe.Pointer(&LLBtorque2_args.arg_TCurie_mul)
	LLBtorque2_args.argptr[13] = unsafe.Pointer(&LLBtorque2_args.arg_Msat_)
	LLBtorque2_args.argptr[14] = unsafe.Pointer(&LLBtorque2_args.arg_Msat_mul)
	LLBtorque2_args.argptr[15] = unsafe.Pointer(&LLBtorque2_args.arg_hth1x)
	LLBtorque2_args.argptr[16] = unsafe.Pointer(&LLBtorque2_args.arg_hth1y)
	LLBtorque2_args.argptr[17] = unsafe.Pointer(&LLBtorque2_args.arg_hth1z)
	LLBtorque2_args.argptr[18] = unsafe.Pointer(&LLBtorque2_args.arg_hth2x)
	LLBtorque2_args.argptr[19] = unsafe.Pointer(&LLBtorque2_args.arg_hth2y)
	LLBtorque2_args.argptr[20] = unsafe.Pointer(&LLBtorque2_args.arg_hth2z)
	LLBtorque2_args.argptr[21] = unsafe.Pointer(&LLBtorque2_args.arg_temp_)
	LLBtorque2_args.argptr[22] = unsafe.Pointer(&LLBtorque2_args.arg_temp_mul)
	LLBtorque2_args.argptr[23] = unsafe.Pointer(&LLBtorque2_args.arg_N)
}

// Wrapper for LLBtorque2 CUDA kernel, asynchronous.
func k_LLBtorque2_async(tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, hx unsafe.Pointer, hy unsafe.Pointer, hz unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, TCurie_ unsafe.Pointer, TCurie_mul float32, Msat_ unsafe.Pointer, Msat_mul float32, hth1x unsafe.Pointer, hth1y unsafe.Pointer, hth1z unsafe.Pointer, hth2x unsafe.Pointer, hth2y unsafe.Pointer, hth2z unsafe.Pointer, temp_ unsafe.Pointer, temp_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("LLBtorque2")
	}

	LLBtorque2_args.Lock()
	defer LLBtorque2_args.Unlock()

	if LLBtorque2_code == 0 {
		LLBtorque2_code = fatbinLoad(LLBtorque2_map, "LLBtorque2")
	}

	LLBtorque2_args.arg_tx = tx
	LLBtorque2_args.arg_ty = ty
	LLBtorque2_args.arg_tz = tz
	LLBtorque2_args.arg_mx = mx
	LLBtorque2_args.arg_my = my
	LLBtorque2_args.arg_mz = mz
	LLBtorque2_args.arg_hx = hx
	LLBtorque2_args.arg_hy = hy
	LLBtorque2_args.arg_hz = hz
	LLBtorque2_args.arg_alpha_ = alpha_
	LLBtorque2_args.arg_alpha_mul = alpha_mul
	LLBtorque2_args.arg_TCurie_ = TCurie_
	LLBtorque2_args.arg_TCurie_mul = TCurie_mul
	LLBtorque2_args.arg_Msat_ = Msat_
	LLBtorque2_args.arg_Msat_mul = Msat_mul
	LLBtorque2_args.arg_hth1x = hth1x
	LLBtorque2_args.arg_hth1y = hth1y
	LLBtorque2_args.arg_hth1z = hth1z
	LLBtorque2_args.arg_hth2x = hth2x
	LLBtorque2_args.arg_hth2y = hth2y
	LLBtorque2_args.arg_hth2z = hth2z
	LLBtorque2_args.arg_temp_ = temp_
	LLBtorque2_args.arg_temp_mul = temp_mul
	LLBtorque2_args.arg_N = N

	args := LLBtorque2_args.argptr[:]
	cu.LaunchKernel(LLBtorque2_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("LLBtorque2")
	}
}

// maps compute capability on PTX code for LLBtorque2 kernel.
var LLBtorque2_map = map[int]string{0: "",
	30: LLBtorque2_ptx_30}

// LLBtorque2 PTX code for various compute capabilities.
const (
	LLBtorque2_ptx_30 = `
.version 6.5
.target sm_30
.address_size 64

	// .globl	LLBtorque2

.visible .entry LLBtorque2(
	.param .u64 LLBtorque2_param_0,
	.param .u64 LLBtorque2_param_1,
	.param .u64 LLBtorque2_param_2,
	.param .u64 LLBtorque2_param_3,
	.param .u64 LLBtorque2_param_4,
	.param .u64 LLBtorque2_param_5,
	.param .u64 LLBtorque2_param_6,
	.param .u64 LLBtorque2_param_7,
	.param .u64 LLBtorque2_param_8,
	.param .u64 LLBtorque2_param_9,
	.param .f32 LLBtorque2_param_10,
	.param .u64 LLBtorque2_param_11,
	.param .f32 LLBtorque2_param_12,
	.param .u64 LLBtorque2_param_13,
	.param .f32 LLBtorque2_param_14,
	.param .u64 LLBtorque2_param_15,
	.param .u64 LLBtorque2_param_16,
	.param .u64 LLBtorque2_param_17,
	.param .u64 LLBtorque2_param_18,
	.param .u64 LLBtorque2_param_19,
	.param .u64 LLBtorque2_param_20,
	.param .u64 LLBtorque2_param_21,
	.param .f32 LLBtorque2_param_22,
	.param .u32 LLBtorque2_param_23
)
{
	.reg .pred 	%p<52>;
	.reg .f32 	%f<402>;
	.reg .b32 	%r<41>;
	.reg .f64 	%fd<10>;
	.reg .b64 	%rd<65>;


	ld.param.u64 	%rd5, [LLBtorque2_param_3];
	ld.param.u64 	%rd6, [LLBtorque2_param_4];
	ld.param.u64 	%rd7, [LLBtorque2_param_5];
	ld.param.u64 	%rd8, [LLBtorque2_param_6];
	ld.param.u64 	%rd9, [LLBtorque2_param_7];
	ld.param.u64 	%rd10, [LLBtorque2_param_8];
	ld.param.u64 	%rd11, [LLBtorque2_param_9];
	ld.param.f32 	%f387, [LLBtorque2_param_10];
	ld.param.u64 	%rd12, [LLBtorque2_param_11];
	ld.param.f32 	%f388, [LLBtorque2_param_12];
	ld.param.u64 	%rd13, [LLBtorque2_param_15];
	ld.param.u64 	%rd14, [LLBtorque2_param_16];
	ld.param.u64 	%rd15, [LLBtorque2_param_17];
	ld.param.u64 	%rd16, [LLBtorque2_param_18];
	ld.param.u64 	%rd17, [LLBtorque2_param_19];
	ld.param.u64 	%rd18, [LLBtorque2_param_20];
	ld.param.u64 	%rd19, [LLBtorque2_param_21];
	ld.param.f32 	%f389, [LLBtorque2_param_22];
	ld.param.u32 	%r2, [LLBtorque2_param_23];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p3, %r1, %r2;
	@%p3 bra 	BB0_37;

	cvta.to.global.u64 	%rd20, %rd5;
	mul.wide.s32 	%rd21, %r1, 4;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.f32 	%f1, [%rd22];
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd24, %rd23, %rd21;
	ld.global.f32 	%f2, [%rd24];
	cvta.to.global.u64 	%rd25, %rd7;
	add.s64 	%rd26, %rd25, %rd21;
	ld.global.f32 	%f3, [%rd26];
	cvta.to.global.u64 	%rd27, %rd8;
	add.s64 	%rd28, %rd27, %rd21;
	ld.global.f32 	%f4, [%rd28];
	cvta.to.global.u64 	%rd29, %rd9;
	add.s64 	%rd30, %rd29, %rd21;
	ld.global.f32 	%f5, [%rd30];
	cvta.to.global.u64 	%rd31, %rd10;
	add.s64 	%rd32, %rd31, %rd21;
	ld.global.f32 	%f6, [%rd32];
	setp.eq.s64	%p4, %rd11, 0;
	@%p4 bra 	BB0_3;

	cvta.to.global.u64 	%rd33, %rd11;
	add.s64 	%rd35, %rd33, %rd21;
	ld.global.f32 	%f70, [%rd35];
	mul.f32 	%f387, %f70, %f387;

BB0_3:
	setp.eq.s64	%p5, %rd12, 0;
	@%p5 bra 	BB0_5;

	cvta.to.global.u64 	%rd36, %rd12;
	add.s64 	%rd38, %rd36, %rd21;
	ld.global.f32 	%f71, [%rd38];
	mul.f32 	%f388, %f71, %f388;

BB0_5:
	setp.eq.s64	%p6, %rd19, 0;
	@%p6 bra 	BB0_7;

	cvta.to.global.u64 	%rd39, %rd19;
	add.s64 	%rd41, %rd39, %rd21;
	ld.global.f32 	%f72, [%rd41];
	mul.f32 	%f389, %f72, %f389;

BB0_7:
	setp.eq.f32	%p7, %f389, 0f00000000;
	selp.f32	%f73, 0f38D1B717, %f389, %p7;
	cvt.f64.f32	%fd2, %f73;
	cvt.f64.f32	%fd1, %f388;
	add.f64 	%fd3, %fd1, %fd1;
	setp.gt.f64	%p8, %fd2, %fd3;
	add.f32 	%f74, %f388, %f388;
	selp.f32	%f390, %f74, %f73, %p8;
	setp.neu.f32	%p9, %f390, %f388;
	@%p9 bra 	BB0_9;

	add.f64 	%fd4, %fd1, 0dBF847AE147AE147B;
	cvt.rn.f32.f64	%f390, %fd4;

BB0_9:
	cvta.to.global.u64 	%rd42, %rd18;
	cvta.to.global.u64 	%rd43, %rd17;
	cvta.to.global.u64 	%rd44, %rd16;
	cvta.to.global.u64 	%rd45, %rd15;
	cvta.to.global.u64 	%rd46, %rd14;
	cvta.to.global.u64 	%rd47, %rd13;
	add.s64 	%rd49, %rd47, %rd21;
	ld.global.f32 	%f16, [%rd49];
	add.s64 	%rd50, %rd46, %rd21;
	ld.global.f32 	%f17, [%rd50];
	add.s64 	%rd51, %rd45, %rd21;
	ld.global.f32 	%f18, [%rd51];
	add.s64 	%rd52, %rd44, %rd21;
	ld.global.f32 	%f19, [%rd52];
	add.s64 	%rd53, %rd43, %rd21;
	ld.global.f32 	%f20, [%rd53];
	add.s64 	%rd1, %rd42, %rd21;
	mul.f32 	%f75, %f2, %f2;
	fma.rn.f32 	%f76, %f1, %f1, %f75;
	fma.rn.f32 	%f21, %f3, %f3, %f76;
	mul.f32 	%f399, %f1, 0f00000000;
	mul.f32 	%f400, %f2, 0f00000000;
	mul.f32 	%f401, %f3, 0f00000000;
	setp.eq.f32	%p10, %f21, 0f00000000;
	setp.eq.f32	%p11, %f388, 0f00000000;
	or.pred  	%p12, %p10, %p11;
	@%p12 bra 	BB0_36;

	ld.global.f32 	%f25, [%rd1];
	add.f32 	%f77, %f387, %f387;
	mul.f32 	%f78, %f77, %f390;
	mul.f32 	%f26, %f388, 0f40400000;
	div.rn.f32 	%f27, %f78, %f26;
	setp.gtu.f32	%p13, %f390, %f388;
	@%p13 bra 	BB0_34;
	bra.uni 	BB0_11;

BB0_34:
	sub.f32 	%f283, %f390, %f388;
	mov.f32 	%f284, 0f347DE56D;
	div.rn.f32 	%f285, %f284, %f283;
	cvt.f64.f32	%fd8, %f285;
	setp.gt.f64	%p50, %fd8, 0d3F1A36E2EB1C432D;
	selp.f32	%f286, 0f38D1B717, %f285, %p50;
	div.rn.f32 	%f287, %f388, %f283;
	mul.f32 	%f288, %f21, 0f3F19999A;
	fma.rn.f32 	%f289, %f288, %f287, 0f3F800000;
	cvt.f64.f32	%fd9, %f286;
	mov.f32 	%f290, 0fBF800000;
	div.rn.f32 	%f291, %f290, %f286;
	setp.lt.f64	%p51, %fd9, 0d3DD5FD7FE1796495;
	selp.f32	%f292, 0fD03A43B7, %f291, %p51;
	mul.f32 	%f397, %f289, %f292;
	mov.f32 	%f398, %f27;
	bra.uni 	BB0_35;

BB0_11:
	div.rn.f32 	%f28, %f390, %f388;
	abs.f32 	%f30, %f28;
	setp.lt.f32	%p14, %f30, 0f00800000;
	mul.f32 	%f84, %f30, 0f4B800000;
	selp.f32	%f85, 0fC3170000, 0fC2FE0000, %p14;
	selp.f32	%f86, %f84, %f30, %p14;
	mov.b32 	 %r9, %f86;
	and.b32  	%r10, %r9, 8388607;
	or.b32  	%r11, %r10, 1065353216;
	mov.b32 	 %f87, %r11;
	shr.u32 	%r12, %r9, 23;
	cvt.rn.f32.u32	%f88, %r12;
	add.f32 	%f89, %f85, %f88;
	setp.gt.f32	%p15, %f87, 0f3FB504F3;
	mul.f32 	%f90, %f87, 0f3F000000;
	add.f32 	%f91, %f89, 0f3F800000;
	selp.f32	%f92, %f90, %f87, %p15;
	selp.f32	%f93, %f91, %f89, %p15;
	add.f32 	%f94, %f92, 0fBF800000;
	add.f32 	%f80, %f92, 0f3F800000;
	// inline asm
	rcp.approx.ftz.f32 %f79,%f80;
	// inline asm
	add.f32 	%f95, %f94, %f94;
	mul.f32 	%f96, %f79, %f95;
	mul.f32 	%f97, %f96, %f96;
	mov.f32 	%f98, 0f3C4CAF63;
	mov.f32 	%f99, 0f3B18F0FE;
	fma.rn.f32 	%f100, %f99, %f97, %f98;
	mov.f32 	%f101, 0f3DAAAABD;
	fma.rn.f32 	%f102, %f100, %f97, %f101;
	mul.rn.f32 	%f103, %f102, %f97;
	mul.rn.f32 	%f104, %f103, %f96;
	sub.f32 	%f105, %f94, %f96;
	neg.f32 	%f106, %f96;
	add.f32 	%f107, %f105, %f105;
	fma.rn.f32 	%f108, %f106, %f94, %f107;
	mul.rn.f32 	%f109, %f79, %f108;
	add.f32 	%f110, %f104, %f96;
	sub.f32 	%f111, %f96, %f110;
	add.f32 	%f112, %f104, %f111;
	add.f32 	%f113, %f109, %f112;
	add.f32 	%f114, %f110, %f113;
	sub.f32 	%f115, %f110, %f114;
	add.f32 	%f116, %f113, %f115;
	mov.f32 	%f117, 0f3F317200;
	mul.rn.f32 	%f118, %f93, %f117;
	mov.f32 	%f119, 0f35BFBE8E;
	mul.rn.f32 	%f120, %f93, %f119;
	add.f32 	%f121, %f118, %f114;
	sub.f32 	%f122, %f118, %f121;
	add.f32 	%f123, %f114, %f122;
	add.f32 	%f124, %f116, %f123;
	add.f32 	%f125, %f120, %f124;
	add.f32 	%f126, %f121, %f125;
	sub.f32 	%f127, %f121, %f126;
	add.f32 	%f128, %f125, %f127;
	mov.f32 	%f129, 0f405F5C29;
	mul.rn.f32 	%f130, %f129, %f126;
	neg.f32 	%f131, %f130;
	fma.rn.f32 	%f132, %f129, %f126, %f131;
	fma.rn.f32 	%f133, %f129, %f128, %f132;
	mov.f32 	%f134, 0f00000000;
	fma.rn.f32 	%f135, %f134, %f126, %f133;
	add.rn.f32 	%f136, %f130, %f135;
	neg.f32 	%f137, %f136;
	add.rn.f32 	%f138, %f130, %f137;
	add.rn.f32 	%f139, %f138, %f135;
	mov.b32 	 %r13, %f136;
	setp.eq.s32	%p16, %r13, 1118925336;
	add.s32 	%r14, %r13, -1;
	mov.b32 	 %f140, %r14;
	add.f32 	%f141, %f139, 0f37000000;
	selp.f32	%f142, %f140, %f136, %p16;
	selp.f32	%f31, %f141, %f139, %p16;
	mul.f32 	%f143, %f142, 0f3FB8AA3B;
	cvt.rzi.f32.f32	%f144, %f143;
	mov.f32 	%f145, 0fBF317200;
	fma.rn.f32 	%f146, %f144, %f145, %f142;
	mov.f32 	%f147, 0fB5BFBE8E;
	fma.rn.f32 	%f148, %f144, %f147, %f146;
	mul.f32 	%f149, %f148, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f150, %f149;
	add.f32 	%f151, %f144, 0f00000000;
	ex2.approx.f32 	%f152, %f151;
	mul.f32 	%f153, %f150, %f152;
	setp.lt.f32	%p17, %f142, 0fC2D20000;
	selp.f32	%f154, 0f00000000, %f153, %p17;
	setp.gt.f32	%p18, %f142, 0f42D20000;
	selp.f32	%f391, 0f7F800000, %f154, %p18;
	setp.eq.f32	%p19, %f391, 0f7F800000;
	@%p19 bra 	BB0_13;

	fma.rn.f32 	%f391, %f391, %f31, %f391;

BB0_13:
	mov.f32 	%f383, 0f3FDF5C29;
	cvt.rzi.f32.f32	%f382, %f383;
	fma.rn.f32 	%f381, %f382, 0fC0000000, 0f405F5C29;
	abs.f32 	%f380, %f381;
	setp.lt.f32	%p20, %f28, 0f00000000;
	setp.eq.f32	%p21, %f380, 0f3F800000;
	and.pred  	%p1, %p20, %p21;
	mov.b32 	 %r15, %f391;
	xor.b32  	%r16, %r15, -2147483648;
	mov.b32 	 %f155, %r16;
	selp.f32	%f393, %f155, %f391, %p1;
	setp.eq.f32	%p22, %f28, 0f00000000;
	@%p22 bra 	BB0_16;
	bra.uni 	BB0_14;

BB0_16:
	add.f32 	%f158, %f28, %f28;
	selp.f32	%f393, %f158, 0f00000000, %p21;
	bra.uni 	BB0_17;

BB0_14:
	setp.geu.f32	%p23, %f28, 0f00000000;
	@%p23 bra 	BB0_17;

	mov.f32 	%f369, 0f405F5C29;
	cvt.rzi.f32.f32	%f157, %f369;
	setp.neu.f32	%p24, %f157, 0f405F5C29;
	selp.f32	%f393, 0f7FFFFFFF, %f393, %p24;

BB0_17:
	abs.f32 	%f384, %f28;
	add.f32 	%f159, %f384, 0f405F5C29;
	mov.b32 	 %r17, %f159;
	setp.lt.s32	%p26, %r17, 2139095040;
	@%p26 bra 	BB0_22;

	abs.f32 	%f385, %f28;
	setp.gtu.f32	%p27, %f385, 0f7F800000;
	@%p27 bra 	BB0_21;
	bra.uni 	BB0_19;

BB0_21:
	add.f32 	%f393, %f28, 0f405F5C29;
	bra.uni 	BB0_22;

BB0_19:
	abs.f32 	%f386, %f28;
	setp.neu.f32	%p28, %f386, 0f7F800000;
	@%p28 bra 	BB0_22;

	selp.f32	%f393, 0fFF800000, 0f7F800000, %p1;

BB0_22:
	mov.f32 	%f366, 0fB5BFBE8E;
	mov.f32 	%f365, 0fBF317200;
	mov.f32 	%f364, 0f00000000;
	mov.f32 	%f363, 0f35BFBE8E;
	mov.f32 	%f362, 0f3F317200;
	mov.f32 	%f361, 0f3DAAAABD;
	mov.f32 	%f360, 0f3C4CAF63;
	mov.f32 	%f359, 0f3B18F0FE;
	mov.f32 	%f162, 0f3F800000;
	sub.f32 	%f163, %f162, %f393;
	setp.eq.f32	%p29, %f28, 0f3F800000;
	selp.f32	%f42, 0f00000000, %f163, %p29;
	abs.f32 	%f44, %f42;
	setp.lt.f32	%p30, %f44, 0f00800000;
	mul.f32 	%f167, %f44, 0f4B800000;
	selp.f32	%f168, 0fC3170000, 0fC2FE0000, %p30;
	selp.f32	%f169, %f167, %f44, %p30;
	mov.b32 	 %r18, %f169;
	and.b32  	%r19, %r18, 8388607;
	or.b32  	%r20, %r19, 1065353216;
	mov.b32 	 %f170, %r20;
	shr.u32 	%r21, %r18, 23;
	cvt.rn.f32.u32	%f171, %r21;
	add.f32 	%f172, %f168, %f171;
	setp.gt.f32	%p31, %f170, 0f3FB504F3;
	mul.f32 	%f173, %f170, 0f3F000000;
	add.f32 	%f174, %f172, 0f3F800000;
	selp.f32	%f175, %f173, %f170, %p31;
	selp.f32	%f176, %f174, %f172, %p31;
	add.f32 	%f177, %f175, 0fBF800000;
	add.f32 	%f161, %f175, 0f3F800000;
	// inline asm
	rcp.approx.ftz.f32 %f160,%f161;
	// inline asm
	add.f32 	%f178, %f177, %f177;
	mul.f32 	%f179, %f160, %f178;
	mul.f32 	%f180, %f179, %f179;
	fma.rn.f32 	%f183, %f359, %f180, %f360;
	fma.rn.f32 	%f185, %f183, %f180, %f361;
	mul.rn.f32 	%f186, %f185, %f180;
	mul.rn.f32 	%f187, %f186, %f179;
	sub.f32 	%f188, %f177, %f179;
	neg.f32 	%f189, %f179;
	add.f32 	%f190, %f188, %f188;
	fma.rn.f32 	%f191, %f189, %f177, %f190;
	mul.rn.f32 	%f192, %f160, %f191;
	add.f32 	%f193, %f187, %f179;
	sub.f32 	%f194, %f179, %f193;
	add.f32 	%f195, %f187, %f194;
	add.f32 	%f196, %f192, %f195;
	add.f32 	%f197, %f193, %f196;
	sub.f32 	%f198, %f193, %f197;
	add.f32 	%f199, %f196, %f198;
	mul.rn.f32 	%f201, %f176, %f362;
	mul.rn.f32 	%f203, %f176, %f363;
	add.f32 	%f204, %f201, %f197;
	sub.f32 	%f205, %f201, %f204;
	add.f32 	%f206, %f197, %f205;
	add.f32 	%f207, %f199, %f206;
	add.f32 	%f208, %f203, %f207;
	add.f32 	%f209, %f204, %f208;
	sub.f32 	%f210, %f204, %f209;
	add.f32 	%f211, %f208, %f210;
	mov.f32 	%f212, 0f3F0A3D71;
	mul.rn.f32 	%f213, %f212, %f209;
	neg.f32 	%f214, %f213;
	fma.rn.f32 	%f215, %f212, %f209, %f214;
	fma.rn.f32 	%f216, %f212, %f211, %f215;
	fma.rn.f32 	%f218, %f364, %f209, %f216;
	add.rn.f32 	%f219, %f213, %f218;
	neg.f32 	%f220, %f219;
	add.rn.f32 	%f221, %f213, %f220;
	add.rn.f32 	%f222, %f221, %f218;
	mov.b32 	 %r22, %f219;
	setp.eq.s32	%p32, %r22, 1118925336;
	add.s32 	%r23, %r22, -1;
	mov.b32 	 %f223, %r23;
	add.f32 	%f224, %f222, 0f37000000;
	selp.f32	%f225, %f223, %f219, %p32;
	selp.f32	%f45, %f224, %f222, %p32;
	mul.f32 	%f226, %f225, 0f3FB8AA3B;
	cvt.rzi.f32.f32	%f227, %f226;
	fma.rn.f32 	%f229, %f227, %f365, %f225;
	fma.rn.f32 	%f231, %f227, %f366, %f229;
	mul.f32 	%f232, %f231, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f233, %f232;
	add.f32 	%f234, %f227, 0f00000000;
	ex2.approx.f32 	%f235, %f234;
	mul.f32 	%f236, %f233, %f235;
	setp.lt.f32	%p33, %f225, 0fC2D20000;
	selp.f32	%f237, 0f00000000, %f236, %p33;
	setp.gt.f32	%p34, %f225, 0f42D20000;
	selp.f32	%f394, 0f7F800000, %f237, %p34;
	setp.eq.f32	%p35, %f394, 0f7F800000;
	@%p35 bra 	BB0_24;

	fma.rn.f32 	%f394, %f394, %f45, %f394;

BB0_24:
	mov.f32 	%f373, 0f3E8A3D71;
	cvt.rzi.f32.f32	%f372, %f373;
	fma.rn.f32 	%f371, %f372, 0fC0000000, 0f3F0A3D71;
	abs.f32 	%f370, %f371;
	setp.lt.f32	%p36, %f42, 0f00000000;
	setp.eq.f32	%p37, %f370, 0f3F800000;
	and.pred  	%p2, %p36, %p37;
	mov.b32 	 %r24, %f394;
	xor.b32  	%r25, %r24, -2147483648;
	mov.b32 	 %f238, %r25;
	selp.f32	%f396, %f238, %f394, %p2;
	setp.eq.f32	%p38, %f42, 0f00000000;
	@%p38 bra 	BB0_27;
	bra.uni 	BB0_25;

BB0_27:
	add.f32 	%f241, %f42, %f42;
	selp.f32	%f396, %f241, 0f00000000, %p37;
	bra.uni 	BB0_28;

BB0_25:
	setp.geu.f32	%p39, %f42, 0f00000000;
	@%p39 bra 	BB0_28;

	mov.f32 	%f379, 0f3F0A3D71;
	cvt.rzi.f32.f32	%f240, %f379;
	setp.neu.f32	%p40, %f240, 0f3F0A3D71;
	selp.f32	%f396, 0f7FFFFFFF, %f396, %p40;

BB0_28:
	abs.f32 	%f374, %f42;
	add.f32 	%f242, %f374, 0f3F0A3D71;
	mov.b32 	 %r26, %f242;
	setp.lt.s32	%p42, %r26, 2139095040;
	@%p42 bra 	BB0_33;

	abs.f32 	%f377, %f42;
	setp.gtu.f32	%p43, %f377, 0f7F800000;
	@%p43 bra 	BB0_32;
	bra.uni 	BB0_30;

BB0_32:
	add.f32 	%f396, %f42, 0f3F0A3D71;
	bra.uni 	BB0_33;

BB0_30:
	abs.f32 	%f378, %f42;
	setp.neu.f32	%p44, %f378, 0f7F800000;
	@%p44 bra 	BB0_33;

	selp.f32	%f396, 0fFF800000, 0f7F800000, %p2;

BB0_33:
	mul.f32 	%f376, %f388, 0f40400000;
	mov.f32 	%f375, 0f3F800000;
	mov.f32 	%f368, 0fB5BFBE8E;
	mov.f32 	%f367, 0fBF317200;
	setp.eq.f32	%p45, %f42, 0f3F800000;
	selp.f32	%f243, 0f3F800000, %f396, %p45;
	cvt.f64.f32	%fd5, %f243;
	setp.lt.f64	%p46, %fd5, 0d3F50624DD2F1A9FC;
	selp.f32	%f244, 0f3A83126F, %f243, %p46;
	mul.f32 	%f245, %f390, 0f19857725;
	rcp.rn.f32 	%f246, %f245;
	div.rn.f32 	%f247, %f388, %f390;
	mul.f32 	%f248, %f247, %f244;
	abs.f32 	%f249, %f248;
	mul.f32 	%f250, %f249, 0f3FB8AA3B;
	cvt.rzi.f32.f32	%f251, %f250;
	fma.rn.f32 	%f253, %f251, %f367, %f249;
	fma.rn.f32 	%f255, %f251, %f368, %f253;
	mul.f32 	%f256, %f255, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f257, %f256;
	add.f32 	%f258, %f251, 0fC0000000;
	ex2.approx.f32 	%f259, %f258;
	mul.f32 	%f260, %f257, %f259;
	mov.f32 	%f261, 0f3E000000;
	div.approx.f32 	%f262, %f261, %f260;
	mov.f32 	%f263, 0f40000000;
	fma.rn.f32 	%f264, %f263, %f260, %f262;
	setp.ltu.f32	%p47, %f249, 0f42B40000;
	selp.f32	%f265, %f264, 0f7F800000, %p47;
	mul.f32 	%f266, %f265, %f265;
	rcp.rn.f32 	%f267, %f266;
	mul.f32 	%f268, %f246, 0f0FA575F3;
	mul.f32 	%f269, %f247, %f267;
	sub.f32 	%f271, %f375, %f269;
	div.rn.f32 	%f272, %f267, %f271;
	mul.f32 	%f273, %f268, %f272;
	cvt.f64.f32	%fd6, %f273;
	setp.gt.f64	%p48, %fd6, 0d3F1A36E2EB1C432D;
	selp.f32	%f274, 0f38D1B717, %f273, %p48;
	div.rn.f32 	%f275, %f390, %f376;
	sub.f32 	%f276, %f375, %f275;
	mul.f32 	%f398, %f387, %f276;
	add.f32 	%f277, %f274, %f274;
	mul.f32 	%f278, %f244, %f244;
	div.rn.f32 	%f279, %f21, %f278;
	sub.f32 	%f280, %f375, %f279;
	cvt.f64.f32	%fd7, %f274;
	rcp.rn.f32 	%f281, %f277;
	setp.lt.f64	%p49, %fd7, 0d3DD5FD7FE1796495;
	selp.f32	%f282, 0f4FBA43B7, %f281, %p49;
	mul.f32 	%f397, %f280, %f282;

BB0_35:
	mul.f32 	%f293, %f397, 0f35A8A9B8;
	mul.f32 	%f294, %f387, %f398;
	mul.f32 	%f295, %f398, %f294;
	sub.f32 	%f296, %f398, %f27;
	div.rn.f32 	%f297, %f296, %f295;
	sqrt.rn.f32 	%f298, %f297;
	div.rn.f32 	%f299, %f27, %f387;
	sqrt.rn.f32 	%f300, %f299;
	fma.rn.f32 	%f301, %f1, %f293, %f4;
	fma.rn.f32 	%f302, %f2, %f293, %f5;
	fma.rn.f32 	%f303, %f3, %f293, %f6;
	fma.rn.f32 	%f304, %f16, %f298, %f301;
	fma.rn.f32 	%f305, %f17, %f298, %f302;
	fma.rn.f32 	%f306, %f18, %f298, %f303;
	mul.f32 	%f307, %f2, %f303;
	mul.f32 	%f308, %f3, %f302;
	sub.f32 	%f309, %f307, %f308;
	mul.f32 	%f310, %f3, %f301;
	mul.f32 	%f311, %f1, %f303;
	sub.f32 	%f312, %f310, %f311;
	mul.f32 	%f313, %f1, %f302;
	mul.f32 	%f314, %f2, %f301;
	sub.f32 	%f315, %f313, %f314;
	mul.f32 	%f316, %f2, %f302;
	fma.rn.f32 	%f317, %f1, %f301, %f316;
	fma.rn.f32 	%f318, %f3, %f303, %f317;
	mul.f32 	%f319, %f2, %f306;
	mul.f32 	%f320, %f3, %f305;
	sub.f32 	%f321, %f319, %f320;
	mul.f32 	%f322, %f3, %f304;
	mul.f32 	%f323, %f1, %f306;
	sub.f32 	%f324, %f322, %f323;
	mul.f32 	%f325, %f1, %f305;
	mul.f32 	%f326, %f2, %f304;
	sub.f32 	%f327, %f325, %f326;
	mul.f32 	%f328, %f2, %f327;
	mul.f32 	%f329, %f3, %f324;
	sub.f32 	%f330, %f328, %f329;
	mul.f32 	%f331, %f3, %f321;
	mul.f32 	%f332, %f1, %f327;
	sub.f32 	%f333, %f331, %f332;
	mul.f32 	%f334, %f1, %f324;
	mul.f32 	%f335, %f2, %f321;
	sub.f32 	%f336, %f334, %f335;
	fma.rn.f32 	%f337, %f387, %f387, 0f3F800000;
	rcp.rn.f32 	%f338, %f337;
	mul.f32 	%f339, %f309, %f338;
	mul.f32 	%f340, %f312, %f338;
	mul.f32 	%f341, %f315, %f338;
	mul.f32 	%f342, %f27, %f338;
	div.rn.f32 	%f343, %f342, %f21;
	mul.f32 	%f344, %f318, %f343;
	mul.f32 	%f345, %f1, %f344;
	mul.f32 	%f346, %f2, %f344;
	mul.f32 	%f347, %f3, %f344;
	sub.f32 	%f348, %f345, %f339;
	sub.f32 	%f349, %f346, %f340;
	sub.f32 	%f350, %f347, %f341;
	mul.f32 	%f351, %f398, %f338;
	div.rn.f32 	%f352, %f351, %f21;
	mul.f32 	%f353, %f352, %f330;
	mul.f32 	%f354, %f352, %f333;
	mul.f32 	%f355, %f352, %f336;
	sub.f32 	%f356, %f348, %f353;
	sub.f32 	%f357, %f349, %f354;
	sub.f32 	%f358, %f350, %f355;
	fma.rn.f32 	%f399, %f19, %f300, %f356;
	fma.rn.f32 	%f400, %f20, %f300, %f357;
	fma.rn.f32 	%f401, %f25, %f300, %f358;

BB0_36:
	ld.param.u64 	%rd64, [LLBtorque2_param_2];
	ld.param.u64 	%rd63, [LLBtorque2_param_1];
	ld.param.u64 	%rd62, [LLBtorque2_param_0];
	mov.u32 	%r40, %ctaid.x;
	mov.u32 	%r39, %ctaid.y;
	mov.u32 	%r38, %nctaid.x;
	mov.u32 	%r37, %tid.x;
	mov.u32 	%r36, %ntid.x;
	mad.lo.s32 	%r35, %r38, %r39, %r40;
	mad.lo.s32 	%r34, %r35, %r36, %r37;
	mul.wide.s32 	%rd61, %r34, 4;
	cvta.to.global.u64 	%rd54, %rd62;
	add.s64 	%rd56, %rd54, %rd61;
	st.global.f32 	[%rd56], %f399;
	cvta.to.global.u64 	%rd57, %rd63;
	add.s64 	%rd58, %rd57, %rd61;
	st.global.f32 	[%rd58], %f400;
	cvta.to.global.u64 	%rd59, %rd64;
	add.s64 	%rd60, %rd59, %rd61;
	st.global.f32 	[%rd60], %f401;

BB0_37:
	ret;
}


`
)
