package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for LLBtorque4 kernel
var LLBtorque4_code cu.Function

// Stores the arguments for LLBtorque4 kernel invocation
type LLBtorque4_args_t struct {
	arg_tx         unsafe.Pointer
	arg_ty         unsafe.Pointer
	arg_tz         unsafe.Pointer
	arg_mx         unsafe.Pointer
	arg_my         unsafe.Pointer
	arg_mz         unsafe.Pointer
	arg_hx         unsafe.Pointer
	arg_hy         unsafe.Pointer
	arg_hz         unsafe.Pointer
	arg_alpha_     unsafe.Pointer
	arg_alpha_mul  float32
	arg_TCurie_    unsafe.Pointer
	arg_TCurie_mul float32
	arg_Msat_      unsafe.Pointer
	arg_Msat_mul   float32
	arg_hth1x      unsafe.Pointer
	arg_hth1y      unsafe.Pointer
	arg_hth1z      unsafe.Pointer
	arg_hth2x      unsafe.Pointer
	arg_hth2y      unsafe.Pointer
	arg_hth2z      unsafe.Pointer
	arg_temp_      unsafe.Pointer
	arg_temp_mul   float32
	arg_a1_        unsafe.Pointer
	arg_a1_mul     float32
	arg_N          int
	argptr         [26]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for LLBtorque4 kernel invocation
var LLBtorque4_args LLBtorque4_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	LLBtorque4_args.argptr[0] = unsafe.Pointer(&LLBtorque4_args.arg_tx)
	LLBtorque4_args.argptr[1] = unsafe.Pointer(&LLBtorque4_args.arg_ty)
	LLBtorque4_args.argptr[2] = unsafe.Pointer(&LLBtorque4_args.arg_tz)
	LLBtorque4_args.argptr[3] = unsafe.Pointer(&LLBtorque4_args.arg_mx)
	LLBtorque4_args.argptr[4] = unsafe.Pointer(&LLBtorque4_args.arg_my)
	LLBtorque4_args.argptr[5] = unsafe.Pointer(&LLBtorque4_args.arg_mz)
	LLBtorque4_args.argptr[6] = unsafe.Pointer(&LLBtorque4_args.arg_hx)
	LLBtorque4_args.argptr[7] = unsafe.Pointer(&LLBtorque4_args.arg_hy)
	LLBtorque4_args.argptr[8] = unsafe.Pointer(&LLBtorque4_args.arg_hz)
	LLBtorque4_args.argptr[9] = unsafe.Pointer(&LLBtorque4_args.arg_alpha_)
	LLBtorque4_args.argptr[10] = unsafe.Pointer(&LLBtorque4_args.arg_alpha_mul)
	LLBtorque4_args.argptr[11] = unsafe.Pointer(&LLBtorque4_args.arg_TCurie_)
	LLBtorque4_args.argptr[12] = unsafe.Pointer(&LLBtorque4_args.arg_TCurie_mul)
	LLBtorque4_args.argptr[13] = unsafe.Pointer(&LLBtorque4_args.arg_Msat_)
	LLBtorque4_args.argptr[14] = unsafe.Pointer(&LLBtorque4_args.arg_Msat_mul)
	LLBtorque4_args.argptr[15] = unsafe.Pointer(&LLBtorque4_args.arg_hth1x)
	LLBtorque4_args.argptr[16] = unsafe.Pointer(&LLBtorque4_args.arg_hth1y)
	LLBtorque4_args.argptr[17] = unsafe.Pointer(&LLBtorque4_args.arg_hth1z)
	LLBtorque4_args.argptr[18] = unsafe.Pointer(&LLBtorque4_args.arg_hth2x)
	LLBtorque4_args.argptr[19] = unsafe.Pointer(&LLBtorque4_args.arg_hth2y)
	LLBtorque4_args.argptr[20] = unsafe.Pointer(&LLBtorque4_args.arg_hth2z)
	LLBtorque4_args.argptr[21] = unsafe.Pointer(&LLBtorque4_args.arg_temp_)
	LLBtorque4_args.argptr[22] = unsafe.Pointer(&LLBtorque4_args.arg_temp_mul)
	LLBtorque4_args.argptr[23] = unsafe.Pointer(&LLBtorque4_args.arg_a1_)
	LLBtorque4_args.argptr[24] = unsafe.Pointer(&LLBtorque4_args.arg_a1_mul)
	LLBtorque4_args.argptr[25] = unsafe.Pointer(&LLBtorque4_args.arg_N)
}

// Wrapper for LLBtorque4 CUDA kernel, asynchronous.
func k_LLBtorque4_async(tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, hx unsafe.Pointer, hy unsafe.Pointer, hz unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, TCurie_ unsafe.Pointer, TCurie_mul float32, Msat_ unsafe.Pointer, Msat_mul float32, hth1x unsafe.Pointer, hth1y unsafe.Pointer, hth1z unsafe.Pointer, hth2x unsafe.Pointer, hth2y unsafe.Pointer, hth2z unsafe.Pointer, temp_ unsafe.Pointer, temp_mul float32, a1_ unsafe.Pointer, a1_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("LLBtorque4")
	}

	LLBtorque4_args.Lock()
	defer LLBtorque4_args.Unlock()

	if LLBtorque4_code == 0 {
		LLBtorque4_code = fatbinLoad(LLBtorque4_map, "LLBtorque4")
	}

	LLBtorque4_args.arg_tx = tx
	LLBtorque4_args.arg_ty = ty
	LLBtorque4_args.arg_tz = tz
	LLBtorque4_args.arg_mx = mx
	LLBtorque4_args.arg_my = my
	LLBtorque4_args.arg_mz = mz
	LLBtorque4_args.arg_hx = hx
	LLBtorque4_args.arg_hy = hy
	LLBtorque4_args.arg_hz = hz
	LLBtorque4_args.arg_alpha_ = alpha_
	LLBtorque4_args.arg_alpha_mul = alpha_mul
	LLBtorque4_args.arg_TCurie_ = TCurie_
	LLBtorque4_args.arg_TCurie_mul = TCurie_mul
	LLBtorque4_args.arg_Msat_ = Msat_
	LLBtorque4_args.arg_Msat_mul = Msat_mul
	LLBtorque4_args.arg_hth1x = hth1x
	LLBtorque4_args.arg_hth1y = hth1y
	LLBtorque4_args.arg_hth1z = hth1z
	LLBtorque4_args.arg_hth2x = hth2x
	LLBtorque4_args.arg_hth2y = hth2y
	LLBtorque4_args.arg_hth2z = hth2z
	LLBtorque4_args.arg_temp_ = temp_
	LLBtorque4_args.arg_temp_mul = temp_mul
	LLBtorque4_args.arg_a1_ = a1_
	LLBtorque4_args.arg_a1_mul = a1_mul
	LLBtorque4_args.arg_N = N

	args := LLBtorque4_args.argptr[:]
	cu.LaunchKernel(LLBtorque4_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("LLBtorque4")
	}
}

// maps compute capability on PTX code for LLBtorque4 kernel.
var LLBtorque4_map = map[int]string{0: "",
	70: LLBtorque4_ptx_70}

// LLBtorque4 PTX code for various compute capabilities.
const (
	LLBtorque4_ptx_70 = `
.version 7.1
.target sm_70
.address_size 64

	// .globl	LLBtorque4

.visible .entry LLBtorque4(
	.param .u64 LLBtorque4_param_0,
	.param .u64 LLBtorque4_param_1,
	.param .u64 LLBtorque4_param_2,
	.param .u64 LLBtorque4_param_3,
	.param .u64 LLBtorque4_param_4,
	.param .u64 LLBtorque4_param_5,
	.param .u64 LLBtorque4_param_6,
	.param .u64 LLBtorque4_param_7,
	.param .u64 LLBtorque4_param_8,
	.param .u64 LLBtorque4_param_9,
	.param .f32 LLBtorque4_param_10,
	.param .u64 LLBtorque4_param_11,
	.param .f32 LLBtorque4_param_12,
	.param .u64 LLBtorque4_param_13,
	.param .f32 LLBtorque4_param_14,
	.param .u64 LLBtorque4_param_15,
	.param .u64 LLBtorque4_param_16,
	.param .u64 LLBtorque4_param_17,
	.param .u64 LLBtorque4_param_18,
	.param .u64 LLBtorque4_param_19,
	.param .u64 LLBtorque4_param_20,
	.param .u64 LLBtorque4_param_21,
	.param .f32 LLBtorque4_param_22,
	.param .u64 LLBtorque4_param_23,
	.param .f32 LLBtorque4_param_24,
	.param .u32 LLBtorque4_param_25
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<541>;
	.reg .b32 	%r<78>;
	.reg .f64 	%fd<10>;
	.reg .b64 	%rd<69>;


	ld.param.u64 	%rd4, [LLBtorque4_param_3];
	ld.param.u64 	%rd5, [LLBtorque4_param_4];
	ld.param.u64 	%rd6, [LLBtorque4_param_5];
	ld.param.u64 	%rd7, [LLBtorque4_param_6];
	ld.param.u64 	%rd8, [LLBtorque4_param_7];
	ld.param.u64 	%rd9, [LLBtorque4_param_8];
	ld.param.u64 	%rd10, [LLBtorque4_param_9];
	ld.param.f32 	%f521, [LLBtorque4_param_10];
	ld.param.u64 	%rd11, [LLBtorque4_param_11];
	ld.param.f32 	%f522, [LLBtorque4_param_12];
	ld.param.u64 	%rd12, [LLBtorque4_param_15];
	ld.param.u64 	%rd13, [LLBtorque4_param_16];
	ld.param.u64 	%rd14, [LLBtorque4_param_17];
	ld.param.u64 	%rd15, [LLBtorque4_param_18];
	ld.param.u64 	%rd16, [LLBtorque4_param_19];
	ld.param.u64 	%rd17, [LLBtorque4_param_20];
	ld.param.u64 	%rd18, [LLBtorque4_param_21];
	ld.param.f32 	%f524, [LLBtorque4_param_22];
	ld.param.u64 	%rd19, [LLBtorque4_param_23];
	ld.param.f32 	%f523, [LLBtorque4_param_24];
	ld.param.u32 	%r2, [LLBtorque4_param_25];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p4, %r1, %r2;
	@%p4 bra 	BB0_58;

	cvta.to.global.u64 	%rd20, %rd4;
	mul.wide.s32 	%rd21, %r1, 4;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.nc.f32 	%f1, [%rd22];
	cvta.to.global.u64 	%rd23, %rd5;
	add.s64 	%rd24, %rd23, %rd21;
	ld.global.nc.f32 	%f2, [%rd24];
	cvta.to.global.u64 	%rd25, %rd6;
	add.s64 	%rd26, %rd25, %rd21;
	ld.global.nc.f32 	%f3, [%rd26];
	cvta.to.global.u64 	%rd27, %rd7;
	add.s64 	%rd28, %rd27, %rd21;
	ld.global.nc.f32 	%f4, [%rd28];
	cvta.to.global.u64 	%rd29, %rd8;
	add.s64 	%rd30, %rd29, %rd21;
	ld.global.nc.f32 	%f5, [%rd30];
	cvta.to.global.u64 	%rd31, %rd9;
	add.s64 	%rd32, %rd31, %rd21;
	ld.global.nc.f32 	%f6, [%rd32];
	setp.eq.s64	%p5, %rd10, 0;
	@%p5 bra 	BB0_3;

	cvta.to.global.u64 	%rd33, %rd10;
	add.s64 	%rd35, %rd33, %rd21;
	ld.global.nc.f32 	%f94, [%rd35];
	mul.f32 	%f521, %f94, %f521;

BB0_3:
	setp.eq.s64	%p6, %rd11, 0;
	@%p6 bra 	BB0_5;

	cvta.to.global.u64 	%rd36, %rd11;
	add.s64 	%rd38, %rd36, %rd21;
	ld.global.nc.f32 	%f95, [%rd38];
	mul.f32 	%f522, %f95, %f522;

BB0_5:
	setp.eq.s64	%p7, %rd19, 0;
	@%p7 bra 	BB0_7;

	cvta.to.global.u64 	%rd39, %rd19;
	add.s64 	%rd41, %rd39, %rd21;
	ld.global.nc.f32 	%f96, [%rd41];
	mul.f32 	%f523, %f96, %f523;

BB0_7:
	setp.eq.s64	%p8, %rd18, 0;
	@%p8 bra 	BB0_9;

	cvta.to.global.u64 	%rd42, %rd18;
	add.s64 	%rd44, %rd42, %rd21;
	ld.global.nc.f32 	%f97, [%rd44];
	mul.f32 	%f524, %f97, %f524;

BB0_9:
	setp.eq.f32	%p9, %f524, 0f00000000;
	selp.f32	%f98, 0f38D1B717, %f524, %p9;
	cvt.f64.f32	%fd2, %f98;
	cvt.f64.f32	%fd1, %f522;
	add.f64 	%fd3, %fd1, %fd1;
	setp.gt.f64	%p10, %fd2, %fd3;
	add.f32 	%f99, %f522, %f522;
	selp.f32	%f525, %f99, %f98, %p10;
	setp.neu.f32	%p11, %f525, %f522;
	@%p11 bra 	BB0_11;

	add.f64 	%fd4, %fd1, 0dBF847AE147AE147B;
	cvt.rn.f32.f64	%f525, %fd4;

BB0_11:
	mul.f32 	%f100, %f2, %f2;
	fma.rn.f32 	%f101, %f1, %f1, %f100;
	fma.rn.f32 	%f18, %f3, %f3, %f101;
	mul.f32 	%f538, %f1, 0f00000000;
	mul.f32 	%f539, %f2, 0f00000000;
	mul.f32 	%f540, %f3, 0f00000000;
	setp.neu.f32	%p12, %f18, 0f00000000;
	setp.neu.f32	%p13, %f522, 0f00000000;
	and.pred  	%p14, %p12, %p13;
	@!%p14 bra 	BB0_57;
	bra.uni 	BB0_12;

BB0_12:
	cvta.to.global.u64 	%rd45, %rd12;
	add.s64 	%rd47, %rd45, %rd21;
	ld.global.nc.f32 	%f22, [%rd47];
	cvta.to.global.u64 	%rd48, %rd13;
	add.s64 	%rd49, %rd48, %rd21;
	ld.global.nc.f32 	%f23, [%rd49];
	cvta.to.global.u64 	%rd50, %rd14;
	add.s64 	%rd51, %rd50, %rd21;
	ld.global.nc.f32 	%f24, [%rd51];
	cvta.to.global.u64 	%rd52, %rd15;
	add.s64 	%rd53, %rd52, %rd21;
	ld.global.nc.f32 	%f25, [%rd53];
	cvta.to.global.u64 	%rd54, %rd16;
	add.s64 	%rd55, %rd54, %rd21;
	ld.global.nc.f32 	%f26, [%rd55];
	cvta.to.global.u64 	%rd56, %rd17;
	add.s64 	%rd57, %rd56, %rd21;
	ld.global.nc.f32 	%f27, [%rd57];
	add.f32 	%f102, %f521, %f521;
	mul.f32 	%f103, %f102, %f525;
	mul.f32 	%f104, %f522, 0f40400000;
	div.rn.f32 	%f28, %f103, %f104;
	setp.gtu.f32	%p15, %f525, %f522;
	@%p15 bra 	BB0_55;
	bra.uni 	BB0_13;

BB0_55:
	sub.f32 	%f411, %f525, %f522;
	mov.f32 	%f412, 0f347DE56D;
	div.rn.f32 	%f413, %f412, %f411;
	cvt.f64.f32	%fd8, %f413;
	setp.gt.f64	%p77, %fd8, 0d3EB0C6F7A0B5ED8D;
	selp.f32	%f414, 0f358637BD, %f413, %p77;
	div.rn.f32 	%f415, %f522, %f411;
	mul.f32 	%f416, %f18, 0f3F19999A;
	fma.rn.f32 	%f417, %f416, %f415, 0f3F800000;
	cvt.f64.f32	%fd9, %f414;
	mov.f32 	%f418, 0fBF800000;
	div.rn.f32 	%f419, %f418, %f414;
	setp.lt.f64	%p78, %fd9, 0d3DD5FD7FE1796495;
	selp.f32	%f420, 0fD03A43B7, %f419, %p78;
	mul.f32 	%f536, %f417, %f420;
	mov.f32 	%f537, %f28;
	bra.uni 	BB0_56;

BB0_13:
	setp.eq.f32	%p16, %f523, 0f00000000;
	selp.f32	%f29, 0f3F800000, %f523, %p16;
	mul.f32 	%f105, %f29, 0f3F000000;
	cvt.rzi.f32.f32	%f106, %f105;
	fma.rn.f32 	%f107, %f106, 0fC0000000, %f29;
	abs.f32 	%f30, %f107;
	div.rn.f32 	%f31, %f525, %f522;
	abs.f32 	%f32, %f31;
	setp.lt.f32	%p17, %f32, 0f00800000;
	mul.f32 	%f108, %f32, 0f4B800000;
	selp.f32	%f109, %f108, %f32, %p17;
	selp.f32	%f110, 0fC3170000, 0fC2FE0000, %p17;
	mov.b32 	 %r9, %f109;
	and.b32  	%r10, %r9, 8388607;
	or.b32  	%r11, %r10, 1065353216;
	mov.b32 	 %f111, %r11;
	shr.u32 	%r12, %r9, 23;
	cvt.rn.f32.u32	%f112, %r12;
	add.f32 	%f113, %f110, %f112;
	setp.gt.f32	%p18, %f111, 0f3FB504F3;
	mul.f32 	%f114, %f111, 0f3F000000;
	add.f32 	%f115, %f113, 0f3F800000;
	selp.f32	%f116, %f115, %f113, %p18;
	selp.f32	%f117, %f114, %f111, %p18;
	add.f32 	%f118, %f117, 0fBF800000;
	add.f32 	%f119, %f117, 0f3F800000;
	rcp.approx.ftz.f32 	%f120, %f119;
	add.f32 	%f121, %f118, %f118;
	mul.f32 	%f122, %f120, %f121;
	mul.f32 	%f123, %f122, %f122;
	mov.f32 	%f124, 0f3C4CAF63;
	mov.f32 	%f125, 0f3B18F0FE;
	fma.rn.f32 	%f126, %f125, %f123, %f124;
	mov.f32 	%f127, 0f3DAAAABD;
	fma.rn.f32 	%f128, %f126, %f123, %f127;
	mul.rn.f32 	%f129, %f128, %f123;
	mul.rn.f32 	%f130, %f129, %f122;
	sub.f32 	%f131, %f118, %f122;
	neg.f32 	%f132, %f122;
	add.f32 	%f133, %f131, %f131;
	fma.rn.f32 	%f134, %f132, %f118, %f133;
	mul.rn.f32 	%f135, %f120, %f134;
	add.f32 	%f136, %f130, %f122;
	sub.f32 	%f137, %f122, %f136;
	add.f32 	%f138, %f130, %f137;
	add.f32 	%f139, %f135, %f138;
	add.f32 	%f140, %f136, %f139;
	sub.f32 	%f141, %f136, %f140;
	add.f32 	%f142, %f139, %f141;
	mov.f32 	%f143, 0f3F317200;
	mul.rn.f32 	%f144, %f116, %f143;
	mov.f32 	%f145, 0f35BFBE8E;
	mul.rn.f32 	%f146, %f116, %f145;
	add.f32 	%f147, %f144, %f140;
	sub.f32 	%f148, %f144, %f147;
	add.f32 	%f149, %f140, %f148;
	add.f32 	%f150, %f142, %f149;
	add.f32 	%f151, %f146, %f150;
	add.f32 	%f152, %f147, %f151;
	sub.f32 	%f153, %f147, %f152;
	add.f32 	%f154, %f151, %f153;
	abs.f32 	%f33, %f29;
	setp.gt.f32	%p19, %f33, 0f77F684DF;
	mul.f32 	%f155, %f29, 0f39000000;
	selp.f32	%f156, %f155, %f29, %p19;
	mul.rn.f32 	%f157, %f156, %f152;
	neg.f32 	%f158, %f157;
	fma.rn.f32 	%f159, %f156, %f152, %f158;
	fma.rn.f32 	%f160, %f156, %f154, %f159;
	mov.f32 	%f161, 0f00000000;
	fma.rn.f32 	%f162, %f161, %f152, %f160;
	add.rn.f32 	%f163, %f157, %f162;
	neg.f32 	%f164, %f163;
	add.rn.f32 	%f165, %f157, %f164;
	add.rn.f32 	%f166, %f165, %f162;
	mov.b32 	 %r13, %f163;
	setp.eq.s32	%p20, %r13, 1118925336;
	add.s32 	%r14, %r13, -1;
	mov.b32 	 %f167, %r14;
	add.f32 	%f168, %f166, 0f37000000;
	selp.f32	%f34, %f168, %f166, %p20;
	selp.f32	%f169, %f167, %f163, %p20;
	mov.f32 	%f170, 0f3FB8AA3B;
	mul.rn.f32 	%f171, %f169, %f170;
	cvt.rzi.f32.f32	%f172, %f171;
	abs.f32 	%f173, %f172;
	setp.gt.f32	%p21, %f173, 0f42FC0000;
	mov.b32 	 %r15, %f172;
	and.b32  	%r16, %r15, -2147483648;
	or.b32  	%r17, %r16, 1123811328;
	mov.b32 	 %f174, %r17;
	selp.f32	%f175, %f174, %f172, %p21;
	mov.f32 	%f176, 0fBF317218;
	fma.rn.f32 	%f177, %f175, %f176, %f169;
	mov.f32 	%f178, 0f3102E308;
	fma.rn.f32 	%f179, %f175, %f178, %f177;
	mul.f32 	%f180, %f179, 0f3FB8AA3B;
	add.f32 	%f181, %f175, 0f4B40007F;
	mov.b32 	 %r18, %f181;
	shl.b32 	%r19, %r18, 23;
	mov.b32 	 %f182, %r19;
	ex2.approx.ftz.f32 	%f183, %f180;
	mul.f32 	%f526, %f183, %f182;
	setp.eq.f32	%p22, %f526, 0f7F800000;
	@%p22 bra 	BB0_15;

	fma.rn.f32 	%f526, %f526, %f34, %f526;

BB0_15:
	setp.neu.f32	%p23, %f30, 0f3F800000;
	setp.geu.f32	%p24, %f31, 0f00000000;
	or.pred  	%p1, %p24, %p23;
	setp.eq.f32	%p25, %f31, 0f00000000;
	@%p25 bra 	BB0_19;
	bra.uni 	BB0_16;

BB0_19:
	setp.eq.f32	%p28, %f30, 0f3F800000;
	add.f32 	%f187, %f31, %f31;
	mov.b32 	 %r22, %f187;
	selp.b32	%r23, %r22, 0, %p28;
	or.b32  	%r24, %r23, 2139095040;
	setp.lt.f32	%p29, %f29, 0f00000000;
	selp.b32	%r25, %r24, %r23, %p29;
	mov.b32 	 %f528, %r25;
	bra.uni 	BB0_20;

BB0_16:
	mov.b32 	 %r20, %f526;
	xor.b32  	%r21, %r20, -2147483648;
	mov.b32 	 %f184, %r21;
	selp.f32	%f528, %f526, %f184, %p1;
	@%p24 bra 	BB0_20;

	cvt.rzi.f32.f32	%f185, %f29;
	setp.eq.f32	%p27, %f185, %f29;
	@%p27 bra 	BB0_20;

	mov.f32 	%f528, 0f7FFFFFFF;

BB0_20:
	abs.f32 	%f515, %f31;
	abs.f32 	%f487, %f29;
	add.f32 	%f188, %f515, %f487;
	mov.b32 	 %r26, %f188;
	setp.lt.s32	%p30, %r26, 2139095040;
	@%p30 bra 	BB0_27;

	abs.f32 	%f518, %f31;
	abs.f32 	%f503, %f29;
	setp.gtu.f32	%p31, %f518, 0f7F800000;
	setp.gtu.f32	%p32, %f503, 0f7F800000;
	or.pred  	%p33, %p31, %p32;
	@%p33 bra 	BB0_26;
	bra.uni 	BB0_22;

BB0_26:
	add.f32 	%f528, %f29, %f31;
	bra.uni 	BB0_27;

BB0_22:
	abs.f32 	%f504, %f29;
	setp.eq.f32	%p34, %f504, 0f7F800000;
	@%p34 bra 	BB0_25;
	bra.uni 	BB0_23;

BB0_25:
	abs.f32 	%f520, %f31;
	setp.gt.f32	%p37, %f520, 0f3F800000;
	selp.b32	%r30, 2139095040, 0, %p37;
	xor.b32  	%r31, %r30, 2139095040;
	setp.lt.f32	%p38, %f29, 0f00000000;
	selp.b32	%r32, %r31, %r30, %p38;
	mov.b32 	 %f189, %r32;
	setp.eq.f32	%p39, %f31, 0fBF800000;
	selp.f32	%f528, 0f3F800000, %f189, %p39;
	bra.uni 	BB0_27;

BB0_23:
	abs.f32 	%f519, %f31;
	setp.neu.f32	%p35, %f519, 0f7F800000;
	@%p35 bra 	BB0_27;

	setp.ltu.f32	%p36, %f29, 0f00000000;
	selp.b32	%r27, 0, 2139095040, %p36;
	or.b32  	%r28, %r27, -2147483648;
	selp.b32	%r29, %r27, %r28, %p1;
	mov.b32 	 %f528, %r29;

BB0_27:
	mov.f32 	%f517, 0fBF317218;
	mov.f32 	%f516, 0f3FB8AA3B;
	mov.f32 	%f494, 0f3102E308;
	mov.f32 	%f493, 0f00000000;
	mov.f32 	%f492, 0f35BFBE8E;
	mov.f32 	%f491, 0f3F317200;
	mov.f32 	%f490, 0f3DAAAABD;
	mov.f32 	%f489, 0f3C4CAF63;
	mov.f32 	%f488, 0f3B18F0FE;
	setp.eq.f32	%p40, %f31, 0f3F800000;
	selp.f32	%f45, 0f3F800000, %f528, %p40;
	mov.f32 	%f190, 0f3F1DDC72;
	cvt.rzi.f32.f32	%f191, %f190;
	fma.rn.f32 	%f192, %f191, 0fC0000000, 0f3F9DDC72;
	abs.f32 	%f46, %f192;
	abs.f32 	%f47, %f45;
	setp.lt.f32	%p41, %f47, 0f00800000;
	mul.f32 	%f193, %f47, 0f4B800000;
	selp.f32	%f194, %f193, %f47, %p41;
	selp.f32	%f195, 0fC3170000, 0fC2FE0000, %p41;
	mov.b32 	 %r33, %f194;
	and.b32  	%r34, %r33, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	 %f196, %r35;
	shr.u32 	%r36, %r33, 23;
	cvt.rn.f32.u32	%f197, %r36;
	add.f32 	%f198, %f195, %f197;
	setp.gt.f32	%p42, %f196, 0f3FB504F3;
	mul.f32 	%f199, %f196, 0f3F000000;
	add.f32 	%f200, %f198, 0f3F800000;
	selp.f32	%f201, %f200, %f198, %p42;
	selp.f32	%f202, %f199, %f196, %p42;
	add.f32 	%f203, %f202, 0fBF800000;
	add.f32 	%f204, %f202, 0f3F800000;
	rcp.approx.ftz.f32 	%f205, %f204;
	add.f32 	%f206, %f203, %f203;
	mul.f32 	%f207, %f205, %f206;
	mul.f32 	%f208, %f207, %f207;
	fma.rn.f32 	%f211, %f488, %f208, %f489;
	fma.rn.f32 	%f213, %f211, %f208, %f490;
	mul.rn.f32 	%f214, %f213, %f208;
	mul.rn.f32 	%f215, %f214, %f207;
	sub.f32 	%f216, %f203, %f207;
	neg.f32 	%f217, %f207;
	add.f32 	%f218, %f216, %f216;
	fma.rn.f32 	%f219, %f217, %f203, %f218;
	mul.rn.f32 	%f220, %f205, %f219;
	add.f32 	%f221, %f215, %f207;
	sub.f32 	%f222, %f207, %f221;
	add.f32 	%f223, %f215, %f222;
	add.f32 	%f224, %f220, %f223;
	add.f32 	%f225, %f221, %f224;
	sub.f32 	%f226, %f221, %f225;
	add.f32 	%f227, %f224, %f226;
	mul.rn.f32 	%f229, %f201, %f491;
	mul.rn.f32 	%f231, %f201, %f492;
	add.f32 	%f232, %f229, %f225;
	sub.f32 	%f233, %f229, %f232;
	add.f32 	%f234, %f225, %f233;
	add.f32 	%f235, %f227, %f234;
	add.f32 	%f236, %f231, %f235;
	add.f32 	%f237, %f232, %f236;
	sub.f32 	%f238, %f232, %f237;
	add.f32 	%f239, %f236, %f238;
	mov.f32 	%f240, 0f3F9DDC72;
	mul.rn.f32 	%f241, %f240, %f237;
	neg.f32 	%f242, %f241;
	fma.rn.f32 	%f243, %f240, %f237, %f242;
	fma.rn.f32 	%f244, %f240, %f239, %f243;
	fma.rn.f32 	%f246, %f493, %f237, %f244;
	add.rn.f32 	%f247, %f241, %f246;
	neg.f32 	%f248, %f247;
	add.rn.f32 	%f249, %f241, %f248;
	add.rn.f32 	%f250, %f249, %f246;
	mov.b32 	 %r37, %f247;
	setp.eq.s32	%p43, %r37, 1118925336;
	add.s32 	%r38, %r37, -1;
	mov.b32 	 %f251, %r38;
	add.f32 	%f252, %f250, 0f37000000;
	selp.f32	%f48, %f252, %f250, %p43;
	selp.f32	%f253, %f251, %f247, %p43;
	mul.rn.f32 	%f255, %f253, %f516;
	cvt.rzi.f32.f32	%f256, %f255;
	abs.f32 	%f257, %f256;
	setp.gt.f32	%p44, %f257, 0f42FC0000;
	mov.b32 	 %r39, %f256;
	and.b32  	%r40, %r39, -2147483648;
	or.b32  	%r41, %r40, 1123811328;
	mov.b32 	 %f258, %r41;
	selp.f32	%f259, %f258, %f256, %p44;
	fma.rn.f32 	%f261, %f259, %f517, %f253;
	fma.rn.f32 	%f263, %f259, %f494, %f261;
	mul.f32 	%f264, %f263, 0f3FB8AA3B;
	add.f32 	%f265, %f259, 0f4B40007F;
	mov.b32 	 %r42, %f265;
	shl.b32 	%r43, %r42, 23;
	mov.b32 	 %f266, %r43;
	ex2.approx.ftz.f32 	%f267, %f264;
	mul.f32 	%f529, %f267, %f266;
	setp.eq.f32	%p45, %f529, 0f7F800000;
	@%p45 bra 	BB0_29;

	fma.rn.f32 	%f529, %f529, %f48, %f529;

BB0_29:
	setp.neu.f32	%p46, %f46, 0f3F800000;
	setp.geu.f32	%p47, %f45, 0f00000000;
	or.pred  	%p2, %p47, %p46;
	setp.eq.f32	%p48, %f45, 0f00000000;
	@%p48 bra 	BB0_33;
	bra.uni 	BB0_30;

BB0_33:
	setp.eq.f32	%p51, %f46, 0f3F800000;
	add.f32 	%f272, %f45, %f45;
	selp.f32	%f531, %f272, 0f00000000, %p51;
	bra.uni 	BB0_34;

BB0_30:
	mov.b32 	 %r44, %f529;
	xor.b32  	%r45, %r44, -2147483648;
	mov.b32 	 %f268, %r45;
	selp.f32	%f531, %f529, %f268, %p2;
	@%p47 bra 	BB0_34;

	mov.f32 	%f512, 0f3F9DDC72;
	cvt.rzi.f32.f32	%f270, %f512;
	setp.eq.f32	%p50, %f270, 0f3F9DDC72;
	@%p50 bra 	BB0_34;

	mov.f32 	%f531, 0f7FFFFFFF;

BB0_34:
	abs.f32 	%f505, %f45;
	add.f32 	%f273, %f505, 0f3F9DDC72;
	mov.b32 	 %r46, %f273;
	setp.lt.s32	%p52, %r46, 2139095040;
	@%p52 bra 	BB0_39;

	abs.f32 	%f510, %f45;
	setp.gtu.f32	%p53, %f510, 0f7F800000;
	@%p53 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	add.f32 	%f531, %f45, 0f3F9DDC72;
	bra.uni 	BB0_39;

BB0_36:
	abs.f32 	%f511, %f45;
	setp.neu.f32	%p54, %f511, 0f7F800000;
	@%p54 bra 	BB0_39;

	selp.f32	%f531, 0f7F800000, 0fFF800000, %p2;

BB0_39:
	mov.f32 	%f507, 0fBF317218;
	mov.f32 	%f506, 0f3FB8AA3B;
	mov.f32 	%f501, 0f3102E308;
	mov.f32 	%f500, 0f00000000;
	mov.f32 	%f499, 0f35BFBE8E;
	mov.f32 	%f498, 0f3F317200;
	mov.f32 	%f497, 0f3DAAAABD;
	mov.f32 	%f496, 0f3C4CAF63;
	mov.f32 	%f495, 0f3B18F0FE;
	mov.f32 	%f274, 0f3F800000;
	sub.f32 	%f275, %f274, %f531;
	setp.eq.f32	%p55, %f45, 0f3F800000;
	selp.f32	%f58, 0f00000000, %f275, %p55;
	mov.f32 	%f276, 0f3E5E2AC3;
	cvt.rzi.f32.f32	%f277, %f276;
	fma.rn.f32 	%f278, %f277, 0fC0000000, 0f3EDE2AC3;
	abs.f32 	%f59, %f278;
	abs.f32 	%f60, %f58;
	setp.lt.f32	%p56, %f60, 0f00800000;
	mul.f32 	%f279, %f60, 0f4B800000;
	selp.f32	%f280, %f279, %f60, %p56;
	selp.f32	%f281, 0fC3170000, 0fC2FE0000, %p56;
	mov.b32 	 %r47, %f280;
	and.b32  	%r48, %r47, 8388607;
	or.b32  	%r49, %r48, 1065353216;
	mov.b32 	 %f282, %r49;
	shr.u32 	%r50, %r47, 23;
	cvt.rn.f32.u32	%f283, %r50;
	add.f32 	%f284, %f281, %f283;
	setp.gt.f32	%p57, %f282, 0f3FB504F3;
	mul.f32 	%f285, %f282, 0f3F000000;
	add.f32 	%f286, %f284, 0f3F800000;
	selp.f32	%f287, %f286, %f284, %p57;
	selp.f32	%f288, %f285, %f282, %p57;
	add.f32 	%f289, %f288, 0fBF800000;
	add.f32 	%f290, %f288, 0f3F800000;
	rcp.approx.ftz.f32 	%f291, %f290;
	add.f32 	%f292, %f289, %f289;
	mul.f32 	%f293, %f291, %f292;
	mul.f32 	%f294, %f293, %f293;
	fma.rn.f32 	%f297, %f495, %f294, %f496;
	fma.rn.f32 	%f299, %f297, %f294, %f497;
	mul.rn.f32 	%f300, %f299, %f294;
	mul.rn.f32 	%f301, %f300, %f293;
	sub.f32 	%f302, %f289, %f293;
	neg.f32 	%f303, %f293;
	add.f32 	%f304, %f302, %f302;
	fma.rn.f32 	%f305, %f303, %f289, %f304;
	mul.rn.f32 	%f306, %f291, %f305;
	add.f32 	%f307, %f301, %f293;
	sub.f32 	%f308, %f293, %f307;
	add.f32 	%f309, %f301, %f308;
	add.f32 	%f310, %f306, %f309;
	add.f32 	%f311, %f307, %f310;
	sub.f32 	%f312, %f307, %f311;
	add.f32 	%f313, %f310, %f312;
	mul.rn.f32 	%f315, %f287, %f498;
	mul.rn.f32 	%f317, %f287, %f499;
	add.f32 	%f318, %f315, %f311;
	sub.f32 	%f319, %f315, %f318;
	add.f32 	%f320, %f311, %f319;
	add.f32 	%f321, %f313, %f320;
	add.f32 	%f322, %f317, %f321;
	add.f32 	%f323, %f318, %f322;
	sub.f32 	%f324, %f318, %f323;
	add.f32 	%f325, %f322, %f324;
	mov.f32 	%f326, 0f3EDE2AC3;
	mul.rn.f32 	%f327, %f326, %f323;
	neg.f32 	%f328, %f327;
	fma.rn.f32 	%f329, %f326, %f323, %f328;
	fma.rn.f32 	%f330, %f326, %f325, %f329;
	fma.rn.f32 	%f332, %f500, %f323, %f330;
	add.rn.f32 	%f333, %f327, %f332;
	neg.f32 	%f334, %f333;
	add.rn.f32 	%f335, %f327, %f334;
	add.rn.f32 	%f336, %f335, %f332;
	mov.b32 	 %r51, %f333;
	setp.eq.s32	%p58, %r51, 1118925336;
	add.s32 	%r52, %r51, -1;
	mov.b32 	 %f337, %r52;
	add.f32 	%f338, %f336, 0f37000000;
	selp.f32	%f61, %f338, %f336, %p58;
	selp.f32	%f339, %f337, %f333, %p58;
	mul.rn.f32 	%f341, %f339, %f506;
	cvt.rzi.f32.f32	%f342, %f341;
	abs.f32 	%f343, %f342;
	setp.gt.f32	%p59, %f343, 0f42FC0000;
	mov.b32 	 %r53, %f342;
	and.b32  	%r54, %r53, -2147483648;
	or.b32  	%r55, %r54, 1123811328;
	mov.b32 	 %f344, %r55;
	selp.f32	%f345, %f344, %f342, %p59;
	fma.rn.f32 	%f347, %f345, %f507, %f339;
	fma.rn.f32 	%f349, %f345, %f501, %f347;
	mul.f32 	%f350, %f349, 0f3FB8AA3B;
	add.f32 	%f351, %f345, 0f4B40007F;
	mov.b32 	 %r56, %f351;
	shl.b32 	%r57, %r56, 23;
	mov.b32 	 %f352, %r57;
	ex2.approx.ftz.f32 	%f353, %f350;
	mul.f32 	%f532, %f353, %f352;
	setp.eq.f32	%p60, %f532, 0f7F800000;
	@%p60 bra 	BB0_41;

	fma.rn.f32 	%f532, %f532, %f61, %f532;

BB0_41:
	setp.neu.f32	%p61, %f59, 0f3F800000;
	setp.geu.f32	%p62, %f58, 0f00000000;
	or.pred  	%p3, %p62, %p61;
	setp.eq.f32	%p63, %f58, 0f00000000;
	@%p63 bra 	BB0_45;
	bra.uni 	BB0_42;

BB0_45:
	setp.eq.f32	%p66, %f59, 0f3F800000;
	add.f32 	%f358, %f58, %f58;
	selp.f32	%f534, %f358, 0f00000000, %p66;
	bra.uni 	BB0_46;

BB0_42:
	mov.b32 	 %r58, %f532;
	xor.b32  	%r59, %r58, -2147483648;
	mov.b32 	 %f354, %r59;
	selp.f32	%f534, %f532, %f354, %p3;
	@%p62 bra 	BB0_46;

	mov.f32 	%f514, 0f3EDE2AC3;
	cvt.rzi.f32.f32	%f356, %f514;
	setp.eq.f32	%p65, %f356, 0f3EDE2AC3;
	@%p65 bra 	BB0_46;

	mov.f32 	%f534, 0f7FFFFFFF;

BB0_46:
	add.f32 	%f359, %f60, 0f3EDE2AC3;
	mov.b32 	 %r60, %f359;
	setp.lt.s32	%p67, %r60, 2139095040;
	@%p67 bra 	BB0_51;

	setp.gtu.f32	%p68, %f60, 0f7F800000;
	@%p68 bra 	BB0_50;
	bra.uni 	BB0_48;

BB0_50:
	add.f32 	%f534, %f58, 0f3EDE2AC3;
	bra.uni 	BB0_51;

BB0_48:
	setp.neu.f32	%p69, %f60, 0f7F800000;
	@%p69 bra 	BB0_51;

	selp.f32	%f534, 0f7F800000, 0fFF800000, %p3;

BB0_51:
	setp.eq.f32	%p70, %f58, 0f3F800000;
	selp.f32	%f360, 0f3F800000, %f534, %p70;
	cvt.f64.f32	%fd5, %f360;
	setp.lt.f64	%p71, %fd5, 0d3F50624DD2F1A9FC;
	selp.f32	%f71, 0f3A83126F, %f360, %p71;
	mov.f32 	%f361, 0f40400000;
	div.rn.f32 	%f72, %f361, %f45;
	mul.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f73, %f73;
	abs.f32 	%f75, %f73;
	setp.ltu.f32	%p72, %f75, 0f3F800000;
	@%p72 bra 	BB0_53;
	bra.uni 	BB0_52;

BB0_53:
	mov.f32 	%f382, 0f394FFF49;
	mov.f32 	%f383, 0f363D0ADA;
	fma.rn.f32 	%f384, %f383, %f74, %f382;
	mov.f32 	%f385, 0f3C08889A;
	fma.rn.f32 	%f386, %f384, %f74, %f385;
	mov.f32 	%f387, 0f3E2AAAAB;
	fma.rn.f32 	%f388, %f386, %f74, %f387;
	mul.f32 	%f389, %f74, %f388;
	fma.rn.f32 	%f535, %f389, %f73, %f73;
	bra.uni 	BB0_54;

BB0_52:
	mov.f32 	%f509, 0fBF317218;
	mov.f32 	%f508, 0f3FB8AA3B;
	mov.f32 	%f502, 0f3102E308;
	mul.rn.f32 	%f363, %f75, %f508;
	cvt.rzi.f32.f32	%f364, %f363;
	abs.f32 	%f365, %f364;
	setp.gt.f32	%p73, %f365, 0f42FC0000;
	mov.b32 	 %r61, %f364;
	and.b32  	%r62, %r61, -2147483648;
	or.b32  	%r63, %r62, 1123811328;
	mov.b32 	 %f366, %r63;
	selp.f32	%f367, %f366, %f364, %p73;
	fma.rn.f32 	%f369, %f367, %f509, %f75;
	fma.rn.f32 	%f371, %f367, %f502, %f369;
	mul.f32 	%f372, %f371, 0f3FB8AA3B;
	add.f32 	%f373, %f367, 0f4B40007D;
	mov.b32 	 %r64, %f373;
	shl.b32 	%r65, %r64, 23;
	mov.b32 	 %f374, %r65;
	ex2.approx.ftz.f32 	%f375, %f372;
	mul.f32 	%f376, %f375, %f374;
	mov.f32 	%f377, 0f3E000000;
	div.approx.f32 	%f378, %f377, %f376;
	neg.f32 	%f379, %f378;
	mov.f32 	%f380, 0f40000000;
	fma.rn.f32 	%f381, %f380, %f376, %f379;
	mov.b32 	 %r66, %f381;
	setp.ltu.f32	%p74, %f75, 0f42B40000;
	selp.b32	%r67, %r66, 2139095040, %p74;
	mov.b32 	 %r68, %f73;
	and.b32  	%r69, %r68, -2147483648;
	or.b32  	%r70, %r67, %r69;
	mov.b32 	 %f535, %r70;

BB0_54:
	mov.f32 	%f513, 0f3F800000;
	mul.f32 	%f390, %f535, %f535;
	rcp.rn.f32 	%f391, %f390;
	rcp.rn.f32 	%f392, %f74;
	sub.f32 	%f393, %f392, %f391;
	mul.f32 	%f394, %f72, %f393;
	sub.f32 	%f396, %f513, %f394;
	div.rn.f32 	%f397, %f393, %f396;
	mul.f32 	%f398, %f525, 0f19857725;
	rcp.rn.f32 	%f399, %f398;
	mul.f32 	%f400, %f399, 0f0FA575F3;
	mul.f32 	%f401, %f400, %f397;
	cvt.f64.f32	%fd6, %f401;
	setp.gt.f64	%p75, %fd6, 0d3EB0C6F7A0B5ED8D;
	selp.f32	%f402, 0f358637BD, %f401, %p75;
	div.rn.f32 	%f403, %f45, 0fC0400000;
	add.f32 	%f404, %f403, 0f3F800000;
	mul.f32 	%f537, %f521, %f404;
	add.f32 	%f405, %f402, %f402;
	mul.f32 	%f406, %f71, %f71;
	div.rn.f32 	%f407, %f18, %f406;
	sub.f32 	%f408, %f513, %f407;
	cvt.f64.f32	%fd7, %f402;
	rcp.rn.f32 	%f409, %f405;
	setp.lt.f64	%p76, %fd7, 0d3DD5FD7FE1796495;
	selp.f32	%f410, 0f4FBA43B7, %f409, %p76;
	mul.f32 	%f536, %f408, %f410;

BB0_56:
	mul.f32 	%f421, %f536, 0f35A8A9B8;
	mul.f32 	%f422, %f521, %f537;
	mul.f32 	%f423, %f537, %f422;
	sub.f32 	%f424, %f537, %f28;
	div.rn.f32 	%f425, %f424, %f423;
	sqrt.rn.f32 	%f426, %f425;
	div.rn.f32 	%f427, %f28, %f521;
	sqrt.rn.f32 	%f428, %f427;
	fma.rn.f32 	%f429, %f1, %f421, %f4;
	fma.rn.f32 	%f430, %f2, %f421, %f5;
	fma.rn.f32 	%f431, %f3, %f421, %f6;
	fma.rn.f32 	%f432, %f22, %f426, %f429;
	fma.rn.f32 	%f433, %f23, %f426, %f430;
	fma.rn.f32 	%f434, %f24, %f426, %f431;
	mul.f32 	%f435, %f2, %f431;
	mul.f32 	%f436, %f3, %f430;
	sub.f32 	%f437, %f435, %f436;
	mul.f32 	%f438, %f3, %f429;
	mul.f32 	%f439, %f1, %f431;
	sub.f32 	%f440, %f438, %f439;
	mul.f32 	%f441, %f1, %f430;
	mul.f32 	%f442, %f2, %f429;
	sub.f32 	%f443, %f441, %f442;
	mul.f32 	%f444, %f2, %f430;
	fma.rn.f32 	%f445, %f1, %f429, %f444;
	fma.rn.f32 	%f446, %f3, %f431, %f445;
	mul.f32 	%f447, %f2, %f434;
	mul.f32 	%f448, %f3, %f433;
	sub.f32 	%f449, %f447, %f448;
	mul.f32 	%f450, %f3, %f432;
	mul.f32 	%f451, %f1, %f434;
	sub.f32 	%f452, %f450, %f451;
	mul.f32 	%f453, %f1, %f433;
	mul.f32 	%f454, %f2, %f432;
	sub.f32 	%f455, %f453, %f454;
	mul.f32 	%f456, %f2, %f455;
	mul.f32 	%f457, %f3, %f452;
	sub.f32 	%f458, %f456, %f457;
	mul.f32 	%f459, %f3, %f449;
	mul.f32 	%f460, %f1, %f455;
	sub.f32 	%f461, %f459, %f460;
	mul.f32 	%f462, %f1, %f452;
	mul.f32 	%f463, %f2, %f449;
	sub.f32 	%f464, %f462, %f463;
	fma.rn.f32 	%f465, %f521, %f521, 0f3F800000;
	rcp.rn.f32 	%f466, %f465;
	mul.f32 	%f467, %f437, %f466;
	mul.f32 	%f468, %f440, %f466;
	mul.f32 	%f469, %f443, %f466;
	mul.f32 	%f470, %f28, %f466;
	div.rn.f32 	%f471, %f470, %f18;
	mul.f32 	%f472, %f446, %f471;
	mul.f32 	%f473, %f1, %f472;
	mul.f32 	%f474, %f2, %f472;
	mul.f32 	%f475, %f3, %f472;
	sub.f32 	%f476, %f473, %f467;
	sub.f32 	%f477, %f474, %f468;
	sub.f32 	%f478, %f475, %f469;
	mul.f32 	%f479, %f537, %f466;
	div.rn.f32 	%f480, %f479, %f18;
	mul.f32 	%f481, %f480, %f458;
	mul.f32 	%f482, %f480, %f461;
	mul.f32 	%f483, %f480, %f464;
	sub.f32 	%f484, %f476, %f481;
	sub.f32 	%f485, %f477, %f482;
	sub.f32 	%f486, %f478, %f483;
	fma.rn.f32 	%f538, %f25, %f428, %f484;
	fma.rn.f32 	%f539, %f26, %f428, %f485;
	fma.rn.f32 	%f540, %f27, %f428, %f486;

BB0_57:
	ld.param.u64 	%rd68, [LLBtorque4_param_2];
	ld.param.u64 	%rd67, [LLBtorque4_param_1];
	ld.param.u64 	%rd66, [LLBtorque4_param_0];
	mov.u32 	%r77, %ctaid.x;
	mov.u32 	%r76, %ctaid.y;
	mov.u32 	%r75, %nctaid.x;
	mov.u32 	%r74, %tid.x;
	mov.u32 	%r73, %ntid.x;
	mad.lo.s32 	%r72, %r75, %r76, %r77;
	mad.lo.s32 	%r71, %r72, %r73, %r74;
	mul.wide.s32 	%rd65, %r71, 4;
	cvta.to.global.u64 	%rd58, %rd66;
	add.s64 	%rd60, %rd58, %rd65;
	st.global.f32 	[%rd60], %f538;
	cvta.to.global.u64 	%rd61, %rd67;
	add.s64 	%rd62, %rd61, %rd65;
	st.global.f32 	[%rd62], %f539;
	cvta.to.global.u64 	%rd63, %rd68;
	add.s64 	%rd64, %rd63, %rd65;
	st.global.f32 	[%rd64], %f540;

BB0_58:
	ret;
}


`
)
